#ifndef _CHROBJDATA_H_
#define _CHROBJDATA_H_
#include "ultra64.h"

typedef struct ModelFileTextures {
    u32 TextureID;
    u8 Width;
    u8 Height;
    u8 MipMapTiles;
    u8 Type;
    u8 RenderDepth;
    u8 sflags;
    u8 tflags;
} ModelFileTextures;

typedef struct ModelJoint {
    u16 NodeType;
    u16 mtxA;
    u16 mtxB;
} ModelJoint;

typedef struct ModelSkeleton {
    short numjoints;
    short pad1; //pad
    ModelJoint* Joints;
    short SkeletonSize;
    short pad2;
} ModelSkeleton;

typedef struct ModelNode {
    short Opcode;
    void * Data;
    struct ModelNode * Parent;
    struct ModelNode * Next;
    struct ModelNode * Previous;
    struct ModelNode * Child;
} ModelNode;

typedef struct ModelFileHeader {
    ModelNode* RootNode;
    ModelSkeleton* Skeleton;
    ModelNode** Switches;
    s16 numSwitches; 
    s16 numMatrices; 
    f32 BoundingVolumeRadius; 
    s16 numRecords;
    s16 numtextures;
    ModelFileTextures* Textures;
    s32 isLoaded;
} ModelFileHeader;

typedef struct ItemModelFileRecord {
    ModelFileHeader* header;
    char * filename;
    float scale;
} ItemModelFileRecord;

struct ChrModelFileRecord {
    ModelFileHeader* header;
    char * filename;
    float scale;
    float pov;
    u8 isMale;
    u8 hasHead;
    u8 pad1;
    u8 pad2;
};

struct player_gait_header {
    u8 field_0x0;
    u8 type;
    u16 field_0x2;
    struct player_gait_object_entry * field_0x4;
    struct player_gait_pos_header * previous;
    void * field_0xc;
    void * field_0x10;
    struct player_gait_pos_header * next;
};

struct player_gait_pos_header {
    u8 field_0x0;
    u8 type;
    u16 field_0x2;
    struct player_gait_position_entry * field_0x4;
    struct player_gait_pos_header * previous;
    void * field_0xc;
    void * field_0x10;
    struct player_gait_pos_header * next;
};

struct player_gait_object_entry {
    u32 field_0x0;
    struct player_gait_pos_header * ptr_header;
    u32 field_0x8;
    u32 field_0xc;
};

struct player_gait_position_entry {
    float z_scale;
    float y_offset;
    float xy_scale;
    u16 field_0xc;
    u16 field_0xe;
    u16 field_0x10;
    u16 field_0x12;
    struct player_gait_pos_header * ptr_header;
    u32 field_0x18;
};

struct struct_13 {
    void * ailist;
    int ailistid;
};

struct headHat
{
    float xoffset;
    float yoffset;
    float zoffset;
    float xsize;
    float ysize;
    float zsize;
};

extern struct ItemModelFileRecord PitemZ_entries[];

extern ModelSkeleton prop_cctv_related;
extern ModelSkeleton prop_console_one_screen_related;
extern ModelSkeleton prop_console_four_screen_related;
extern ModelSkeleton prop_tv_holder_related;
extern ModelSkeleton prop_rotating_stuff_related;
extern ModelSkeleton prop_eyelid_door_related;
extern ModelSkeleton prop_iris_door_related;
extern ModelSkeleton prop_walletbond_related;
extern ModelSkeleton prop_car_related;
extern ModelSkeleton prop_flying_related;
extern ModelSkeleton prop_door_related;
extern ModelSkeleton item_tank_related;
extern ModelSkeleton item_hat_related;
extern ModelSkeleton model_object_standard_object;
extern ModelSkeleton prop_weapon_related;
extern ModelSkeleton model_guard_character;
extern struct player_gait_header player_gait_hdr;
extern struct player_gait_pos_header player_gait_pos_hdr_1;
extern struct player_gait_pos_header player_gait_pos_hdr_2;
extern struct player_gait_pos_header player_gait_pos_hdr_3;
extern struct player_gait_object_entry player_gait_obj;
extern struct player_gait_position_entry player_gait_pos_1;
extern struct player_gait_position_entry player_gait_pos_2;
extern struct player_gait_position_entry player_gait_pos_3;

extern struct ModelFileHeader player_gait_object;

extern struct ModelFileHeader GwppkZ_struct;
extern struct ModelFileHeader GwppksilZ_struct;
extern struct ModelFileHeader Gtt33Z_struct;
extern struct ModelFileHeader GskorpianZ_struct;
extern struct ModelFileHeader Gak47Z_struct;
extern struct ModelFileHeader GuziZ_struct;
extern struct ModelFileHeader Gmp5kZ_struct;
extern struct ModelFileHeader Gmp5ksilZ_struct;
extern struct ModelFileHeader Gm16Z_struct;
extern struct ModelFileHeader Gfnp90Z_struct;
extern struct ModelFileHeader G8003C900_struct;
extern struct ModelFileHeader GrugerZ_struct;
extern struct ModelFileHeader GgoldengunZ_struct;
extern struct ModelFileHeader GshotgunZ_struct;
extern struct ModelFileHeader GautoshotZ_struct;
extern struct ModelFileHeader GgrenadelaunchZ_struct;
extern struct ModelFileHeader GspectreZ_struct;
extern struct ModelFileHeader GlaserZ_struct;
extern struct ModelFileHeader GrocketlaunchZ_struct;
extern struct ModelFileHeader GknifeZ_header;
extern struct ModelFileHeader GthrowknifeZ_struct;
extern struct ModelFileHeader GtaserZ_struct;
extern struct ModelFileHeader GremotemineZ_struct;
extern struct ModelFileHeader GproximitymineZ_struct;
extern struct ModelFileHeader GtimedmineZ_struct;
extern struct ModelFileHeader GtriggerZ_struct;
extern struct ModelFileHeader GgrenadeZ_struct;
extern struct ModelFileHeader GfistZ_header;
extern struct ModelFileHeader GsniperrifleZ_struct;
extern struct ModelFileHeader GcartridgeZ_struct;
extern struct ModelFileHeader GcartrifleZ_struct;
extern struct ModelFileHeader GcartblueZ_struct;
extern struct ModelFileHeader GcartshellZ_struct;
extern struct ModelFileHeader GjoypadZ_struct;
extern struct ModelFileHeader G8003CC00_struct;
extern struct ModelFileHeader G8003CC20_struct;
extern struct ModelFileHeader GbombcaseZ_struct;
extern struct ModelFileHeader GflarepistolZ_struct;
extern struct ModelFileHeader GpitongunZ_struct;
extern struct ModelFileHeader G8003CCA0_struct;
extern struct ModelFileHeader GsilverwppkZ_struct;
extern struct ModelFileHeader GgoldwppkZ_struct;
extern struct ModelFileHeader G8003CD00_struct;
extern struct ModelFileHeader GbungeeZ_struct;
extern struct ModelFileHeader GdoordecoderZ_struct;
extern struct ModelFileHeader GbombdefuserZ_struct;
extern struct ModelFileHeader GbugdetectorZ_struct;
extern struct ModelFileHeader GsafecrackercaseZ_struct;
extern struct ModelFileHeader GcameraZ_struct;
extern struct ModelFileHeader GlockexploderZ_struct;
extern struct ModelFileHeader GdoorexploderZ_struct;
extern struct ModelFileHeader GkeyanalysercaseZ_struct;
extern struct ModelFileHeader GweaponcaseZ_struct;
extern struct ModelFileHeader GkeycardZ_struct;
extern struct ModelFileHeader GkeyyaleZ_struct;
extern struct ModelFileHeader GkeyboltZ_struct;
extern struct ModelFileHeader GbugZ_struct;
extern struct ModelFileHeader GmicrocameraZ_struct;
extern struct ModelFileHeader GexplosivefloppyZ_struct;
extern struct ModelFileHeader GgoldeneyekeyZ_struct;
extern struct ModelFileHeader GpolarizedglassesZ_struct;
extern struct ModelFileHeader GcreditcardZ_struct;
extern struct ModelFileHeader GdarkglassesZ_struct;
extern struct ModelFileHeader GwatchidentifierZ_struct;
extern struct ModelFileHeader GwatchcommunicatorZ_struct;
extern struct ModelFileHeader GwatchlaserZ_struct;
extern struct ModelFileHeader GwatchgeigercounterZ_struct;
extern struct ModelFileHeader GwatchmagnetrepelZ_struct;
extern struct ModelFileHeader GwatchmagnetattractZ_struct;
extern struct ModelFileHeader GgaskeyringZ_struct;
extern struct ModelFileHeader GdatathiefZ_struct;
extern struct ModelFileHeader GbriefcaseZ_struct;
extern struct ModelFileHeader GblackboxZ_struct;
extern struct ModelFileHeader GplastiqueZ_struct;
extern struct ModelFileHeader GvideotapeZ_struct;
extern struct ModelFileHeader GclipboardZ_struct;
extern struct ModelFileHeader GstafflistZ_struct;
extern struct ModelFileHeader GdossierredZ_struct;
extern struct ModelFileHeader GaudiotapeZ_struct;
extern struct ModelFileHeader GdattapeZ_struct;
extern struct ModelFileHeader GplansZ_struct;
extern struct ModelFileHeader GspyfileZ_struct;
extern struct ModelFileHeader GblueprintsZ_struct;
extern struct ModelFileHeader GcircuitboardZ_struct;
extern struct ModelFileHeader GmapZ_struct;
extern struct ModelFileHeader GspooltapeZ_struct;
extern struct ModelFileHeader GmicrofilmZ_struct;
extern struct ModelFileHeader GmicrocodeZ_struct;
extern struct ModelFileHeader GlectreZ_struct;
extern struct ModelFileHeader GmoneyZ_struct;
extern struct ModelFileHeader GgoldbarZ_struct;
extern struct ModelFileHeader GheroinZ_struct;
extern ModelSkeleton weapon_gun_controller;

extern struct ModelFileHeader CcamguardZ_struct;
extern struct ModelFileHeader CgreyguardZ_struct;
extern struct ModelFileHeader ColiveguardZ_struct;
extern struct ModelFileHeader CrusguardZ_struct;
extern struct ModelFileHeader CtrevguardZ_struct;
extern struct ModelFileHeader CborisZ_struct;
extern struct ModelFileHeader CorumovZ_struct;
extern struct ModelFileHeader CtrevelyanZ_struct;
extern struct ModelFileHeader CboilertrevZ_struct;
extern struct ModelFileHeader CvalentinZ_struct;
extern struct ModelFileHeader CxeniaZ_struct;
extern struct ModelFileHeader CbaronsamediZ_struct;
extern struct ModelFileHeader CjawsZ_struct;
extern struct ModelFileHeader CmaydayZ_struct;
extern struct ModelFileHeader CoddjobZ_struct;
extern struct ModelFileHeader CnatalyaZ_struct;
extern struct ModelFileHeader CarmourguardZ_struct;
extern struct ModelFileHeader CcommguardZ_struct;
extern struct ModelFileHeader CgreatguardZ_struct;
extern struct ModelFileHeader CnavyguardZ_struct;
extern struct ModelFileHeader CsnowguardZ_struct;
extern struct ModelFileHeader CbluewomanZ_struct;
extern struct ModelFileHeader CfattechwomanZ_struct;
extern struct ModelFileHeader CtechwomanZ_struct;
extern struct ModelFileHeader CjeanwomanZ_struct;
extern struct ModelFileHeader CgreymanZ_struct;
extern struct ModelFileHeader CbluemanZ_struct;
extern struct ModelFileHeader CredmanZ_struct;
extern struct ModelFileHeader CcardimanZ_struct;
extern struct ModelFileHeader CcheckmanZ_struct;
extern struct ModelFileHeader CtechmanZ_struct;
extern struct ModelFileHeader CpilotZ_struct;
extern struct ModelFileHeader Cgreatguard2Z_struct;
extern struct ModelFileHeader CbluecamguardZ_struct;
extern struct ModelFileHeader CmoonguardZ_struct;
extern struct ModelFileHeader CmoonfemaleZ_struct;
extern struct ModelFileHeader CboilerbondZ_struct;
extern struct ModelFileHeader CsuitbondZ_struct;
extern struct ModelFileHeader CtimberbondZ_struct;
extern struct ModelFileHeader CsnowbondZ_struct;
extern struct ModelFileHeader CdjbondZ_struct;
extern struct ModelFileHeader Csuit_lf_handz_struct;
extern struct ModelFileHeader CheadkarlZ_struct;
extern struct ModelFileHeader CheadalanZ_struct;
extern struct ModelFileHeader CheadpeteZ_struct;
extern struct ModelFileHeader CheadmartinZ_struct;
extern struct ModelFileHeader stru_D_8003D9D0;
extern struct ModelFileHeader stru_D_8003D9F0;
extern struct ModelFileHeader stru_D_8003DA10;
extern struct ModelFileHeader stru_D_8003DA30;
extern struct ModelFileHeader stru_D_8003DA50;
extern struct ModelFileHeader stru_D_8003DA70;
extern struct ModelFileHeader stru_D_8003DA90;
extern struct ModelFileHeader stru_D_8003DAB0;
extern struct ModelFileHeader stru_D_8003DAD0;
extern struct ModelFileHeader stru_D_8003DAF0;
extern struct ModelFileHeader stru_D_8003DB10;
extern struct ModelFileHeader stru_D_8003DB30;
extern struct ModelFileHeader stru_D_8003DB50;
extern struct ModelFileHeader stru_D_8003DB70;
extern struct ModelFileHeader stru_D_8003DB90;
extern struct ModelFileHeader stru_D_8003DBB0;
extern struct ModelFileHeader stru_D_8003DBD0;
extern struct ModelFileHeader stru_D_8003DBF0;
extern struct ModelFileHeader stru_D_8003DC10;
extern struct ModelFileHeader stru_D_8003DC30;
extern struct ModelFileHeader stru_D_8003DC50;
extern struct ModelFileHeader stru_D_8003DC70;
extern struct ModelFileHeader stru_D_8003DC90;
extern struct ModelFileHeader stru_D_8003DCB0;
extern struct ModelFileHeader stru_D_8003DCD0;
extern struct ModelFileHeader stru_D_8003DCF0;
extern struct ModelFileHeader stru_D_8003DD10;
extern struct ModelFileHeader stru_D_8003DD30;
extern struct ModelFileHeader stru_D_8003DD50;
extern struct ModelFileHeader CheadbrosnansuitZ_struct;
extern struct ModelFileHeader CheadbrosnantimberZ_struct;
extern struct ModelFileHeader CheadbrosnansnowZ_struct;
extern struct ModelFileHeader CheadbrosnanZ_struct;
extern struct ModelFileHeader CspicebondZ_struct;

extern struct ModelFileHeader Palarm1z_header;
extern struct ModelFileHeader Palarm2Z_header;
extern struct ModelFileHeader PexplosionbitZ_header;
extern struct ModelFileHeader Pammo_crate1Z_header;
extern struct ModelFileHeader Pammo_crate2Z_header;
extern struct ModelFileHeader Pammo_crate3Z_header;
extern struct ModelFileHeader Pammo_crate4Z_header;
extern struct ModelFileHeader Pammo_crate5Z_header;
extern struct ModelFileHeader Pbin1Z_header;
extern struct ModelFileHeader Pblotter1Z_header;
extern struct ModelFileHeader Pbook1Z_header;
extern struct ModelFileHeader Pbookshelf1Z_header;
extern struct ModelFileHeader Pbridge_console1aZ_header;
extern struct ModelFileHeader Pbridge_console1bZ_header;
extern struct ModelFileHeader Pbridge_console2aZ_header;
extern struct ModelFileHeader Pbridge_console2bZ_header;
extern struct ModelFileHeader Pbridge_console3aZ_header;
extern struct ModelFileHeader Pbridge_console3bZ_header;
extern struct ModelFileHeader Pcard_box1Z_header;
extern struct ModelFileHeader Pcard_box2Z_header;
extern struct ModelFileHeader Pcard_box3Z_header;
extern struct ModelFileHeader Pcard_box4_lgZ_header;
extern struct ModelFileHeader Pcard_box5_lgZ_header;
extern struct ModelFileHeader Pcard_box6_lgZ_header;
extern struct ModelFileHeader PcctvZ_header;
extern struct ModelFileHeader Pconsole1Z_header;
extern struct ModelFileHeader Pconsole2Z_header;
extern struct ModelFileHeader Pconsole3Z_header;
extern struct ModelFileHeader Pconsole_sevaZ_header;
extern struct ModelFileHeader Pconsole_sevbZ_header;
extern struct ModelFileHeader Pconsole_sevcZ_header;
extern struct ModelFileHeader Pconsole_sevdZ_header;
extern struct ModelFileHeader Pconsole_sev2aZ_header;
extern struct ModelFileHeader Pconsole_sev2bZ_header;
extern struct ModelFileHeader Pconsole_sev2cZ_header;
extern struct ModelFileHeader Pconsole_sev2dZ_header;
extern struct ModelFileHeader Pconsole_sev_GEaZ_header;
extern struct ModelFileHeader Pconsole_sev_GEbZ_header;
extern struct ModelFileHeader Pdesk1Z_header;
extern struct ModelFileHeader Pdesk2Z_header;
extern struct ModelFileHeader Pdesk_lamp2Z_header;
extern struct ModelFileHeader Pdisc_readerZ_header;
extern struct ModelFileHeader Pdisk_drive1Z_header;
extern struct ModelFileHeader Pfiling_cabinet1Z_header;
extern struct ModelFileHeader Pjerry_can1Z_header;
extern struct ModelFileHeader Pkeyboard1Z_header;
extern struct ModelFileHeader Pkit_units1Z_header;
extern struct ModelFileHeader Pletter_tray1Z_header;
extern struct ModelFileHeader Pmainframe1Z_header;
extern struct ModelFileHeader Pmainframe2Z_header;
extern struct ModelFileHeader Pmetal_chair1Z_header;
extern struct ModelFileHeader Pmetal_crate1Z_header;
extern struct ModelFileHeader Pmetal_crate2Z_header;
extern struct ModelFileHeader Pmetal_crate3Z_header;
extern struct ModelFileHeader Pmetal_crate4Z_header;
extern struct ModelFileHeader Pmissile_rackZ_header;
extern struct ModelFileHeader Pmissile_rack2Z_header;
extern struct ModelFileHeader Poil_drum1Z_header;
extern struct ModelFileHeader Poil_drum2Z_header;
extern struct ModelFileHeader Poil_drum3Z_header;
extern struct ModelFileHeader Poil_drum5Z_header;
extern struct ModelFileHeader Poil_drum6Z_header;
extern struct ModelFileHeader Poil_drum7Z_header;
extern struct ModelFileHeader PpadlockZ_header;
extern struct ModelFileHeader Pphone1Z_header;
extern struct ModelFileHeader Pradio_unit1Z_header;
extern struct ModelFileHeader Pradio_unit2Z_header;
extern struct ModelFileHeader Pradio_unit3Z_header;
extern struct ModelFileHeader Pradio_unit4Z_header;
extern struct ModelFileHeader Psat1_reflectZ_header;
extern struct ModelFileHeader PsatdishZ_header;
extern struct ModelFileHeader PsatboxZ_header;
extern struct ModelFileHeader Pstool1Z_header;
extern struct ModelFileHeader Pswivel_chair1Z_header;
extern struct ModelFileHeader Ptorpedo_rackZ_header;
extern struct ModelFileHeader Ptv1Z_header;
extern struct ModelFileHeader Ptv_holderZ_header;
extern struct ModelFileHeader PtvscreenZ_header;
extern struct ModelFileHeader Ptv4screenZ_header;
extern struct ModelFileHeader Pwood_lg_crate1Z_header;
extern struct ModelFileHeader Pwood_lg_crate2Z_header;
extern struct ModelFileHeader Pwood_md_crate3Z_header;
extern struct ModelFileHeader Pwood_sm_crate4Z_header;
extern struct ModelFileHeader Pwood_sm_crate5Z_header;
extern struct ModelFileHeader Pwood_sm_crate6Z_header;
extern struct ModelFileHeader Pwooden_table1Z_header;
extern struct ModelFileHeader Pswipe_card2Z_header;
extern struct ModelFileHeader Pborg_crateZ_header;
extern struct ModelFileHeader Pboxes4x4Z_header;
extern struct ModelFileHeader Pboxes3x4Z_header;
extern struct ModelFileHeader Pboxes2x4Z_header;
extern struct ModelFileHeader Psec_panelZ_header;
extern struct ModelFileHeader PICBM_noseZ_header;
extern struct ModelFileHeader PICBMZ_header;
extern struct ModelFileHeader Ptuning_console1Z_header;
extern struct ModelFileHeader Pdesk_arecibo1Z_header;
extern struct ModelFileHeader Plocker3Z_header;
extern struct ModelFileHeader Plocker4Z_header;
extern struct ModelFileHeader ProofgunZ_header;
extern struct ModelFileHeader Pdest_engineZ_header;
extern struct ModelFileHeader Pdest_exocetZ_header;
extern struct ModelFileHeader Pdest_gunZ_header;
extern struct ModelFileHeader Pdest_harpoonZ_header;
extern struct ModelFileHeader Pdest_seawolfZ_header;
extern struct ModelFileHeader PwindowZ_header;
extern struct ModelFileHeader Pwindow_lib_lg1Z_header;
extern struct ModelFileHeader Pwindow_lib_sm1Z_header;
extern struct ModelFileHeader Pwindow_cor11Z_header;
extern struct ModelFileHeader Pjungle3_treeZ_header;
extern struct ModelFileHeader PpalmZ_header;
extern struct ModelFileHeader PpalmtreeZ_header;
extern struct ModelFileHeader Pplant2bZ_header;
extern struct ModelFileHeader PlabbenchZ_header;
extern struct ModelFileHeader PgasbarrelZ_header;
extern struct ModelFileHeader PgasbarrelsZ_header;
extern struct ModelFileHeader PbodyarmourZ_header;
extern struct ModelFileHeader PbodyarmourvestZ_header;
extern struct ModelFileHeader PgastankZ_header;
extern struct ModelFileHeader Pglassware1Z_header;
extern struct ModelFileHeader PhatchboltZ_header;
extern struct ModelFileHeader PbrakeunitZ_header;
extern struct ModelFileHeader Pak47magZ_header;
extern struct ModelFileHeader Pm16magZ_header;
extern struct ModelFileHeader Pmp5kmagZ_header;
extern struct ModelFileHeader PskorpionmagZ_header;
extern struct ModelFileHeader PspectremagZ_header;
extern struct ModelFileHeader PuzimagZ_header;
extern struct ModelFileHeader PsilencerZ_header;
extern struct ModelFileHeader PchrextinguisherZ_header;
extern struct ModelFileHeader PboxcartridgesZ_header;
extern struct ModelFileHeader Pfnp90magZ_header;
extern struct ModelFileHeader PgoldenshellsZ_header;
extern struct ModelFileHeader PmagnumshellsZ_header;
extern struct ModelFileHeader PwppkmagZ_header;
extern struct ModelFileHeader Ptt33magZ_header;
extern struct ModelFileHeader Psev_doorZ_header;
extern struct ModelFileHeader Psev_door3Z_header;
extern struct ModelFileHeader Psev_door3_windZ_header;
extern struct ModelFileHeader Psev_door4_windZ_header;
extern struct ModelFileHeader Psev_trislideZ_header;
extern struct ModelFileHeader Psev_door_v1Z_header;
extern struct ModelFileHeader Psteel_door1Z_header;
extern struct ModelFileHeader Psteel_door2Z_header;
extern struct ModelFileHeader Psteel_door3Z_header;
extern struct ModelFileHeader Psilo_lift_doorZ_header;
extern struct ModelFileHeader Psteel_door2bZ_header;
extern struct ModelFileHeader Pdoor_roller1Z_header;
extern struct ModelFileHeader Pdoor_roller2Z_header;
extern struct ModelFileHeader Pdoor_roller3Z_header;
extern struct ModelFileHeader Pdoor_roller4Z_header;
extern struct ModelFileHeader Pdoor_st_arec1Z_header;
extern struct ModelFileHeader Pdoor_st_arec2Z_header;
extern struct ModelFileHeader Pdoor_dest1Z_header;
extern struct ModelFileHeader Pdoor_dest2Z_header;
extern struct ModelFileHeader Pgas_plant_sw_do1Z_header;
extern struct ModelFileHeader Pgas_plant_sw2_do1Z_header;
extern struct ModelFileHeader Pgas_plant_sw3_do1Z_header;
extern struct ModelFileHeader Pgas_plant_sw4_do1Z_header;
extern struct ModelFileHeader Pgas_plant_met1_do1Z_header;
extern struct ModelFileHeader Pgas_plant_wc_cub1Z_header;
extern struct ModelFileHeader Pgasplant_clear_doorZ_header;
extern struct ModelFileHeader Ptrain_doorZ_header;
extern struct ModelFileHeader Ptrain_door2Z_header;
extern struct ModelFileHeader Ptrain_door3Z_header;
extern struct ModelFileHeader Pdoor_eyelidZ_header;
extern struct ModelFileHeader Pdoor_irisZ_header;
extern struct ModelFileHeader PsevdoorwoodZ_header;
extern struct ModelFileHeader PsevdoorwindZ_header;
extern struct ModelFileHeader PsevdoornowindZ_header;
extern struct ModelFileHeader PsevdoormetslideZ_header;
extern struct ModelFileHeader Pcryptdoor1aZ_header;
extern struct ModelFileHeader Pcryptdoor1bZ_header;
extern struct ModelFileHeader Pcryptdoor2aZ_header;
extern struct ModelFileHeader Pcryptdoor2bZ_header;
extern struct ModelFileHeader Pcryptdoor3Z_header;
extern struct ModelFileHeader Pcryptdoor4Z_header;
extern struct ModelFileHeader PvertdoorZ_header;
extern struct ModelFileHeader PhatchdoorZ_header;
extern struct ModelFileHeader PdamgatedoorZ_header;
extern struct ModelFileHeader PdamtundoorZ_header;
extern struct ModelFileHeader PdamchaindoorZ_header;
extern struct ModelFileHeader PsilotopdoorZ_header;
extern struct ModelFileHeader Pdoorprison1Z_header;
extern struct ModelFileHeader PdoorstatgateZ_header;
extern struct ModelFileHeader PchrkalashZ_header;
extern struct ModelFileHeader PchrgrenadelaunchZ_header;
extern struct ModelFileHeader PchrknifeZ_header;
extern struct ModelFileHeader PchrlaserZ_header;
extern struct ModelFileHeader Pchrm16Z_header;
extern struct ModelFileHeader Pchrmp5kZ_header;
extern struct ModelFileHeader PchrrugerZ_header;
extern struct ModelFileHeader PchrwppkZ_header;
extern struct ModelFileHeader PchrshotgunZ_header;
extern struct ModelFileHeader PchrskorpionZ_header;
extern struct ModelFileHeader PchrspectreZ_header;
extern struct ModelFileHeader PchruziZ_header;
extern struct ModelFileHeader PchrgrenadeZ_header;
extern struct ModelFileHeader Pchrfnp90Z_header;
extern struct ModelFileHeader PchrbriefcaseZ_header;
extern struct ModelFileHeader PchrremotemineZ_header;
extern struct ModelFileHeader PchrproximitymineZ_header;
extern struct ModelFileHeader PchrtimedmineZ_header;
extern struct ModelFileHeader PchrrocketZ_header;
extern struct ModelFileHeader PchrgrenaderoundZ_header;
extern struct ModelFileHeader PchrwppksilZ_header;
extern struct ModelFileHeader Pchrtt33Z_header;
extern struct ModelFileHeader Pchrmp5ksilZ_header;
extern struct ModelFileHeader PchrautoshotZ_header;
extern struct ModelFileHeader PchrgoldenZ_header;
extern struct ModelFileHeader PchrthrowknifeZ_header;
extern struct ModelFileHeader PchrsniperrifleZ_header;
extern struct ModelFileHeader PchrrocketlaunchZ_header;
extern struct ModelFileHeader PhatfurryZ_header;
extern struct ModelFileHeader PhatfurrybrownZ_header;
extern struct ModelFileHeader PhatfurryblackZ_header;
extern struct ModelFileHeader PhattbirdZ_header;
extern struct ModelFileHeader PhattbirdbrownZ_header;
extern struct ModelFileHeader PhathelmetZ_header;
extern struct ModelFileHeader PhathelmetgreyZ_header;
extern struct ModelFileHeader PhatmoonZ_header;
extern struct ModelFileHeader PhatberetZ_header;
extern struct ModelFileHeader PhatberetblueZ_header;
extern struct ModelFileHeader PhatberetredZ_header;
extern struct ModelFileHeader PhatpeakedZ_header;
extern struct ModelFileHeader PchrwristdartZ_header;
extern struct ModelFileHeader PchrexplosivepenZ_header;
extern struct ModelFileHeader PchrbombcaseZ_header;
extern struct ModelFileHeader PchrflarepistolZ_header;
extern struct ModelFileHeader PchrpitongunZ_header;
extern struct ModelFileHeader PchrfingergunZ_header;
extern struct ModelFileHeader PchrsilverwppkZ_header;
extern struct ModelFileHeader PchrgoldwppkZ_header;
extern struct ModelFileHeader PchrdynamiteZ_header;
extern struct ModelFileHeader PchrbungeeZ_header;
extern struct ModelFileHeader PchrdoordecoderZ_header;
extern struct ModelFileHeader PchrbombdefuserZ_header;
extern struct ModelFileHeader PchrbugdetectorZ_header;
extern struct ModelFileHeader PchrsafecrackercaseZ_header;
extern struct ModelFileHeader PchrcameraZ_header;
extern struct ModelFileHeader PchrlockexploderZ_header;
extern struct ModelFileHeader PchrdoorexploderZ_header;
extern struct ModelFileHeader PchrkeyanalysercaseZ_header;
extern struct ModelFileHeader PchrweaponcaseZ_header;
extern struct ModelFileHeader PchrkeyyaleZ_header;
extern struct ModelFileHeader PchrkeyboltZ_header;
extern struct ModelFileHeader PchrbugZ_header;
extern struct ModelFileHeader PchrmicrocameraZ_header;
extern struct ModelFileHeader PfloppyZ_header;
extern struct ModelFileHeader PchrgoldeneyekeyZ_header;
extern struct ModelFileHeader PchrpolarizedglassesZ_header;
extern struct ModelFileHeader PchrcreditcardZ_header;
extern struct ModelFileHeader PchrdarkglassesZ_header;
extern struct ModelFileHeader PchrgaskeyringZ_header;
extern struct ModelFileHeader PchrdatathiefZ_header;
extern struct ModelFileHeader PsafeZ_header;
extern struct ModelFileHeader PbombZ_header;
extern struct ModelFileHeader PchrplansZ_header;
extern struct ModelFileHeader PchrspyfileZ_header;
extern struct ModelFileHeader PchrblueprintsZ_header;
extern struct ModelFileHeader PchrcircuitboardZ_header;
extern struct ModelFileHeader PchrmapZ_header;
extern struct ModelFileHeader PchrspooltapeZ_header;
extern struct ModelFileHeader PchraudiotapeZ_header;
extern struct ModelFileHeader PchrmicrofilmZ_header;
extern struct ModelFileHeader PchrmicrocodeZ_header;
extern struct ModelFileHeader PchrlectreZ_header;
extern struct ModelFileHeader PchrmoneyZ_header;
extern struct ModelFileHeader PchrgoldbarZ_header;
extern struct ModelFileHeader PchrheroinZ_header;
extern struct ModelFileHeader PchrclipboardZ_header;
extern struct ModelFileHeader PchrdossierredZ_header;
extern struct ModelFileHeader PchrstafflistZ_header;
extern struct ModelFileHeader PchrdattapeZ_header;
extern struct ModelFileHeader PchrplastiqueZ_header;
extern struct ModelFileHeader PchrblackboxZ_header;
extern struct ModelFileHeader PchrvideotapeZ_header;
extern struct ModelFileHeader PnintendologoZ_header;
extern struct ModelFileHeader PgoldeneyelogoZ_header;
extern struct ModelFileHeader PwalletbondZ_header;
extern struct ModelFileHeader PmiltruckZ_header;
extern struct ModelFileHeader PjeepZ_header;
extern struct ModelFileHeader ParticZ_header;
extern struct ModelFileHeader PhelicopterZ_header;
extern struct ModelFileHeader PtigerZ_header;
extern struct ModelFileHeader PmilcopterZ_header;
extern struct ModelFileHeader PhindZ_header;
extern struct ModelFileHeader PartictrailerZ_header;
extern struct ModelFileHeader PmotorbikeZ_header;
extern struct ModelFileHeader PtankZ_header;
extern struct ModelFileHeader PapcZ_header;
extern struct ModelFileHeader PspeedboatZ_header;
extern struct ModelFileHeader PplaneZ_header;
extern struct ModelFileHeader Pgun_runway1Z_header;
extern struct ModelFileHeader PsafedoorZ_header;
extern struct ModelFileHeader Pkey_holderZ_header;
extern struct ModelFileHeader PhatchsevxZ_header;
extern struct ModelFileHeader PsevdishZ_header;
extern struct ModelFileHeader Parchsecdoor1Z_header;
extern struct ModelFileHeader Parchsecdoor2Z_header;
extern struct ModelFileHeader PgroundgunZ_header;
extern struct ModelFileHeader PtrainextdoorZ_header;
extern struct ModelFileHeader PcarbmwZ_header;
extern struct ModelFileHeader PcarescortZ_header;
extern struct ModelFileHeader PcargolfZ_header;
extern struct ModelFileHeader PcarweirdZ_header;
extern struct ModelFileHeader PcarzilZ_header;
extern struct ModelFileHeader Pshuttle_door_lZ_header;
extern struct ModelFileHeader Pshuttle_door_rZ_header;
extern struct ModelFileHeader Pdepot_gate_entryZ_header;
extern struct ModelFileHeader Pdepot_door_steelZ_header;
extern struct ModelFileHeader Pglassware2Z_header;
extern struct ModelFileHeader Pglassware3Z_header;
extern struct ModelFileHeader Pglassware4Z_header;
extern struct ModelFileHeader PlandmineZ_header;
extern struct ModelFileHeader Pplant1Z_header;
extern struct ModelFileHeader Pplant11Z_header;
extern struct ModelFileHeader Pplant2Z_header;
extern struct ModelFileHeader Pplant3Z_header;
extern struct ModelFileHeader Pjungle5_treeZ_header;
extern struct ModelFileHeader PlegalpageZ_header;
extern struct ModelFileHeader Pst_pete_room_1iZ_header;
extern struct ModelFileHeader Pst_pete_room_2iZ_header;
extern struct ModelFileHeader Pst_pete_room_3tZ_header;
extern struct ModelFileHeader Pst_pete_room_5cZ_header;
extern struct ModelFileHeader Pst_pete_room_6cZ_header;
extern struct ModelFileHeader Pdoor_rollertrainZ_header;
extern struct ModelFileHeader Pdoor_winZ_header;
extern struct ModelFileHeader Pdoor_aztecZ_header;
extern struct ModelFileHeader PshuttleZ_header;
extern struct ModelFileHeader Pdoor_azt_deskZ_header;
extern struct ModelFileHeader Pdoor_azt_desk_topZ_header;
extern struct ModelFileHeader Pdoor_azt_chairZ_header;
extern struct ModelFileHeader Pdoor_mfZ_header;
extern struct ModelFileHeader PflagZ_header;
extern struct ModelFileHeader PbarricadeZ_header;
extern struct ModelFileHeader PmodemboxZ_header;
extern struct ModelFileHeader PdoorpanelZ_header;
extern struct ModelFileHeader PdoorconsoleZ_header;
extern struct ModelFileHeader PchrtesttubeZ_header;
extern struct ModelFileHeader Pbollardz_header;

extern struct ChrModelFileRecord c_item_entries[];
extern ModelSkeleton model_guard_character;
extern ModelSkeleton model_suit_lf_hand;
#endif
