TARGET = ge007.u
LD_SCRIPT = $(TARGET).ld
OBSEG_DIR = obseg

$(OBSEG_DIR)/text/%.bin: $(OBSEG_DIR)/text/%.asm
	$(BASS) -o $@ $<

TEXT_RZ_FILES = \
    $(OBSEG_DIR)/text/LameE.rz \
    $(OBSEG_DIR)/text/LarchE.rz \
    $(OBSEG_DIR)/text/LarecE.rz \
    $(OBSEG_DIR)/text/LarkE.rz \
    $(OBSEG_DIR)/text/LashE.rz \
    $(OBSEG_DIR)/text/LaztE.rz \
    $(OBSEG_DIR)/text/LcatE.rz \
    $(OBSEG_DIR)/text/LcaveE.rz \
    $(OBSEG_DIR)/text/LcradE.rz \
    $(OBSEG_DIR)/text/LcrypE.rz \
    $(OBSEG_DIR)/text/LdamE.rz \
    $(OBSEG_DIR)/text/LdepoE.rz \
    $(OBSEG_DIR)/text/LdestE.rz \
    $(OBSEG_DIR)/text/LdishE.rz \
    $(OBSEG_DIR)/text/LearE.rz \
    $(OBSEG_DIR)/text/LeldE.rz \
    $(OBSEG_DIR)/text/LgunE.rz \
    $(OBSEG_DIR)/text/LimpE.rz \
    $(OBSEG_DIR)/text/LjunE.rz \
    $(OBSEG_DIR)/text/LleeE.rz \
    $(OBSEG_DIR)/text/LlenE.rz \
    $(OBSEG_DIR)/text/LlipE.rz \
    $(OBSEG_DIR)/text/LlueE.rz \
    $(OBSEG_DIR)/text/LmiscE.rz \
    $(OBSEG_DIR)/text/LmpmenuE.rz \
    $(OBSEG_DIR)/text/LmpweaponsE.rz \
    $(OBSEG_DIR)/text/LoatE.rz \
    $(OBSEG_DIR)/text/LoptionsE.rz \
    $(OBSEG_DIR)/text/LpamE.rz \
    $(OBSEG_DIR)/text/LpeteE.rz \
    $(OBSEG_DIR)/text/LpropobjE.rz \
    $(OBSEG_DIR)/text/LrefE.rz \
    $(OBSEG_DIR)/text/LritE.rz \
    $(OBSEG_DIR)/text/LrunE.rz \
    $(OBSEG_DIR)/text/LsevbE.rz \
    $(OBSEG_DIR)/text/LsevE.rz \
    $(OBSEG_DIR)/text/LsevxbE.rz \
    $(OBSEG_DIR)/text/LsevxE.rz \
    $(OBSEG_DIR)/text/LshoE.rz \
    $(OBSEG_DIR)/text/LsiloE.rz \
    $(OBSEG_DIR)/text/LstatE.rz \
    $(OBSEG_DIR)/text/LtitleE.rz \
    $(OBSEG_DIR)/text/LtraE.rz \
    $(OBSEG_DIR)/text/LwaxE.rz


MUSIC_RZ_FILES = \
    music/music_archives.rz \
    music/music_archivesx.rz \
    music/music_aztec.rz \
    music/music_aztecx.rz \
    music/music_bunker1.rz \
    music/music_bunker1x.rz \
    music/music_bunker2.rz \
    music/music_bunker2x.rz \
    music/music_citadel.rz \
    music/music_control.rz \
    music/music_controlx.rz \
    music/music_cradle.rz \
    music/music_cradlex.rz \
    music/music_cuba.rz \
    music/music_dam.rz \
    music/music_damx.rz \
    music/music_deathsolo.rz \
    music/music_depot.rz \
    music/music_depotx.rz \
    music/music_egyptian.rz \
    music/music_egyptianx.rz \
    music/music_elevator_control.rz \
    music/music_elevator_wc.rz \
    music/music_facility.rz \
    music/music_facilityx.rz \
    music/music_folders.rz \
    music/music_frigate_outro.rz \
    music/music_frigate.rz \
    music/music_frigatex.rz \
    music/music_intro_eye.rz \
    music/music_jungle_perimeter_unused.rz \
    music/music_jungle.rz \
    music/music_jungle_unused.rz \
    music/music_junglex.rz \
    music/music_multideath_alt.rz \
    music/music_multiplayerdeath.rz \
    music/music_nint_rare_logo.rz \
    music/music_no_music.rz \
    music/music_null.rz \
    music/music_runway_plane.rz \
    music/music_runway.rz \
    music/music_runwayx.rz \
    music/music_silo.rz \
    music/music_silox.rz \
    music/music_solo_death_abrev.rz \
    music/music_statue_ending.rz \
    music/music_statue.rz \
    music/music_statuex.rz \
    music/music_streets.rz \
    music/music_streetsx.rz \
    music/music_surface1.rz \
    music/music_surface2_ending.rz \
    music/music_surface2.rz \
    music/music_surfacex.rz \
    music/music_train.rz \
    music/music_trainx.rz \
    music/music_watchmusic.rz \
    music/music_watercaverns.rz \
    music/music_watercavernsx.rz \
    music/music_windblowing.rz
