TARGET = ge007.u
LD_SCRIPT = $(TARGET).ld
OBSEG_DIR = obseg

$(OBSEG_DIR)/text/%.bin: $(OBSEG_DIR)/text/%.asm
	$(BASS) -o $@ $<

TEXT_RZ_FILES = \
    $(OBSEG_DIR)/text/LameE.rz \
    $(OBSEG_DIR)/text/LarchE.rz \
    $(OBSEG_DIR)/text/LarecE.rz \
    $(OBSEG_DIR)/text/LarkE.rz \
    $(OBSEG_DIR)/text/LashE.rz \
    $(OBSEG_DIR)/text/LaztE.rz \
    $(OBSEG_DIR)/text/LcatE.rz \
    $(OBSEG_DIR)/text/LcaveE.rz \
    $(OBSEG_DIR)/text/LcradE.rz \
    $(OBSEG_DIR)/text/LcrypE.rz \
    $(OBSEG_DIR)/text/LdamE.rz \
    $(OBSEG_DIR)/text/LdepoE.rz \
    $(OBSEG_DIR)/text/LdestE.rz \
    $(OBSEG_DIR)/text/LdishE.rz \
    $(OBSEG_DIR)/text/LearE.rz \
    $(OBSEG_DIR)/text/LeldE.rz \
    $(OBSEG_DIR)/text/LgunE.rz \
    $(OBSEG_DIR)/text/LimpE.rz \
    $(OBSEG_DIR)/text/LjunE.rz \
    $(OBSEG_DIR)/text/LleeE.rz \
    $(OBSEG_DIR)/text/LlenE.rz \
    $(OBSEG_DIR)/text/LlipE.rz \
    $(OBSEG_DIR)/text/LlueE.rz \
    $(OBSEG_DIR)/text/LmiscE.rz \
    $(OBSEG_DIR)/text/LmpmenuE.rz \
    $(OBSEG_DIR)/text/LmpweaponsE.rz \
    $(OBSEG_DIR)/text/LoatE.rz \
    $(OBSEG_DIR)/text/LoptionsE.rz \
    $(OBSEG_DIR)/text/LpamE.rz \
    $(OBSEG_DIR)/text/LpeteE.rz \
    $(OBSEG_DIR)/text/LpropobjE.rz \
    $(OBSEG_DIR)/text/LrefE.rz \
    $(OBSEG_DIR)/text/LritE.rz \
    $(OBSEG_DIR)/text/LrunE.rz \
    $(OBSEG_DIR)/text/LsevbE.rz \
    $(OBSEG_DIR)/text/LsevE.rz \
    $(OBSEG_DIR)/text/LsevxbE.rz \
    $(OBSEG_DIR)/text/LsevxE.rz \
    $(OBSEG_DIR)/text/LshoE.rz \
    $(OBSEG_DIR)/text/LsiloE.rz \
    $(OBSEG_DIR)/text/LstatE.rz \
    $(OBSEG_DIR)/text/LtitleE.rz \
    $(OBSEG_DIR)/text/LtraE.rz \
    $(OBSEG_DIR)/text/LwaxE.rz


MUSIC_RZ_FILES = \
    music/Marchives.rz \
    music/Marchivesx.rz \
    music/Maztec.rz \
    music/Maztecx.rz \
    music/Mbunker1.rz \
    music/Mbunker1x.rz \
    music/Mbunker2.rz \
    music/Mbunker2x.rz \
    music/Mcitadel.rz \
    music/Mcontrol.rz \
    music/Mcontrolx.rz \
    music/Mcradle.rz \
    music/Mcradlex.rz \
    music/Mcuba.rz \
    music/Mdam.rz \
    music/Mdamx.rz \
    music/Mdeathsolo.rz \
    music/Mdepot.rz \
    music/Mdepotx.rz \
    music/Megyptian.rz \
    music/Megyptianx.rz \
    music/Melevator_control.rz \
    music/Melevator_wc.rz \
    music/Mfacility.rz \
    music/Mfacilityx.rz \
    music/Mfolders.rz \
    music/Mfrigate_outro.rz \
    music/Mfrigate.rz \
    music/Mfrigatex.rz \
    music/Mintro_eye.rz \
    music/Mjungle_perimeter_unused.rz \
    music/Mjungle.rz \
    music/Mjungle_unused.rz \
    music/Mjunglex.rz \
    music/Mmultideath_alt.rz \
    music/Mmultiplayerdeath.rz \
    music/Mnint_rare_logo.rz \
    music/Mno_music.rz \
    music/Mnull1.rz \
    music/Mnull2.rz \
    music/Mnull3.rz \
    music/Mrunway_plane.rz \
    music/Mrunway.rz \
    music/Mrunwayx.rz \
    music/Msilo.rz \
    music/Msilox.rz \
    music/Msolo_death_abrev.rz \
    music/Mstatue_ending.rz \
    music/Mstatue.rz \
    music/Mstatuex.rz \
    music/Mstreets.rz \
    music/Mstreetsx.rz \
    music/Msurface1.rz \
    music/Msurface2_ending.rz \
    music/Msurface2.rz \
    music/Msurface1x.rz \
    music/Msurface2x.rz \
    music/Mtrain.rz \
    music/Mtrainx.rz \
    music/Mwatchmusic.rz \
    music/Mwatercaverns.rz \
    music/Mwatercavernsx.rz \
    music/Mwindblowing.rz
