BUILD_DIR := build

OBFILES := 
OBOBJECTS := $(BG_SEG_FILES) $(CHR_RZ_FILES) $(GUN_RZ_FILES) $(PROP_RZ_FILES) $(STAN_RZ_FILES) $(BRIEF_RZ_FILES) $(SETUP_RZ_FILES) $(TEXT_RZ_FILES)
OBSEGMENT := obsegment.o
OBSEG_DIR := assets/obseg


#bg
$(BUILD_DIR)/$(OBSEG_DIR)/bg/%.seg: $(OBSEG_DIR)/bg/%.bin
	$(MAKEBG) $< $@

BG_SEG_FILES = \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_sev_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_silo_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_stat_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_arec_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_arch_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_tra_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_dest_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_sevb_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_azt_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_pete_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_depo_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_ref_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_cryp_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_dam_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_ark_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_run_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_sevx_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_jun_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_dish_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_cave_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_cat_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_crad_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_imp_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_ash_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_ame_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_oat_all_p.seg \
	$(BUILD_DIR)/$(OBSEG_DIR)/bg/bg_len_all_p.seg 




#chr
$(BUILD_DIR)/$(OBSEG_DIR)/chr/%.rz: $(OBSEG_DIR)/chr/%.bin
	$(RZ_COMP) $< $@

CHR_RZ_FILES = \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CarmourguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CbaronsamediZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CbluecamguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CbluemanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CbluewomanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CboilerbondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CboilertrevZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CborisZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CcamguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CcardimanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CcheckmanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CcommguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CdjbondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CfattechwomanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/Cgreatguard2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CgreatguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CgreyguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CgreymanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadalanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbalaclavaZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbikeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbrosnanboilerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbrosnansnowZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbrosnansuitZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbrosnantimberZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbrosnanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadchrisZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheaddaveZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheaddesZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadduncanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheaddwayneZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadgrahamZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadgrantZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadjimZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/Cheadjoe2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadjoelZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadjoeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadkarlZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadkenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadleeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadmandyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadmarionZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadmarkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadmartinZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadmishkinZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadneilZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadpeteZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadrobinZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadsallyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadscottZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadshaunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadsteveeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadstevehZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CheadvivienZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CjawsZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CjeanwomanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CmaydayZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CmoonfemaleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CmoonguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CnatalyaZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CnavyguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CoddjobZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/ColiveguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CorumovZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CpilotZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CredmanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CrusguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CsnowbondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CsnowguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CspicebondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CsuitbondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/Csuit_lf_handZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CtechmanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CtechwomanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CtimberbondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CtrevelyanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CtrevguardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CvalentinZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/chr/CxeniaZ.rz




#gun
$(BUILD_DIR)/$(OBSEG_DIR)/gun/%.rz: $(OBSEG_DIR)/gun/%.bin
	$(RZ_COMP) $< $@

GUN_RZ_FILES = \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/Gak47Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GaudiotapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GautoshotZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GblackboxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GblueprintsZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GbombcaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GbombdefuserZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GbriefcaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GbugdetectorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GbugZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GbungeeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcameraZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcartblueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcartridgeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcartrifleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcartshellZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcircuitboardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GclipboardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GcreditcardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdarkglassesZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdatathiefZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdattapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdoordecoderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdoorexploderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdossierredZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GdynamiteZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GexplosivefloppyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GexplosivepenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GextinguisherZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GfingergunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GfistZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GflarepistolZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/Gfnp90Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgaskeyringZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgoldbarZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgoldeneyekeyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgoldengunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgoldwppkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgrenadelaunchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GgrenadeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GheroinZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GjoypadZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GkeyanalysercaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GkeyboltZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GkeycardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GkeyyaleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GknifeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GlaserZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GlectreZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GlockexploderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/Gm16Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GmapZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GmicrocameraZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GmicrocodeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GmicrofilmZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GmoneyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/Gmp5ksilZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/Gmp5kZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GpitongunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GplansZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GplastiqueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GpolarizedglassesZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GproximitymineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GremotemineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GrocketlaunchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GrugerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GsafecrackercaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GshotgunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GsilverwppkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GskorpionZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GsniperrifleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GspectreZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GspooltapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GspyfileZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GstafflistZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GtaserZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GthrowknifeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GtimedmineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GtriggerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/Gtt33Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GuziZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GvideotapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwatchcommunicatorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwatchgeigercounterZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwatchidentifierZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwatchlaserZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwatchmagnetattractZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwatchmagnetrepelZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GweaponcaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwppksilZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwppkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/gun/GwristdartZ.rz




#prop
$(BUILD_DIR)/$(OBSEG_DIR)/prop/%.rz: $(OBSEG_DIR)/prop/%.bin
	$(RZ_COMP) $< $@

PROP_RZ_FILES = \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pak47magZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Palarm1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Palarm2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pammo_crate1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pammo_crate2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pammo_crate3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pammo_crate4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pammo_crate5Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PapcZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Parchsecdoor1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Parchsecdoor2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PartictrailerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/ParticZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PbarricadeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbin1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pblotter1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PbodyarmourvestZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PbodyarmourZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PbollardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PbombZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbook1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbookshelf1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pborg_crateZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PboxcartridgesZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pboxes2x4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pboxes3x4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pboxes4x4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PbrakeunitZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbridge_console1aZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbridge_console1bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbridge_console2aZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbridge_console2bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbridge_console3aZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pbridge_console3bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PcarbmwZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcard_box1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcard_box2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcard_box3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcard_box4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcard_box5Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcard_box6Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PcarescortZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PcargolfZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PcarweirdZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PcarzilZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PcctvZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchraudiotapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrautoshotZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrblackboxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrblueprintsZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrbombcaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrbombdefuserZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrbriefcaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrbugdetectorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrbugZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrbungeeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrcameraZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrcircuitboardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrclipboardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrcreditcardZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdarkglassesZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdatathiefZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdattapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdoordecoderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdoorexploderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdossierredZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrdynamiteZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrexplosivepenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrextinguisherZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrfingergunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrflarepistolZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pchrfnp90Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgaskeyringZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgoldbarZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgoldeneyekeyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgoldenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgoldwppkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgrenadelaunchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgrenaderoundZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrgrenadeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrheroinZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrkalashZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrkeyanalysercaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrkeyboltZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrkeyyaleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrknifeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrlaserZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrlectreZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrlockexploderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pchrm16Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrmapZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrmicrocameraZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrmicrocodeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrmicrofilmZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrmoneyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pchrmp5ksilZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pchrmp5kZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrpitongunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrplansZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrplastiqueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrpolarizedglassesZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrproximitymineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrremotemineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrrocketlaunchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrrocketZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrrugerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrsafecrackercaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrshotgunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrsilverwppkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrskorpionZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrsniperrifleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrspectreZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrspooltapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrspyfileZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrstafflistZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrtesttubeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrthrowknifeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrtimedmineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pchrtt33Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchruziZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrvideotapeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrweaponcaseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrwppksilZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrwppkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PchrwristdartZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sev2aZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sev2bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sev2cZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sev2dZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sevaZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sevbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sevcZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sevdZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sev_GEaZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pconsole_sev_GEbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcryptdoor1aZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcryptdoor1bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcryptdoor2aZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcryptdoor2bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcryptdoor3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pcryptdoor4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PdamchaindoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PdamgatedoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PdamtundoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdepot_door_steelZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdepot_gate_entryZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdesk1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdesk2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdesk_arecibo1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdesk_lamp2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdest_engineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdest_exocetZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdest_gunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdest_harpoonZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdest_seawolfZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdisc_readerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdisk_drive1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_azt_chairZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_azt_desk_topZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_azt_deskZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_aztecZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PdoorconsoleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_dest1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_dest2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_eyelidZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_irisZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_mfZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PdoorpanelZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoorprison1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_roller1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_roller2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_roller3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_roller4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_rollertrainZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_st_arec1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_st_arec2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PdoorstatgateZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pdoor_winZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PexplosionbitZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pfiling_cabinet1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PflagZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PfloppyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pfnp90magZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PgasbarrelsZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PgasbarrelZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgasplant_clear_doorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgas_plant_met1_do1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgas_plant_sw2_do1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgas_plant_sw3_do1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgas_plant_sw4_do1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgas_plant_sw_do1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgas_plant_wc_cub1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PgastankZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pglassware1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pglassware2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pglassware3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pglassware4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PgoldeneyelogoZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PgoldenshellsZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PgroundgunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pgun_runway1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatberetblueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatberetredZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatberetZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatchboltZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatchdoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatchsevxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatfurryblackZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatfurrybrownZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatfurryZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhathelmetgreyZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhathelmetZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatmoonZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhatpeakedZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhattbirdbrownZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhattbirdZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhelicopterZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PhindZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PICBM_noseZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PICBMZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PjeepZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pjerry_can1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pjungle3_treeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pjungle5_treeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pkeyboard1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pkey_holderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pkit_units1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PlabbenchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PlandmineZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PlegalpageZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pletter_tray1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Plocker3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Plocker4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pm16magZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PmagnumshellsZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmainframe1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmainframe2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmetal_chair1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmetal_crate1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmetal_crate2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmetal_crate3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmetal_crate4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PmilcopterZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PmiltruckZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmissile_rack2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmissile_rackZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PmodemboxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PmotorbikeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pmp5kmagZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PnintendologoZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Poil_drum1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Poil_drum2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Poil_drum3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Poil_drum5Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Poil_drum6Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Poil_drum7Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PpadlockZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PpalmtreeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PpalmZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pphone1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PplaneZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pplant11Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pplant1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pplant2bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pplant2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pplant3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pradio_unit1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pradio_unit2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pradio_unit3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pradio_unit4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/ProofgunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsafedoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsafeZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psat1_reflectZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsatboxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsatdishZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psec_panelZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsevdishZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psev_door3_windZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psev_door3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psev_door4_windZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsevdoormetslideZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsevdoornowindZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psev_door_v1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsevdoorwindZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsevdoorwoodZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psev_doorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psev_trislideZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pshuttle_door_lZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pshuttle_door_rZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PshuttleZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsilencerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psilo_lift_doorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PsilotopdoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PskorpionmagZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PspectremagZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PspeedboatZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psteel_door1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psteel_door2bZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psteel_door2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Psteel_door3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pstool1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pst_pete_room_1iZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pst_pete_room_2iZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pst_pete_room_3tZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pst_pete_room_5cZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pst_pete_room_6cZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pswipe_card2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pswivel_chair1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PtankZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PtigerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptorpedo_rackZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptrain_door2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptrain_door3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptrain_doorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PtrainextdoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptt33magZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptuning_console1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptv1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptv4screenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Ptv_holderZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PtvscreenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PuzimagZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PvertdoorZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PwalletbondZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwindow_cor11Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwindow_lib_lg1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwindow_lib_sm1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PwindowZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwooden_table1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwood_lg_crate1Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwood_lg_crate2Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwood_md_crate3Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwood_sm_crate4Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwood_sm_crate5Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/Pwood_sm_crate6Z.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/prop/PwppkmagZ.rz




#stan
$(BUILD_DIR)/$(OBSEG_DIR)/stan/%.rz: $(OBSEG_DIR)/stan/%.bin
	$(RZ_COMP) $< $@

STAN_RZ_FILES = \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_ame_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_arch_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_arec_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_ark_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_ash_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_azt_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_cat_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_cave_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_crad_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_cryp_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_dam_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_depo_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_dest_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_dish_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_imp_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_jun_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_len_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_oat_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_pete_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_ref_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_run_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_sev_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_sevb_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_sevx_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_silo_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_stat_all_p_stanZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/stan/Tbg_tra_all_p_stanZ.rz 




#brief
$(BUILD_DIR)/$(OBSEG_DIR)/brief/%.rz: $(OBSEG_DIR)/brief/%.bin
	$(RZ_COMP) $< $@

BRIEF_RZ_FILES = \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefarchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefarkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefaztZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefcaveZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefcontrolZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefcradZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefcrypZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefdamZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefdepoZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefdestZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefjunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefpeteZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefrunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefsevbunkerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefsevbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefsevxbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefsevxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefsiloZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbriefstatueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/brief/UbrieftraZ.rz




#setup
$(BUILD_DIR)/$(OBSEG_DIR)/setup/%.rz: $(OBSEG_DIR)/setup/%.bin
	$(RZ_COMP) $< $@

SETUP_RZ_FILES = \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupameZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setuparchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setuparkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupashZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupcaveZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupcradZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupcrypZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupdishZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupimpZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupoatZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setuprefZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupsevbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/Ump_setupstatueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetuparchZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetuparkZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupaztZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupcaveZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupcontrolZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupcradZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupcrypZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupdamZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupdepoZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupdestZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupjunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetuplenZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetuppeteZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetuprunZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupsevbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupsevbunkerZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupsevxZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupsevxbZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupsiloZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetupstatueZ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/setup/UsetuptraZ.rz




#text
$(BUILD_DIR)/$(OBSEG_DIR)/text/%.rz: $(OBSEG_DIR)/text/%.bin
	$(RZ_COMP) $< $@

$(OBSEG_DIR)/text/%.bin: $(OBSEG_DIR)/text/%.elf
	$(OBJCOPY) $< $@ -O binary

$(OBSEG_DIR)/text/%.elf: $(OBSEG_DIR)/text/%.o
	$(LD) -T LnameE.ld -o $@

$(OBSEG_DIR)/text/%.o: $(OBSEG_DIR)/text/%.c
	$(CC) -c $(CFLAGS) -o $@ -O2 $<
	mv $@ assets/obseg/text/LnameE.o

TEXT_RZ_FILES := \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LameJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LarchJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LarecJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LarkJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LashJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LaztJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcatJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcaveJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcradJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcrypJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdamJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdepoJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdestJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdishJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LearJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LeldJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LgunJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LimpJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LjunJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LleeJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LlenJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LlipJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LlueJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LmiscJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LmpmenuJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LmpweaponsJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LoatJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LoptionsJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LpamJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LpeteJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LpropobjJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LrefJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LritJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LrunJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevbJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevxbJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevxJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LshoJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsiloJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LstatJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LtitleJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LtraJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LwaxJ.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LameE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LarchE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LarecE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LarkE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LashE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LaztE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcatE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcaveE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcradE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LcrypE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdamE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdepoE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdestE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LdishE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LearE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LeldE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LgunE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LimpE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LjunE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LleeE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LlenE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LlipE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LlueE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LmiscE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LmpmenuE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LmpweaponsE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LoatE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LoptionsE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LpamE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LpeteE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LpropobjE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LrefE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LritE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LrunE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevbE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevxbE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsevxE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LshoE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LsiloE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LstatE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LtitleE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LtraE.rz \
    $(BUILD_DIR)/$(OBSEG_DIR)/text/LwaxE.rz 











