# Makefile to rebuild Goldeneye 007 split image
# Modified from sm64tools generated buildfile

# BUILD_DIR is location where all build artifacts are placed
BUILD_DIR = build

##################### Compiler Options #######################
CROSS = mips64-elf-
AS = $(CROSS)as
CC = $(CROSS)gcc
LD = $(CROSS)ld
OBJDUMP = $(CROSS)objdump
OBJCOPY = $(CROSS)objcopy

ASFLAGS = -mtune=vr4300 -march=vr4300
CFLAGS  = -Wall -O2 -mtune=vr4300 -march=vr4300 -G 0 -c
LDFLAGS = -T $(LD_SCRIPT) -Map $(BUILD_DIR)/ge007.map

####################### Other Tools #########################

# N64 tools
TOOLS_DIR = ./tools
BASS = bass
DATASEG_COMP = $(TOOLS_DIR)/data_compress.sh
RZ_COMP = $(TOOLS_DIR)/1172compress.sh
N64CKSUM = $(TOOLS_DIR)/n64cksum
EMULATOR = mupen64plus
EMU_FLAGS = --noosd
LOADER = loader64
LOADER_FLAGS = -vwf

FixPath = $(subst /,\,$1)

######################## Targets #############################

default: all

# file dependencies generated by splitter
MAKEFILE_DATA = Makefile.data
include $(MAKEFILE_DATA)

all: $(TARGET).z64

clean:
	rm -f $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).o $(BUILD_DIR)/$(TARGET).bin $(BUILD_DIR)/ge007.map $(TARGET).z64 $(BUILD_DIR)/entry.o $(BUILD_DIR)/code.o $(BUILD_DIR)/rarezip.o $(BUILD_DIR)/tlbcode.o

cleandata:
	rm -f $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).o $(BUILD_DIR)/$(TARGET).bin $(BUILD_DIR)/ge007.map $(TARGET).z64 $(BUILD_DIR)/entry.o $(BUILD_DIR)/code.o $(BUILD_DIR)/rarezip.o $(BUILD_DIR)/tlbcode.o $(TEXT_RZ_FILES)

$(OBSEG_DIR)/text/%.rz: $(OBSEG_DIR)/text/%.bin
	$(RZ_COMP) $< $@

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(BUILD_DIR)/$(TARGET).o: $(TARGET).s Makefile $(MAKEFILE_DATA) $(TEXT_RZ_FILES) | $(BUILD_DIR)
	$(AS) $(ASFLAGS) -o $@ $<

$(BUILD_DIR)/%.o: src/%.s Makefile | $(BUILD_DIR)
	$(AS) $(ASFLAGS) -o $@ $<

$(BUILD_DIR)/%.o: %.c Makefile.as | $(BUILD_DIR)
	$(CC) $(CFLAGS) -o $@ $<

$(BUILD_DIR)/$(TARGET).elf: $(BUILD_DIR)/$(TARGET).o $(BUILD_DIR)/entry.o $(BUILD_DIR)/code.o $(BUILD_DIR)/rarezip.o $(BUILD_DIR)/tlbcode.o $(LD_SCRIPT)
	$(LD) $(LDFLAGS) -o $@ $< $(LIBS)

$(BUILD_DIR)/$(TARGET).bin: $(BUILD_DIR)/$(TARGET).elf
	$(OBJCOPY) $< $@ -O binary

# final z64 updates checksum
$(TARGET).z64: $(BUILD_DIR)/$(TARGET).bin
	$(DATASEG_COMP) $<
	$(N64CKSUM) $< $@

$(BUILD_DIR)/$(TARGET).hex: $(TARGET).z64
	xxd $< > $@

$(BUILD_DIR)/$(TARGET).objdump: $(BUILD_DIR)/$(TARGET).elf
	$(OBJDUMP) -D $< > $@

test: $(TARGET).z64
	$(EMULATOR) $(EMU_FLAGS) $<

load: $(TARGET).z64
	$(LOADER) $(LOADER_FLAGS) $<

.PHONY: all clean default diff test cleandata
