# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

insert_imageDL:
/* 050C00 7F01C0D0 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 050C04 7F01C0D4 AFB00018 */  sw    $s0, 0x18($sp)
/* 050C08 7F01C0D8 AFBF001C */  sw    $ra, 0x1c($sp)
/* 050C0C 7F01C0DC 3C0EBA00 */  lui   $t6, (0xBA001402 >> 16) # lui $t6, 0xba00
/* 050C10 7F01C0E0 35CE1402 */  ori   $t6, (0xBA001402 & 0xFFFF) # ori $t6, $t6, 0x1402
/* 050C14 7F01C0E4 3C0F0030 */  lui   $t7, 0x30
/* 050C18 7F01C0E8 AC8F0004 */  sw    $t7, 4($a0)
/* 050C1C 7F01C0EC AC8E0000 */  sw    $t6, ($a0)
/* 050C20 7F01C0F0 24900008 */  addiu $s0, $a0, 8
/* 050C24 7F01C0F4 AFB00030 */  sw    $s0, 0x30($sp)
/* 050C28 7F01C0F8 0C001107 */  jal   get_video2_settings_txtClipW
/* 050C2C 7F01C0FC 26100008 */   addiu $s0, $s0, 8
/* 050C30 7F01C100 2458FFFF */  addiu $t8, $v0, -1
/* 050C34 7F01C104 8FA90030 */  lw    $t1, 0x30($sp)
/* 050C38 7F01C108 33190FFF */  andi  $t9, $t8, 0xfff
/* 050C3C 7F01C10C 3C01FF10 */  lui   $at, 0xff10
/* 050C40 7F01C110 03214025 */  or    $t0, $t9, $at
/* 050C44 7F01C114 0C000F07 */  jal   get_video2buf_offset28
/* 050C48 7F01C118 AD280000 */   sw    $t0, ($t1)
/* 050C4C 7F01C11C 0C003A2C */  jal   osVirtualToPhysical
/* 050C50 7F01C120 00402025 */   move  $a0, $v0
/* 050C54 7F01C124 8FAA0030 */  lw    $t2, 0x30($sp)
/* 050C58 7F01C128 02001825 */  move  $v1, $s0
/* 050C5C 7F01C12C 3C0C0001 */  lui   $t4, (0x00010001 >> 16) # lui $t4, 1
/* 050C60 7F01C130 AD420004 */  sw    $v0, 4($t2)
/* 050C64 7F01C134 358C0001 */  ori   $t4, (0x00010001 & 0xFFFF) # ori $t4, $t4, 1
/* 050C68 7F01C138 3C0BF700 */  lui   $t3, 0xf700
/* 050C6C 7F01C13C AC6B0000 */  sw    $t3, ($v1)
/* 050C70 7F01C140 AC6C0004 */  sw    $t4, 4($v1)
/* 050C74 7F01C144 26100008 */  addiu $s0, $s0, 8
/* 050C78 7F01C148 AFB00028 */  sw    $s0, 0x28($sp)
/* 050C7C 7F01C14C 0C001107 */  jal   get_video2_settings_txtClipW
/* 050C80 7F01C150 26100008 */   addiu $s0, $s0, 8
/* 050C84 7F01C154 0C00110B */  jal   get_video2_settings_txtClipH
/* 050C88 7F01C158 A7A20022 */   sh    $v0, 0x22($sp)
/* 050C8C 7F01C15C 87B90022 */  lh    $t9, 0x22($sp)
/* 050C90 7F01C160 244DFFFF */  addiu $t5, $v0, -1
/* 050C94 7F01C164 8FA30028 */  lw    $v1, 0x28($sp)
/* 050C98 7F01C168 31AE03FF */  andi  $t6, $t5, 0x3ff
/* 050C9C 7F01C16C 2728FFFF */  addiu $t0, $t9, -1
/* 050CA0 7F01C170 310903FF */  andi  $t1, $t0, 0x3ff
/* 050CA4 7F01C174 000E7880 */  sll   $t7, $t6, 2
/* 050CA8 7F01C178 3C01F600 */  lui   $at, 0xf600
/* 050CAC 7F01C17C 01E1C025 */  or    $t8, $t7, $at
/* 050CB0 7F01C180 00095380 */  sll   $t2, $t1, 0xe
/* 050CB4 7F01C184 030A5825 */  or    $t3, $t8, $t2
/* 050CB8 7F01C188 AC6B0000 */  sw    $t3, ($v1)
/* 050CBC 7F01C18C AC600004 */  sw    $zero, 4($v1)
/* 050CC0 7F01C190 8FBF001C */  lw    $ra, 0x1c($sp)
/* 050CC4 7F01C194 02001025 */  move  $v0, $s0
/* 050CC8 7F01C198 8FB00018 */  lw    $s0, 0x18($sp)
/* 050CCC 7F01C19C 03E00008 */  jr    $ra
/* 050CD0 7F01C1A0 27BD0038 */   addiu $sp, $sp, 0x38

sub_GAME_7F01C1A4:
/* 050CD4 7F01C1A4 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 050CD8 7F01C1A8 3C0E0103 */  lui   $t6, (0x01030040 >> 16) # lui $t6, 0x103
/* 050CDC 7F01C1AC AFBF0014 */  sw    $ra, 0x14($sp)
/* 050CE0 7F01C1B0 35CE0040 */  ori   $t6, (0x01030040 & 0xFFFF) # ori $t6, $t6, 0x40
/* 050CE4 7F01C1B4 AC8E0000 */  sw    $t6, ($a0)
/* 050CE8 7F01C1B8 00801825 */  move  $v1, $a0
/* 050CEC 7F01C1BC 24850008 */  addiu $a1, $a0, 8
/* 050CF0 7F01C1C0 3C048007 */  lui   $a0, %hi(matrix_buffer_gunbarrel_0) # $a0, 0x8007
/* 050CF4 7F01C1C4 8C84955C */  lw    $a0, %lo(matrix_buffer_gunbarrel_0)($a0)
/* 050CF8 7F01C1C8 AFA50020 */  sw    $a1, 0x20($sp)
/* 050CFC 7F01C1CC 0C003A2C */  jal   osVirtualToPhysical
/* 050D00 7F01C1D0 AFA3001C */   sw    $v1, 0x1c($sp)
/* 050D04 7F01C1D4 8FA3001C */  lw    $v1, 0x1c($sp)
/* 050D08 7F01C1D8 8FA80020 */  lw    $t0, 0x20($sp)
/* 050D0C 7F01C1DC 3C0F0102 */  lui   $t7, (0x01020040 >> 16) # lui $t7, 0x102
/* 050D10 7F01C1E0 35EF0040 */  ori   $t7, (0x01020040 & 0xFFFF) # ori $t7, $t7, 0x40
/* 050D14 7F01C1E4 AC620004 */  sw    $v0, 4($v1)
/* 050D18 7F01C1E8 3C188003 */  lui   $t8, %hi(D_8002A7D0) # $t8, 0x8003
/* 050D1C 7F01C1EC AD0F0000 */  sw    $t7, ($t0)
/* 050D20 7F01C1F0 8F18A7D0 */  lw    $t8, %lo(D_8002A7D0)($t8)
/* 050D24 7F01C1F4 3C098007 */  lui   $t1, %hi(matrix_buffer_rarelogo_2) # $t1, 0x8007
/* 050D28 7F01C1F8 8D299564 */  lw    $t1, %lo(matrix_buffer_rarelogo_2)($t1)
/* 050D2C 7F01C1FC 25050008 */  addiu $a1, $t0, 8
/* 050D30 7F01C200 0018C980 */  sll   $t9, $t8, 6
/* 050D34 7F01C204 AFA50020 */  sw    $a1, 0x20($sp)
/* 050D38 7F01C208 AFA80018 */  sw    $t0, 0x18($sp)
/* 050D3C 7F01C20C 0C003A2C */  jal   osVirtualToPhysical
/* 050D40 7F01C210 03292021 */   addu  $a0, $t9, $t1
/* 050D44 7F01C214 8FA30020 */  lw    $v1, 0x20($sp)
/* 050D48 7F01C218 8FA80018 */  lw    $t0, 0x18($sp)
/* 050D4C 7F01C21C 3C0AE700 */  lui   $t2, 0xe700
/* 050D50 7F01C220 24640008 */  addiu $a0, $v1, 8
/* 050D54 7F01C224 AD020004 */  sw    $v0, 4($t0)
/* 050D58 7F01C228 3C0BBA00 */  lui   $t3, (0xBA001402 >> 16) # lui $t3, 0xba00
/* 050D5C 7F01C22C AC600004 */  sw    $zero, 4($v1)
/* 050D60 7F01C230 AC6A0000 */  sw    $t2, ($v1)
/* 050D64 7F01C234 356B1402 */  ori   $t3, (0xBA001402 & 0xFFFF) # ori $t3, $t3, 0x1402
/* 050D68 7F01C238 24860008 */  addiu $a2, $a0, 8
/* 050D6C 7F01C23C AC8B0000 */  sw    $t3, ($a0)
/* 050D70 7F01C240 AC800004 */  sw    $zero, 4($a0)
/* 050D74 7F01C244 3C0CB900 */  lui   $t4, (0xB900031D >> 16) # lui $t4, 0xb900
/* 050D78 7F01C248 3C0D0055 */  lui   $t5, (0x00552048 >> 16) # lui $t5, 0x55
/* 050D7C 7F01C24C 35AD2048 */  ori   $t5, (0x00552048 & 0xFFFF) # ori $t5, $t5, 0x2048
/* 050D80 7F01C250 358C031D */  ori   $t4, (0xB900031D & 0xFFFF) # ori $t4, $t4, 0x31d
/* 050D84 7F01C254 ACCC0000 */  sw    $t4, ($a2)
/* 050D88 7F01C258 ACCD0004 */  sw    $t5, 4($a2)
/* 050D8C 7F01C25C 24C70008 */  addiu $a3, $a2, 8
/* 050D90 7F01C260 3C0EB700 */  lui   $t6, 0xb700
/* 050D94 7F01C264 240F0204 */  li    $t7, 516
/* 050D98 7F01C268 ACEF0004 */  sw    $t7, 4($a3)
/* 050D9C 7F01C26C ACEE0000 */  sw    $t6, ($a3)
/* 050DA0 7F01C270 8FBF0014 */  lw    $ra, 0x14($sp)
/* 050DA4 7F01C274 24E20008 */  addiu $v0, $a3, 8
/* 050DA8 7F01C278 27BD0020 */  addiu $sp, $sp, 0x20
/* 050DAC 7F01C27C 03E00008 */  jr    $ra
/* 050DB0 7F01C280 00000000 */   nop   

die_blood_image_routine:
/* 050DB4 7F01C284 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 050DB8 7F01C288 AFBF0024 */  sw    $ra, 0x24($sp)
/* 050DBC 7F01C28C AFB10020 */  sw    $s1, 0x20($sp)
/* 050DC0 7F01C290 14800008 */  bnez  $a0, .L7F01C2B4
/* 050DC4 7F01C294 AFB0001C */   sw    $s0, 0x1c($sp)
/* 050DC8 7F01C298 3C118008 */  lui   $s1, %hi(ptr_BONDdata) # $s1, 0x8008
/* 050DCC 7F01C29C 2631A0B0 */  addiu $s1, %lo(ptr_BONDdata) # addiu $s1, $s1, -0x5f50
/* 050DD0 7F01C2A0 8E2F0000 */  lw    $t7, ($s1)
/* 050DD4 7F01C2A4 3C0E8003 */  lui   $t6, %hi(die_blood_images) # $t6, 0x8003
/* 050DD8 7F01C2A8 25CEBB30 */  addiu $t6, %lo(die_blood_images) # addiu $t6, $t6, -0x44d0
/* 050DDC 7F01C2AC 1000000D */  b     .L7F01C2E4
/* 050DE0 7F01C2B0 ADEE11A8 */   sw    $t6, 0x11a8($t7)
.L7F01C2B4:
/* 050DE4 7F01C2B4 24010001 */  li    $at, 1
/* 050DE8 7F01C2B8 1481000A */  bne   $a0, $at, .L7F01C2E4
/* 050DEC 7F01C2BC 3C118008 */   lui   $s1, %hi(ptr_BONDdata) # $s1, 0x8008
/* 050DF0 7F01C2C0 2631A0B0 */  addiu $s1, %lo(ptr_BONDdata) # addiu $s1, $s1, -0x5f50
/* 050DF4 7F01C2C4 8E300000 */  lw    $s0, ($s1)
/* 050DF8 7F01C2C8 3C188003 */  lui   $t8, %hi(D_8002C50C) # $t8, 0x8003
/* 050DFC 7F01C2CC 2718C50C */  addiu $t8, %lo(D_8002C50C) # addiu $t8, $t8, -0x3af4
/* 050E00 7F01C2D0 8E0211AC */  lw    $v0, 0x11ac($s0)
/* 050E04 7F01C2D4 0058082B */  sltu  $at, $v0, $t8
/* 050E08 7F01C2D8 10200002 */  beqz  $at, .L7F01C2E4
/* 050E0C 7F01C2DC 00000000 */   nop   
/* 050E10 7F01C2E0 AE0211A8 */  sw    $v0, 0x11a8($s0)
.L7F01C2E4:
/* 050E14 7F01C2E4 3C118008 */  lui   $s1, %hi(ptr_BONDdata) # $s1, 0x8008
/* 050E18 7F01C2E8 2631A0B0 */  addiu $s1, %lo(ptr_BONDdata) # addiu $s1, $s1, -0x5f50
/* 050E1C 7F01C2EC 8E300000 */  lw    $s0, ($s1)
/* 050E20 7F01C2F0 24080001 */  li    $t0, 1
/* 050E24 7F01C2F4 24041E00 */  li    $a0, 7680
/* 050E28 7F01C2F8 8E1911B8 */  lw    $t9, 0x11b8($s0)
/* 050E2C 7F01C2FC 01194823 */  subu  $t1, $t0, $t9
/* 050E30 7F01C300 0FC2F5C5 */  jal   sub_GAME_7F0BD714
/* 050E34 7F01C304 AE0911B8 */   sw    $t1, 0x11b8($s0)
/* 050E38 7F01C308 8E300000 */  lw    $s0, ($s1)
/* 050E3C 7F01C30C 24041E00 */  li    $a0, 7680
/* 050E40 7F01C310 8E0A11B8 */  lw    $t2, 0x11b8($s0)
/* 050E44 7F01C314 000A5880 */  sll   $t3, $t2, 2
/* 050E48 7F01C318 020B6021 */  addu  $t4, $s0, $t3
/* 050E4C 7F01C31C 0FC2F5C5 */  jal   sub_GAME_7F0BD714
/* 050E50 7F01C320 AD8211B0 */   sw    $v0, 0x11b0($t4)
/* 050E54 7F01C324 8E2D0000 */  lw    $t5, ($s1)
/* 050E58 7F01C328 AFA20030 */  sw    $v0, 0x30($sp)
/* 050E5C 7F01C32C 27AE0037 */  addiu $t6, $sp, 0x37
/* 050E60 7F01C330 8DA411A8 */  lw    $a0, 0x11a8($t5)
/* 050E64 7F01C334 AFAE0010 */  sw    $t6, 0x10($sp)
/* 050E68 7F01C338 24050050 */  li    $a1, 80
/* 050E6C 7F01C33C 24060060 */  li    $a2, 96
/* 050E70 7F01C340 0FC072B8 */  jal   decrypt_bleeding_animation_data
/* 050E74 7F01C344 00403825 */   move  $a3, $v0
/* 050E78 7F01C348 8E2F0000 */  lw    $t7, ($s1)
/* 050E7C 7F01C34C 24050050 */  li    $a1, 80
/* 050E80 7F01C350 24060060 */  li    $a2, 96
/* 050E84 7F01C354 ADE211AC */  sw    $v0, 0x11ac($t7)
/* 050E88 7F01C358 8E300000 */  lw    $s0, ($s1)
/* 050E8C 7F01C35C 8FA40030 */  lw    $a0, 0x30($sp)
/* 050E90 7F01C360 8E1811B8 */  lw    $t8, 0x11b8($s0)
/* 050E94 7F01C364 00184080 */  sll   $t0, $t8, 2
/* 050E98 7F01C368 0208C821 */  addu  $t9, $s0, $t0
/* 050E9C 7F01C36C 0FC0745B */  jal   sub_GAME_7F01D16C
/* 050EA0 7F01C370 8F2711B0 */   lw    $a3, 0x11b0($t9)
/* 050EA4 7F01C374 8E300000 */  lw    $s0, ($s1)
/* 050EA8 7F01C378 24050050 */  li    $a1, 80
/* 050EAC 7F01C37C 8E0911B8 */  lw    $t1, 0x11b8($s0)
/* 050EB0 7F01C380 00095080 */  sll   $t2, $t1, 2
/* 050EB4 7F01C384 020A5821 */  addu  $t3, $s0, $t2
/* 050EB8 7F01C388 8D6411B0 */  lw    $a0, 0x11b0($t3)
/* 050EBC 7F01C38C 0FC0740B */  jal   sub_GAME_7F01D02C
/* 050EC0 7F01C390 00803025 */   move  $a2, $a0
/* 050EC4 7F01C394 8E300000 */  lw    $s0, ($s1)
/* 050EC8 7F01C398 24050050 */  li    $a1, 80
/* 050ECC 7F01C39C 8E0C11B8 */  lw    $t4, 0x11b8($s0)
/* 050ED0 7F01C3A0 000C6880 */  sll   $t5, $t4, 2
/* 050ED4 7F01C3A4 020D7021 */  addu  $t6, $s0, $t5
/* 050ED8 7F01C3A8 8DC411B0 */  lw    $a0, 0x11b0($t6)
/* 050EDC 7F01C3AC 0FC073BB */  jal   sub_GAME_7F01CEEC
/* 050EE0 7F01C3B0 00803025 */   move  $a2, $a0
/* 050EE4 7F01C3B4 8E300000 */  lw    $s0, ($s1)
/* 050EE8 7F01C3B8 24051E00 */  li    $a1, 7680
/* 050EEC 7F01C3BC 8E0F11B8 */  lw    $t7, 0x11b8($s0)
/* 050EF0 7F01C3C0 000FC080 */  sll   $t8, $t7, 2
/* 050EF4 7F01C3C4 02184021 */  addu  $t0, $s0, $t8
/* 050EF8 7F01C3C8 8D0411B0 */  lw    $a0, 0x11b0($t0)
/* 050EFC 7F01C3CC 0FC07325 */  jal   sub_GAME_7F01CC94
/* 050F00 7F01C3D0 00803025 */   move  $a2, $a0
/* 050F04 7F01C3D4 8E390000 */  lw    $t9, ($s1)
/* 050F08 7F01C3D8 8FBF0024 */  lw    $ra, 0x24($sp)
/* 050F0C 7F01C3DC 3C0A8003 */  lui   $t2, %hi(D_8002C50C) # $t2, 0x8003
/* 050F10 7F01C3E0 8F2911AC */  lw    $t1, 0x11ac($t9)
/* 050F14 7F01C3E4 254AC50C */  addiu $t2, %lo(D_8002C50C) # addiu $t2, $t2, -0x3af4
/* 050F18 7F01C3E8 8FB10020 */  lw    $s1, 0x20($sp)
/* 050F1C 7F01C3EC 8FB0001C */  lw    $s0, 0x1c($sp)
/* 050F20 7F01C3F0 012A102B */  sltu  $v0, $t1, $t2
/* 050F24 7F01C3F4 38420001 */  xori  $v0, $v0, 1
/* 050F28 7F01C3F8 03E00008 */  jr    $ra
/* 050F2C 7F01C3FC 27BD0038 */   addiu $sp, $sp, 0x38


