# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

sub_GAME_7F01D500:
/* 052030 7F01D500 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 052034 7F01D504 AFBF0014 */  sw    $ra, 0x14($sp)
/* 052038 7F01D508 3C048003 */  lui   $a0, %hi(selected_folder_num) # $a0, 0x8003
/* 05203C 7F01D50C 0FC07C0C */  jal   get_screen_ratio_settings_for_mpgame_from_folder
/* 052040 7F01D510 8C84A8E8 */   lw    $a0, %lo(selected_folder_num)($a0)
/* 052044 7F01D514 8FBF0014 */  lw    $ra, 0x14($sp)
/* 052048 7F01D518 27BD0018 */  addiu $sp, $sp, 0x18
/* 05204C 7F01D51C 03E00008 */  jr    $ra
/* 052050 7F01D520 00000000 */   nop   

sub_GAME_7F01D524:
/* 052054 7F01D524 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 052058 7F01D528 AFBF0014 */  sw    $ra, 0x14($sp)
/* 05205C 7F01D52C 3C048003 */  lui   $a0, %hi(selected_folder_num) # $a0, 0x8003
/* 052060 7F01D530 0FC07C61 */  jal   delete_update_eeprom_file
/* 052064 7F01D534 8C84A8E8 */   lw    $a0, %lo(selected_folder_num)($a0)
/* 052068 7F01D538 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05206C 7F01D53C 27BD0018 */  addiu $sp, $sp, 0x18
/* 052070 7F01D540 03E00008 */  jr    $ra
/* 052074 7F01D544 00000000 */   nop   

sub_GAME_7F01D548:
/* 052078 7F01D548 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 05207C 7F01D54C AFBF0014 */  sw    $ra, 0x14($sp)
/* 052080 7F01D550 3C048003 */  lui   $a0, %hi(selected_folder_num) # $a0, 0x8003
/* 052084 7F01D554 0FC07CA7 */  jal   copy_eeprom_to_stack_set_folder_num
/* 052088 7F01D558 8C84A8E8 */   lw    $a0, %lo(selected_folder_num)($a0)
/* 05208C 7F01D55C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 052090 7F01D560 27BD0018 */  addiu $sp, $sp, 0x18
/* 052094 7F01D564 03E00008 */  jr    $ra
/* 052098 7F01D568 00000000 */   nop   

would_have_returned_bond_for_folder_num:
/* 05209C 7F01D56C 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0520A0 7F01D570 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0520A4 7F01D574 3C048003 */  lui   $a0, %hi(selected_folder_num) # $a0, 0x8003
/* 0520A8 7F01D578 0FC07AF0 */  jal   removed_would_have_returned_bond_for_folder_num
/* 0520AC 7F01D57C 8C84A8E8 */   lw    $a0, %lo(selected_folder_num)($a0)
/* 0520B0 7F01D580 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0520B4 7F01D584 27BD0018 */  addiu $sp, $sp, 0x18
/* 0520B8 7F01D588 03E00008 */  jr    $ra
/* 0520BC 7F01D58C 00000000 */   nop   


