#!/usr/bin/env python3
"""Generate editor weapon choices from the game's canonical item/prop enums."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]
# Keep player-facing names here; native IDs come from bondconstants.h.
CHOICES = (
    ('WPPK', 'CHRWPPK', 'PP7 Special Issue'),
    ('WPPKSIL', 'CHRWPPKSIL', 'PP7 (Silenced)'),
    ('TT33', 'CHRTT33', 'DD44 Dostovei'),
    ('SKORPION', 'CHRSKORPION', 'Klobb'),
    ('AK47', 'CHRKALASH', 'KF7 Soviet'),
    ('UZI', 'CHRUZI', 'ZMG (9mm)'),
    ('MP5K', 'CHRMP5K', 'D5K Deutsche'),
    ('MP5KSIL', 'CHRMP5KSIL', 'D5K (Silenced)'),
    ('SPECTRE', 'CHRSPECTRE', 'Phantom'),
    ('M16', 'CHRM16', 'AR33 Assault Rifle'),
    ('FNP90', 'CHRFNP90', 'RC-P90'),
    ('SHOTGUN', 'CHRSHOTGUN', 'Shotgun'),
    ('AUTOSHOT', 'CHRAUTOSHOT', 'Automatic Shotgun'),
    ('SNIPERRIFLE', 'CHRSNIPERRIFLE', 'Sniper Rifle'),
    ('RUGER', 'CHRRUGER', 'Cougar Magnum'),
    ('GOLDENGUN', 'CHRGOLDEN', 'Golden Gun'),
    ('SILVERWPPK', 'CHRSILVERWPPK', 'Silver PP7'),
    ('GOLDWPPK', 'CHRGOLDWPPK', 'Gold PP7'),
    ('LASER', 'CHRLASER', 'Moonraker Laser'),
    ('GRENADELAUNCH', 'CHRGRENADELAUNCH', 'Grenade Launcher'),
    ('ROCKETLAUNCH', 'CHRROCKETLAUNCH', 'Rocket Launcher'),
    ('GRENADE', 'CHRGRENADE', 'Grenade'),
    ('TIMEDMINE', 'CHRTIMEDMINE', 'Timed Mine'),
    ('PROXIMITYMINE', 'CHRPROXIMITYMINE', 'Proximity Mine'),
    ('REMOTEMINE', 'CHRREMOTEMINE', 'Remote Mine'),
    ('KNIFE', 'CHRKNIFE', 'Hunting Knife'),
    ('THROWKNIFE', 'CHRTHROWKNIFE', 'Throwing Knife'),
)

def enum_values(source, name):
    body = re.search(r'typedef enum ' + name + r'\s*\{(.*?)\}\s*' + name + r'\s*;', source, re.S)[1]
    body = re.sub(r'/\*.*?\*/|//[^\n]*', '', body, flags=re.S)
    value, result = -1, {}
    for entry in body.split(','):
        entry = entry.strip()
        if not entry:
            continue
        parts = entry.split('=')
        key = parts[0].strip()
        if not re.fullmatch(r'\w+', key):
            raise ValueError(f'Unsupported {name} enum entry: {entry}')
        value = int(parts[1].strip(), 0) if len(parts) == 2 else value + 1
        result[key] = value
    return result

def generate():
    source = (ROOT / 'src/bondconstants.h').read_text()
    items, props = enum_values(source, 'ITEM_IDS'), enum_values(source, 'PROP')
    lines = ['/* Generated by scripts/generate_weapon_choices.py; do not edit IDs. */',
             'static const SetupWeaponChoice g_SetupWeaponChoices[] = {',
             '    {-1, -1, "None"},']
    for item, prop, name in CHOICES:
        lines.append(f'    {{{items["ITEM_" + item]}, {props["PROP_" + prop]}, "{name}"}}, /* ITEM_{item}, PROP_{prop} */')
    lines += ['};', '']
    return '\n'.join(lines)

def generate_hats():
    source = (ROOT / 'src/bondconstants.h').read_text()
    props, fittings = enum_values(source, 'PROP'), enum_values(source, 'HATTYPE')
    hats = (
        ('HATFURRY', 'FURRY', 'Fur Hat (Blue)'),
        ('HATFURRYBROWN', 'FURRY', 'Fur Hat (Brown)'),
        ('HATFURRYBLACK', 'FURRY', 'Fur Hat (Black)'),
        ('HATTBIRD', 'BIRD', 'Side Cap (Light Green)'),
        ('HATTBIRDBROWN', 'BIRD', 'Side Cap (Dark Green)'),
        ('HATHELMET', 'HELMATE', 'Combat Helmet (Green)'),
        ('HATHELMETGREY', 'HELMATE', 'Combat Helmet (Grey)'),
        ('HATMOON', 'MOON', 'Elite Headgear'),
        ('HATBERET', 'BERRET', 'Beret (Black)'),
        ('HATBERETBLUE', 'BERRET', 'Beret (Navy)'),
        ('HATBERETRED', 'BERRET', 'Beret (Burgundy)'),
        ('HATPEAKED', 'PEAKED', "Officer's Peaked Cap"),
    )
    lines = ['/* Generated by scripts/generate_weapon_choices.py; do not edit IDs. */',
             'static const SetupHatChoice g_SetupHatChoices[] = {',
             '    {-1, -1, "No hat"},']
    for prop, fitting, name in hats:
        lines.append(f'    {{{props["PROP_" + prop]}, {fittings["HATTYPE_" + fitting]}, "{name}"}}, /* PROP_{prop} */')
    return '\n'.join(lines + ['};', ''])

def generate_intro():
    items = enum_values((ROOT / 'src/bondconstants.h').read_text(), 'ITEM_IDS')
    names = {item: name for item, _, name in CHOICES}
    names.update({
        'NOTHING': 'None', 'UNARMED': 'Unarmed', 'FIST': 'Fist',
        'WATCHLASER': 'Watch Laser', 'TRIGGER': 'Remote Mine Detonator',
        'TASER': 'Taser', 'TANKSHELLS': 'Tank', 'BOMBCASE': 'Bomb Case',
        'PLASTIQUE': 'Plastique', 'FLAREPISTOL': 'Flare Pistol', 'PITONGUN': 'Piton Gun',
        'DOORDECODER': 'Door Decoder', 'BOMBDEFUSER': 'Bomb Defuser',
        'LOCKEXPLODER': 'Lock Exploder', 'DOOREXPLODER': 'Door Exploder',
        'WEAPONCASE': 'Weapon Case', 'SAFECRACKERCASE': 'Safe Cracker',
        'KEYANALYSERCASE': 'Key Analyser', 'BUG': 'Covert Modem',
        'MICROCAMERA': 'Micro Camera', 'BUGDETECTOR': 'Bug Detector',
        'EXPLOSIVEFLOPPY': 'Explosive Floppy', 'POLARIZEDGLASSES': 'Polarized Glasses',
        'DARKGLASSES': 'Dark Glasses', 'CREDITCARD': 'Credit Card',
        'GASKEYRING': 'Gas Keyring', 'DATATHIEF': 'Datathief',
        'WATCHIDENTIFIER': 'Watch Identifier', 'WATCHCOMMUNICATOR': 'Watch Communicator',
        'WATCHGEIGERCOUNTER': 'Watch Geiger Counter', 'WATCHMAGNETREPEL': 'Watch Magnet (Repel)',
        'WATCHMAGNETATTRACT': 'Watch Magnet (Attract)', 'GOLDENEYEKEY': 'GoldenEye Key',
        'BLACKBOX': 'Black Box', 'CIRCUITBOARD': 'Circuit Board', 'STAFFLIST': 'Staff List',
        'DOSSIERRED': 'Red Dossier', 'SPYFILE': 'Spy File', 'AUDIOTAPE': 'Audio Tape',
        'VIDEOTAPE': 'Video Tape', 'DATTAPE': 'DAT Tape', 'SPOOLTAPE': 'Spool Tape',
        'GOLDBAR': 'Gold Bar', 'KEYYALE': 'Yale Key', 'KEYBOLT': 'Bolt Key',
        'SUIT_LF_HAND': 'Suit Left Hand', 'ROCKETROUND': 'Rocket Round',
        'GRENADEROUND': 'Grenade Round',
    })
    lines = ['/* Generated by scripts/generate_weapon_choices.py; do not edit IDs. */',
             'static const SetupIntroChoice g_SetupIntroItemChoices[] = {']
    for key, value in items.items():
        if key == 'ITEM_IDS_MAX':
            continue
        short = key.removeprefix('ITEM_')
        name = names.get(short, short.replace('_', ' ').title())
        lines.append(f'    {{{value}, "{name}"}}, /* {key} */')
    return '\n'.join(lines + ['};', ''])

if __name__ == '__main__':
    (ROOT / 'tools/geditor/src/weaponchoices.h').write_text(generate())
    (ROOT / 'tools/geditor/src/introchoices.h').write_text(generate_intro())
    (ROOT / 'tools/geditor/src/hatchoices.h').write_text(generate_hats())
