#!/usr/bin/env python3
"""Regenerate GEditor's stationary idle frames from the game's asset sources."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.dont_write_bytecode = True
sys.path.insert(0, str(ROOT / 'tools'))
from make_animation_entries_uncompressed import (  # noqa: E402
    DATA_HEADER_RE, parse_entry_arrays, read_packed_value,
)


def expand(path):
    text = path.read_text()
    text = re.sub(r'/\*.*?\*/|//[^\n]*', '', text, flags=re.S)
    return re.sub(r'#include\s*<([^>]+)>',
                  lambda m: expand(ROOT / m[1]), text)


def generate():
    entries = dict(parse_entry_arrays((ROOT / 'assets/animationtable_entries.c').read_text()))
    headers = {m['name']: m for m in DATA_HEADER_RE.finditer(
        (ROOT / 'assets/animationtable_data.c').read_text())}
    lines = ['/* Generated by tools/geditor/scripts/generate_idle_poses.py.',
             '   Viewport snapshots only; no runtime animation or root motion. */',
             '#ifndef GEDITOR_IDLEPOSES_H', '#define GEDITOR_IDLEPOSES_H', '']
    for name in ('idle_unarmed', 'idle'):
        # Frame zero is the loop's stationary starting stance, used by chrlvIdleAnimationRelated.
        info, layout = int(headers[name]['info'], 16), int(headers[name]['layout'], 16)
        width, bits = (info >> 8) & 255, layout & 65535
        if bits % 8 or not 1 <= width <= 16 or bits // width != 45:
            raise ValueError(f'{name}: unexpected guard channel layout')
        frame = entries[name][:bits // 8]
        angles = [read_packed_value(frame, c * width, width) << (16 - width)
                  for c in range(45)]
        lines += [f'/* ANIM_ENTRY_{name}, frame 0: 15 joint rotations. */',
                  f'static const unsigned short g_EditorPose_{name}[45] = {{']
        lines += ['    ' + ', '.join(f'0x{v:04x}' for v in angles[i:i+9]) + ','
                  for i in range(0, 45, 9)]
        lines += ['};', '']

    # Follow gunGetItemStats and the exact gitem_structs order, including items without models.
    stats = dict(re.findall(r'WeaponStats\s+(\w+)\s*=\s*\{(.*?)\};',
                           expand(ROOT / 'assets/obseg/gun/gunWeaponStats.inc.c'), re.S))
    records = expand(ROOT / 'assets/obseg/gun/gunModelFileRecord.inc.c')
    pattern = r'(?:GUNFILERECORD|SUIT_LFRECORD)\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(GUNSTATS\(\w+\)|NULL)|\{\s*NULL\s*,\s*NULL\s*,\s*(\w+)\s*,\s*(GUNSTATS\(\w+\)|NULL)'
    handed = []
    for m in re.finditer(pattern, records):
        nomodel, ref = (m[2], m[3]) if m[1] else (m[4], m[5])
        if nomodel not in ('0', 'FALSE', '1', 'TRUE'):
            raise ValueError('unsupported has_no_model expression')
        name = ref[9:-1] + '_stats' if ref.startswith('GUNSTATS(') else 'default_weaponstats'
        if nomodel in ('1', 'TRUE'):
            name = 'default_weaponstats'
        handed.append(int('WEAPONSTATBITFLAG_ONLY_1_HANDED' in stats[name]))
    enum_source = (ROOT / 'src/bondconstants.h').read_text().split('typedef enum ITEM_IDS', 1)[1].split('} ITEM_IDS', 1)[0]
    item_count = len(re.findall(r'\bITEM_[A-Z0-9_]+\b', enum_source)) - 2  # NOTHING and MAX
    if len(handed) != item_count:
        raise ValueError(f'expected {item_count} item records, found {len(handed)}')
    lines += ['/* WEAPONSTATBITFLAG_ONLY_1_HANDED by ITEM_IDS, including default stats. */',
              'static const unsigned char g_EditorItemOneHanded[] = {']
    lines += ['    ' + ', '.join(map(str, handed[i:i+16])) + ','
              for i in range(0, len(handed), 16)]
    lines += ['};', '', '#endif', '']
    (ROOT / 'tools/geditor/src/idleposes.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    generate()
