#!/usr/bin/env python3
"""Names, offsets and skeleton compatibility for native animation previews."""
import re
from pathlib import Path

root = Path(__file__).resolve().parents[3]
lines = ['/* Generated by scripts/generate_model_animations.py. */',
         'static const struct { const char *name; DWORD offset; } g_AnimationNames[] = {']
for name, offset in re.findall(r'^#define PTR_ANIM_(\w+)\s+(0x[\da-fA-F]+)',
                             (root / 'assets/animationtable_data.h').read_text(), re.M):
    lines.append(f'    {{"{name}", {offset}}},')
lines += ['};', '', 'static const struct { const char *name; int channels; } g_AnimatedModels[] = {']
for folder, prefix in [('chr', 'C'), ('prop', 'P')]:
    for path in sorted((root / f'assets/obseg/{folder}').glob('*/*odelFileHeader.inc.c')):
        match = re.search(r'MODELFILEHEADER\(\s*(\w+),.*?&SKELETON\((guard|flying)\)', path.read_text())
        if match:
            name, skeleton = match.groups()
            lines.append(f'    {{"{prefix}{name}Z", {45 if skeleton == "guard" else 3}}},')
lines += ['};', '']
(root / 'tools/geditor/src/modelanimationdata.h').write_text('\n'.join(lines))
