#!/usr/bin/env python3
"""Build body display names from the game's body enum and multiplayer labels."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]


def generate():
    constants = (ROOT / 'src/bondconstants.h').read_text()
    enum = re.search(r'typedef enum BODIES\s*\{(.*?)\}\s*BODIES;', constants, re.S)[1]
    # GUD and the editor use the standard body table without ALL_BONDS.
    enum = re.sub(r'#ifdef ALL_BONDS.*?#endif', '', enum, flags=re.S)
    enum = re.sub(r'/\*.*?\*/|//[^\n]*', '', enum, flags=re.S)
    ids, value = {}, -1
    for entry in enum.split(','):
        parts = entry.strip().split('=')
        key = parts[0].strip()
        if not key:
            continue
        if not re.fullmatch(r'\w+', key):
            raise ValueError(f'Unsupported body enum entry: {entry}')
        if len(parts) == 2:
            rhs = parts[1].strip()
            value = ids[rhs] if rhs in ids else int(rhs, 0)
        else:
            value += 1
        ids[key] = value

    records = (ROOT / 'assets/obseg/chr/chrModelFileRecords.inc.c').read_text()
    files = [re.search(r'"([^"]+)"', (ROOT / path).read_text())[1]
             for path in re.findall(r'#include <([^>]+)>', records)]
    if len(files) != ids['BODIES_MAX']:
        raise ValueError('Body enum and character model table disagree')

    titles = {int(index): json.loads(quoted).strip() for quoted, index in re.findall(
        r'("(?:[^"\\]|\\.)*")\s*,\s*//TITLE_STR_(\d+)',
        (ROOT / 'assets/obseg/text/LtitleE.c').read_text())}
    front = (ROOT / 'src/game/front.c').read_text()
    mp = re.search(r'mp_chr_setup\[\]\s*=\s*\{(.*?)\n\};', front, re.S)[1]
    names = {}
    for title, photo, body in re.findall(
            r'getStringID\(LTITLE,\s*TITLE_STR_(\d+)\w*\),\s*\w+,\s*(\w+),\s*(BODY_\w+)', mp):
        # Prefer the generic Siberian guard over Mishkin's use of that body.
        # The later developer-head choices all reuse Bond's tuxedo body.
        if body not in names or (photo == 'IMG_MPC_RANDOM' and body != 'BODY_Brosnan_Tuxedo'):
            names[body] = titles[int(title)]

    lines = ['/* Generated by scripts/generate_character_names.py. */',
             'static const struct { const char *file, *name; } g_CharacterBodyNames[] = {']
    for body, index in ids.items():
        if not body.startswith('BODY_') or (index >= ids['HEAD_START']
                and body != 'BODY_Natalya_Jungle_Fatigues'):
            continue
        name = names.get(body, body.removeprefix('BODY_').replace('_', ' ').strip())
        lines.append(f'    {{{json.dumps(files[index])}, {json.dumps(name)}}}, /* {body} */')
    return '\n'.join(lines + ['};', ''])


if __name__ == '__main__':
    (ROOT / 'tools/geditor/src/characternames.h').write_text(generate())
