# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

null_init_main_3:
/* 035500 7F0009D0 03E00008 */  jr    $ra
/* 035504 7F0009D4 00000000 */   nop   

/* 035508 7F0009D8 00000000 */  nop   
/* 03550C 7F0009DC 00000000 */  nop   

