# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

sub_GAME_7F007980:
/* 03C4B0 7F007980 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 03C4B4 7F007984 AFBF002C */  sw    $ra, 0x2c($sp)
/* 03C4B8 7F007988 AFB40028 */  sw    $s4, 0x28($sp)
/* 03C4BC 7F00798C AFB30024 */  sw    $s3, 0x24($sp)
/* 03C4C0 7F007990 AFB20020 */  sw    $s2, 0x20($sp)
/* 03C4C4 7F007994 AFB1001C */  sw    $s1, 0x1c($sp)
/* 03C4C8 7F007998 AFB00018 */  sw    $s0, 0x18($sp)
/* 03C4CC 7F00799C 0FC26919 */  jal   get_num_players
/* 03C4D0 7F0079A0 0000A025 */   move  $s4, $zero
/* 03C4D4 7F0079A4 1840001B */  blez  $v0, .L7F007A14
/* 03C4D8 7F0079A8 00147080 */   sll   $t6, $s4, 2
/* 03C4DC 7F0079AC 3C0F8008 */  lui   $t7, %hi(ptr_BONDdata_p1) # $t7, 0x8008
/* 03C4E0 7F0079B0 25EF9EE0 */  addiu $t7, %lo(ptr_BONDdata_p1) # addiu $t7, $t7, -0x6120
/* 03C4E4 7F0079B4 01CF9021 */  addu  $s2, $t6, $t7
/* 03C4E8 7F0079B8 24130750 */  li    $s3, 1872
/* 03C4EC 7F0079BC 00008825 */  move  $s1, $zero
.L7F0079C0:
/* 03C4F0 7F0079C0 8E580000 */  lw    $t8, ($s2)
.L7F0079C4:
/* 03C4F4 7F0079C4 03118021 */  addu  $s0, $t8, $s1
/* 03C4F8 7F0079C8 8E040A44 */  lw    $a0, 0xa44($s0)
/* 03C4FC 7F0079CC 26100870 */  addiu $s0, $s0, 0x870
/* 03C500 7F0079D0 50800008 */  beql  $a0, $zero, .L7F0079F4
/* 03C504 7F0079D4 263103A8 */   addiu $s1, $s1, 0x3a8
/* 03C508 7F0079D8 0C00237C */  jal   func_70008DF0
/* 03C50C 7F0079DC 00000000 */   nop   
/* 03C510 7F0079E0 50400004 */  beql  $v0, $zero, .L7F0079F4
/* 03C514 7F0079E4 263103A8 */   addiu $s1, $s1, 0x3a8
/* 03C518 7F0079E8 0C002408 */  jal   func_70009020
/* 03C51C 7F0079EC 8E0401D4 */   lw    $a0, 0x1d4($s0)
/* 03C520 7F0079F0 263103A8 */  addiu $s1, $s1, 0x3a8
.L7F0079F4:
/* 03C524 7F0079F4 5633FFF3 */  bnel  $s1, $s3, .L7F0079C4
/* 03C528 7F0079F8 8E580000 */   lw    $t8, ($s2)
/* 03C52C 7F0079FC 26940001 */  addiu $s4, $s4, 1
/* 03C530 7F007A00 0FC26919 */  jal   get_num_players
/* 03C534 7F007A04 26520004 */   addiu $s2, $s2, 4
/* 03C538 7F007A08 0282082A */  slt   $at, $s4, $v0
/* 03C53C 7F007A0C 5420FFEC */  bnezl $at, .L7F0079C0
/* 03C540 7F007A10 00008825 */   move  $s1, $zero
.L7F007A14:
/* 03C544 7F007A14 8FBF002C */  lw    $ra, 0x2c($sp)
/* 03C548 7F007A18 8FB00018 */  lw    $s0, 0x18($sp)
/* 03C54C 7F007A1C 8FB1001C */  lw    $s1, 0x1c($sp)
/* 03C550 7F007A20 8FB20020 */  lw    $s2, 0x20($sp)
/* 03C554 7F007A24 8FB30024 */  lw    $s3, 0x24($sp)
/* 03C558 7F007A28 8FB40028 */  lw    $s4, 0x28($sp)
/* 03C55C 7F007A2C 03E00008 */  jr    $ra
/* 03C560 7F007A30 27BD0030 */   addiu $sp, $sp, 0x30

/* 03C564 7F007A34 00000000 */  nop   
/* 03C568 7F007A38 00000000 */  nop   
/* 03C56C 7F007A3C 00000000 */  nop   

