# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

sub_GAME_7F007970:
/* 03C4A0 7F007970 03E00008 */  jr    $ra
/* 03C4A4 7F007974 00000000 */   nop   

/* 03C4A8 7F007978 00000000 */  nop   
/* 03C4AC 7F00797C 00000000 */  nop   

