# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

sub_GAME_7F0074D0:
/* 03C000 7F0074D0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C004 7F0074D4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 03C008 7F0074D8 0FC1578B */  jal   stop_alarm
/* 03C00C 7F0074DC 00000000 */   nop   
/* 03C010 7F0074E0 0FC157BE */  jal   sub_GAME_7F055EF8
/* 03C014 7F0074E4 00000000 */   nop   
/* 03C018 7F0074E8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 03C01C 7F0074EC 27BD0018 */  addiu $sp, $sp, 0x18
/* 03C020 7F0074F0 03E00008 */  jr    $ra
/* 03C024 7F0074F4 00000000 */   nop   

/* 03C028 7F0074F8 00000000 */  nop   
/* 03C02C 7F0074FC 00000000 */  nop   

