# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

store_favorite_weapon_current_player:
/* 0521B0 7F01D680 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0521B4 7F01D684 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0521B8 7F01D688 AFA40018 */  sw    $a0, 0x18($sp)
/* 0521BC 7F01D68C 0FC26C54 */  jal   get_cur_playernum
/* 0521C0 7F01D690 AFA5001C */   sw    $a1, 0x1c($sp)
/* 0521C4 7F01D694 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0521C8 7F01D698 3C0F8007 */  lui   $t7, %hi(fav_weapon_right_player1) # $t7, 0x8007
/* 0521CC 7F01D69C 8FB80018 */  lw    $t8, 0x18($sp)
/* 0521D0 7F01D6A0 8FB9001C */  lw    $t9, 0x1c($sp)
/* 0521D4 7F01D6A4 25EF96F0 */  addiu $t7, %lo(fav_weapon_right_player1) # addiu $t7, $t7, -0x6910
/* 0521D8 7F01D6A8 000270C0 */  sll   $t6, $v0, 3
/* 0521DC 7F01D6AC 01CF1821 */  addu  $v1, $t6, $t7
/* 0521E0 7F01D6B0 27BD0018 */  addiu $sp, $sp, 0x18
/* 0521E4 7F01D6B4 AC780000 */  sw    $t8, ($v1)
/* 0521E8 7F01D6B8 03E00008 */  jr    $ra
/* 0521EC 7F01D6BC AC790004 */   sw    $t9, 4($v1)

sub_GAME_7F01D6C0:
/* 0521F0 7F01D6C0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0521F4 7F01D6C4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0521F8 7F01D6C8 0C0031BF */  jal   func_7000C6FC
/* 0521FC 7F01D6CC 00000000 */   nop   
/* 052200 7F01D6D0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 052204 7F01D6D4 27BD0018 */  addiu $sp, $sp, 0x18
/* 052208 7F01D6D8 03E00008 */  jr    $ra
/* 05220C 7F01D6DC 00000000 */   nop   

sub_GAME_7F01D6E0:
/* 052210 7F01D6E0 27BDFFA0 */  addiu $sp, $sp, -0x60
/* 052214 7F01D6E4 3C0E8003 */  lui   $t6, %hi(D_8002C520) # $t6, 0x8003
/* 052218 7F01D6E8 27A20000 */  addiu $v0, $sp, 0
/* 05221C 7F01D6EC 25CEC520 */  addiu $t6, %lo(D_8002C520) # addiu $t6, $t6, -0x3ae0
/* 052220 7F01D6F0 25D90060 */  addiu $t9, $t6, 0x60
/* 052224 7F01D6F4 00404025 */  move  $t0, $v0
.L7F01D6F8:
/* 052228 7F01D6F8 8DC10000 */  lw    $at, ($t6)
/* 05222C 7F01D6FC 25CE000C */  addiu $t6, $t6, 0xc
/* 052230 7F01D700 2508000C */  addiu $t0, $t0, 0xc
/* 052234 7F01D704 AD01FFF4 */  sw    $at, -0xc($t0)
/* 052238 7F01D708 8DC1FFF8 */  lw    $at, -8($t6)
/* 05223C 7F01D70C AD01FFF8 */  sw    $at, -8($t0)
/* 052240 7F01D710 8DC1FFFC */  lw    $at, -4($t6)
/* 052244 7F01D714 15D9FFF8 */  bne   $t6, $t9, .L7F01D6F8
/* 052248 7F01D718 AD01FFFC */   sw    $at, -4($t0)
/* 05224C 7F01D71C 3C098007 */  lui   $t1, %hi(save6) # $t1, 0x8007
/* 052250 7F01D720 25299B00 */  addiu $t1, %lo(save6) # addiu $t1, $t1, -0x6500
/* 052254 7F01D724 00406825 */  move  $t5, $v0
/* 052258 7F01D728 244C0060 */  addiu $t4, $v0, 0x60
.L7F01D72C:
/* 05225C 7F01D72C 8DA10000 */  lw    $at, ($t5)
/* 052260 7F01D730 25AD000C */  addiu $t5, $t5, 0xc
/* 052264 7F01D734 2529000C */  addiu $t1, $t1, 0xc
/* 052268 7F01D738 AD21FFF4 */  sw    $at, -0xc($t1)
/* 05226C 7F01D73C 8DA1FFF8 */  lw    $at, -8($t5)
/* 052270 7F01D740 AD21FFF8 */  sw    $at, -8($t1)
/* 052274 7F01D744 8DA1FFFC */  lw    $at, -4($t5)
/* 052278 7F01D748 15ACFFF8 */  bne   $t5, $t4, .L7F01D72C
/* 05227C 7F01D74C AD21FFFC */   sw    $at, -4($t1)
/* 052280 7F01D750 03E00008 */  jr    $ra
/* 052284 7F01D754 27BD0060 */   addiu $sp, $sp, 0x60

sub_GAME_7F01D758:
/* 052288 7F01D758 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 05228C 7F01D75C AFBF0014 */  sw    $ra, 0x14($sp)
/* 052290 7F01D760 0FC075B0 */  jal   sub_GAME_7F01D6C0
/* 052294 7F01D764 AFA40018 */   sw    $a0, 0x18($sp)
/* 052298 7F01D768 10400009 */  beqz  $v0, .L7F01D790
/* 05229C 7F01D76C 8FA70018 */   lw    $a3, 0x18($sp)
/* 0522A0 7F01D770 24E40008 */  addiu $a0, $a3, 8
/* 0522A4 7F01D774 24E50020 */  addiu $a1, $a3, 0x20
/* 0522A8 7F01D778 0FC26D80 */  jal   sub_GAME_7F09B600
/* 0522AC 7F01D77C 00E03025 */   move  $a2, $a3
/* 0522B0 7F01D780 8FA50018 */  lw    $a1, 0x18($sp)
/* 0522B4 7F01D784 00002025 */  move  $a0, $zero
/* 0522B8 7F01D788 0C003202 */  jal   func_7000C808
/* 0522BC 7F01D78C 24060020 */   li    $a2, 32
.L7F01D790:
/* 0522C0 7F01D790 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0522C4 7F01D794 27BD0018 */  addiu $sp, $sp, 0x18
/* 0522C8 7F01D798 03E00008 */  jr    $ra
/* 0522CC 7F01D79C 00000000 */   nop   


