# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

alloc_intro_matrices:
/* 0357A0 7F000C70 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0357A4 7F000C74 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0357A8 7F000C78 3C018003 */  lui   $at, %hi(D_8002A7D0) # $at, 0x8003
/* 0357AC 7F000C7C AC20A7D0 */  sw    $zero, %lo(D_8002A7D0)($at)
/* 0357B0 7F000C80 24040080 */  li    $a0, 128
/* 0357B4 7F000C84 0C0025C8 */  jal   func_70009720
/* 0357B8 7F000C88 24050004 */   li    $a1, 4
/* 0357BC 7F000C8C 3C018007 */  lui   $at, %hi(matrix_buffer_rarelogo_0) # $at, 0x8007
/* 0357C0 7F000C90 AC229558 */  sw    $v0, %lo(matrix_buffer_rarelogo_0)($at)
/* 0357C4 7F000C94 24040040 */  li    $a0, 64
/* 0357C8 7F000C98 0C0025C8 */  jal   func_70009720
/* 0357CC 7F000C9C 24050004 */   li    $a1, 4
/* 0357D0 7F000CA0 3C018007 */  lui   $at, %hi(matrix_buffer_gunbarrel_0) # $at, 0x8007
/* 0357D4 7F000CA4 AC22955C */  sw    $v0, %lo(matrix_buffer_gunbarrel_0)($at)
/* 0357D8 7F000CA8 24040080 */  li    $a0, 128
/* 0357DC 7F000CAC 0C0025C8 */  jal   func_70009720
/* 0357E0 7F000CB0 24050004 */   li    $a1, 4
/* 0357E4 7F000CB4 3C018007 */  lui   $at, %hi(matrix_buffer_rarelogo_1) # $at, 0x8007
/* 0357E8 7F000CB8 AC229560 */  sw    $v0, %lo(matrix_buffer_rarelogo_1)($at)
/* 0357EC 7F000CBC 24040080 */  li    $a0, 128
/* 0357F0 7F000CC0 0C0025C8 */  jal   func_70009720
/* 0357F4 7F000CC4 24050004 */   li    $a1, 4
/* 0357F8 7F000CC8 3C018007 */  lui   $at, %hi(matrix_buffer_rarelogo_2) # $at, 0x8007
/* 0357FC 7F000CCC AC229564 */  sw    $v0, %lo(matrix_buffer_rarelogo_2)($at)
/* 035800 7F000CD0 24040080 */  li    $a0, 128
/* 035804 7F000CD4 0C0025C8 */  jal   func_70009720
/* 035808 7F000CD8 24050004 */   li    $a1, 4
/* 03580C 7F000CDC 3C018007 */  lui   $at, %hi(matrix_buffer_gunbarrel_1) # $at, 0x8007
/* 035810 7F000CE0 AC229568 */  sw    $v0, %lo(matrix_buffer_gunbarrel_1)($at)
/* 035814 7F000CE4 24040080 */  li    $a0, 128
/* 035818 7F000CE8 0C0025C8 */  jal   func_70009720
/* 03581C 7F000CEC 24050004 */   li    $a1, 4
/* 035820 7F000CF0 3C018007 */  lui   $at, %hi(matrix_buffer_intro_backdrop) # $at, 0x8007
/* 035824 7F000CF4 AC22956C */  sw    $v0, %lo(matrix_buffer_intro_backdrop)($at)
/* 035828 7F000CF8 24040080 */  li    $a0, 128
/* 03582C 7F000CFC 0C0025C8 */  jal   func_70009720
/* 035830 7F000D00 24050004 */   li    $a1, 4
/* 035834 7F000D04 8FBF0014 */  lw    $ra, 0x14($sp)
/* 035838 7F000D08 3C018007 */  lui   $at, %hi(matrix_buffer_intro_bond) # $at, 0x8007
/* 03583C 7F000D0C AC229570 */  sw    $v0, %lo(matrix_buffer_intro_bond)($at)
/* 035840 7F000D10 03E00008 */  jr    $ra
/* 035844 7F000D14 27BD0018 */   addiu $sp, $sp, 0x18

/* 035848 7F000D18 00000000 */  nop   
/* 03584C 7F000D1C 00000000 */  nop   

