# text

# Pattern rules for building .rz files from .bin files
$(BUILD_DIR)/$(OBSEG_DIR)/text/%.rz: $(OBSEG_DIR)/text/%.bin
	$(RZ_COMP) $< $@

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.rz: $(BUILD_DIR)/$(OBSEG_DIR)/text/%.bin
	$(RZ_COMP) $< $@

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.bin: $(BUILD_DIR)/$(OBSEG_DIR)/text/%.elf
	$(OBJCOPY) $< $@ -O binary

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.elf: $(BUILD_DIR)/$(OBSEG_DIR)/text/%.o
	$(LD) -T assets/obseg/text/LnameX.ld -o $@ $<

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.o: $(OBSEG_DIR)/text/%.c
	$(CC) -c $(CFLAGS) -o $@ -O2 $<

TEXT_RZ_FILES := $(foreach name,$(TEXTNAMELIST),$(BUILD_DIR)/$(OBSEG_DIR)/text/L$(name)E.rz)

# Default target
all: $(TEXT_RZ_FILES)

.PHONY: all
