# brief

# Build .bin from .elf
$(BUILD_DIR)/$(OBSEG_DIR)/brief/%.bin: $(BUILD_DIR)/$(OBSEG_DIR)/brief/%.elf
	$(OBJCOPY) $< $@ -O binary

# Build .elf from .o
$(BUILD_DIR)/$(OBSEG_DIR)/brief/%.elf: $(BUILD_DIR)/$(OBSEG_DIR)/brief/%.o
	$(LD) -T assets/obseg/brief/Ubrief.ld -o $@ $<

# Build .o from .c
$(BUILD_DIR)/$(OBSEG_DIR)/brief/%.o: $(OBSEG_DIR)/brief/%.c
	$(CC) -c $(CFLAGS) -o $@ -O2 $<

# Build BRIEF_NAMES from BRIEFNAMELIST
BRIEF_NAMES = $(foreach lvl,$(BRIEFNAMELIST),Ubrief$(lvl)Z)

BRIEF_BIN_FILES = $(addprefix $(BUILD_DIR)/$(OBSEG_DIR)/brief/, $(addsuffix .bin, $(BRIEF_NAMES)))

# Default target
all: $(BRIEF_BIN_FILES)

.PHONY: all
