# text

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.bin: $(BUILD_DIR)/$(OBSEG_DIR)/text/%.elf
	$(OBJCOPY) $< $@ -O binary

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.elf: $(BUILD_DIR)/$(OBSEG_DIR)/text/%.o
	$(LD) -T assets/obseg/text/LnameX.ld -o $@ $<

$(BUILD_DIR)/$(OBSEG_DIR)/text/%.o: $(OBSEG_DIR)/text/%.c
	$(CC) -c $(CFLAGS) -o $@ -O2 $<

TEXT_BIN_FILES := $(foreach name,$(TEXTNAMELIST),$(BUILD_DIR)/$(OBSEG_DIR)/text/L$(name)E.bin)

# Default target
all: $(TEXT_BIN_FILES)

.PHONY: all
