# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel boot1
/* 001110 70000510 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 001114 70000514 AFBF0024 */  sw    $ra, 0x24($sp)
/* 001118 70000518 AFB10020 */  sw    $s1, 0x20($sp)
/* 00111C 7000051C 0C00012F */  jal   get_cdata_vaddr_start
/* 001120 70000520 AFB0001C */   sw    $s0, 0x1c($sp)
/* 001124 70000524 0C000132 */  jal   get_rodata_rom_start
/* 001128 70000528 00408025 */   move  $s0, $v0
/* 00112C 7000052C 0C000135 */  jal   get_rodata_rom_end
/* 001130 70000530 AFA20034 */   sw    $v0, 0x34($sp)
/* 001134 70000534 8FAE0034 */  lw    $t6, 0x34($sp)
/* 001138 70000538 0C000138 */  jal   getRareZipASMRomstart
/* 00113C 7000053C 004E8823 */   subu  $s1, $v0, $t6
/* 001140 70000540 0C00013B */  jal   getRareZipASMRomend
/* 001144 70000544 AFA20028 */   sw    $v0, 0x28($sp)
/* 001148 70000548 8FAF0028 */  lw    $t7, 0x28($sp)
/* 00114C 7000054C 3C0A7020 */  lui   $t2, 0x7020
/* 001150 70000550 02002825 */  move  $a1, $s0
/* 001154 70000554 004FC023 */  subu  $t8, $v0, $t7
/* 001158 70000558 02382021 */  addu  $a0, $s1, $t8
/* 00115C 7000055C 2483FFFF */  addiu $v1, $a0, -1
/* 001160 70000560 0460000A */  bltz  $v1, .L7000058C
/* 001164 70000564 3C068030 */   lui   $a2, 0x8030
/* 001168 70000568 3C197020 */  lui   $t9, 0x7020
/* 00116C 7000056C 03312023 */  subu  $a0, $t9, $s1
/* 001170 70000570 02031021 */  addu  $v0, $s0, $v1
.L70000574:
/* 001174 70000574 90480000 */  lbu   $t0, ($v0)
/* 001178 70000578 00834821 */  addu  $t1, $a0, $v1
/* 00117C 7000057C 2463FFFF */  addiu $v1, $v1, -1
/* 001180 70000580 2442FFFF */  addiu $v0, $v0, -1
/* 001184 70000584 0461FFFB */  bgez  $v1, .L70000574
/* 001188 70000588 A1280000 */   sb    $t0, ($t1)
.L7000058C:
/* 00118C 7000058C 0C00013E */  jal   jump_decompressfile
/* 001190 70000590 01512023 */   subu  $a0, $t2, $s1
/* 001194 70000594 3C0B0003 */  lui   $t3, %hi(_rarezipSegmentRomStart) # $t3, 3
/* 001198 70000598 3C0C0000 */  lui   $t4, %hi(_codeSegmentRomStart) # $t4, 0
/* 00119C 7000059C 258C1050 */  addiu $t4, %lo(_codeSegmentRomStart) # addiu $t4, $t4, 0x1050
/* 0011A0 700005A0 256B3590 */  addiu $t3, %lo(_rarezipSegmentRomStart) # addiu $t3, $t3, 0x3590
/* 0011A4 700005A4 3C01000F */  lui   $at, (0x000FFFB1 >> 16) # lui $at, 0xf
/* 0011A8 700005A8 3421FFB1 */  ori   $at, (0x000FFFB1 & 0xFFFF) # ori $at, $at, 0xffb1
/* 0011AC 700005AC 016C1023 */  subu  $v0, $t3, $t4
/* 0011B0 700005B0 0041082A */  slt   $at, $v0, $at
/* 0011B4 700005B4 14200013 */  bnez  $at, .L70000604
/* 0011B8 700005B8 3C01FFF0 */   lui   $at, (0xFFF00050 >> 16) # lui $at, 0xfff0
/* 0011BC 700005BC 34210050 */  ori   $at, (0xFFF00050 & 0xFFFF) # ori $at, $at, 0x50
/* 0011C0 700005C0 3C050010 */  lui   $a1, %hi(0x00101000) # $a1, 0x10
/* 0011C4 700005C4 3C067010 */  lui   $a2, %hi(0x70100400) # $a2, 0x7010
/* 0011C8 700005C8 24C60400 */  addiu $a2, %lo(0x70100400) # addiu $a2, $a2, 0x400
/* 0011CC 700005CC 24A51000 */  addiu $a1, %lo(0x00101000) # addiu $a1, $a1, 0x1000
/* 0011D0 700005D0 00413821 */  addu  $a3, $v0, $at
/* 0011D4 700005D4 0C0033E4 */  jal   osPiRawStartDma
/* 0011D8 700005D8 00002025 */   move  $a0, $zero
/* 0011DC 700005DC 0C00341C */  jal   osPiGetStatus
/* 0011E0 700005E0 00000000 */   nop   
/* 0011E4 700005E4 304D0001 */  andi  $t5, $v0, 1
/* 0011E8 700005E8 11A00006 */  beqz  $t5, .L70000604
/* 0011EC 700005EC 00000000 */   nop   
.L700005F0:
/* 0011F0 700005F0 0C00341C */  jal   osPiGetStatus
/* 0011F4 700005F4 00000000 */   nop   
/* 0011F8 700005F8 304E0001 */  andi  $t6, $v0, 1
/* 0011FC 700005FC 15C0FFFC */  bnez  $t6, .L700005F0
/* 001200 70000600 00000000 */   nop   
.L70000604:
/* 001204 70000604 0C003420 */  jal   osInitialize
/* 001208 70000608 00000000 */   nop   
/* 00120C 7000060C 0C0006EC */  jal   set_hardwire_TLB_to_2
/* 001210 70000610 00000000 */   nop   
/* 001214 70000614 3C108000 */  lui   $s0, %hi(0x80000001) # $s0, 0x8000
/* 001218 70000618 3C027000 */  lui   $v0, %hi(resolve_TLBaddress_for_InvalidHit) # $v0, 0x7000
/* 00121C 7000061C 3C048000 */  lui   $a0, (0x80000080 >> 16) # lui $a0, 0x8000
/* 001220 70000620 24421B60 */  addiu $v0, %lo(resolve_TLBaddress_for_InvalidHit) # addiu $v0, $v0, 0x1b60
/* 001224 70000624 02001825 */  move  $v1, $s0
/* 001228 70000628 34840080 */  ori   $a0, (0x80000080 & 0xFFFF) # ori $a0, $a0, 0x80
.L7000062C:
/* 00122C 7000062C 8C4F0000 */  lw    $t7, ($v0)
/* 001230 70000630 24630010 */  addiu $v1, $v1, 0x10
/* 001234 70000634 24420010 */  addiu $v0, $v0, 0x10
/* 001238 70000638 AC6FFFF0 */  sw    $t7, -0x10($v1)
/* 00123C 7000063C 8C58FFF4 */  lw    $t8, -0xc($v0)
/* 001240 70000640 AC78FFF4 */  sw    $t8, -0xc($v1)
/* 001244 70000644 8C59FFF8 */  lw    $t9, -8($v0)
/* 001248 70000648 AC79FFF8 */  sw    $t9, -8($v1)
/* 00124C 7000064C 8C48FFFC */  lw    $t0, -4($v0)
/* 001250 70000650 1464FFF6 */  bne   $v1, $a0, .L7000062C
/* 001254 70000654 AC68FFFC */   sw    $t0, -4($v1)
/* 001258 70000658 0C0034C8 */  jal   osWritebackDCacheAll
/* 00125C 7000065C 00000000 */   nop   
/* 001260 70000660 02002025 */  move  $a0, $s0
/* 001264 70000664 0C0034D4 */  jal   osInvalICache
/* 001268 70000668 24054000 */   li    $a1, 16384
/* 00126C 7000066C 24100002 */  li    $s0, 2
/* 001270 70000670 24110020 */  li    $s1, 32
.L70000674:
/* 001274 70000674 0C0034F4 */  jal   osUnmapTLB
/* 001278 70000678 02002025 */   move  $a0, $s0
/* 00127C 7000067C 26100001 */  addiu $s0, %lo(0x80000001) # addiu $s0, $s0, 1
/* 001280 70000680 1611FFFC */  bne   $s0, $s1, .L70000674
/* 001284 70000684 00000000 */   nop   
/* 001288 70000688 0C003504 */  jal   __osGetFpcCsr
/* 00128C 7000068C 00000000 */   nop   
/* 001290 70000690 0C003508 */  jal   __osSetFpcCsr
/* 001294 70000694 34440E80 */   ori   $a0, $v0, 0xe80
/* 001298 70000698 3C04803B */  lui   $a0, %hi(sp_main) # $a0, 0x803b
/* 00129C 7000069C 2484B950 */  addiu $a0, %lo(sp_main) # addiu $a0, $a0, -0x46b0
/* 0012A0 700006A0 0C0001BC */  jal   grow_stack
/* 0012A4 700006A4 34058000 */   li    $a1, 32768
glabel generate_main_thread
/* 0012A8 700006A8 3C108006 */  lui   $s0, %hi(mainthread) # $s0, 0x8006
/* 0012AC 700006AC 2610D640 */  addiu $s0, %lo(mainthread) # addiu $s0, $s0, -0x29c0
/* 0012B0 700006B0 3C067000 */  lui   $a2, %hi(main_entry) # $a2, 0x7000
/* 0012B4 700006B4 240C000A */  li    $t4, 10
/* 0012B8 700006B8 AFAC0014 */  sw    $t4, 0x14($sp)
/* 0012BC 700006BC 24C6089C */  addiu $a2, %lo(main_entry) # addiu $a2, $a2, 0x89c
/* 0012C0 700006C0 02002025 */  move  $a0, $s0
/* 0012C4 700006C4 24050003 */  li    $a1, 3
/* 0012C8 700006C8 00003825 */  move  $a3, $zero
/* 0012CC 700006CC 0C00350C */  jal   osCreateThread
/* 0012D0 700006D0 AFA20010 */   sw    $v0, 0x10($sp)
/* 0012D4 700006D4 0C003560 */  jal   osStartThread
/* 0012D8 700006D8 02002025 */   move  $a0, $s0
/* 0012DC 700006DC 8FBF0024 */  lw    $ra, 0x24($sp)
/* 0012E0 700006E0 8FB0001C */  lw    $s0, 0x1c($sp)
/* 0012E4 700006E4 8FB10020 */  lw    $s1, 0x20($sp)
/* 0012E8 700006E8 03E00008 */  jr    $ra
/* 0012EC 700006EC 27BD0040 */   addiu $sp, $sp, 0x40

glabel grow_stack
/* 0012F0 700006F0 00851021 */  addu  $v0, $a0, $a1
/* 0012F4 700006F4 03E00008 */  jr    $ra
/* 0012F8 700006F8 2442FFF8 */   addiu $v0, $v0, -8

glabel set_hw_address_and_unknown
/* 0012FC 700006FC 240E0001 */  li    $t6, 1
/* 001300 70000700 3C018002 */  lui   $at, %hi(unknown_init_val) # $at, 0x8002
/* 001304 70000704 AC2E3044 */  sw    $t6, %lo(unknown_init_val)($at)
/* 001308 70000708 3C018002 */  lui   $at, %hi(cart_hw_address) # $at, 0x8002
/* 00130C 7000070C 3C0F1000 */  lui   $t7, 0x1000
/* 001310 70000710 03E00008 */  jr    $ra
/* 001314 70000714 AC2F3048 */   sw    $t7, %lo(cart_hw_address)($at) # sw    $t7, 0x3048($at)

glabel idle_entry
/* 001318 70000718 AFA40000 */  sw    $a0, ($sp)
.L7000071C:
/* 00131C 7000071C 1000FFFF */  b     .L7000071C
/* 001320 70000720 00000000 */   nop   
/* 001324 70000724 00000000 */  nop   
/* 001328 70000728 00000000 */  nop   
/* 00132C 7000072C 00000000 */  nop   
/* 001330 70000730 03E00008 */  jr    $ra
/* 001334 70000734 00000000 */   nop   

glabel start_idle_thread
/* 001338 70000738 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00133C 7000073C AFBF001C */  sw    $ra, 0x1c($sp)
/* 001340 70000740 3C04803B */  lui   $a0, %hi(sp_idle) # $a0, 0x803b
/* 001344 70000744 2484B710 */  addiu $a0, %lo(sp_idle) # addiu $a0, $a0, -0x48f0
/* 001348 70000748 0C0001BC */  jal   grow_stack
/* 00134C 7000074C 24050040 */   li    $a1, 64
/* 001350 70000750 3C048006 */  lui   $a0, %hi(idlethread) # $a0, 0x8006
/* 001354 70000754 3C067000 */  lui   $a2, %hi(idle_entry) # $a2, 0x7000
/* 001358 70000758 24C60718 */  addiu $a2, %lo(idle_entry) # addiu $a2, $a2, 0x718
/* 00135C 7000075C 2484D490 */  addiu $a0, %lo(idlethread) # addiu $a0, $a0, -0x2b70
/* 001360 70000760 24050001 */  li    $a1, 1
/* 001364 70000764 00003825 */  move  $a3, $zero
/* 001368 70000768 AFA20010 */  sw    $v0, 0x10($sp)
/* 00136C 7000076C 0C00350C */  jal   osCreateThread
/* 001370 70000770 AFA00014 */   sw    $zero, 0x14($sp)
/* 001374 70000774 3C048006 */  lui   $a0, %hi(idlethread) # $a0, 0x8006
/* 001378 70000778 0C003560 */  jal   osStartThread
/* 00137C 7000077C 2484D490 */   addiu $a0, %lo(idlethread) # addiu $a0, $a0, -0x2b70
/* 001380 70000780 8FBF001C */  lw    $ra, 0x1c($sp)
/* 001384 70000784 27BD0020 */  addiu $sp, $sp, 0x20
/* 001388 70000788 03E00008 */  jr    $ra
/* 00138C 7000078C 00000000 */   nop   

glabel start_rmon_thread
/* 001390 70000790 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 001394 70000794 AFBF001C */  sw    $ra, 0x1c($sp)
/* 001398 70000798 3C04803B */  lui   $a0, %hi(sp_rmon) # $a0, 0x803b
/* 00139C 7000079C 2484B410 */  addiu $a0, %lo(sp_rmon) # addiu $a0, $a0, -0x4bf0
/* 0013A0 700007A0 0C0001BC */  jal   grow_stack
/* 0013A4 700007A4 24050300 */   li    $a1, 768
/* 0013A8 700007A8 3C048006 */  lui   $a0, %hi(rmonthread) # $a0, 0x8006
/* 0013AC 700007AC 3C067001 */  lui   $a2, %hi(rmonMain) # $a2, 0x7001
/* 0013B0 700007B0 240E00FA */  li    $t6, 250
/* 0013B4 700007B4 AFAE0014 */  sw    $t6, 0x14($sp)
/* 0013B8 700007B8 24C6CEA0 */  addiu $a2, %lo(rmonMain) # addiu $a2, $a2, -0x3160
/* 0013BC 700007BC 2484D2E0 */  addiu $a0, %lo(rmonthread) # addiu $a0, $a0, -0x2d20
/* 0013C0 700007C0 00002825 */  move  $a1, $zero
/* 0013C4 700007C4 00003825 */  move  $a3, $zero
/* 0013C8 700007C8 0C00350C */  jal   osCreateThread
/* 0013CC 700007CC AFA20010 */   sw    $v0, 0x10($sp)
/* 0013D0 700007D0 3C048006 */  lui   $a0, %hi(rmonthread) # $a0, 0x8006
/* 0013D4 700007D4 0C003560 */  jal   osStartThread
/* 0013D8 700007D8 2484D2E0 */   addiu $a0, %lo(rmonthread) # addiu $a0, $a0, -0x2d20
/* 0013DC 700007DC 8FBF001C */  lw    $ra, 0x1c($sp)
/* 0013E0 700007E0 27BD0020 */  addiu $sp, $sp, 0x20
/* 0013E4 700007E4 03E00008 */  jr    $ra
/* 0013E8 700007E8 00000000 */   nop   

glabel setup_message_queue_for_scheduler
/* 0013EC 700007EC 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0013F0 700007F0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0013F4 700007F4 3C048006 */  lui   $a0, %hi(msgQ_Q_fast3d) # $a0, 0x8006
/* 0013F8 700007F8 3C058006 */  lui   $a1, %hi(msgQ_buf_8005D9B8) # $a1, 0x8006
/* 0013FC 700007FC 24A5D9B8 */  addiu $a1, %lo(msgQ_buf_8005D9B8) # addiu $a1, $a1, -0x2648
/* 001400 70000800 2484D9A0 */  addiu $a0, %lo(msgQ_Q_fast3d) # addiu $a0, $a0, -0x2660
/* 001404 70000804 0C0035B4 */  jal   osCreateMesgQueue
/* 001408 70000808 24060020 */   li    $a2, 32
/* 00140C 7000080C 3C0E8000 */  lui   $t6, %hi(osTvType) # $t6, 0x8000
/* 001410 70000810 8DCE0300 */  lw    $t6, %lo(osTvType)($t6)
/* 001414 70000814 24010002 */  li    $at, 2
/* 001418 70000818 3C048006 */  lui   $a0, %hi(D_8005DA40) # $a0, 0x8006
/* 00141C 7000081C 15C1000A */  bne   $t6, $at, .L70000848
/* 001420 70000820 2484DA40 */   addiu $a0, %lo(D_8005DA40) # addiu $a0, $a0, -0x25c0
/* 001424 70000824 3C048006 */  lui   $a0, %hi(D_8005DA40) # $a0, 0x8006
/* 001428 70000828 3C058006 */  lui   $a1, %hi(shedthread) # $a1, 0x8006
/* 00142C 7000082C 24A5D7F0 */  addiu $a1, %lo(shedthread) # addiu $a1, $a1, -0x2810
/* 001430 70000830 2484DA40 */  addiu $a0, %lo(D_8005DA40) # addiu $a0, $a0, -0x25c0
/* 001434 70000834 2406001E */  li    $a2, 30
/* 001438 70000838 0C0002AB */  jal   osCreateScheduler
/* 00143C 7000083C 24070001 */   li    $a3, 1
/* 001440 70000840 10000006 */  b     .L7000085C
/* 001444 70000844 00000000 */   nop   
.L70000848:
/* 001448 70000848 3C058006 */  lui   $a1, %hi(shedthread) # $a1, 0x8006
/* 00144C 7000084C 24A5D7F0 */  addiu $a1, %lo(shedthread) # addiu $a1, $a1, -0x2810
/* 001450 70000850 24060002 */  li    $a2, 2
/* 001454 70000854 0C0002AB */  jal   osCreateScheduler
/* 001458 70000858 24070001 */   li    $a3, 1
.L7000085C:
/* 00145C 7000085C 3C048006 */  lui   $a0, %hi(D_8005DA40) # $a0, 0x8006
/* 001460 70000860 3C058006 */  lui   $a1, %hi(dword_CODE_bss_8005DB18) # $a1, 0x8006
/* 001464 70000864 3C068006 */  lui   $a2, %hi(msgQ_Q_fast3d) # $a2, 0x8006
/* 001468 70000868 24C6D9A0 */  addiu $a2, %lo(msgQ_Q_fast3d) # addiu $a2, $a2, -0x2660
/* 00146C 7000086C 24A5DB18 */  addiu $a1, %lo(dword_CODE_bss_8005DB18) # addiu $a1, $a1, -0x24e8
/* 001470 70000870 2484DA40 */  addiu $a0, %lo(D_8005DA40) # addiu $a0, $a0, -0x25c0
/* 001474 70000874 0C000305 */  jal   osScAddClient
/* 001478 70000878 00003825 */   move  $a3, $zero
/* 00147C 7000087C 3C048006 */  lui   $a0, %hi(D_8005DA40) # $a0, 0x8006
/* 001480 70000880 0C00033E */  jal   osScGetCmdQ
/* 001484 70000884 2484DA40 */   addiu $a0, %lo(D_8005DA40) # addiu $a0, $a0, -0x25c0
/* 001488 70000888 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00148C 7000088C 3C018006 */  lui   $at, %hi(mq) # $at, 0x8006
/* 001490 70000890 AC22DA38 */  sw    $v0, %lo(mq)($at)
/* 001494 70000894 03E00008 */  jr    $ra
/* 001498 70000898 27BD0018 */   addiu $sp, $sp, 0x18

glabel main_entry
/* 00149C 7000089C 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0014A0 700008A0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0014A4 700008A4 0C0001CE */  jal   start_idle_thread
/* 0014A8 700008A8 AFA40018 */   sw    $a0, 0x18($sp)
/* 0014AC 700008AC 0C002B4C */  jal   start_nulled_entry
/* 0014B0 700008B0 00000000 */   nop   
/* 0014B4 700008B4 0C002B3C */  jal   start_pi_manager
/* 0014B8 700008B8 00000000 */   nop   
/* 0014BC 700008BC 0C0001E4 */  jal   start_rmon_thread
/* 0014C0 700008C0 00000000 */   nop   
/* 0014C4 700008C4 0C002970 */  jal   check_boot_switches
/* 0014C8 700008C8 00000000 */   nop   
/* 0014CC 700008CC 50400004 */  beql  $v0, $zero, .L700008E0
/* 0014D0 700008D0 00002025 */   move  $a0, $zero
/* 0014D4 700008D4 0C0035D0 */  jal   osStopThread
/* 0014D8 700008D8 00002025 */   move  $a0, $zero
/* 0014DC 700008DC 00002025 */  move  $a0, $zero
.L700008E0:
/* 0014E0 700008E0 0C003600 */  jal   osSetThreadPri
/* 0014E4 700008E4 2405000A */   li    $a1, 10
/* 0014E8 700008E8 0C0001FB */  jal   setup_message_queue_for_scheduler
/* 0014EC 700008EC 00000000 */   nop   
/* 0014F0 700008F0 0C001807 */  jal   setup_gamevalues_and_launchmainloop
/* 0014F4 700008F4 00000000 */   nop   
/* 0014F8 700008F8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0014FC 700008FC 27BD0018 */  addiu $sp, $sp, 0x18
/* 001500 70000900 03E00008 */  jr    $ra
/* 001504 70000904 00000000 */   nop   

glabel setuplastentryofdebughandler
/* 001508 70000908 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 00150C 7000090C 3C0E8002 */  lui   $t6, %hi(debug_handler_table) # $t6, 0x8002
/* 001510 70000910 27A30008 */  addiu $v1, $sp, 8
/* 001514 70000914 25CE304C */  addiu $t6, %lo(debug_handler_table) # addiu $t6, $t6, 0x304c
/* 001518 70000918 25D90030 */  addiu $t9, $t6, 0x30
/* 00151C 7000091C 00604025 */  move  $t0, $v1
.L70000920:
/* 001520 70000920 8DC10000 */  lw    $at, ($t6)
/* 001524 70000924 25CE000C */  addiu $t6, $t6, 0xc
/* 001528 70000928 2508000C */  addiu $t0, $t0, 0xc
/* 00152C 7000092C AD01FFF4 */  sw    $at, -0xc($t0)
/* 001530 70000930 8DC1FFF8 */  lw    $at, -8($t6)
/* 001534 70000934 AD01FFF8 */  sw    $at, -8($t0)
/* 001538 70000938 8DC1FFFC */  lw    $at, -4($t6)
/* 00153C 7000093C 15D9FFF8 */  bne   $t6, $t9, .L70000920
/* 001540 70000940 AD01FFFC */   sw    $at, -4($t0)
/* 001544 70000944 8DC10000 */  lw    $at, ($t6)
/* 001548 70000948 00601025 */  move  $v0, $v1
/* 00154C 7000094C AD010000 */  sw    $at, ($t0)
/* 001550 70000950 8DD90004 */  lw    $t9, 4($t6)
/* 001554 70000954 AD190004 */  sw    $t9, 4($t0)
/* 001558 70000958 8C490008 */  lw    $t1, 8($v0)
.L7000095C:
/* 00155C 7000095C 24420008 */  addiu $v0, $v0, 8
/* 001560 70000960 5520FFFE */  bnezl $t1, .L7000095C
/* 001564 70000964 8C490008 */   lw    $t1, 8($v0)
/* 001568 70000968 03E00008 */  jr    $ra
/* 00156C 7000096C 27BD0040 */   addiu $sp, $sp, 0x40

.section .data
unknown_init_val:
  .word 2

cart_hw_address:
  .word 0x10000000

.macro debug_handler_table_entry sp, string
 .word \sp
 .word \string
.endm

#referenced by setuplastentryofdebughandler
.globl debug_handler_table
.type debug_handler_table, @object
.size debug_handler_table, 0x30
debug_handler_table:
  debug_handler_table_entry sp_boot, aBoot
  debug_handler_table_entry sp_rmon, aRmon
  debug_handler_table_entry sp_idle, aIdle
  debug_handler_table_entry sp_shed, aShed
  debug_handler_table_entry sp_main, aMain
  debug_handler_table_entry sp_audi, aAudi
debug_handler_table_end:




.section .rodata
aBoot: .asciiz "boot"
.align 2

aRmon: .asciiz "rmon"
.align 2

aIdle: .asciiz "idle"
.align 2

aShed: .asciiz "shed"
.align 2

aMain: .asciiz "main"
.align 2

aAudi: .asciiz "audi"
.align 2

.section .bss
glabel rmonthread
 .space 0x1B0
glabel idlethread
 .space 0x1B0
glabel mainthread
 .space 0x1B0
glabel shedthread
 .space 0x1B0

# these should probably be moved to better homes
glabel msgQ_Q_fast3d
  .space 0x18
glabel msgQ_buf_8005D9B8
  .space 0x80
glabel mq
  .space 0x8
glabel D_8005DA40
  .space 0xD8
glabel dword_CODE_bss_8005DB18
  .space 0x18
glabel target_for_counters_maybe
  .space 0x10
glabel dword_CODE_bss_8005DB40
  .space 0xB0
glabel TLB_managment_table
  .space 0x800
glabel TLB_manager_mapping_table_start
  .space 0xB4
glabel TLB_manager_mapping_table_end
  .space 0x4
glabel ptr_TLBallocatedblock
  .space 0x10
glabel dword_CODE_bss_8005E4B8
  .space 0x8
glabel dword_CODE_bss_8005E4C0
  .space 0x4
glabel dword_CODE_bss_8005E4C4
  .space 0x4
glabel dword_CODE_bss_8005E4C8
  .space 0x4
glabel dword_CODE_bss_8005E4CC
  .space 0x4
glabel dword_CODE_bss_8005E4D0
  .space 0x8
glabel dword_CODE_bss_8005E4D8
  .space 0x8
glabel dword_CODE_bss_8005E4E0
  .space 0x38
glabel dword_CODE_bss_8005E518
  .space 0x8
glabel dword_CODE_bss_8005E520
  .space 0x4
glabel dword_CODE_bss_8005E524
  .space 0xC
glabel audithread
  .space 0x1B0
glabel dword_CODE_bss_8005E6E0
  .space 0x18
glabel dword_CODE_bss_8005E6F8
  .space 0x20
glabel msgQ_Q_8005E718
  .space 0x18
glabel msgQ_buf_8005E730
  .space 0x20
glabel dword_CODE_bss_8005E750
  .space 0x50
glabel dword_CODE_bss_8005E7A0
  .space 0x10
glabel off_CODE_bss_8005E7B0
  .space 0x4
glabel dword_CODE_bss_8005E7B4
  .space 0x4
glabel dword_CODE_bss_8005E7B8
  .space 0x8
glabel dword_CODE_bss_8005E7C0
  .space 0x4
glabel dword_CODE_bss_8005E7C4
  .space 0x10
glabel dword_CODE_bss_8005E7D4
  .space 0x4EC
glabel dword_CODE_bss_8005ECC0
  .space 0x4
glabel dword_CODE_bss_8005ECC4
  .space 0x4
glabel dword_CODE_bss_8005ECC8
  .space 0x4
glabel dword_CODE_bss_8005ECCC
  .space 0x4
glabel dword_CODE_bss_8005ECD0
  .space 0x600
glabel audDMAMessageQ
  .space 0x18
glabel audDMAMessageBUF
  .space 0x108
glabel dword_CODE_bss_8005F3F0
  .space 0x10
glabel displaylist_0
  .space 0x850
glabel displaylist_1
  .space 0x850
glabel displaylist_bank
  .space 0x4
glabel dword_CODE_bss_800604A4
  .space 0x4
glabel dword_CODE_bss_800604A8
  .space 0x8
glabel dword_CODE_bss_800604B0
  .space 0x300
glabel dword_CODE_bss_800607B0
  .space 0x10
glabel dword_CODE_bss_800607C0
  .space 0xC
glabel dword_CODE_bss_800607CC
  .space 0x4
glabel dword_CODE_bss_800607D0
  .space 0xC
glabel dword_CODE_bss_800607DC
  .space 0x4
glabel dword_CODE_bss_800607E0
  .space 0x40
glabel m
  .space 0x4
glabel word_CODE_bss_80060824
  .space 0x4
glabel dword_CODE_bss_80060828
  .space 0x1C
glabel dword_CODE_bss_80060844
  .space 0x14
glabel dword_CODE_bss_80060858
  .space 0x14
glabel dword_CODE_bss_8006086C
  .space 0xC
glabel off_CODE_bss_80060878
  .space 0x1
glabel byte_CODE_bss_80060879
  .space 0x3
glabel dword_CODE_bss_8006087C
  .space 0x4
glabel dword_CODE_bss_80060880
  .space 0x4
glabel dword_CODE_bss_80060884
  .space 0x4
glabel dword_CODE_bss_80060888
  .space 0x4
glabel dword_CODE_bss_8006088C
  .space 0x4
glabel dword_CODE_bss_80060890
  .space 0x400
glabel thread_video_manager_debugthread
  .space 0x6B0
glabel dword_CODE_bss_80061340
  .space 0x2300
glabel interrupt_entry_c_buffer
  .space 0x18
glabel dword_CODE_bss_80063658
  .space 0x4
glabel ptr_tlbthread_maybe
  .space 0x4
glabel dword_CODE_bss_80063660
  .space 0x4
glabel current_indy_read_buf_resourceID
  .space 0x4
glabel ptr_indy_read_buf_string1
  .space 0x4
glabel ptr_indy_read_buf_string2
  .space 0x4
glabel indy_read_buffer
  .space 0x60
glabel memoryMesgMB
  .space 0x18
glabel ptr_memorymsg
  .space 0x8
glabel memoryMesgQueue
  .space 0x20
glabel dword_CODE_bss_80063710
  .space 0x10
glabel ptr_sfx_buf
  .space 0x4
glabel dword_CODE_bss_80063724
  .space 0x4
glabel ptr_1st_music_ctrl_block
  .space 0x4
glabel ptr_2nd_music_ctrl_block
  .space 0x4
glabel ptr_3rd_music_ctrl_block
  .space 0x4
glabel ptr_musicdatatable
  .space 0x4
glabel D_80063738
  .space 0x80
glabel D_800637B8
  .space 0x7E
glabel D_80063836
  .space 0x2
glabel D_80063838
  .space 0x4
glabel D_8006383C
  .space 0x4
glabel D_80063840
  .space 0x4
glabel D_80063844
  .space 0x2
glabel D_80063846
  .space 0x2
glabel D_80063848
  .space 0x2
glabel D_8006384A
  .space 0x2
glabel D_8006384C
  .space 0x2
glabel D_8006384E
  .space 0x2
glabel D_80063850
  .space 0x4
glabel D_80063854
  .space 0x4
glabel D_80063858
  .space 0x8
glabel D_80063860
  .space 0xF8
glabel D_80063958
  .space 0xF8
glabel D_80063A50
  .space 0x154
glabel D_80063BA4
  .space 0x4
glabel D_80063BA8
  .space 0x8
glabel memory_bank_ptrs
  .space 0x10
glabel D_80063BC0
  .space 0x4
glabel D_80063BC4
  .space 0x4
glabel D_80063BC8
  .space 0x8
glabel D_80063BD0
  .space 0x4
glabel D_80063BD4
  .space 0x4
glabel D_80063BD8
  .space 0x18
glabel ptr_model_room_buf_pri
  .space 0x8
glabel dword_CODE_bss_80063BF8
  .space 0x24
glabel dword_CODE_bss_80063C1C
  .space 0x4
glabel ptr_model_room_buf_secondary
  .space 0x4
glabel size_modelroom_buf
  .space 0x4
glabel ptr_table_allocated_mem_blocks
  .space 0x4
glabel dword_CODE_bss_80063C2C
  .space 0x4
glabel index_for_loadedroom
  .space 0x4
glabel dword_CODE_bss_80063C34
  .space 0x4
glabel ptr_first_entry_in_alloc_table
  .space 0x4
glabel dword_CODE_bss_80063C3C
  .space 0xC
glabel dword_CODE_bss_80063C48
  .space 0xFC0
glabel dword_CODE_bss_80064C08
  .space 0x8
glabel dword_CODE_bss_80064C10
  .space 0x8
glabel dword_CODE_bss_80064C18
  .space 0x4
glabel dword_CODE_bss_80064C1C
  .space 0x4
glabel dword_CODE_bss_80064C20
  .space 0x4
glabel dword_CODE_bss_80064C24
  .space 0xC
glabel boot_token_from_indy
  .space 0x280
glabel dword_CODE_bss_80064EB0
  .space 0x20
glabel dword_CODE_bss_80064ED0
  .space 0x20
glabel vi_c_debug_MSG
  .space 0x20
glabel vi_c_debug_MQ
  .space 0x20
glabel controller_input_index
  .space 0x1E0
glabel dword_CODE_bss_80065110
  .space 0x4
glabel dword_CODE_bss_80065114
  .space 0x4
glabel dword_CODE_bss_80065118
  .space 0x4
glabel dword_CODE_bss_8006511C
  .space 0x10
glabel dword_CODE_bss_8006512C
  .space 0x1E0
glabel dword_CODE_bss_8006530C
  .space 0x8
glabel dword_CODE_bss_80065314
  .space 0x10
glabel dword_CODE_bss_80065324
  .space 0x4
glabel dword_CODE_bss_80065328
  .space 0x28
glabel interrupt5_thread_list_buf
  .space 0x18
glabel dword_CODE_bss_80065368
  .space 0x8
glabel dword_CODE_bss_80065370
  .space 0x18
glabel dword_CODE_bss_80065388
  .space 0x8
glabel dword_CODE_bss_80065390
  .space 0x18
glabel dword_CODE_bss_800653A8
  .space 0x8
glabel dword_CODE_bss_800653B0
  .space 0x18
glabel dword_CODE_bss_800653C8
  .space 0x8
glabel dword_CODE_bss_800653D0
  .space 0x18
glabel player1_controllerstatus
  .space 0x4
glabel player2_controllerstatus
  .space 0x4
glabel player3_controllerstatus
  .space 0x4
glabel player4_controllerstatus
  .space 0x4
glabel player1_controller_packet
  .space 0x1A8
glabel rumble_off_player1_packet_buffer
  .space 0x100
glabel rumble_on_player_packet_buffers
  .space 0x100
glabel rumble_on_buffer
  .space 0x20
glabel rumble_off_buffer
  .space 0x20
glabel __osFinalRom
  .space 0x10
glabel vi_thread
  .space 0x1B0
glabel vi_thread_sp_maybe
  .space 0x1000
glabel interrupt_entry_buffer
  .space 0x18
glabel dword_CODE_bss_800669B8
  .space 0x18
glabel word_CODE_bss_800669D0
  .space 0x2
glabel byte_CODE_bss_800669D2
  .space 0x2
glabel dword_CODE_bss_800669D4
  .space 0x14
glabel word_CODE_bss_800669E8
  .space 0x2
glabel byte_CODE_bss_800669EA
  .space 0x2
glabel dword_CODE_bss_800669EC
  .space 0x14
glabel word_CODE_bss_80066A00
  .space 0x10
glabel __osEventStateTab
  .space 0x40
glabel dword_CODE_bss_80066A50
  .space 0x40
glabel dword_CODE_bss_80066A90
  .space 0x40
glabel piThread
  .space 0x1B0
glabel cmdBuf
  .space 0x1000
glabel pieventQueue
  .space 0x18
glabel piEventBuf
  .space 0x8
glabel __osContPifRam
  .space 0x3C
glabel dword_CODE_bss_80067CDC
  .space 0x4
glabel __osContLastCmd
  .space 0x1
glabel __osMaxControllers
  .space 0x7
glabel __osEepromTimer
  .space 0x20
glabel __osEepromTimerQ
  .space 0x18
glabel __osEepromTimerMsg
  .space 0x10
glabel __osEepPifRam
  .space 0x3C
glabel __osEepPifRam_end
  .space 0x4
glabel __osPfsPifRam
  .space 0x3C
glabel __osPfsPifRam_end
  .space 0x4
glabel dword_CODE_bss_80067DB0
  .space 0x8
glabel dword_CODE_bss_80067DB8
  .space 0x18
glabel flt_CODE_bss_80067DD0
  .space 0x10
glabel flt_CODE_bss_80067DE0
  .space 0x10
glabel leoDiskStack
  .space 0x1000
glabel __osBaseTimer
  .space 0x20
glabel __osCurrentTime
  .space 0x8
glabel __osBaseCounter
  .space 0x4
glabel __osViIntrCount
  .space 0x4
glabel __osTimerCounter
  .space 0x10
glabel __osThreadSave
  .space 0x18
glabel __osFaultedThread
  .space 0x8
glabel T_CONTEXT_AT
  .space 0x38
glabel T_CONTEXT_T0
  .space 0x8
glabel T_CONTEXT_T1
  .space 0x8
glabel T_CONTEXT_T2
  .space 0xB0
glabel T_CONTEXT_SR
  .space 0x98
glabel dword_CODE_bss_80068FE0
  .space 0x8
glabel __osPiAccessQueue
  .space 0x18
glabel LeoDiskHandle
  .space 0x74
glabel __osDiskHandle
  .space 0x4
glabel dword_CODE_bss_80069078
  .space 0xF8
glabel dword_CODE_bss_80069170
  .space 0x2D0
glabel dword_CODE_bss_80069440
  .space 0x18
glabel dword_CODE_bss_80069458
  .space 0xC0
glabel dword_CODE_bss_80069518
  .space 0x20
glabel ptr_animation_table
  .space 0x8
glabel if_positive_last_mp_weapon_set_num
  .space 0x10
glabel dword_CODE_bss_80069550
  .space 0x4
glabel dword_CODE_bss_80069554
  .space 0x4
glabel matrix_buffer_rarelogo_0
  .space 0x4
glabel matrix_buffer_gunbarrel_0
  .space 0x4
glabel matrix_buffer_rarelogo_1
  .space 0x4
glabel matrix_buffer_rarelogo_2
  .space 0x4
glabel matrix_buffer_gunbarrel_1
  .space 0x4
glabel matrix_buffer_intro_backdrop
  .space 0x4
glabel matrix_buffer_intro_bond
  .space 0x4
glabel x
  .space 0x4
glabel y
  .space 0x4
glabel dword_CODE_bss_8006957C
  .space 0x4
glabel dword_CODE_bss_80069580
  .space 0x4
glabel word_CODE_bss_80069584
  .space 0x4
glabel dword_CODE_bss_80069588
  .space 0x4
glabel dword_CODE_bss_8006958C
  .space 0x4
glabel virtualaddress
  .space 0x4
glabel dword_CODE_bss_80069594
  .space 0xC
glabel flt_CODE_bss_800695A0
  .space 0x4
glabel flt_CODE_bss_800695A4
  .space 0x4
glabel flt_CODE_bss_800695A8
  .space 0x4
glabel flt_CODE_bss_800695AC
  .space 0x4
glabel flt_CODE_bss_800695B0
  .space 0x4
glabel flt_CODE_bss_800695B4
  .space 0x4
glabel flt_CODE_bss_800695B8
  .space 0x4
glabel flt_CODE_bss_800695BC
  .space 0x4
glabel flt_CODE_bss_800695C0
  .space 0x8
glabel flt_CODE_bss_800695C8
  .space 0x4
glabel flt_CODE_bss_800695CC
  .space 0x4
glabel flt_CODE_bss_800695D0
  .space 0x8
glabel flt_CODE_bss_800695D8
  .space 0x4
glabel flt_CODE_bss_800695DC
  .space 0x4
glabel flt_CODE_bss_800695E0
  .space 0x4
glabel flt_CODE_bss_800695E4
  .space 0x4
glabel flt_CODE_bss_800695E8
  .space 0x4
glabel flt_CODE_bss_800695EC
  .space 0x4
glabel flt_CODE_bss_800695F0
  .space 0x8
glabel flt_CODE_bss_800695F8
  .space 0x4
glabel flt_CODE_bss_800695FC
  .space 0x4
glabel flt_CODE_bss_80069600
  .space 0x8
glabel flt_CODE_bss_80069608
  .space 0x4
glabel flt_CODE_bss_8006960C
  .space 0x4
glabel flt_CODE_bss_80069610
  .space 0x4
glabel flt_CODE_bss_80069614
  .space 0x4
glabel flt_CODE_bss_80069618
  .space 0x8
glabel dword_CODE_bss_80069620
  .space 0x31
glabel cheat_available
  .space 0x1
glabel CHEAT_AVAILABLE_INVINCIBLE
  .space 0x1
glabel CHEAT_AVAILABLE_ALLGUNS
  .space 0x4
glabel CHEAT_AVAILABLE_LINEMODE
  .space 0x1
glabel CHEAT_AVAILABLE_2X_HEALTH
  .space 0x1
glabel CHEAT_AVAILABLE_2X_ARMOR
  .space 0x1
glabel CHEAT_AVAILABLE_BOND_INVIS
  .space 0x1
glabel CHEAT_AVAILABLE_INFINITE_AMMO
  .space 0x1
glabel CHEAT_AVAILABLE_DK_MODE
  .space 0x1
glabel CHEAT_AVAILABLE_EXTRA_WEAPONS
  .space 0x1
glabel CHEAT_AVAILABLE_TINY_BOND
  .space 0x1
glabel CHEAT_AVAILABLE_PAINTBALL
  .space 0x1
glabel CHEAT_AVAILABLE_10X_HEALTH
  .space 0x1
glabel CHEAT_AVAILABLE_MAGNUM
  .space 0x1
glabel CHEAT_AVAILABLE_LASER
  .space 0x1
glabel CHEAT_AVAILABLE_GOLDENGUN
  .space 0x1
glabel CHEAT_AVAILABLE_SILVERPP7
  .space 0x1
glabel CHEAT_AVAILABLE_GOLDPP7
  .space 0x1
glabel CHEAT_AVAILABLE_MP_INVINCIBILITY
  .space 0x1
glabel CHEAT_AVAILABLE_NO_MP_RADAR
  .space 0x1
glabel CHEAT_AVAILABLE_TURBO
  .space 0x1
glabel CHEAT_AVAILABLE_DEBUG_MODE
  .space 0x1
glabel CHEAT_AVAILABLE_FAST_ANI
  .space 0x1
glabel CHEAT_AVAILABLE_SLOW_ANI
  .space 0x1
glabel CHEAT_AVAILABLE_ENMY_ROCKETS
  .space 0x1
glabel CHEAT_AVAILABLE_2X_ROCKET
  .space 0x1
glabel CHEAT_AVAILABLE_2X_GRENADE_LAUNCHER
  .space 0x1
glabel CHEAT_AVAILABLE_2X_RCP90
  .space 0x1
glabel CHEAT_AVAILABLE_2X_THROWING_KNIVES
  .space 0x1
glabel CHEAT_AVAILABLE_2X_HUNTING_KNIVES
  .space 0x1
glabel CHEAT_AVAILABLE_2X_LASER
  .space 0x2E
glabel cheat_activated
  .space 0x1
glabel CHEAT_AVAILABLE_EXTRA_CHARS
  .space 0x1
glabel cheat_activated_1
  .space 0x1
glabel cheat_activated_2
  .space 0x1
glabel CHEAT_AVAILABLE_MAX_AMMO
  .space 0x1
glabel cheat_activated_4
  .space 0x1
glabel cheat_activated_5
  .space 0x1
glabel cheat_activated_6
  .space 0x1
glabel cheat_activated_7
  .space 0x1
glabel cheat_activated_8
  .space 0x1
glabel cheat_activated_9
  .space 0x1
glabel cheat_activated_10
  .space 0x1
glabel cheat_activated_11
  .space 0x1
glabel cheat_activated_12
  .space 0x1
glabel cheat_activated_13
  .space 0x1
glabel cheat_activated_14
  .space 0x1
glabel cheat_activated_15
  .space 0x1
glabel cheat_activated_16
  .space 0x1
glabel cheat_activated_17
  .space 0x1
glabel cheat_activated_18
  .space 0x1
glabel cheat_activated_19
  .space 0x1
glabel cheat_activated_20
  .space 0x1
glabel cheat_activated_21
  .space 0x1
glabel cheat_activated_22
  .space 0x1
glabel cheat_activated_23
  .space 0x1
glabel cheat_activated_24
  .space 0x1
glabel cheat_activated_25
  .space 0x1
glabel cheat_activated_26
  .space 0x1
glabel cheat_activated_27
  .space 0x1
glabel cheat_activated_28
  .space 0x1
glabel cheat_activated_29
  .space 0x1
glabel cheat_activated_30
  .space 0x1
glabel cheat_activated_31
  .space 0x1
glabel cheat_activated_32
  .space 0x1
glabel cheat_activated_33
  .space 0x1
glabel cheat_activated_34
  .space 0x1
glabel cheat_activated_35
  .space 0x1
glabel cheat_activated_36
  .space 0x1
glabel cheat_activated_37
  .space 0x1
glabel cheat_activated_38
  .space 0x1
glabel cheat_activated_39
  .space 0x1
glabel cheat_activated_40
  .space 0x1
glabel cheat_activated_41
  .space 0x1
glabel cheat_activated_42
  .space 0x1
glabel cheat_activated_43
  .space 0x1
glabel cheat_activated_44
  .space 0x1
glabel cheat_activated_45
  .space 0x1
glabel cheat_activated_46
  .space 0x1
glabel cheat_activated_47
  .space 0x1
glabel cheat_activated_48
  .space 0x1
glabel cheat_activated_49
  .space 0x1
glabel cheat_activated_50
  .space 0x1
glabel cheat_activated_51
  .space 0x1
glabel cheat_activated_52
  .space 0x1
glabel cheat_activated_53
  .space 0x1
glabel cheat_activated_54
  .space 0x1
glabel cheat_activated_55
  .space 0x1
glabel cheat_activated_56
  .space 0x1
glabel cheat_activated_57
  .space 0x1
glabel cheat_activated_58
  .space 0x1
glabel cheat_activated_59
  .space 0x1
glabel cheat_activated_60
  .space 0x1
glabel cheat_activated_61
  .space 0x1
glabel cheat_activated_62
  .space 0x1
glabel cheat_activated_63
  .space 0x1
glabel cheat_activated_64
  .space 0x1
glabel cheat_activated_65
  .space 0x1
glabel cheat_activated_66
  .space 0x1
glabel cheat_activated_67
  .space 0x1
glabel cheat_activated_68
  .space 0x1
glabel cheat_activated_69
  .space 0x1
glabel cheat_activated_70
  .space 0x1
glabel cheat_activated_71
  .space 0x1
glabel cheat_activated_72
  .space 0x1
glabel cheat_activated_73
  .space 0x1
glabel cheat_activated_74
  .space 0x1
glabel cheat_activated_75
  .space 0x1
glabel cheat_activated_76
  .space 0x1
glabel cheat_activated_77
  .space 0x1
glabel cheat_activated_78
  .space 0x1
glabel fav_weapon_right_player1
  .space 0x4
glabel fav_weapon_left_player1
  .space 0x4
glabel fav_weapon_right_player2
  .space 0x4
glabel fav_weapon_left_player2
  .space 0x4
glabel fav_weapon_right_player3
  .space 0x4
glabel fav_weapon_left_player3
  .space 0x4
glabel fav_weapon_right_player4
  .space 0x4
glabel fav_weapon_left_player4
  .space 0x4
glabel mp_char_cur_select_player1
  .space 0x4
glabel mp_char_cur_select_player2
  .space 0x4
glabel mp_char_cur_select_player3
  .space 0x4
glabel mp_char_cur_select_player4
  .space 0x4
glabel mp_char_prev_select_player1
  .space 0x4
glabel mp_char_prev_select_player2
  .space 0x4
glabel mp_char_prev_select_player3
  .space 0x4
glabel mp_char_prev_select_player4
  .space 0x4
glabel dword_CODE_bss_80069730
  .space 0x4
glabel dword_CODE_bss_80069734
  .space 0x4
glabel dword_CODE_bss_80069738
  .space 0x4
glabel dword_CODE_bss_8006973C
  .space 0x4
glabel has_selected_char_player1
  .space 0x4
glabel has_selected_char_player2
  .space 0x4
glabel has_selected_char_player3
  .space 0x4
glabel has_selected_char_player4
  .space 0x4
glabel size_mp_select_image_player1
  .space 0x4
glabel size_mp_select_image_player2
  .space 0x4
glabel size_mp_select_image_player3
  .space 0x4
glabel size_mp_select_image_player4
  .space 0x4
glabel dword_CODE_bss_80069760
  .space 0x4
glabel dword_CODE_bss_80069764
  .space 0x4
glabel dword_CODE_bss_80069768
  .space 0x4
glabel dword_CODE_bss_8006976C
  .space 0x4
glabel dword_CODE_bss_80069770
  .space 0x4
glabel dword_CODE_bss_80069774
  .space 0x4
glabel dword_CODE_bss_80069778
  .space 0x4
glabel current_mp_stage_highlighted
  .space 0x4
glabel dword_CODE_bss_80069780
  .space 0x4
glabel mission_difficulty_highlighted
  .space 0x4
glabel dword_CODE_bss_80069788
  .space 0x4
glabel dword_CODE_bss_8006978C
  .space 0x4
glabel dword_CODE_bss_80069790
  .space 0x4
glabel highlight_enemy_reaction
  .space 0x4
glabel highlight_enemy_health
  .space 0x4
glabel highlight_enemy_accuracy
  .space 0x4
glabel highlight_enemy_damage
  .space 0x8
glabel handicap_player1
  .space 0x4
glabel handicap_player2
  .space 0x4
glabel handicap_player3
  .space 0x4
glabel handicap_player4
  .space 0x4
glabel controlstyle_player1
  .space 0x4
glabel controlstyle_player2
  .space 0x4
glabel controlstyle_player3
  .space 0x4
glabel controlstyle_player4
  .space 0x4
glabel highlight_players
  .space 0x4
glabel highlight_scenario
  .space 0x4
glabel highlight_gameselect
  .space 0x4
glabel highlight_gamelength
  .space 0x4
glabel highlight_character
  .space 0x4
glabel highlight_weaponselect
  .space 0x4
glabel highlight_health
  .space 0x4
glabel highlight_controlstyle
  .space 0x4
glabel highlight_aimadjustment
  .space 0x8
glabel dword_CODE_bss_800697F0
  .space 0x130
glabel save1
  .space 0x60
glabel save2
  .space 0x60
glabel save3
  .space 0x60
glabel save4
  .space 0x60
glabel save5
  .space 0x60
glabel save6
  .space 0x60
glabel dword_CODE_bss_80069B60
  .space 0x10
glabel sfx_related
  .space 0x4
glabel dword_CODE_bss_80069B74
  .space 0x4
glabel dword_CODE_bss_80069B78
  .space 0xB8
glabel ptr_list_object_lookup_indices
  .space 0x4
glabel num_obj_position_data_entries
  .space 0x4
glabel pos_data_entry
  .space 0x24
glabel dword_CODE_bss_80069C5C
  .space 0x10
glabel dword_CODE_bss_80069C6C
  .space 0x24
glabel dword_CODE_bss_80069C90
  .space 0x10
glabel dword_CODE_bss_80069CA0
  .space 0x24
glabel dword_CODE_bss_80069CC4
  .space 0x10
glabel dword_CODE_bss_80069CD4
  .space 0x34
glabel dword_CODE_bss_80069D08
  .space 0x34
glabel dword_CODE_bss_80069D3C
  .space 0x34
glabel dword_CODE_bss_80069D70
  .space 0x34
glabel dword_CODE_bss_80069DA4
  .space 0x7874
glabel ptr_room_lookup_buffer_maybe
  .space 0x4
glabel dword_CODE_bss_8007161C
  .space 0x4
glabel dword_CODE_bss_80071620
  .space 0x94
glabel dword_CODE_bss_800716B4
  .space 0x73C
glabel dword_CODE_bss_80071DF0
  .space 0x4
glabel dword_CODE_bss_80071DF4
  .space 0x4
glabel dword_CODE_bss_80071DF8
  .space 0x8
glabel dword_CODE_bss_80071E00
  .space 0x4
glabel dword_CODE_bss_80071E04
  .space 0x4
glabel dword_CODE_bss_80071E08
  .space 0x70
glabel gas_damage_flag
  .space 0x4
glabel gas_cutoff_flag
  .space 0x4
glabel autogenerated_weapons
  .space 0xFF0
glabel dword_CODE_bss_80072E70
  .space 0x500
glabel dword_CODE_bss_80073370
  .space 0xA50
glabel dword_CODE_bss_80073DC0
  .space 0x1270
glabel dword_CODE_bss_80075030
  .space 0xB40
glabel objinst
  .space 0x4
glabel dword_CODE_bss_80075B74
  .space 0x4
glabel flt_CODE_bss_80075B78
  .space 0x4
glabel flt_CODE_bss_80075B7C
  .space 0x4
glabel flt_CODE_bss_80075B80
  .space 0x8
glabel flt_CODE_bss_80075B88
  .space 0x4
glabel flt_CODE_bss_80075B8C
  .space 0x4
glabel flt_CODE_bss_80075B90
  .space 0x8
glabel dword_CODE_bss_80075B98
  .space 0x6C
glabel dword_CODE_bss_80075C04
  .space 0xC
glabel dword_CODE_bss_80075C10
  .space 0x78
glabel dword_CODE_bss_80075C88
  .space 0x78
glabel ptr_setup_path_tbl
  .space 0x4
glabel ptr_setup_path_link
  .space 0x4
glabel ptr_setup_intro
  .space 0x4
glabel ptr_setup_objects
  .space 0x4
glabel ptr_setup_path_sets
  .space 0x4
glabel ptr_setup_actions
  .space 0x4
glabel ptr_0xxxpresets
  .space 0x4
glabel ptr_2xxxpresets
  .space 0x4
glabel dword_CODE_bss_80075D20
  .space 0x4
glabel dword_CODE_bss_80075D24
  .space 0x4
glabel dword_CODE_bss_80075D28
  .space 0x8
glabel objective_ptrs
  .space 0x4
glabel dword_CODE_bss_80075D34
  .space 0x4
glabel dword_CODE_bss_80075D38
  .space 0x20
glabel dword_CODE_bss_80075D58
  .space 0x4
glabel dword_CODE_bss_80075D5C
  .space 0x4
glabel dword_CODE_bss_80075D60
  .space 0x20
glabel ptr_last_tag_entry_type16
  .space 0x4
glabel ptr_last_briefing_setup_entry_type23
  .space 0x4
glabel ptr_last_enter_room_subobject_entry_type20
  .space 0x4
glabel ptr_last_deposit_in_room_subobject_entry_type21
  .space 0x4
glabel ptr_last_photo_obj_in_room_subobject_entry_type1E
  .space 0x10
glabel flt_CODE_bss_80075DA0
  .space 0x10
glabel dword_CODE_bss_80075DB0
  .space 0x8
glabel dword_CODE_bss_80075DB8
  .space 0x4
glabel dword_CODE_bss_80075DBC
  .space 0x4
glabel dword_CODE_bss_80075DC0
  .space 0x4
glabel dword_CODE_bss_80075DC4
  .space 0x4
glabel dword_CODE_bss_80075DC8
  .space 0x9C
glabel dword_CODE_bss_80075E64
  .space 0x4
glabel dword_CODE_bss_80075E68
  .space 0xBE0
glabel dword_CODE_bss_80076A48
  .space 0x8
glabel dword_CODE_bss_80076A50
  .space 0xC
glabel dword_CODE_bss_80076A5C
  .space 0x8
glabel dword_CODE_bss_80076A64
  .space 0xC
glabel dword_CODE_bss_80076A70
  .space 0x4
glabel dword_CODE_bss_80076A74
  .space 0x4
glabel dword_CODE_bss_80076A78
  .space 0xC
glabel dword_CODE_bss_80076A84
  .space 0x4
glabel dword_CODE_bss_80076A88
  .space 0x4
glabel dword_CODE_bss_80076A8C
  .space 0x14
glabel dword_CODE_bss_80076AA0
  .space 0x14
glabel dword_CODE_bss_80076AB4
  .space 0x14
glabel dword_CODE_bss_80076AC8
  .space 0x14
glabel dword_CODE_bss_80076ADC
  .space 0x2E2C
glabel dword_CODE_bss_80079908
  .space 0x28
glabel ptr_allocation_0
  .space 0x4
glabel ptr_allocation_1
  .space 0xC
glabel flt_CODE_bss_80079940
  .space 0x4
glabel flt_CODE_bss_80079944
  .space 0x4
glabel flt_CODE_bss_80079948
  .space 0x4
glabel flt_CODE_bss_8007994C
  .space 0x4
glabel flt_CODE_bss_80079950
  .space 0x4
glabel flt_CODE_bss_80079954
  .space 0x4
glabel flt_CODE_bss_80079958
  .space 0x4
glabel flt_CODE_bss_8007995C
  .space 0x4
glabel flt_CODE_bss_80079960
  .space 0x4
glabel flt_CODE_bss_80079964
  .space 0x4
glabel flt_CODE_bss_80079968
  .space 0x4
glabel flt_CODE_bss_8007996C
  .space 0x4
glabel flt_CODE_bss_80079970
  .space 0x4
glabel flt_CODE_bss_80079974
  .space 0x4
glabel flt_CODE_bss_80079978
  .space 0x4
glabel flt_CODE_bss_8007997C
  .space 0x4
glabel flt_CODE_bss_80079980
  .space 0x10
glabel flt_CODE_bss_80079990
  .space 0x4
glabel flt_CODE_bss_80079994
  .space 0x4
glabel flt_CODE_bss_80079998
  .space 0x4
glabel dword_CODE_bss_8007999C
  .space 0x4
glabel dword_CODE_bss_800799A0
  .space 0x8
glabel flt_CODE_bss_800799A8
  .space 0x4
glabel flt_CODE_bss_800799AC
  .space 0x4
glabel flt_CODE_bss_800799B0
  .space 0x4
glabel dword_CODE_bss_800799B4
  .space 0x4
glabel dword_CODE_bss_800799B8
  .space 0x4
glabel flt_CODE_bss_800799BC
  .space 0x4
glabel flt_CODE_bss_800799C0
  .space 0x4
glabel flt_CODE_bss_800799C4
  .space 0x4
glabel flt_CODE_bss_800799C8
  .space 0x8
glabel flt_CODE_bss_800799D0
  .space 0x4
glabel flt_CODE_bss_800799D4
  .space 0x4
glabel flt_CODE_bss_800799D8
  .space 0x8
glabel starting_right_weapon
  .space 0x4
glabel starting_left_weapon
  .space 0x4
glabel flt_CODE_bss_800799E8
  .space 0x4
glabel flt_CODE_bss_800799EC
  .space 0x4
glabel flt_CODE_bss_800799F0
  .space 0x4
glabel dword_CODE_bss_800799F4
  .space 0x4
glabel dword_CODE_bss_800799F8
  .space 0x4
glabel dword_CODE_bss_800799FC
  .space 0x4
glabel flt_CODE_bss_80079A00
  .space 0x4
glabel flt_CODE_bss_80079A04
  .space 0x4
glabel flt_CODE_bss_80079A08
  .space 0x4
glabel flt_CODE_bss_80079A0C
  .space 0x4
glabel flt_CODE_bss_80079A10
  .space 0x4
glabel dword_CODE_bss_80079A14
  .space 0x4
glabel dword_CODE_bss_80079A18
  .space 0x4
glabel dword_CODE_bss_80079A1C
  .space 0x4
glabel dword_CODE_bss_80079A20
  .space 0x4
glabel watch_time_0
  .space 0x4
glabel dword_CODE_bss_80079A28
  .space 0x200
glabel dword_CODE_bss_80079C28
  .space 0x40
glabel dword_CODE_bss_80079C68
  .space 0x8
glabel dword_CODE_bss_80079C70
  .space 0x130
glabel dword_CODE_bss_80079DA0
  .space 0x4
glabel dword_CODE_bss_80079DA4
  .space 0x4
glabel dword_CODE_bss_80079DA8
  .space 0x20
glabel dword_CODE_bss_80079DC8
  .space 0x3C
glabel flt_CODE_bss_80079E04
  .space 0x4
glabel flt_CODE_bss_80079E08
  .space 0x4
glabel flt_CODE_bss_80079E0C
  .space 0x4
glabel flt_CODE_bss_80079E10
  .space 0x10
glabel dword_CODE_bss_80079E20
  .space 0x10
glabel off_CODE_bss_80079E30
  .space 0x1
glabel byte_CODE_bss_80079E31
  .space 0x1
glabel byte_CODE_bss_80079E32
  .space 0x1
glabel byte_CODE_bss_80079E33
  .space 0x48
glabel byte_CODE_bss_80079E7B
  .space 0x5
glabel flt_CODE_bss_80079E80
  .space 0x4
glabel flt_CODE_bss_80079E84
  .space 0x4
glabel flt_CODE_bss_80079E88
  .space 0x8
glabel dword_CODE_bss_80079E90
  .space 0x8
glabel dword_CODE_bss_80079E98
  .space 0x48
glabel ptr_BONDdata_p1
  .space 0x4
glabel ptr_BONDdata_p2
  .space 0x4
glabel ptr_BONDdata_p3
  .space 0x4
glabel ptr_BONDdata_p4
  .space 0x4
glabel player1_playerdata
  .space 0x70
glabel player2_player_data
  .space 0x70
glabel player3_player_data
  .space 0x70
glabel player4_player_data
  .space 0x70
glabel ptr_BONDdata
  .space 0x4
glabel cur_player_stat_ptr
  .space 0x4
glabel player_num
  .space 0x4
glabel random_byte
  .space 0x4
glabel dword_CODE_bss_8007A0C0
  .space 0x4
glabel dword_CODE_bss_8007A0C4
  .space 0x4
glabel dword_CODE_bss_8007A0C8
  .space 0x4
glabel dword_CODE_bss_8007A0CC
  .space 0x4
glabel dword_CODE_bss_8007A0D0
  .space 0x4
glabel dword_CODE_bss_8007A0D4
  .space 0x4
glabel dword_CODE_bss_8007A0D8
  .space 0x4
glabel dword_CODE_bss_8007A0DC
  .space 0x4
glabel dword_CODE_bss_8007A0E0
  .space 0x4
glabel dword_CODE_bss_8007A0E4
  .space 0x4
glabel dword_CODE_bss_8007A0E8
  .space 0x4
glabel dword_CODE_bss_8007A0EC
  .space 0x4
glabel word_CODE_bss_8007A0F0
  .space 0x2
glabel word_CODE_bss_8007A0F2
  .space 0xE
glabel dword_CODE_bss_8007A100
  .space 0x40
glabel ptr_smoke_buf
  .space 0x4
glabel ptr_explosion_buf
  .space 0x4
glabel max_casings
  .space 0x4
glabel ptr_ejected_casing_buf
  .space 0x4
glabel ptr_scorch_buf
  .space 0x4
glabel ptr_bullet_impact_buf
  .space 0xC
glabel dword_CODE_bss_8007A160
  .space 0x4
glabel dword_CODE_bss_8007A164
  .space 0xC
glabel dword_CODE_bss_8007A170
  .space 0x4
glabel word_CODE_bss_8007A174
  .space 0x36C
glabel dword_CODE_bss_8007A4E0
  .space 0x4
glabel word_CODE_bss_8007A4E4
  .space 0xBB4
glabel dword_CODE_bss_8007B098
  .space 0x8
glabel dword_CODE_bss_8007B0A0
  .space 0x40
glabel dword_CODE_bss_8007B0E0
  .space 0x40
glabel clippingfile
  .space 0x4
glabel ptr_firstroom
  .space 0x4
glabel dword_CODE_bss_8007B128
  .space 0x4
glabel dword_CODE_bss_8007B12C
  .space 0x4
glabel dword_CODE_bss_8007B130
  .space 0x4
glabel dword_CODE_bss_8007B134
  .space 0x220
glabel dword_CODE_bss_8007B354
  .space 0x4
glabel dword_CODE_bss_8007B358
  .space 0x684
glabel dword_CODE_bss_8007B9DC
  .space 0x8
glabel dword_CODE_bss_8007B9E4
  .space 0x4
glabel dword_CODE_bss_8007B9E8
  .space 0x8
glabel flt_CODE_bss_8007B9F0
  .space 0x4
glabel flt_CODE_bss_8007B9F4
  .space 0x4
glabel flt_CODE_bss_8007B9F8
  .space 0x4
glabel flt_CODE_bss_8007B9FC
  .space 0x4
glabel flt_CODE_bss_8007BA00
  .space 0x4
glabel dword_CODE_bss_8007BA04
  .space 0x8
glabel dword_CODE_bss_8007BA0C
  .space 0x4
glabel dword_CODE_bss_8007BA10
  .space 0x580
glabel ptr_bg_data
  .space 0x4
glabel ptr_clipping
  .space 0x4
glabel dword_CODE_bss_8007BF98
  .space 0x8
glabel list_visible_rooms_in_cur_global_vis_packet
  .space 0x98
glabel num_visible_rooms_in_cur_global_vis_packet
  .space 0x8
glabel dword_CODE_bss_8007C040
  .space 0x60
glabel dword_CODE_bss_8007C0A0
  .space 0x60
glabel dword_CODE_bss_8007C100
  .space 0x3E80
glabel ptr_bgdata_portals
  .space 0x4
glabel ptr_bgdata_offsets
  .space 0x4
glabel dword_CODE_bss_8007FF88
  .space 0x4
glabel ptr_bgdata_room_fileposition_list
  .space 0x4
glabel dword_CODE_bss_8007FF90
  .space 0x4
glabel dword_CODE_bss_8007FF94
  .space 0x4
glabel dword_CODE_bss_8007FF98
  .space 0x8
glabel dword_CODE_bss_8007FFA0
  .space 0x4
glabel dword_CODE_bss_8007FFA4
  .space 0x165C
glabel dword_CODE_bss_80081600
  .space 0x10
glabel dword_CODE_bss_80081610
  .space 0x8
glabel table_for_portals
  .space 0xFA0
glabel dword_CODE_bss_800825B8
  .space 0x8
glabel sky_enabled
  .space 0x4
glabel ptr_nearfog_enviroment_values
  .space 0x4
glabel buffer_far_pervasiveness
  .space 0x4
glabel far_fog
  .space 0xC
glabel flt_CODE_bss_800825D8
  .space 0x4
glabel flt_CODE_bss_800825DC
  .space 0x4
glabel buffer_far_ambiant
  .space 0x4
glabel bg_dif_light
  .space 0x4
glabel env_table_hit
  .space 0x4
glabel env_table_match_start
  .space 0x4
glabel env_table_match_end
  .space 0x8
glabel dword_CODE_bss_800825F8
  .space 0x4
glabel flt_CODE_bss_800825FC
  .space 0x4
glabel flt_CODE_bss_80082600
  .space 0x18
glabel dword_CODE_bss_80082618
  .space 0x4
glabel dword_CODE_bss_8008261C
  .space 0x4
glabel off_CODE_bss_80082620
  .space 0x1
glabel byte_CODE_bss_80082621
  .space 0x1
glabel byte_CODE_bss_80082622
  .space 0x3E
glabel light_fixture_table
  .space 0x4B0
glabel cur_entry_lightfixture_table
  .space 0x2
glabel index_of_cur_entry_lightfixture_table
  .space 0x6
glabel word_CODE_bss_80082B18
  .space 0x800
glabel dword_CODE_bss_80083318
  .space 0x8
glabel dword_CODE_bss_80083320
  .space 0x130
glabel dword_CODE_bss_80083450
  .space 0x4B0
glabel dword_CODE_bss_80083900
  .space 0x4B0
glabel dword_CODE_bss_80083DB0
  .space 0x4B00
glabel ptr_resource_data
  .space 0x14
glabel ptr_res_data_next
  .space 0x14
glabel dword_CODE_bss_800888D8
  .space 0x3958
glabel ptr_mgfx0_alloc_start
  .space 0x4
glabel ptr_mgfx1_alloc_start
  .space 0x4
glabel ptr_mgfx_end
  .space 0x8
glabel ptr_mvtx0_alloc_start
  .space 0x4
glabel ptr_mvtx1_alloc_start
  .space 0x4
glabel ptr_mvtx_end
  .space 0x4
glabel ptr_mvtx_cur_pos
  .space 0x4
glabel bank_in_mgfx_alloc_table
  .space 0x4
glabel dword_CODE_bss_8008C254
  .space 0xC
glabel ptr_jfont_DL
  .space 0x10
glabel ramrom_data_target
  .space 0xF
glabel byte_CODE_bss_8008C27F
  .space 0x101
glabel dword_CODE_bss_8008C380
  .space 0xE8
glabel dword_CODE_bss_8008C468
  .space 0xF
glabel byte_CODE_bss_8008C477
  .space 0x17
glabel word_CODE_bss_8008C48E
  .space 0x162
glabel record_slot_num
  .space 0x4
glabel addres_demo_loaded
  .space 0x4
glabel dword_CODE_bss_8008C5F8
  .space 0x8
glabel dword_CODE_bss_8008C600
  .space 0x4
glabel dword_CODE_bss_8008C604
  .space 0x4
glabel dword_CODE_bss_8008C608
  .space 0x4
glabel dword_CODE_bss_8008C60C
  .space 0x4
glabel dword_CODE_bss_8008C610
  .space 0x4
glabel dword_CODE_bss_8008C614
  .space 0x4
glabel dword_CODE_bss_8008C618
  .space 0x4
glabel dword_CODE_bss_8008C61C
  .space 0x4
glabel dword_CODE_bss_8008C620
  .space 0x4
glabel dword_CODE_bss_8008C624
  .space 0x4
glabel dword_CODE_bss_8008C628
  .space 0x4
glabel dword_CODE_bss_8008C62C
  .space 0x4
glabel dword_CODE_bss_8008C630
  .space 0x4
glabel dword_CODE_bss_8008C634
  .space 0xC
glabel ptr_text
  .space 0x4
glabel table_text_pointers
  .space 0x94
glabel dword_CODE_bss_8008C6D8
  .space 0x4
glabel dword_CODE_bss_8008C6DC
  .space 0x4
glabel dword_CODE_bss_8008C6E0
  .space 0x4
glabel dword_CODE_bss_8008C6E4
  .space 0x4
glabel dword_CODE_bss_8008C6E8
  .space 0x4
glabel dword_CODE_bss_8008C6EC
  .space 0x4
glabel dword_CODE_bss_8008C6F0
  .space 0x4
glabel ptr_j_char_data_buf
  .space 0x4
glabel ptr_j_char_registry
  .space 0x8
glabel stop_play_flag
  .space 0x4
glabel is_gameover_flag
  .space 0x4
glabel dword_CODE_bss_8008C708
  .space 0x4
glabel dword_CODE_bss_8008C70C
  .space 0x4
glabel time_trigger_alt_gameover_msg
  .space 0x4
glabel dword_CODE_bss_8008C714
  .space 0x4
glabel is_paused
  .space 0x4
glabel who_paused
  .space 0x4
glabel ptr_texture_alloc_start
  .space 0x4
glabel ptr_texture_alloc_end
  .space 0x4
glabel ptr_next_available_space
  .space 0x4
glabel ptr_last_entry_facemapping
  .space 0x4
glabel word_CODE_bss_8008C730
  .space 0x960
glabel dword_CODE_bss_8008D090
  .space 0x4
glabel dword_CODE_bss_8008D094
  .space 0xC
glabel dword_CODE_bss_8008D0A0
  .space 0x4
glabel dword_CODE_bss_8008D0A4
  .space 0x4
glabel dword_CODE_bss_8008D0A8
  .space 0x8
glabel globalbank_rdram_offset
  .space 0x4
glabel ptr_explosionDL
  .space 0x4
glabel image
  .space 0x4
glabel dword_CODE_bss_8008D0BC
  .space 0x4
glabel dword_CODE_bss_8008D0C0
  .space 0x4
glabel dword_CODE_bss_8008D0C4
  .space 0x4
glabel dword_CODE_bss_8008D0C8
  .space 0x4
glabel dword_CODE_bss_8008D0CC
  .space 0x4
glabel dword_CODE_bss_8008D0D0
  .space 0x4
glabel dword_CODE_bss_8008D0D4
  .space 0x4
glabel dword_CODE_bss_8008D0D8
  .space 0x4
glabel dword_CODE_bss_8008D0DC
  .space 0x4
glabel dword_CODE_bss_8008D0E0
  .space 0x4
glabel dword_CODE_bss_8008D0E4
  .space 0x4
glabel dword_CODE_bss_8008D0E8
  .space 0x4
glabel dword_CODE_bss_8008D0EC
  .space 0x4
glabel dword_CODE_bss_8008D0F0
  .space 0x4
glabel dword_CODE_bss_8008D0F4
  .space 0x4
glabel dword_CODE_bss_8008D0F8
  .space 0x4
glabel dword_CODE_bss_8008D0FC
  .space 0x4
glabel dword_CODE_bss_8008D100
  .space 0x4
glabel dword_CODE_bss_8008D104
  .space 0x4
glabel dword_CODE_bss_8008D108
  .space 0x4
glabel dword_CODE_bss_8008D10C
  .space 0x4
glabel dword_CODE_bss_8008D110
  .space 0x4
glabel imgcall
  .space 0x4
glabel dword_CODE_bss_8008D118
  .space 0x4
glabel dword_CODE_bss_8008D11C
  .space 0x4
glabel dword_CODE_bss_8008D120
  .space 0x4
glabel dword_CODE_bss_8008D124
  .space 0x4
glabel dword_CODE_bss_8008D128
  .space 0x4
glabel dword_CODE_bss_8008D12C
  .space 0x4
glabel dword_CODE_bss_8008D130
  .space 0x4
glabel dword_CODE_bss_8008D134
  .space 0xC
glabel dword_CODE_bss_8008D140
  .space 0x8
glabel dword_CODE_bss_8008D148
  .space 0x160
glabel dword_CODE_bss_8008D2A8
  .space 0xA0
glabel dword_CODE_bss_8008D348
  .space 0x8
glabel dword_CODE_bss_8008D350
  .space 0x4
glabel dword_CODE_bss_8008D354
  .space 0x4
glabel dword_CODE_bss_8008D358
  .space 0x4
glabel dword_CODE_bss_8008D35C
  .space 0x4
glabel dword_CODE_bss_8008D360
  .space 0x4
glabel dword_CODE_bss_8008D364
  .space 0x4
glabel dword_CODE_bss_8008D368
  .space 0x4
glabel dword_CODE_bss_8008D36C
  .space 0x4
glabel dword_CODE_bss_8008D370
  .space 0x400
glabel dword_CODE_bss_8008D770
  .space 0xBA0
glabel viewport_img_width
  .space 0x4
glabel viewport_img_height
  .space 0xC
glabel ptr_sectrum_monitor_data_temp_buf
  .space 0x4
glabel ptr_sectrum_game_data_temp_buf
  .space 0x4
glabel ptr_spectrum_roms
  .space 0x4
glabel ptr_300alloc
  .space 0x4
glabel ptr_6000alloc
  .space 0x4
glabel ptr_pc_keyboard_table_alloc
  .space 0x4
glabel spectrum_header16_15
  .space 0x1
glabel byte_CODE_bss_8008E339
  .space 0x1
glabel byte_CODE_bss_8008E33A
  .space 0x1
glabel byte_CODE_bss_8008E33B
  .space 0x1
glabel off_CODE_bss_8008E33C
  .space 0x1
glabel byte_CODE_bss_8008E33D
  .space 0x1
glabel byte_CODE_bss_8008E33E
  .space 0x1
glabel byte_CODE_bss_8008E33F
  .space 0x1
glabel off_CODE_bss_8008E340
  .space 0x1
glabel byte_CODE_bss_8008E341
  .space 0x1
glabel byte_CODE_bss_8008E342
  .space 0x1
glabel byte_CODE_bss_8008E343
  .space 0x1
glabel off_CODE_bss_8008E344
  .space 0x1
glabel byte_CODE_bss_8008E345
  .space 0x1
glabel byte_CODE_bss_8008E346
  .space 0x1
glabel byte_CODE_bss_8008E347
  .space 0x1
glabel spec_I
  .space 0x1
glabel byte_CODE_bss_8008E349
  .space 0x1
glabel spec_IFF2_lower
  .space 0x1
glabel spec_IFF2_upper
  .space 0x1
glabel spec_IM
  .space 0x1
glabel byte_CODE_bss_8008E34D
  .space 0x1
glabel spec_IX
  .space 0x2
glabel spec_IY
  .space 0x2
glabel spec_SP
  .space 0x2
glabel spec_PC
  .space 0x2
