# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel debug_sp_related_11
/* 006020 70005420 3C0E8002 */  lui   $t6, %hi(ptr_sp_rmon_0) # $t6, 0x8002
/* 006024 70005424 25CE36DC */  addiu $t6, %lo(ptr_sp_rmon_0) # addiu $t6, $t6, 0x36dc
/* 006028 70005428 8DC10000 */  lw    $at, ($t6)
/* 00602C 7000542C 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 006030 70005430 27A7001C */  addiu $a3, $sp, 0x1c
/* 006034 70005434 ACE10000 */  sw    $at, ($a3)
/* 006038 70005438 8DD90004 */  lw    $t9, 4($t6)
/* 00603C 7000543C 3C098002 */  lui   $t1, %hi(ptr_sp_idle_1) # $t1, 0x8002
/* 006040 70005440 252936F0 */  addiu $t1, %lo(ptr_sp_idle_1) # addiu $t1, $t1, 0x36f0
/* 006044 70005444 ACF90004 */  sw    $t9, 4($a3)
/* 006048 70005448 8DC10008 */  lw    $at, 8($t6)
/* 00604C 7000544C 27A80008 */  addiu $t0, $sp, 8
/* 006050 70005450 00803025 */  move  $a2, $a0
/* 006054 70005454 ACE10008 */  sw    $at, 8($a3)
/* 006058 70005458 8DD9000C */  lw    $t9, 0xc($t6)
/* 00605C 7000545C ACF9000C */  sw    $t9, 0xc($a3)
/* 006060 70005460 8DC10010 */  lw    $at, 0x10($t6)
/* 006064 70005464 ACE10010 */  sw    $at, 0x10($a3)
/* 006068 70005468 8D210000 */  lw    $at, ($t1)
/* 00606C 7000546C AD010000 */  sw    $at, ($t0)
/* 006070 70005470 8D2C0004 */  lw    $t4, 4($t1)
/* 006074 70005474 AD0C0004 */  sw    $t4, 4($t0)
/* 006078 70005478 8D210008 */  lw    $at, 8($t1)
/* 00607C 7000547C AD010008 */  sw    $at, 8($t0)
/* 006080 70005480 8D2C000C */  lw    $t4, 0xc($t1)
/* 006084 70005484 AD0C000C */  sw    $t4, 0xc($t0)
/* 006088 70005488 8D210010 */  lw    $at, 0x10($t1)
/* 00608C 7000548C 18A00004 */  blez  $a1, .L700054A0
/* 006090 70005490 AD010010 */   sw    $at, 0x10($t0)
/* 006094 70005494 2CA10006 */  sltiu $at, $a1, 6
/* 006098 70005498 14200003 */  bnez  $at, .L700054A8
/* 00609C 7000549C 00051080 */   sll   $v0, $a1, 2
.L700054A0:
/* 0060A0 700054A0 1000000E */  b     .L700054DC
/* 0060A4 700054A4 00001025 */   move  $v0, $zero
.L700054A8:
/* 0060A8 700054A8 3C018000 */  lui   $at, 0x8000
/* 0060AC 700054AC 00E26821 */  addu  $t5, $a3, $v0
/* 0060B0 700054B0 0102C021 */  addu  $t8, $t0, $v0
/* 0060B4 700054B4 00C1082B */  sltu  $at, $a2, $at
/* 0060B8 700054B8 8DA30000 */  lw    $v1, ($t5)
/* 0060BC 700054BC 14200003 */  bnez  $at, .L700054CC
/* 0060C0 700054C0 8F040000 */   lw    $a0, ($t8)
/* 0060C4 700054C4 10000005 */  b     .L700054DC
/* 0060C8 700054C8 00801025 */   move  $v0, $a0
.L700054CC:
/* 0060CC 700054CC 3C01F000 */  lui   $at, 0xf000
/* 0060D0 700054D0 00C17824 */  and   $t7, $a2, $at
/* 0060D4 700054D4 00837023 */  subu  $t6, $a0, $v1
/* 0060D8 700054D8 01EE1025 */  or    $v0, $t7, $t6
.L700054DC:
/* 0060DC 700054DC 03E00008 */  jr    $ra
/* 0060E0 700054E0 27BD0030 */   addiu $sp, $sp, 0x30

glabel debug_sp_related_12
/* 0060E4 700054E4 3C0E8002 */  lui   $t6, %hi(ptr_sp_rmon_1) # $t6, 0x8002
/* 0060E8 700054E8 25CE3704 */  addiu $t6, %lo(ptr_sp_rmon_1) # addiu $t6, $t6, 0x3704
/* 0060EC 700054EC 8DC10000 */  lw    $at, ($t6)
/* 0060F0 700054F0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0060F4 700054F4 27A20004 */  addiu $v0, $sp, 4
/* 0060F8 700054F8 AC410000 */  sw    $at, ($v0)
/* 0060FC 700054FC 8DD90004 */  lw    $t9, 4($t6)
/* 006100 70005500 AC590004 */  sw    $t9, 4($v0)
/* 006104 70005504 8DC10008 */  lw    $at, 8($t6)
/* 006108 70005508 AC410008 */  sw    $at, 8($v0)
/* 00610C 7000550C 8DD9000C */  lw    $t9, 0xc($t6)
/* 006110 70005510 AC59000C */  sw    $t9, 0xc($v0)
/* 006114 70005514 8DC10010 */  lw    $at, 0x10($t6)
/* 006118 70005518 18A00004 */  blez  $a1, .L7000552C
/* 00611C 7000551C AC410010 */   sw    $at, 0x10($v0)
/* 006120 70005520 2CA10006 */  sltiu $at, $a1, 6
/* 006124 70005524 14200003 */  bnez  $at, .L70005534
/* 006128 70005528 00054080 */   sll   $t0, $a1, 2
.L7000552C:
/* 00612C 7000552C 1000000A */  b     .L70005558
/* 006130 70005530 00001025 */   move  $v0, $zero
.L70005534:
/* 006134 70005534 3C018000 */  lui   $at, 0x8000
/* 006138 70005538 00484821 */  addu  $t1, $v0, $t0
/* 00613C 7000553C 0081082B */  sltu  $at, $a0, $at
/* 006140 70005540 14200003 */  bnez  $at, .L70005550
/* 006144 70005544 8D230000 */   lw    $v1, ($t1)
/* 006148 70005548 10000003 */  b     .L70005558
/* 00614C 7000554C 00601025 */   move  $v0, $v1
.L70005550:
/* 006150 70005550 3C01F000 */  lui   $at, 0xf000
/* 006154 70005554 00811024 */  and   $v0, $a0, $at
.L70005558:
/* 006158 70005558 03E00008 */  jr    $ra
/* 00615C 7000555C 27BD0018 */   addiu $sp, $sp, 0x18

.section .data
.macro exception f1 f2 f3
    .word \f1
    .word \f2
    .word \f3
.endm

debug_processor_error_table:
exception 0x80000000, 0x80000000, aBd
exception 0x8000, 0x8000, aIp8
exception 0x4000, 0x4000, aIp7
exception 0x2000, 0x2000, aIp6
exception 0x1000, 0x1000, aIp5
exception 0x800, 0x800, aIp4
exception 0x400, 0x400, aIp3
exception 0x200, 0x200, aIp2
exception 0x100, 0x100, aIp1
exception 0x7C, 0, aInt
exception 0x7C, 4, aTlbmod
exception 0x7C, 8, aTlbload
exception 0x7C, 0xC, aTlbstore
exception 0x7C, 0x10, aAddressErrorOnLoadOrInstructionFet
exception 0x7C, 0x14, aAddressErrorOnStore
exception 0x7C, 0x18, aBusErrorExceptionOnInstructionFetc
exception 0x7C, 0x1C, aBusErrorExceptionOnDataReference
exception 0x7C, 0x20, aSyscall
exception 0x7C, 0x24, aBrk
exception 0x7C, 0x28, aReservedInstruction
exception 0x7C, 0x2C, aCopUnusable
exception 0x7C, 0x30, aOverflow
exception 0x7C, 0x34, aTrap
exception 0x7C, 0x38, aVirtualCoherencyExceptionOnIntruct
exception 0x7C, 0x3C, aFpException
exception 0x7C, 0x5C, aWatchpoint
exception 0x7C, 0x7C, aVirtualCoherencyExceptionOnDataRef
exception 0, 0, aExceptionNULL_0
exception 0x80000000, 0x80000000, aCu3
exception 0x40000000, 0x40000000, aCu2
exception 0x20000000, 0x20000000, aCu1
exception 0x10000000, 0x10000000, aCu0
exception 0x8000000, 0x8000000, aRp
exception 0x4000000, 0x4000000, aFr
exception 0x2000000, 0x2000000, aRe
exception 0x400000, 0x400000, aBev
exception 0x200000, 0x200000, aTs
exception 0x100000, 0x100000, aSr
exception 0x40000, 0x40000, aCh
exception 0x20000, 0x20000, aCe
exception 0x10000, 0x10000, aDe
exception 0x8000, 0x8000, aIm8
exception 0x4000, 0x4000, aIm7
exception 0x2000, 0x2000, aIm6
exception 0x1000, 0x1000, aIm5
exception 0x800, 0x800, aIm4
exception 0x400, 0x400, aIm3
exception 0x200, 0x200, aIm2
exception 0x100, 0x100, aIm1
exception 0x80, 0x80, aKx
exception 0x40, 0x40, aSx
exception 0x20, 0x20, aUx
exception 0x18, 0x10, aUsr
exception 0x18, 8, aSup
exception 0x18, 0, aKer
exception 4, 4, aErl
exception 2, 2, aExl
exception 1, 1, aIe
exception 0, 0, aExceptionNULL_1
exception 0x1000000, 0x1000000, aFs
exception 0x800000, 0x800000, aC_1
exception 0x20000, 0x20000, aUnimplemented
exception 0x10000, 0x10000, aInvalidOp
exception 0x8000, 0x8000, aBy0_0
exception 0x4000, 0x4000, aOverflow_0
exception 0x2000, 0x2000, aUnderflow
exception 0x1000, 0x1000, aInexactOp
exception 0x800, 0x800, aEv
exception 0x400, 0x400, aEz
exception 0x200, 0x200, aEo
exception 0x100, 0x100, aEu
exception 0x80, 0x80, aEi
exception 0x40, 0x40, aFv
exception 0x20, 0x20, aFz
exception 0x10, 0x10, aFo
exception 8, 8, aFu
exception 4, 4, aFi
exception 3, 0, aRn
exception 3, 1, aRz
exception 3, 2, aRp_1
exception 3, 3, aRm
exception 0, 0, aExceptionNULL

ptr_sp_rmon_0:  .word sp_rmon
ptr_sp_idle_0:  .word sp_idle
ptr_sp_shed_0:  .word sp_shed
ptr_sp_main_0:  .word sp_main
ptr_sp_audi_0:  .word sp_audi
ptr_sp_idle_1:  .word sp_idle
ptr_sp_shed_1:  .word sp_shed
ptr_sp_main_1:  .word sp_main
ptr_sp_audi_1:  .word sp_audi
ptr_sp_debug_0: .word sp_debug
ptr_sp_rmon_1:  .word sp_rmon
ptr_sp_idle_2:  .word sp_idle
ptr_sp_shed_2:  .word sp_shed
ptr_sp_main_2:  .word sp_main
ptr_sp_audi_2:  .word sp_audi

glabel stderr_buffer
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0
.word          0,         0,         0,         0,         0,         0,         0,         0,         0,         0

glabel std_error_font_bitcode
.word 0,0x22220200,0x55000000,0x5F5F500,0x27427200,0x5124500,0x34255300,0x22000000,0x24444420,0x42222240
.word 0x6F6F600,0x272000,0x240,0x70000,0x200,0x11224480,0x25555200,0x26222700,0x25125700,0x61211600
.word 0x33557300,0x64611600,0x24655200,0x71112200,0x25755200,0x25531600,0x200200,0x200640,0x1242100,0x707000
.word 0x4212400,0x7120200,0x25FF5700,0x2557D00,0x6575E00,0x7445300,0x7555600,0x7565700,0x7564400,0x7C95700
.word 0x5575500,0x7222700,0x3111600,0x5665500,0x4445F00,0xDFF9D00,0xF777D00,0x7DD5700,0x7564600,0x7995770
.word 0x7565500,0x7461E00,0x7222200,0xD999600,0xD552200,0xDF77500,0xD625500,0x5622600,0x7125700,0x32222230
.word 0x44222110,0x62222260,0x25000000,0x700,0x42200000,0x67D700,0x44755700,0x788600,0x117DD700,0x6FC700
.word 0x32722700,0x7DD730,0x44755500,0x2622700,0x2711130,0x44766500,0x62222700,0xFFFF00,0x755D00,0x6DD600
.word 0x755740,0x799710,0x744600,0x775700,0x2722300,0x555700,0x552200,0x577500,0x562500,0x552220
.word 0x703700,0x12242210,0x2222220,0x42212240,0x5A0000

glabel ptr_videobuffer1
.word 0                 

glabel ptr_videobuffer2
.word 0    

.section .rodata
aBd: .asciiz "BD"
aIp8: .asciiz "IP8"
aIp7: .asciiz "IP7"
aIp6: .asciiz "IP6"
aIp5: .asciiz "IP5"
aIp4: .asciiz "IP4"
aIp3: .asciiz "IP3"
aIp2: .asciiz "IP2"
aIp1: .asciiz "IP1"
aInt: .asciiz "Int"
aTlbmod: .asciiz "TLBmod"
aTlbload: .asciiz "TLBload"
aTlbstore: .asciiz "TLBstore"
aAddressErrorOnLoadOrInstructionFet: .asciiz "Address error on load or instruction fetch"
aAddressErrorOnStore: .asciiz "Address error on store"
aBusErrorExceptionOnInstructionFetc: .asciiz "Bus error exception on instruction fetch"
aBusErrorExceptionOnDataReference: .asciiz "Bus error exception on data reference"
aSyscall: .asciiz "Syscall"
aBrk: .asciiz "Brk"
aReservedInstruction: .asciiz "Reserved instruction"
aCopUnusable: .asciiz "Cop unusable"
aOverflow: .asciiz "Overflow"
aTrap: .asciiz "Trap"
aVirtualCoherencyExceptionOnIntruct: .asciiz "Virtual coherency exception on intruction fetch"
aFpException: .asciiz "Fp exception"
aWatchpoint: .asciiz "Watchpoint"
aVirtualCoherencyExceptionOnDataRef: .asciiz "Virtual coherency exception on data reference"
aExceptionNULL_0: .word 0
aCu3: .asciiz "CU3"
aCu2: .asciiz "CU2"
aCu1: .asciiz "CU1"
aCu0: .asciiz "CU0"
aRp: .asciiz "RP"
aFr: .asciiz "FR"
aRe: .asciiz "RE"
aBev: .asciiz "BEV"
aTs: .asciiz "TS"
aSr: .asciiz "SR"
aCh: .asciiz "CH"
aCe: .asciiz "CE"
aDe: .asciiz "DE"
aIm8: .asciiz "IM8"
aIm7: .asciiz "IM7"
aIm6: .asciiz "IM6"
aIm5: .asciiz "IM5"
aIm4: .asciiz "IM4"
aIm3: .asciiz "IM3"
aIm2: .asciiz "IM2"
aIm1: .asciiz "IM1"
aKx: .asciiz "KX"
aSx: .asciiz "SX"
aUx: .asciiz "UX"
aUsr: .asciiz "USR"
aSup: .asciiz "SUP"
aKer: .asciiz "KER"
aErl: .asciiz "ERL"
aExl: .asciiz "EXL"
aIe: .asciiz "IE"
aExceptionNULL_1: .word 0
aFs: .asciiz "FS"
aC_1: .asciiz "C"
aUnimplemented: .asciiz "Unimplemented"
aInvalidOp: .asciiz "Invalid op"
aBy0_0: .asciiz "/ by 0.0"
aOverflow_0: .asciiz "Overflow"
aUnderflow: .asciiz "Underflow"
aInexactOp: .asciiz "Inexact op"
aEv: .asciiz "EV"
aEz: .asciiz "EZ"
aEo: .asciiz "EO"
aEu: .asciiz "EU"
aEi: .asciiz "EI"
aFv: .asciiz "FV"
aFz: .asciiz "FZ"
aFo: .asciiz "FO"
aFu: .asciiz "FU"
aFi: .asciiz "FI"
aRn: .asciiz "RN"
aRz: .asciiz "RZ"
aRp_1: .asciiz "RP"
aRm: .asciiz "RM"
aExceptionNULL: .word 0
.align 4


.section .bss
