# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

debug_text_related_2:
/* 00B9B0 8000ADB0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00B9B4 8000ADB4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00B9B8 8000ADB8 0C002BC0 */  jal   debug_text_related_1
/* 00B9BC 8000ADBC 00000000 */   nop   
/* 00B9C0 8000ADC0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00B9C4 8000ADC4 27BD0018 */  addiu $sp, $sp, 0x18
/* 00B9C8 8000ADC8 03E00008 */  jr    $ra
/* 00B9CC 8000ADCC 00000000 */   nop   

display_text_to_coord:
/* 00B9D0 8000ADD0 AFA60008 */  sw    $a2, 8($sp)
/* 00B9D4 8000ADD4 30CE00FF */  andi  $t6, $a2, 0xff
/* 00B9D8 8000ADD8 3C038002 */  lui   $v1, %hi(stdout_environment_color) # $v1, 0x8002
/* 00B9DC 8000ADDC 3C088002 */  lui   $t0, %hi(stdout_primary_color_table) # $t0, 0x8002
/* 00B9E0 8000ADE0 3C0A8002 */  lui   $t2, %hi(stdout_environment_color_table) # $t2, 0x8002
/* 00B9E4 8000ADE4 3C098002 */  lui   $t1, %hi(D_800268B0) # $t1, 0x8002
/* 00B9E8 8000ADE8 01C03025 */  move  $a2, $t6
/* 00B9EC 8000ADEC AFA40000 */  sw    $a0, ($sp)
/* 00B9F0 8000ADF0 252968B0 */  addiu $t1, %lo(D_800268B0) # addiu $t1, $t1, 0x68b0
/* 00B9F4 8000ADF4 254A6710 */  addiu $t2, %lo(stdout_environment_color_table) # addiu $t2, $t2, 0x6710
/* 00B9F8 8000ADF8 25086610 */  addiu $t0, %lo(stdout_primary_color_table) # addiu $t0, $t0, 0x6610
/* 00B9FC 8000ADFC 8C6368AC */  lw    $v1, %lo(stdout_environment_color)($v1)
/* 00BA00 8000AE00 00001025 */  move  $v0, $zero
/* 00BA04 8000AE04 00003825 */  move  $a3, $zero
.L8000AE08:
/* 00BA08 8000AE08 8D0F0004 */  lw    $t7, 4($t0)
/* 00BA0C 8000AE0C 25080008 */  addiu $t0, $t0, 8
/* 00BA10 8000AE10 0147C821 */  addu  $t9, $t2, $a3
/* 00BA14 8000AE14 546F0006 */  bnel  $v1, $t7, .L8000AE30
/* 00BA18 8000AE18 24420001 */   addiu $v0, $v0, 1
/* 00BA1C 8000AE1C 8D380004 */  lw    $t8, 4($t1)
/* 00BA20 8000AE20 8F2B0004 */  lw    $t3, 4($t9)
/* 00BA24 8000AE24 530B0020 */  beql  $t8, $t3, .L8000AEA8
/* 00BA28 8000AE28 8FAE0000 */   lw    $t6, ($sp)
/* 00BA2C 8000AE2C 24420001 */  addiu $v0, $v0, 1
.L8000AE30:
/* 00BA30 8000AE30 28410020 */  slti  $at, $v0, 0x20
/* 00BA34 8000AE34 1420FFF4 */  bnez  $at, .L8000AE08
/* 00BA38 8000AE38 24E70008 */   addiu $a3, $a3, 8
/* 00BA3C 8000AE3C 3C078002 */  lui   $a3, %hi(string_formatting) # $a3, 0x8002
/* 00BA40 8000AE40 24E76810 */  addiu $a3, %lo(string_formatting) # addiu $a3, $a3, 0x6810
/* 00BA44 8000AE44 8CE30000 */  lw    $v1, ($a3)
/* 00BA48 8000AE48 3C0E8002 */  lui   $t6, %hi(stdout_primary_color) # $t6, 0x8002
/* 00BA4C 8000AE4C 25CE68A8 */  addiu $t6, %lo(stdout_primary_color) # addiu $t6, $t6, 0x68a8
/* 00BA50 8000AE50 8DC10000 */  lw    $at, ($t6)
/* 00BA54 8000AE54 3C0C8002 */  lui   $t4, %hi(stdout_primary_color_table) # $t4, 0x8002
/* 00BA58 8000AE58 258C6610 */  addiu $t4, %lo(stdout_primary_color_table) # addiu $t4, $t4, 0x6610
/* 00BA5C 8000AE5C 000320C0 */  sll   $a0, $v1, 3
/* 00BA60 8000AE60 008C6821 */  addu  $t5, $a0, $t4
/* 00BA64 8000AE64 ADA10000 */  sw    $at, ($t5)
/* 00BA68 8000AE68 8DD90004 */  lw    $t9, 4($t6)
/* 00BA6C 8000AE6C 0144C021 */  addu  $t8, $t2, $a0
/* 00BA70 8000AE70 246F0001 */  addiu $t7, $v1, 1
/* 00BA74 8000AE74 ADB90004 */  sw    $t9, 4($t5)
/* 00BA78 8000AE78 8D210000 */  lw    $at, ($t1)
/* 00BA7C 8000AE7C AF010000 */  sw    $at, ($t8)
/* 00BA80 8000AE80 8D2C0004 */  lw    $t4, 4($t1)
/* 00BA84 8000AE84 AF0C0004 */  sw    $t4, 4($t8)
/* 00BA88 8000AE88 05E10004 */  bgez  $t7, .L8000AE9C
/* 00BA8C 8000AE8C 31ED001F */   andi  $t5, $t7, 0x1f
/* 00BA90 8000AE90 11A00002 */  beqz  $t5, .L8000AE9C
/* 00BA94 8000AE94 00000000 */   nop   
/* 00BA98 8000AE98 25ADFFE0 */  addiu $t5, $t5, -0x20
.L8000AE9C:
/* 00BA9C 8000AE9C ACED0000 */  sw    $t5, ($a3)
/* 00BAA0 8000AEA0 01A01025 */  move  $v0, $t5
/* 00BAA4 8000AEA4 8FAE0000 */  lw    $t6, ($sp)
.L8000AEA8:
/* 00BAA8 8000AEA8 00055840 */  sll   $t3, $a1, 1
/* 00BAAC 8000AEAC 3C0C8002 */  lui   $t4, %hi(stdout_debug_menu_screen_buffer) # $t4, 0x8002
/* 00BAB0 8000AEB0 000EC8C0 */  sll   $t9, $t6, 3
/* 00BAB4 8000AEB4 032EC821 */  addu  $t9, $t9, $t6
/* 00BAB8 8000AEB8 0019C880 */  sll   $t9, $t9, 2
/* 00BABC 8000AEBC 032EC823 */  subu  $t9, $t9, $t6
/* 00BAC0 8000AEC0 0019C840 */  sll   $t9, $t9, 1
/* 00BAC4 8000AEC4 032BC021 */  addu  $t8, $t9, $t3
/* 00BAC8 8000AEC8 258C5030 */  addiu $t4, %lo(stdout_debug_menu_screen_buffer) # addiu $t4, $t4, 0x5030
/* 00BACC 8000AECC 030C1821 */  addu  $v1, $t8, $t4
/* 00BAD0 8000AED0 A0660000 */  sb    $a2, ($v1)
/* 00BAD4 8000AED4 03E00008 */  jr    $ra
/* 00BAD8 8000AED8 A0620001 */   sb    $v0, 1($v1)

debug_menu_text_related:
/* 00BADC 8000AEDC 3C0E8002 */  lui   $t6, %hi(debug_menu_x_pos_offset) # $t6, 0x8002
/* 00BAE0 8000AEE0 8DCE4FA0 */  lw    $t6, %lo(debug_menu_x_pos_offset)($t6)
/* 00BAE4 8000AEE4 3C018002 */  lui   $at, %hi(debug_menu_x_text_pos) # $at, 0x8002
/* 00BAE8 8000AEE8 3C0F8002 */  lui   $t7, %hi(debug_menu_y_pos_offset) # $t7, 0x8002
/* 00BAEC 8000AEEC 8DEF4FA4 */  lw    $t7, %lo(debug_menu_y_pos_offset)($t7)
/* 00BAF0 8000AEF0 AC2E4FA8 */  sw    $t6, %lo(debug_menu_x_text_pos)($at)
/* 00BAF4 8000AEF4 3C018002 */  lui   $at, 0x8002
/* 00BAF8 8000AEF8 03E00008 */  jr    $ra
/* 00BAFC 8000AEFC AC2F4FAC */   sw    $t7, 0x4fac($at)

debug_text_related_1:
/* 00BB00 8000AF00 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 00BB04 8000AF04 AFB30020 */  sw    $s3, 0x20($sp)
/* 00BB08 8000AF08 AFB2001C */  sw    $s2, 0x1c($sp)
/* 00BB0C 8000AF0C AFB10018 */  sw    $s1, 0x18($sp)
/* 00BB10 8000AF10 AFBF0024 */  sw    $ra, 0x24($sp)
/* 00BB14 8000AF14 AFB00014 */  sw    $s0, 0x14($sp)
/* 00BB18 8000AF18 24110050 */  li    $s1, 80
/* 00BB1C 8000AF1C 00009025 */  move  $s2, $zero
/* 00BB20 8000AF20 24130023 */  li    $s3, 35
/* 00BB24 8000AF24 00008025 */  move  $s0, $zero
.L8000AF28:
/* 00BB28 8000AF28 02002025 */  move  $a0, $s0
.L8000AF2C:
/* 00BB2C 8000AF2C 02402825 */  move  $a1, $s2
/* 00BB30 8000AF30 0C002B74 */  jal   display_text_to_coord
/* 00BB34 8000AF34 00003025 */   move  $a2, $zero
/* 00BB38 8000AF38 26100001 */  addiu $s0, $s0, 1
/* 00BB3C 8000AF3C 5611FFFB */  bnel  $s0, $s1, .L8000AF2C
/* 00BB40 8000AF40 02002025 */   move  $a0, $s0
/* 00BB44 8000AF44 26520001 */  addiu $s2, $s2, 1
/* 00BB48 8000AF48 5653FFF7 */  bnel  $s2, $s3, .L8000AF28
/* 00BB4C 8000AF4C 00008025 */   move  $s0, $zero
/* 00BB50 8000AF50 0C002BB7 */  jal   debug_menu_text_related
/* 00BB54 8000AF54 00000000 */   nop   
/* 00BB58 8000AF58 0C002B68 */  jal   null_function
/* 00BB5C 8000AF5C 00000000 */   nop   
/* 00BB60 8000AF60 8FBF0024 */  lw    $ra, 0x24($sp)
/* 00BB64 8000AF64 3C018002 */  lui   $at, %hi(string_formatting) # $at, 0x8002
/* 00BB68 8000AF68 8FB00014 */  lw    $s0, 0x14($sp)
/* 00BB6C 8000AF6C 8FB10018 */  lw    $s1, 0x18($sp)
/* 00BB70 8000AF70 8FB2001C */  lw    $s2, 0x1c($sp)
/* 00BB74 8000AF74 8FB30020 */  lw    $s3, 0x20($sp)
/* 00BB78 8000AF78 AC206810 */  sw    $zero, %lo(string_formatting)($at)
/* 00BB7C 8000AF7C 03E00008 */  jr    $ra
/* 00BB80 8000AF80 27BD0028 */   addiu $sp, $sp, 0x28

stubbed_function:
/* 00BB84 8000AF84 AFA40000 */  sw    $a0, ($sp)
/* 00BB88 8000AF88 AFA50004 */  sw    $a1, 4($sp)
/* 00BB8C 8000AF8C AFA60008 */  sw    $a2, 8($sp)
/* 00BB90 8000AF90 03E00008 */  jr    $ra
/* 00BB94 8000AF94 AFA7000C */   sw    $a3, 0xc($sp)

something_debug_info_related:
/* 00BB98 8000AF98 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 00BB9C 8000AF9C AFB30020 */  sw    $s3, 0x20($sp)
/* 00BBA0 8000AFA0 AFB2001C */  sw    $s2, 0x1c($sp)
/* 00BBA4 8000AFA4 AFB10018 */  sw    $s1, 0x18($sp)
/* 00BBA8 8000AFA8 AFBF0024 */  sw    $ra, 0x24($sp)
/* 00BBAC 8000AFAC AFB00014 */  sw    $s0, 0x14($sp)
/* 00BBB0 8000AFB0 24110021 */  li    $s1, 33
/* 00BBB4 8000AFB4 24120050 */  li    $s2, 80
/* 00BBB8 8000AFB8 24930021 */  addiu $s3, $a0, 0x21
.L8000AFBC:
/* 00BBBC 8000AFBC 0660000D */  bltz  $s3, .L8000AFF4
/* 00BBC0 8000AFC0 2A610023 */   slti  $at, $s3, 0x23
/* 00BBC4 8000AFC4 1020000B */  beqz  $at, .L8000AFF4
/* 00BBC8 8000AFC8 00008025 */   move  $s0, $zero
/* 00BBCC 8000AFCC 02002025 */  move  $a0, $s0
.L8000AFD0:
/* 00BBD0 8000AFD0 02602825 */  move  $a1, $s3
/* 00BBD4 8000AFD4 02003025 */  move  $a2, $s0
/* 00BBD8 8000AFD8 0C002BE1 */  jal   stubbed_function
/* 00BBDC 8000AFDC 02203825 */   move  $a3, $s1
/* 00BBE0 8000AFE0 26100001 */  addiu $s0, $s0, 1
/* 00BBE4 8000AFE4 5612FFFA */  bnel  $s0, $s2, .L8000AFD0
/* 00BBE8 8000AFE8 02002025 */   move  $a0, $s0
/* 00BBEC 8000AFEC 1000000A */  b     .L8000B018
/* 00BBF0 8000AFF0 02201025 */   move  $v0, $s1
.L8000AFF4:
/* 00BBF4 8000AFF4 00008025 */  move  $s0, $zero
/* 00BBF8 8000AFF8 02002025 */  move  $a0, $s0
.L8000AFFC:
/* 00BBFC 8000AFFC 02202825 */  move  $a1, $s1
/* 00BC00 8000B000 0C002B74 */  jal   display_text_to_coord
/* 00BC04 8000B004 00003025 */   move  $a2, $zero
/* 00BC08 8000B008 26100001 */  addiu $s0, $s0, 1
/* 00BC0C 8000B00C 5612FFFB */  bnel  $s0, $s2, .L8000AFFC
/* 00BC10 8000B010 02002025 */   move  $a0, $s0
/* 00BC14 8000B014 02201025 */  move  $v0, $s1
.L8000B018:
/* 00BC18 8000B018 2673FFFF */  addiu $s3, $s3, -1
/* 00BC1C 8000B01C 1620FFE7 */  bnez  $s1, .L8000AFBC
/* 00BC20 8000B020 2631FFFF */   addiu $s1, $s1, -1
/* 00BC24 8000B024 8FBF0024 */  lw    $ra, 0x24($sp)
/* 00BC28 8000B028 8FB00014 */  lw    $s0, 0x14($sp)
/* 00BC2C 8000B02C 8FB10018 */  lw    $s1, 0x18($sp)
/* 00BC30 8000B030 8FB2001C */  lw    $s2, 0x1c($sp)
/* 00BC34 8000B034 8FB30020 */  lw    $s3, 0x20($sp)
/* 00BC38 8000B038 03E00008 */  jr    $ra
/* 00BC3C 8000B03C 27BD0028 */   addiu $sp, $sp, 0x28

set_final_debug_text_positions:
/* 00BC40 8000B040 3C0E8002 */  lui   $t6, %hi(debug_menu_x_pos_offset) # $t6, 0x8002
/* 00BC44 8000B044 8DCE4FA0 */  lw    $t6, %lo(debug_menu_x_pos_offset)($t6)
/* 00BC48 8000B048 3C0F8002 */  lui   $t7, %hi(debug_menu_y_pos_offset) # $t7, 0x8002
/* 00BC4C 8000B04C 8DEF4FA4 */  lw    $t7, %lo(debug_menu_y_pos_offset)($t7)
/* 00BC50 8000B050 3C018002 */  lui   $at, %hi(debug_menu_x_text_pos) # $at, 0x8002
/* 00BC54 8000B054 008E2021 */  addu  $a0, $a0, $t6
/* 00BC58 8000B058 AC244FA8 */  sw    $a0, %lo(debug_menu_x_text_pos)($at)
/* 00BC5C 8000B05C 3C018002 */  lui   $at, 0x8002
/* 00BC60 8000B060 00AF2821 */  addu  $a1, $a1, $t7
/* 00BC64 8000B064 03E00008 */  jr    $ra
/* 00BC68 8000B068 AC254FAC */   sw    $a1, 0x4fac($at)

set_debug_text_color:
/* 00BC6C 8000B06C 00047600 */  sll   $t6, $a0, 0x18
/* 00BC70 8000B070 00057C00 */  sll   $t7, $a1, 0x10
/* 00BC74 8000B074 01CFC025 */  or    $t8, $t6, $t7
/* 00BC78 8000B078 0006CA00 */  sll   $t9, $a2, 8
/* 00BC7C 8000B07C 240900FF */  li    $t1, 255
/* 00BC80 8000B080 01275023 */  subu  $t2, $t1, $a3
/* 00BC84 8000B084 03194025 */  or    $t0, $t8, $t9
/* 00BC88 8000B088 010A5825 */  or    $t3, $t0, $t2
/* 00BC8C 8000B08C 3C018002 */  lui   $at, 0x8002
/* 00BC90 8000B090 03E00008 */  jr    $ra
/* 00BC94 8000B094 AC2B68AC */   sw    $t3, 0x68ac($at)

set_color_speedgraph:
/* 00BC98 8000B098 00047600 */  sll   $t6, $a0, 0x18
/* 00BC9C 8000B09C 00057C00 */  sll   $t7, $a1, 0x10
/* 00BCA0 8000B0A0 01CFC025 */  or    $t8, $t6, $t7
/* 00BCA4 8000B0A4 0006CA00 */  sll   $t9, $a2, 8
/* 00BCA8 8000B0A8 240900FF */  li    $t1, 255
/* 00BCAC 8000B0AC 01275023 */  subu  $t2, $t1, $a3
/* 00BCB0 8000B0B0 03194025 */  or    $t0, $t8, $t9
/* 00BCB4 8000B0B4 010A5825 */  or    $t3, $t0, $t2
/* 00BCB8 8000B0B8 3C018002 */  lui   $at, 0x8002
/* 00BCBC 8000B0BC 03E00008 */  jr    $ra
/* 00BCC0 8000B0C0 AC2B68B4 */   sw    $t3, 0x68b4($at)

write_char_to_screen:
/* 00BCC4 8000B0C4 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 00BCC8 8000B0C8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00BCCC 8000B0CC 0C001107 */  jal   get_video2_settings_txtClipW
/* 00BCD0 8000B0D0 AFA40028 */   sw    $a0, 0x28($sp)
/* 00BCD4 8000B0D4 244EFFF3 */  addiu $t6, $v0, -0xd
/* 00BCD8 8000B0D8 05C10003 */  bgez  $t6, .L8000B0E8
/* 00BCDC 8000B0DC 000E7883 */   sra   $t7, $t6, 2
/* 00BCE0 8000B0E0 25C10003 */  addiu $at, $t6, 3
/* 00BCE4 8000B0E4 00017883 */  sra   $t7, $at, 2
.L8000B0E8:
/* 00BCE8 8000B0E8 0C00110B */  jal   get_video2_settings_txtClipH
/* 00BCEC 8000B0EC AFAF0024 */   sw    $t7, 0x24($sp)
/* 00BCF0 8000B0F0 2448FFF6 */  addiu $t0, $v0, -0xa
/* 00BCF4 8000B0F4 24010007 */  li    $at, 7
/* 00BCF8 8000B0F8 0101001A */  div   $zero, $t0, $at
/* 00BCFC 8000B0FC 93A6002B */  lbu   $a2, 0x2b($sp)
/* 00BD00 8000B100 00004012 */  mflo  $t0
/* 00BD04 8000B104 3C028002 */  lui   $v0, %hi(debug_menu_x_text_pos) # $v0, 0x8002
/* 00BD08 8000B108 10C00005 */  beqz  $a2, .L8000B120
/* 00BD0C 8000B10C 00C01825 */   move  $v1, $a2
/* 00BD10 8000B110 28610020 */  slti  $at, $v1, 0x20
/* 00BD14 8000B114 1420000C */  bnez  $at, .L8000B148
/* 00BD18 8000B118 2861007F */   slti  $at, $v1, 0x7f
/* 00BD1C 8000B11C 1020000A */  beqz  $at, .L8000B148
.L8000B120:
/* 00BD20 8000B120 3C078002 */   lui   $a3, %hi(debug_menu_y_text_pos) # $a3, 0x8002
/* 00BD24 8000B124 24E74FAC */  addiu $a3, %lo(debug_menu_y_text_pos) # addiu $a3, $a3, 0x4fac
/* 00BD28 8000B128 24424FA8 */  addiu $v0, %lo(debug_menu_x_text_pos) # addiu $v0, $v0, 0x4fa8
/* 00BD2C 8000B12C 8C440000 */  lw    $a0, ($v0)
/* 00BD30 8000B130 8CE50000 */  lw    $a1, ($a3)
/* 00BD34 8000B134 AFA3001C */  sw    $v1, 0x1c($sp)
/* 00BD38 8000B138 0C002B74 */  jal   display_text_to_coord
/* 00BD3C 8000B13C AFA80020 */   sw    $t0, 0x20($sp)
/* 00BD40 8000B140 8FA3001C */  lw    $v1, 0x1c($sp)
/* 00BD44 8000B144 8FA80020 */  lw    $t0, 0x20($sp)
.L8000B148:
/* 00BD48 8000B148 3C028002 */  lui   $v0, %hi(debug_menu_x_text_pos) # $v0, 0x8002
/* 00BD4C 8000B14C 24424FA8 */  addiu $v0, %lo(debug_menu_x_text_pos) # addiu $v0, $v0, 0x4fa8
/* 00BD50 8000B150 8C590000 */  lw    $t9, ($v0)
/* 00BD54 8000B154 3C078002 */  lui   $a3, %hi(debug_menu_y_text_pos) # $a3, 0x8002
/* 00BD58 8000B158 2401000D */  li    $at, 13
/* 00BD5C 8000B15C 27290001 */  addiu $t1, $t9, 1
/* 00BD60 8000B160 24E74FAC */  addiu $a3, %lo(debug_menu_y_text_pos) # addiu $a3, $a3, 0x4fac
/* 00BD64 8000B164 10610007 */  beq   $v1, $at, .L8000B184
/* 00BD68 8000B168 AC490000 */   sw    $t1, ($v0)
/* 00BD6C 8000B16C 2401000A */  li    $at, 10
/* 00BD70 8000B170 10610004 */  beq   $v1, $at, .L8000B184
/* 00BD74 8000B174 8FAB0024 */   lw    $t3, 0x24($sp)
/* 00BD78 8000B178 012B082A */  slt   $at, $t1, $t3
/* 00BD7C 8000B17C 5420000D */  bnezl $at, .L8000B1B4
/* 00BD80 8000B180 8FBF0014 */   lw    $ra, 0x14($sp)
.L8000B184:
/* 00BD84 8000B184 8CED0000 */  lw    $t5, ($a3)
/* 00BD88 8000B188 3C0C8002 */  lui   $t4, %hi(debug_menu_x_pos_offset) # $t4, 0x8002
/* 00BD8C 8000B18C 8D8C4FA0 */  lw    $t4, %lo(debug_menu_x_pos_offset)($t4)
/* 00BD90 8000B190 25AE0001 */  addiu $t6, $t5, 1
/* 00BD94 8000B194 01C8082A */  slt   $at, $t6, $t0
/* 00BD98 8000B198 ACEE0000 */  sw    $t6, ($a3)
/* 00BD9C 8000B19C 14200004 */  bnez  $at, .L8000B1B0
/* 00BDA0 8000B1A0 AC4C0000 */   sw    $t4, ($v0)
/* 00BDA4 8000B1A4 3C188002 */  lui   $t8, %hi(debug_menu_y_pos_offset) # $t8, 0x8002
/* 00BDA8 8000B1A8 8F184FA4 */  lw    $t8, %lo(debug_menu_y_pos_offset)($t8)
/* 00BDAC 8000B1AC ACF80000 */  sw    $t8, ($a3)
.L8000B1B0:
/* 00BDB0 8000B1B0 8FBF0014 */  lw    $ra, 0x14($sp)
.L8000B1B4:
/* 00BDB4 8000B1B4 27BD0028 */  addiu $sp, $sp, 0x28
/* 00BDB8 8000B1B8 03E00008 */  jr    $ra
/* 00BDBC 8000B1BC 00000000 */   nop   

debug_text_related_0:
/* 00BDC0 8000B1C0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00BDC4 8000B1C4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00BDC8 8000B1C8 0C002C10 */  jal   set_final_debug_text_positions
/* 00BDCC 8000B1CC AFA60020 */   sw    $a2, 0x20($sp)
/* 00BDD0 8000B1D0 0C002C31 */  jal   write_char_to_screen
/* 00BDD4 8000B1D4 93A40023 */   lbu   $a0, 0x23($sp)
/* 00BDD8 8000B1D8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00BDDC 8000B1DC 27BD0018 */  addiu $sp, $sp, 0x18
/* 00BDE0 8000B1E0 03E00008 */  jr    $ra
/* 00BDE4 8000B1E4 00000000 */   nop   

write_string_stdout:
/* 00BDE8 8000B1E8 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00BDEC 8000B1EC AFBF001C */  sw    $ra, 0x1c($sp)
/* 00BDF0 8000B1F0 AFB10018 */  sw    $s1, 0x18($sp)
/* 00BDF4 8000B1F4 AFB00014 */  sw    $s0, 0x14($sp)
/* 00BDF8 8000B1F8 90900000 */  lbu   $s0, ($a0)
/* 00BDFC 8000B1FC 00808825 */  move  $s1, $a0
/* 00BE00 8000B200 12000006 */  beqz  $s0, .L8000B21C
/* 00BE04 8000B204 320400FF */   andi  $a0, $s0, 0xff
.L8000B208:
/* 00BE08 8000B208 0C002C31 */  jal   write_char_to_screen
/* 00BE0C 8000B20C 26310001 */   addiu $s1, $s1, 1
/* 00BE10 8000B210 92300000 */  lbu   $s0, ($s1)
/* 00BE14 8000B214 5600FFFC */  bnezl $s0, .L8000B208
/* 00BE18 8000B218 320400FF */   andi  $a0, $s0, 0xff
.L8000B21C:
/* 00BE1C 8000B21C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 00BE20 8000B220 8FB00014 */  lw    $s0, 0x14($sp)
/* 00BE24 8000B224 8FB10018 */  lw    $s1, 0x18($sp)
/* 00BE28 8000B228 03E00008 */  jr    $ra
/* 00BE2C 8000B22C 27BD0020 */   addiu $sp, $sp, 0x20

debug_text_related:
/* 00BE30 8000B230 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00BE34 8000B234 AFBF001C */  sw    $ra, 0x1c($sp)
/* 00BE38 8000B238 AFB10018 */  sw    $s1, 0x18($sp)
/* 00BE3C 8000B23C 00C08825 */  move  $s1, $a2
/* 00BE40 8000B240 0C002C10 */  jal   set_final_debug_text_positions
/* 00BE44 8000B244 AFB00014 */   sw    $s0, 0x14($sp)
/* 00BE48 8000B248 92300000 */  lbu   $s0, ($s1)
/* 00BE4C 8000B24C 12000006 */  beqz  $s0, .L8000B268
/* 00BE50 8000B250 320400FF */   andi  $a0, $s0, 0xff
.L8000B254:
/* 00BE54 8000B254 0C002C31 */  jal   write_char_to_screen
/* 00BE58 8000B258 26310001 */   addiu $s1, $s1, 1
/* 00BE5C 8000B25C 92300000 */  lbu   $s0, ($s1)
/* 00BE60 8000B260 5600FFFC */  bnezl $s0, .L8000B254
/* 00BE64 8000B264 320400FF */   andi  $a0, $s0, 0xff
.L8000B268:
/* 00BE68 8000B268 8FBF001C */  lw    $ra, 0x1c($sp)
/* 00BE6C 8000B26C 8FB00014 */  lw    $s0, 0x14($sp)
/* 00BE70 8000B270 8FB10018 */  lw    $s1, 0x18($sp)
/* 00BE74 8000B274 03E00008 */  jr    $ra
/* 00BE78 8000B278 27BD0020 */   addiu $sp, $sp, 0x20

read_screen_display_block_and_write_chars:
/* 00BE7C 8000B27C 27BDFF78 */  addiu $sp, $sp, -0x88
/* 00BE80 8000B280 AFB5002C */  sw    $s5, 0x2c($sp)
/* 00BE84 8000B284 AFB1001C */  sw    $s1, 0x1c($sp)
/* 00BE88 8000B288 AFB00018 */  sw    $s0, 0x18($sp)
/* 00BE8C 8000B28C 3C078002 */  lui   $a3, %hi(stdout_primary_color_table) # $a3, 0x8002
/* 00BE90 8000B290 00808025 */  move  $s0, $a0
/* 00BE94 8000B294 AFBF003C */  sw    $ra, 0x3c($sp)
/* 00BE98 8000B298 AFBE0038 */  sw    $fp, 0x38($sp)
/* 00BE9C 8000B29C AFB70034 */  sw    $s7, 0x34($sp)
/* 00BEA0 8000B2A0 AFB60030 */  sw    $s6, 0x30($sp)
/* 00BEA4 8000B2A4 AFB40028 */  sw    $s4, 0x28($sp)
/* 00BEA8 8000B2A8 AFB30024 */  sw    $s3, 0x24($sp)
/* 00BEAC 8000B2AC AFB20020 */  sw    $s2, 0x20($sp)
/* 00BEB0 8000B2B0 00808825 */  move  $s1, $a0
/* 00BEB4 8000B2B4 2406FFFF */  li    $a2, -1
/* 00BEB8 8000B2B8 24E76610 */  addiu $a3, %lo(stdout_primary_color_table) # addiu $a3, $a3, 0x6610
/* 00BEBC 8000B2BC 0000A825 */  move  $s5, $zero
/* 00BEC0 8000B2C0 00004025 */  move  $t0, $zero
.L8000B2C4:
/* 00BEC4 8000B2C4 3C0E8002 */  lui   $t6, 0x8002
/* 00BEC8 8000B2C8 25C55030 */  addiu $a1, $t6, 0x5030
/* 00BECC 8000B2CC 01052021 */  addu  $a0, $t0, $a1
.L8000B2D0:
/* 00BED0 8000B2D0 90820000 */  lbu   $v0, ($a0)
/* 00BED4 8000B2D4 24A50046 */  addiu $a1, $a1, 0x46
/* 00BED8 8000B2D8 90830001 */  lbu   $v1, 1($a0)
/* 00BEDC 8000B2DC 10400006 */  beqz  $v0, .L8000B2F8
/* 00BEE0 8000B2E0 00000000 */   nop   
/* 00BEE4 8000B2E4 50660004 */  beql  $v1, $a2, .L8000B2F8
/* 00BEE8 8000B2E8 26310018 */   addiu $s1, $s1, 0x18
/* 00BEEC 8000B2EC 26310010 */  addiu $s1, $s1, 0x10
/* 00BEF0 8000B2F0 00603025 */  move  $a2, $v1
/* 00BEF4 8000B2F4 26310018 */  addiu $s1, $s1, 0x18
.L8000B2F8:
/* 00BEF8 8000B2F8 14A7FFF5 */  bne   $a1, $a3, .L8000B2D0
/* 00BEFC 8000B2FC 24840046 */   addiu $a0, $a0, 0x46
/* 00BF00 8000B300 25080002 */  addiu $t0, $t0, 2
/* 00BF04 8000B304 29010046 */  slti  $at, $t0, 0x46
/* 00BF08 8000B308 1420FFEE */  bnez  $at, .L8000B2C4
/* 00BF0C 8000B30C 00000000 */   nop   
/* 00BF10 8000B310 0FC2F5DF */  jal   func_8F0BD77C
/* 00BF14 8000B314 02002025 */   move  $a0, $s0
/* 00BF18 8000B318 02302023 */  subu  $a0, $s1, $s0
/* 00BF1C 8000B31C 1C800003 */  bgtz  $a0, .L8000B32C
/* 00BF20 8000B320 2443F800 */   addiu $v1, $v0, -0x800
/* 00BF24 8000B324 10000080 */  b     .L8000B528
/* 00BF28 8000B328 02001025 */   move  $v0, $s0
.L8000B32C:
/* 00BF2C 8000B32C 1C600004 */  bgtz  $v1, .L8000B340
/* 00BF30 8000B330 2414FFFF */   li    $s4, -1
/* 00BF34 8000B334 3C018002 */  lui   $at, %hi(D_800268B8) # $at, 0x8002
/* 00BF38 8000B338 10000017 */  b     .L8000B398
/* 00BF3C 8000B33C AC2068B8 */   sw    $zero, %lo(D_800268B8)($at)
.L8000B340:
/* 00BF40 8000B340 0064082A */  slt   $at, $v1, $a0
/* 00BF44 8000B344 10200011 */  beqz  $at, .L8000B38C
/* 00BF48 8000B348 00037A00 */   sll   $t7, $v1, 8
/* 00BF4C 8000B34C 01E37823 */  subu  $t7, $t7, $v1
/* 00BF50 8000B350 01E4001A */  div   $zero, $t7, $a0
/* 00BF54 8000B354 14800002 */  bnez  $a0, .L8000B360
/* 00BF58 8000B358 00000000 */   nop   
/* 00BF5C 8000B35C 0007000D */  break 7
.L8000B360:
/* 00BF60 8000B360 2401FFFF */  li    $at, -1
/* 00BF64 8000B364 14810004 */  bne   $a0, $at, .L8000B378
/* 00BF68 8000B368 3C018000 */   lui   $at, 0x8000
/* 00BF6C 8000B36C 15E10002 */  bne   $t7, $at, .L8000B378
/* 00BF70 8000B370 00000000 */   nop   
/* 00BF74 8000B374 0006000D */  break 6
.L8000B378:
/* 00BF78 8000B378 3C018002 */  lui   $at, %hi(D_800268B8) # $at, 0x8002
/* 00BF7C 8000B37C 0000C012 */  mflo  $t8
/* 00BF80 8000B380 AC3868B8 */  sw    $t8, %lo(D_800268B8)($at)
/* 00BF84 8000B384 10000005 */  b     .L8000B39C
/* 00BF88 8000B388 02001025 */   move  $v0, $s0
.L8000B38C:
/* 00BF8C 8000B38C 24190100 */  li    $t9, 256
/* 00BF90 8000B390 3C018002 */  lui   $at, %hi(D_800268B8) # $at, 0x8002
/* 00BF94 8000B394 AC3968B8 */  sw    $t9, %lo(D_800268B8)($at)
.L8000B398:
/* 00BF98 8000B398 02001025 */  move  $v0, $s0
.L8000B39C:
/* 00BF9C 8000B39C 3C0A8002 */  lui   $t2, %hi(stdout_display_list) # $t2, 0x8002
/* 00BFA0 8000B3A0 254A4FB0 */  addiu $t2, %lo(stdout_display_list) # addiu $t2, $t2, 0x4fb0
/* 00BFA4 8000B3A4 3C090600 */  lui   $t1, 0x600
/* 00BFA8 8000B3A8 AC490000 */  sw    $t1, ($v0)
/* 00BFAC 8000B3AC AC4A0004 */  sw    $t2, 4($v0)
/* 00BFB0 8000B3B0 3C1E8002 */  lui   $fp, %hi(stdout_environment_color_table) # $fp, 0x8002
/* 00BFB4 8000B3B4 3C178002 */  lui   $s7, %hi(stdout_primary_color_table) # $s7, 0x8002
/* 00BFB8 8000B3B8 26100008 */  addiu $s0, $s0, 8
/* 00BFBC 8000B3BC 26F76610 */  addiu $s7, %lo(stdout_primary_color_table) # addiu $s7, $s7, 0x6610
/* 00BFC0 8000B3C0 27DE6710 */  addiu $fp, %lo(stdout_environment_color_table) # addiu $fp, $fp, 0x6710
/* 00BFC4 8000B3C4 AFA00040 */  sw    $zero, 0x40($sp)
/* 00BFC8 8000B3C8 0000A825 */  move  $s5, $zero
/* 00BFCC 8000B3CC 24160050 */  li    $s6, 80
.L8000B3D0:
/* 00BFD0 8000B3D0 8FAB0040 */  lw    $t3, 0x40($sp)
/* 00BFD4 8000B3D4 3C0C8002 */  lui   $t4, %hi(stdout_debug_menu_screen_buffer) # $t4, 0x8002
/* 00BFD8 8000B3D8 258C5030 */  addiu $t4, %lo(stdout_debug_menu_screen_buffer) # addiu $t4, $t4, 0x5030
/* 00BFDC 8000B3DC 00008825 */  move  $s1, $zero
/* 00BFE0 8000B3E0 016C9021 */  addu  $s2, $t3, $t4
.L8000B3E4:
/* 00BFE4 8000B3E4 92530000 */  lbu   $s3, ($s2)
/* 00BFE8 8000B3E8 92430001 */  lbu   $v1, 1($s2)
/* 00BFEC 8000B3EC 52600045 */  beql  $s3, $zero, .L8000B504
/* 00BFF0 8000B3F0 26310001 */   addiu $s1, $s1, 1
/* 00BFF4 8000B3F4 1074000D */  beq   $v1, $s4, .L8000B42C
/* 00BFF8 8000B3F8 000310C0 */   sll   $v0, $v1, 3
/* 00BFFC 8000B3FC 02E26821 */  addu  $t5, $s7, $v0
/* 00C000 8000B400 8DA10000 */  lw    $at, ($t5)
/* 00C004 8000B404 03C2C021 */  addu  $t8, $fp, $v0
/* 00C008 8000B408 26100010 */  addiu $s0, $s0, 0x10
/* 00C00C 8000B40C AE01FFF0 */  sw    $at, -0x10($s0)
/* 00C010 8000B410 8DAF0004 */  lw    $t7, 4($t5)
/* 00C014 8000B414 0060A025 */  move  $s4, $v1
/* 00C018 8000B418 AE0FFFF4 */  sw    $t7, -0xc($s0)
/* 00C01C 8000B41C 8F010000 */  lw    $at, ($t8)
/* 00C020 8000B420 AE01FFF8 */  sw    $at, -8($s0)
/* 00C024 8000B424 8F090004 */  lw    $t1, 4($t8)
/* 00C028 8000B428 AE09FFFC */  sw    $t1, -4($s0)
.L8000B42C:
/* 00C02C 8000B42C 0C002914 */  jal   random_related
/* 00C030 8000B430 00000000 */   nop   
/* 00C034 8000B434 3C0B8002 */  lui   $t3, %hi(D_800268B8) # $t3, 0x8002
/* 00C038 8000B438 8D6B68B8 */  lw    $t3, %lo(D_800268B8)($t3)
/* 00C03C 8000B43C 304A00FF */  andi  $t2, $v0, 0xff
/* 00C040 8000B440 014B082B */  sltu  $at, $t2, $t3
/* 00C044 8000B444 5020002F */  beql  $at, $zero, .L8000B504
/* 00C048 8000B448 26310001 */   addiu $s1, $s1, 1
/* 00C04C 8000B44C 0FC2F5DF */  jal   func_8F0BD77C
/* 00C050 8000B450 02002025 */   move  $a0, $s0
/* 00C054 8000B454 28410400 */  slti  $at, $v0, 0x400
/* 00C058 8000B458 14200029 */  bnez  $at, .L8000B500
/* 00C05C 8000B45C 02001025 */   move  $v0, $s0
/* 00C060 8000B460 00111900 */  sll   $v1, $s1, 4
/* 00C064 8000B464 001520C0 */  sll   $a0, $s5, 3
/* 00C068 8000B468 00952023 */  subu  $a0, $a0, $s5
/* 00C06C 8000B46C 246C0010 */  addiu $t4, $v1, 0x10
/* 00C070 8000B470 318E0FFF */  andi  $t6, $t4, 0xfff
/* 00C074 8000B474 00042080 */  sll   $a0, $a0, 2
/* 00C078 8000B478 306A0FFF */  andi  $t2, $v1, 0xfff
/* 00C07C 8000B47C 000A5B00 */  sll   $t3, $t2, 0xc
/* 00C080 8000B480 000E6B00 */  sll   $t5, $t6, 0xc
/* 00C084 8000B484 2499001C */  addiu $t9, $a0, 0x1c
/* 00C088 8000B488 308C0FFF */  andi  $t4, $a0, 0xfff
/* 00C08C 8000B48C 3C01E400 */  lui   $at, 0xe400
/* 00C090 8000B490 2666FFE0 */  addiu $a2, $s3, -0x20
/* 00C094 8000B494 00065143 */  sra   $t2, $a2, 5
/* 00C098 8000B498 01A17825 */  or    $t7, $t5, $at
/* 00C09C 8000B49C 016C7025 */  or    $t6, $t3, $t4
/* 00C0A0 8000B4A0 33380FFF */  andi  $t8, $t9, 0xfff
/* 00C0A4 8000B4A4 01F84825 */  or    $t1, $t7, $t8
/* 00C0A8 8000B4A8 000A58C0 */  sll   $t3, $t2, 3
/* 00C0AC 8000B4AC 016A5823 */  subu  $t3, $t3, $t2
/* 00C0B0 8000B4B0 26100008 */  addiu $s0, $s0, 8
/* 00C0B4 8000B4B4 02002825 */  move  $a1, $s0
/* 00C0B8 8000B4B8 000B5940 */  sll   $t3, $t3, 5
/* 00C0BC 8000B4BC AC490000 */  sw    $t1, ($v0)
/* 00C0C0 8000B4C0 30D8001F */  andi  $t8, $a2, 0x1f
/* 00C0C4 8000B4C4 AC4E0004 */  sw    $t6, 4($v0)
/* 00C0C8 8000B4C8 00184DC0 */  sll   $t1, $t8, 0x17
/* 00C0CC 8000B4CC 316CFFFF */  andi  $t4, $t3, 0xffff
/* 00C0D0 8000B4D0 26100008 */  addiu $s0, $s0, 8
/* 00C0D4 8000B4D4 3C0DB400 */  lui   $t5, 0xb400
/* 00C0D8 8000B4D8 ACAD0000 */  sw    $t5, ($a1)
/* 00C0DC 8000B4DC 02003825 */  move  $a3, $s0
/* 00C0E0 8000B4E0 012C7025 */  or    $t6, $t1, $t4
/* 00C0E4 8000B4E4 ACAE0004 */  sw    $t6, 4($a1)
/* 00C0E8 8000B4E8 3C190400 */  lui   $t9, (0x04000400 >> 16) # lui $t9, 0x400
/* 00C0EC 8000B4EC 37390400 */  ori   $t9, (0x04000400 & 0xFFFF) # ori $t9, $t9, 0x400
/* 00C0F0 8000B4F0 3C0DB300 */  lui   $t5, 0xb300
/* 00C0F4 8000B4F4 ACED0000 */  sw    $t5, ($a3)
/* 00C0F8 8000B4F8 ACF90004 */  sw    $t9, 4($a3)
/* 00C0FC 8000B4FC 26100008 */  addiu $s0, $s0, 8
.L8000B500:
/* 00C100 8000B500 26310001 */  addiu $s1, $s1, 1
.L8000B504:
/* 00C104 8000B504 1636FFB7 */  bne   $s1, $s6, .L8000B3E4
/* 00C108 8000B508 26520046 */   addiu $s2, $s2, 0x46
/* 00C10C 8000B50C 8FAF0040 */  lw    $t7, 0x40($sp)
/* 00C110 8000B510 26B50001 */  addiu $s5, $s5, 1
/* 00C114 8000B514 24010023 */  li    $at, 35
/* 00C118 8000B518 25F80002 */  addiu $t8, $t7, 2
/* 00C11C 8000B51C 16A1FFAC */  bne   $s5, $at, .L8000B3D0
/* 00C120 8000B520 AFB80040 */   sw    $t8, 0x40($sp)
/* 00C124 8000B524 02001025 */  move  $v0, $s0
.L8000B528:
/* 00C128 8000B528 8FBF003C */  lw    $ra, 0x3c($sp)
/* 00C12C 8000B52C 8FB00018 */  lw    $s0, 0x18($sp)
/* 00C130 8000B530 8FB1001C */  lw    $s1, 0x1c($sp)
/* 00C134 8000B534 8FB20020 */  lw    $s2, 0x20($sp)
/* 00C138 8000B538 8FB30024 */  lw    $s3, 0x24($sp)
/* 00C13C 8000B53C 8FB40028 */  lw    $s4, 0x28($sp)
/* 00C140 8000B540 8FB5002C */  lw    $s5, 0x2c($sp)
/* 00C144 8000B544 8FB60030 */  lw    $s6, 0x30($sp)
/* 00C148 8000B548 8FB70034 */  lw    $s7, 0x34($sp)
/* 00C14C 8000B54C 8FBE0038 */  lw    $fp, 0x38($sp)
/* 00C150 8000B550 03E00008 */  jr    $ra
/* 00C154 8000B554 27BD0088 */   addiu $sp, $sp, 0x88

/* 00C158 8000B558 00000000 */  nop   
/* 00C15C 8000B55C 00000000 */  nop   

