# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

init_audi:
/* 0027D0 80001BD0 27BDFEE8 */  addiu $sp, $sp, -0x118
/* 0027D4 80001BD4 AFB3002C */  sw    $s3, 0x2c($sp)
/* 0027D8 80001BD8 3C0E7000 */  lui   $t6, %hi(KSEG_audi_related_3) # $t6, 0x7000
/* 0027DC 80001BDC AFBF0034 */  sw    $ra, 0x34($sp)
/* 0027E0 80001BE0 AFB40030 */  sw    $s4, 0x30($sp)
/* 0027E4 80001BE4 AFB20028 */  sw    $s2, 0x28($sp)
/* 0027E8 80001BE8 AFB10024 */  sw    $s1, 0x24($sp)
/* 0027EC 80001BEC AFB00020 */  sw    $s0, 0x20($sp)
/* 0027F0 80001BF0 25CE25D8 */  addiu $t6, %lo(KSEG_audi_related_3) # addiu $t6, $t6, 0x25d8
/* 0027F4 80001BF4 00809825 */  move  $s3, $a0
/* 0027F8 80001BF8 AC8E0010 */  sw    $t6, 0x10($a0)
/* 0027FC 80001BFC 0C003A4C */  jal   osAiSetFrequency
/* 002800 80001C00 24045622 */   li    $a0, 22050
/* 002804 80001C04 00027840 */  sll   $t7, $v0, 1
/* 002808 80001C08 448F2000 */  mtc1  $t7, $f4
/* 00280C 80001C0C 3C014270 */  li    $at, 0x42700000 # 60.000000
/* 002810 80001C10 44814000 */  mtc1  $at, $f8
/* 002814 80001C14 468021A0 */  cvt.s.w $f6, $f4
/* 002818 80001C18 24190001 */  li    $t9, 1
/* 00281C 80001C1C 3C048006 */  lui   $a0, %hi(dword_CODE_bss_8005ECC4) # $a0, 0x8006
/* 002820 80001C20 3C148006 */  lui   $s4, %hi(dword_CODE_bss_8005ECC8) # $s4, 0x8006
/* 002824 80001C24 2484ECC4 */  addiu $a0, %lo(dword_CODE_bss_8005ECC4) # addiu $a0, $a0, -0x133c
/* 002828 80001C28 AE620018 */  sw    $v0, 0x18($s3)
/* 00282C 80001C2C 46083003 */  div.s $f0, $f6, $f8
/* 002830 80001C30 2694ECC8 */  addiu $s4, %lo(dword_CODE_bss_8005ECC8) # addiu $s4, $s4, -0x1338
/* 002834 80001C34 4458F800 */  cfc1  $t8, $31
/* 002838 80001C38 44D9F800 */  ctc1  $t9, $31
/* 00283C 80001C3C 00000000 */  nop   
/* 002840 80001C40 460002A4 */  cvt.w.s $f10, $f0
/* 002844 80001C44 4459F800 */  cfc1  $t9, $31
/* 002848 80001C48 00000000 */  nop   
/* 00284C 80001C4C 33390078 */  andi  $t9, $t9, 0x78
/* 002850 80001C50 13200012 */  beqz  $t9, .L80001C9C
/* 002854 80001C54 3C014F00 */   li    $at, 0x4F000000 # 2147483648.000000
/* 002858 80001C58 44815000 */  mtc1  $at, $f10
/* 00285C 80001C5C 24190001 */  li    $t9, 1
/* 002860 80001C60 460A0281 */  sub.s $f10, $f0, $f10
/* 002864 80001C64 44D9F800 */  ctc1  $t9, $31
/* 002868 80001C68 00000000 */  nop   
/* 00286C 80001C6C 460052A4 */  cvt.w.s $f10, $f10
/* 002870 80001C70 4459F800 */  cfc1  $t9, $31
/* 002874 80001C74 00000000 */  nop   
/* 002878 80001C78 33390078 */  andi  $t9, $t9, 0x78
/* 00287C 80001C7C 17200005 */  bnez  $t9, .L80001C94
/* 002880 80001C80 00000000 */   nop   
/* 002884 80001C84 44195000 */  mfc1  $t9, $f10
/* 002888 80001C88 3C018000 */  lui   $at, 0x8000
/* 00288C 80001C8C 10000007 */  b     .L80001CAC
/* 002890 80001C90 0321C825 */   or    $t9, $t9, $at
.L80001C94:
/* 002894 80001C94 10000005 */  b     .L80001CAC
/* 002898 80001C98 2419FFFF */   li    $t9, -1
.L80001C9C:
/* 00289C 80001C9C 44195000 */  mfc1  $t9, $f10
/* 0028A0 80001CA0 00000000 */  nop   
/* 0028A4 80001CA4 0720FFFB */  bltz  $t9, .L80001C94
/* 0028A8 80001CA8 00000000 */   nop   
.L80001CAC:
/* 0028AC 80001CAC 03201825 */  move  $v1, $t9
/* 0028B0 80001CB0 44D8F800 */  ctc1  $t8, $31
/* 0028B4 80001CB4 44838000 */  mtc1  $v1, $f16
/* 0028B8 80001CB8 AC990000 */  sw    $t9, ($a0)
/* 0028BC 80001CBC 07210005 */  bgez  $t9, .L80001CD4
/* 0028C0 80001CC0 468084A0 */   cvt.s.w $f18, $f16
/* 0028C4 80001CC4 3C014F80 */  li    $at, 0x4F800000 # 4294967296.000000
/* 0028C8 80001CC8 44812000 */  mtc1  $at, $f4
/* 0028CC 80001CCC 00000000 */  nop   
/* 0028D0 80001CD0 46049480 */  add.s $f18, $f18, $f4
.L80001CD4:
/* 0028D4 80001CD4 4600903C */  c.lt.s $f18, $f0
/* 0028D8 80001CD8 00000000 */  nop   
/* 0028DC 80001CDC 45000003 */  bc1f  .L80001CEC
/* 0028E0 80001CE0 24680001 */   addiu $t0, $v1, 1
/* 0028E4 80001CE4 AC880000 */  sw    $t0, ($a0)
/* 0028E8 80001CE8 01001825 */  move  $v1, $t0
.L80001CEC:
/* 0028EC 80001CEC 3069000F */  andi  $t1, $v1, 0xf
/* 0028F0 80001CF0 11200004 */  beqz  $t1, .L80001D04
/* 0028F4 80001CF4 2401FFF0 */   li    $at, -16
/* 0028F8 80001CF8 00615024 */  and   $t2, $v1, $at
/* 0028FC 80001CFC 25430010 */  addiu $v1, $t2, 0x10
/* 002900 80001D00 AC830000 */  sw    $v1, ($a0)
.L80001D04:
/* 002904 80001D04 246CFFF0 */  addiu $t4, $v1, -0x10
/* 002908 80001D08 3C018006 */  lui   $at, %hi(dword_CODE_bss_8005ECC0) # $at, 0x8006
/* 00290C 80001D0C AC2CECC0 */  sw    $t4, %lo(dword_CODE_bss_8005ECC0)($at)
/* 002910 80001D10 246D0035 */  addiu $t5, $v1, 0x35
/* 002914 80001D14 AE8D0000 */  sw    $t5, ($s4)
/* 002918 80001D18 926E001C */  lbu   $t6, 0x1c($s3)
/* 00291C 80001D1C 24010006 */  li    $at, 6
/* 002920 80001D20 3C048006 */  lui   $a0, %hi(dword_CODE_bss_8005E750) # $a0, 0x8006
/* 002924 80001D24 15C1001A */  bne   $t6, $at, .L80001D90
/* 002928 80001D28 2484E750 */   addiu $a0, %lo(dword_CODE_bss_8005E750) # addiu $a0, $a0, -0x18b0
/* 00292C 80001D2C 3C0F8002 */  lui   $t7, %hi(D_80023100) # $t7, 0x8002
/* 002930 80001D30 27A20048 */  addiu $v0, $sp, 0x48
/* 002934 80001D34 25EF3100 */  addiu $t7, %lo(D_80023100) # addiu $t7, $t7, 0x3100
/* 002938 80001D38 25F900C0 */  addiu $t9, $t7, 0xc0
/* 00293C 80001D3C 00404025 */  move  $t0, $v0
.L80001D40:
/* 002940 80001D40 8DE10000 */  lw    $at, ($t7)
/* 002944 80001D44 25EF000C */  addiu $t7, $t7, 0xc
/* 002948 80001D48 2508000C */  addiu $t0, $t0, 0xc
/* 00294C 80001D4C AD01FFF4 */  sw    $at, -0xc($t0)
/* 002950 80001D50 8DE1FFF8 */  lw    $at, -8($t7)
/* 002954 80001D54 AD01FFF8 */  sw    $at, -8($t0)
/* 002958 80001D58 8DE1FFFC */  lw    $at, -4($t7)
/* 00295C 80001D5C 15F9FFF8 */  bne   $t7, $t9, .L80001D40
/* 002960 80001D60 AD01FFFC */   sw    $at, -4($t0)
/* 002964 80001D64 8DE10000 */  lw    $at, ($t7)
/* 002968 80001D68 3C048006 */  lui   $a0, %hi(dword_CODE_bss_8005E750) # $a0, 0x8006
/* 00296C 80001D6C 2484E750 */  addiu $a0, %lo(dword_CODE_bss_8005E750) # addiu $a0, $a0, -0x18b0
/* 002970 80001D70 AD010000 */  sw    $at, ($t0)
/* 002974 80001D74 8DF90004 */  lw    $t9, 4($t7)
/* 002978 80001D78 02602825 */  move  $a1, $s3
/* 00297C 80001D7C AD190004 */  sw    $t9, 4($t0)
/* 002980 80001D80 0C003AC7 */  jal   alInit
/* 002984 80001D84 AE620020 */   sw    $v0, 0x20($s3)
/* 002988 80001D88 10000003 */  b     .L80001D98
/* 00298C 80001D8C 00000000 */   nop   
.L80001D90:
/* 002990 80001D90 0C003AC7 */  jal   alInit
/* 002994 80001D94 02602825 */   move  $a1, $s3
.L80001D98:
/* 002998 80001D98 3C108006 */  lui   $s0, %hi(dword_CODE_bss_8005E518) # $s0, 0x8006
/* 00299C 80001D9C 3C118006 */  lui   $s1, %hi(dword_CODE_bss_8005E524) # $s1, 0x8006
/* 0029A0 80001DA0 2631E524 */  addiu $s1, %lo(dword_CODE_bss_8005E524) # addiu $s1, $s1, -0x1adc
/* 0029A4 80001DA4 2610E518 */  addiu $s0, %lo(dword_CODE_bss_8005E518) # addiu $s0, $s0, -0x1ae8
.L80001DA8:
/* 0029A8 80001DA8 8E660014 */  lw    $a2, 0x14($s3)
/* 0029AC 80001DAC 24090060 */  li    $t1, 96
/* 0029B0 80001DB0 AFA90010 */  sw    $t1, 0x10($sp)
/* 0029B4 80001DB4 00002025 */  move  $a0, $zero
/* 0029B8 80001DB8 00002825 */  move  $a1, $zero
/* 0029BC 80001DBC 0C003AD4 */  jal   alHeapDBAlloc
/* 0029C0 80001DC0 24070001 */   li    $a3, 1
/* 0029C4 80001DC4 8E8A0000 */  lw    $t2, ($s4)
/* 0029C8 80001DC8 AE020008 */  sw    $v0, 8($s0)
/* 0029CC 80001DCC 8E660014 */  lw    $a2, 0x14($s3)
/* 0029D0 80001DD0 000A5880 */  sll   $t3, $t2, 2
/* 0029D4 80001DD4 AFAB0010 */  sw    $t3, 0x10($sp)
/* 0029D8 80001DD8 00002025 */  move  $a0, $zero
/* 0029DC 80001DDC 00002825 */  move  $a1, $zero
/* 0029E0 80001DE0 0C003AD4 */  jal   alHeapDBAlloc
/* 0029E4 80001DE4 24070001 */   li    $a3, 1
/* 0029E8 80001DE8 8E0C0008 */  lw    $t4, 8($s0)
/* 0029EC 80001DEC 26100004 */  addiu $s0, $s0, 4
/* 0029F0 80001DF0 0211082B */  sltu  $at, $s0, $s1
/* 0029F4 80001DF4 1420FFEC */  bnez  $at, .L80001DA8
/* 0029F8 80001DF8 AD820000 */   sw    $v0, ($t4)
/* 0029FC 80001DFC 3C048006 */  lui   $a0, %hi(msgQ_Q_8005E718) # $a0, 0x8006
/* 002A00 80001E00 3C058006 */  lui   $a1, %hi(msgQ_buf_8005E730) # $a1, 0x8006
/* 002A04 80001E04 24A5E730 */  addiu $a1, %lo(msgQ_buf_8005E730) # addiu $a1, $a1, -0x18d0
/* 002A08 80001E08 2484E718 */  addiu $a0, %lo(msgQ_Q_8005E718) # addiu $a0, $a0, -0x18e8
/* 002A0C 80001E0C 0C0035B4 */  jal   osCreateMesgQueue
/* 002A10 80001E10 24060008 */   li    $a2, 8
/* 002A14 80001E14 3C048006 */  lui   $a0, %hi(dword_CODE_bss_8005E6E0) # $a0, 0x8006
/* 002A18 80001E18 3C058006 */  lui   $a1, %hi(dword_CODE_bss_8005E6F8) # $a1, 0x8006
/* 002A1C 80001E1C 24A5E6F8 */  addiu $a1, %lo(dword_CODE_bss_8005E6F8) # addiu $a1, $a1, -0x1908
/* 002A20 80001E20 2484E6E0 */  addiu $a0, %lo(dword_CODE_bss_8005E6E0) # addiu $a0, $a0, -0x1920
/* 002A24 80001E24 0C0035B4 */  jal   osCreateMesgQueue
/* 002A28 80001E28 24060008 */   li    $a2, 8
/* 002A2C 80001E2C 3C048006 */  lui   $a0, %hi(audDMAMessageQ) # $a0, 0x8006
/* 002A30 80001E30 3C058006 */  lui   $a1, %hi(audDMAMessageBUF) # $a1, 0x8006
/* 002A34 80001E34 24A5F2E8 */  addiu $a1, %lo(audDMAMessageBUF) # addiu $a1, $a1, -0xd18
/* 002A38 80001E38 2484F2D0 */  addiu $a0, %lo(audDMAMessageQ) # addiu $a0, $a0, -0xd30
/* 002A3C 80001E3C 0C0035B4 */  jal   osCreateMesgQueue
/* 002A40 80001E40 24060040 */   li    $a2, 64
/* 002A44 80001E44 3C028006 */  lui   $v0, %hi(dword_CODE_bss_8005E7C0) # $v0, 0x8006
/* 002A48 80001E48 2442E7C0 */  addiu $v0, %lo(dword_CODE_bss_8005E7C0) # addiu $v0, $v0, -0x1840
/* 002A4C 80001E4C 3C118006 */  lui   $s1, %hi(dword_CODE_bss_8005E7C0) # $s1, 0x8006
/* 002A50 80001E50 3C108006 */  lui   $s0, %hi(dword_CODE_bss_8005E7D4) # $s0, 0x8006
/* 002A54 80001E54 AC400004 */  sw    $zero, 4($v0)
/* 002A58 80001E58 AC400000 */  sw    $zero, ($v0)
/* 002A5C 80001E5C 2610E7D4 */  addiu $s0, %lo(dword_CODE_bss_8005E7D4) # addiu $s0, $s0, -0x182c
/* 002A60 80001E60 2631E7C0 */  addiu $s1, %lo(dword_CODE_bss_8005E7C0) # addiu $s1, $s1, -0x1840
/* 002A64 80001E64 00009025 */  move  $s2, $zero
.L80001E68:
/* 002A68 80001E68 02002025 */  move  $a0, $s0
/* 002A6C 80001E6C 0C003AB0 */  jal   alLink
/* 002A70 80001E70 02202825 */   move  $a1, $s1
/* 002A74 80001E74 8E660014 */  lw    $a2, 0x14($s3)
/* 002A78 80001E78 240D0200 */  li    $t5, 512
/* 002A7C 80001E7C AFAD0010 */  sw    $t5, 0x10($sp)
/* 002A80 80001E80 00002025 */  move  $a0, $zero
/* 002A84 80001E84 00002825 */  move  $a1, $zero
/* 002A88 80001E88 0C003AD4 */  jal   alHeapDBAlloc
/* 002A8C 80001E8C 24070001 */   li    $a3, 1
/* 002A90 80001E90 26520001 */  addiu $s2, $s2, 1
/* 002A94 80001E94 2A41003F */  slti  $at, $s2, 0x3f
/* 002A98 80001E98 26310014 */  addiu $s1, $s1, 0x14
/* 002A9C 80001E9C 26100014 */  addiu $s0, $s0, 0x14
/* 002AA0 80001EA0 1420FFF1 */  bnez  $at, .L80001E68
/* 002AA4 80001EA4 AE22FFFC */   sw    $v0, -4($s1)
/* 002AA8 80001EA8 8E660014 */  lw    $a2, 0x14($s3)
/* 002AAC 80001EAC 240E0200 */  li    $t6, 512
/* 002AB0 80001EB0 AFAE0010 */  sw    $t6, 0x10($sp)
/* 002AB4 80001EB4 00002025 */  move  $a0, $zero
/* 002AB8 80001EB8 00002825 */  move  $a1, $zero
/* 002ABC 80001EBC 0C003AD4 */  jal   alHeapDBAlloc
/* 002AC0 80001EC0 24070001 */   li    $a3, 1
/* 002AC4 80001EC4 AE220010 */  sw    $v0, 0x10($s1)
/* 002AC8 80001EC8 3C118006 */  lui   $s1, %hi(dword_CODE_bss_8005E520) # $s1, 0x8006
/* 002ACC 80001ECC 3C108006 */  lui   $s0, %hi(dword_CODE_bss_8005E518) # $s0, 0x8006
/* 002AD0 80001ED0 2610E518 */  addiu $s0, %lo(dword_CODE_bss_8005E518) # addiu $s0, $s0, -0x1ae8
/* 002AD4 80001ED4 2631E520 */  addiu $s1, %lo(dword_CODE_bss_8005E520) # addiu $s1, $s1, -0x1ae0
.L80001ED8:
/* 002AD8 80001ED8 8E660014 */  lw    $a2, 0x14($s3)
/* 002ADC 80001EDC 24185DC0 */  li    $t8, 24000
/* 002AE0 80001EE0 AFB80010 */  sw    $t8, 0x10($sp)
/* 002AE4 80001EE4 00002025 */  move  $a0, $zero
/* 002AE8 80001EE8 00002825 */  move  $a1, $zero
/* 002AEC 80001EEC 0C003AD4 */  jal   alHeapDBAlloc
/* 002AF0 80001EF0 24070001 */   li    $a3, 1
/* 002AF4 80001EF4 26100004 */  addiu $s0, $s0, 4
/* 002AF8 80001EF8 1611FFF7 */  bne   $s0, $s1, .L80001ED8
/* 002AFC 80001EFC AE02FFFC */   sw    $v0, -4($s0)
/* 002B00 80001F00 3C04803B */  lui   $a0, %hi(sp_audi) # $a0, 0x803b
/* 002B04 80001F04 24843950 */  addiu $a0, %lo(sp_audi) # addiu $a0, $a0, 0x3950
/* 002B08 80001F08 0C0001BC */  jal   grow_stack
/* 002B0C 80001F0C 24051000 */   li    $a1, 4096
/* 002B10 80001F10 3C048006 */  lui   $a0, %hi(audithread) # $a0, 0x8006
/* 002B14 80001F14 3C067000 */  lui   $a2, %hi(KSEG_audi_entry) # $a2, 0x7000
/* 002B18 80001F18 24190014 */  li    $t9, 20
/* 002B1C 80001F1C AFB90014 */  sw    $t9, 0x14($sp)
/* 002B20 80001F20 24C61F7C */  addiu $a2, %lo(KSEG_audi_entry) # addiu $a2, $a2, 0x1f7c
/* 002B24 80001F24 2484E530 */  addiu $a0, %lo(audithread) # addiu $a0, $a0, -0x1ad0
/* 002B28 80001F28 24050004 */  li    $a1, 4
/* 002B2C 80001F2C 00003825 */  move  $a3, $zero
/* 002B30 80001F30 0C00350C */  jal   osCreateThread
/* 002B34 80001F34 AFA20010 */   sw    $v0, 0x10($sp)
/* 002B38 80001F38 8FBF0034 */  lw    $ra, 0x34($sp)
/* 002B3C 80001F3C 8FB00020 */  lw    $s0, 0x20($sp)
/* 002B40 80001F40 8FB10024 */  lw    $s1, 0x24($sp)
/* 002B44 80001F44 8FB20028 */  lw    $s2, 0x28($sp)
/* 002B48 80001F48 8FB3002C */  lw    $s3, 0x2c($sp)
/* 002B4C 80001F4C 8FB40030 */  lw    $s4, 0x30($sp)
/* 002B50 80001F50 03E00008 */  jr    $ra
/* 002B54 80001F54 27BD0118 */   addiu $sp, $sp, 0x118

startaudithread:
/* 002B58 80001F58 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 002B5C 80001F5C AFBF0014 */  sw    $ra, 0x14($sp)
/* 002B60 80001F60 3C048006 */  lui   $a0, %hi(audithread) # $a0, 0x8006
/* 002B64 80001F64 0C003560 */  jal   osStartThread
/* 002B68 80001F68 2484E530 */   addiu $a0, %lo(audithread) # addiu $a0, $a0, -0x1ad0
/* 002B6C 80001F6C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 002B70 80001F70 27BD0018 */  addiu $sp, $sp, 0x18
/* 002B74 80001F74 03E00008 */  jr    $ra
/* 002B78 80001F78 00000000 */   nop   

audi_entry:
/* 002B7C 80001F7C 27BDFF90 */  addiu $sp, $sp, -0x70
/* 002B80 80001F80 AFB60030 */  sw    $s6, 0x30($sp)
/* 002B84 80001F84 3C168006 */  lui   $s6, %hi(dword_CODE_bss_8005E6E0) # $s6, 0x8006
/* 002B88 80001F88 AFA40070 */  sw    $a0, 0x70($sp)
/* 002B8C 80001F8C 26D6E6E0 */  addiu $s6, %lo(dword_CODE_bss_8005E6E0) # addiu $s6, $s6, -0x1920
/* 002B90 80001F90 AFBF003C */  sw    $ra, 0x3c($sp)
/* 002B94 80001F94 AFB20020 */  sw    $s2, 0x20($sp)
/* 002B98 80001F98 AFB1001C */  sw    $s1, 0x1c($sp)
/* 002B9C 80001F9C 3C048006 */  lui   $a0, %hi(D_8005DA40) # $a0, 0x8006
/* 002BA0 80001FA0 3C058006 */  lui   $a1, %hi(dword_CODE_bss_8005E7A0) # $a1, 0x8006
/* 002BA4 80001FA4 AFBE0038 */  sw    $fp, 0x38($sp)
/* 002BA8 80001FA8 AFB70034 */  sw    $s7, 0x34($sp)
/* 002BAC 80001FAC AFB5002C */  sw    $s5, 0x2c($sp)
/* 002BB0 80001FB0 AFB40028 */  sw    $s4, 0x28($sp)
/* 002BB4 80001FB4 AFB30024 */  sw    $s3, 0x24($sp)
/* 002BB8 80001FB8 AFB00018 */  sw    $s0, 0x18($sp)
/* 002BBC 80001FBC 00008825 */  move  $s1, $zero
/* 002BC0 80001FC0 00009025 */  move  $s2, $zero
/* 002BC4 80001FC4 AFA00064 */  sw    $zero, 0x64($sp)
/* 002BC8 80001FC8 AFA00060 */  sw    $zero, 0x60($sp)
/* 002BCC 80001FCC 24A5E7A0 */  addiu $a1, %lo(dword_CODE_bss_8005E7A0) # addiu $a1, $a1, -0x1860
/* 002BD0 80001FD0 2484DA40 */  addiu $a0, %lo(D_8005DA40) # addiu $a0, $a0, -0x25c0
/* 002BD4 80001FD4 02C03025 */  move  $a2, $s6
/* 002BD8 80001FD8 0C000305 */  jal   osScAddClient
/* 002BDC 80001FDC 24070001 */   li    $a3, 1
/* 002BE0 80001FE0 3C158006 */  lui   $s5, %hi(dword_CODE_bss_8005E4E0) # $s5, 0x8006
/* 002BE4 80001FE4 3C148006 */  lui   $s4, %hi(dword_CODE_bss_8005E4D8) # $s4, 0x8006
/* 002BE8 80001FE8 3C138006 */  lui   $s3, %hi(dword_CODE_bss_8005E4B8) # $s3, 0x8006
/* 002BEC 80001FEC 3C108006 */  lui   $s0, %hi(dword_CODE_bss_8005E4D0) # $s0, 0x8006
/* 002BF0 80001FF0 2610E4D0 */  addiu $s0, %lo(dword_CODE_bss_8005E4D0) # addiu $s0, $s0, -0x1b30
/* 002BF4 80001FF4 2673E4B8 */  addiu $s3, %lo(dword_CODE_bss_8005E4B8) # addiu $s3, $s3, -0x1b48
/* 002BF8 80001FF8 2694E4D8 */  addiu $s4, %lo(dword_CODE_bss_8005E4D8) # addiu $s4, $s4, -0x1b28
/* 002BFC 80001FFC 26B5E4E0 */  addiu $s5, %lo(dword_CODE_bss_8005E4E0) # addiu $s5, $s5, -0x1b20
/* 002C00 80002000 241E0001 */  li    $fp, 1
/* 002C04 80002004 27B70064 */  addiu $s7, $sp, 0x64
/* 002C08 80002008 02C02025 */  move  $a0, $s6
.L8000200C:
/* 002C0C 8000200C 02E02825 */  move  $a1, $s7
/* 002C10 80002010 0C003774 */  jal   osRecvMesg
/* 002C14 80002014 03C03025 */   move  $a2, $fp
/* 002C18 80002018 8FAE0064 */  lw    $t6, 0x64($sp)
/* 002C1C 8000201C 24010005 */  li    $at, 5
/* 002C20 80002020 85C40000 */  lh    $a0, ($t6)
/* 002C24 80002024 109E0007 */  beq   $a0, $fp, .L80002044
/* 002C28 80002028 00000000 */   nop   
/* 002C2C 8000202C 10810071 */  beq   $a0, $at, .L800021F4
/* 002C30 80002030 2401000A */   li    $at, 10
/* 002C34 80002034 50810072 */  beql  $a0, $at, .L80002200
/* 002C38 80002038 03C09025 */   move  $s2, $fp
/* 002C3C 8000203C 10000070 */  b     .L80002200
/* 002C40 80002040 00000000 */   nop   
.L80002044:
/* 002C44 80002044 0C003AEC */  jal   osGetTime
/* 002C48 80002048 00000000 */   nop   
/* 002C4C 8000204C AE820000 */  sw    $v0, ($s4)
/* 002C50 80002050 AE830004 */  sw    $v1, 4($s4)
/* 002C54 80002054 0C000A15 */  jal   video_related_3
/* 002C58 80002058 3C040003 */   lui   $a0, 3
/* 002C5C 8000205C 3C0F8002 */  lui   $t7, %hi(D_800230F4) # $t7, 0x8002
/* 002C60 80002060 8DEF30F4 */  lw    $t7, %lo(D_800230F4)($t7)
/* 002C64 80002064 24010003 */  li    $at, 3
/* 002C68 80002068 3C048006 */  lui   $a0, 0x8006
/* 002C6C 8000206C 01E1001B */  divu  $zero, $t7, $at
/* 002C70 80002070 0000C010 */  mfhi  $t8
/* 002C74 80002074 0018C880 */  sll   $t9, $t8, 2
/* 002C78 80002078 00992021 */  addu  $a0, $a0, $t9
/* 002C7C 8000207C 8C84E520 */  lw    $a0, -0x1ae0($a0)
/* 002C80 80002080 0C000891 */  jal   process_audio_packet
/* 002C84 80002084 8FA50060 */   lw    $a1, 0x60($sp)
/* 002C88 80002088 26310001 */  addiu $s1, $s1, 1
/* 002C8C 8000208C 0C000A15 */  jal   video_related_3
/* 002C90 80002090 3C040006 */   lui   $a0, 6
/* 002C94 80002094 0C003AEC */  jal   osGetTime
/* 002C98 80002098 00000000 */   nop   
/* 002C9C 8000209C 8E8A0000 */  lw    $t2, ($s4)
/* 002CA0 800020A0 8E8B0004 */  lw    $t3, 4($s4)
/* 002CA4 800020A4 AEA20000 */  sw    $v0, ($s5)
/* 002CA8 800020A8 004AC023 */  subu  $t8, $v0, $t2
/* 002CAC 800020AC 006B082B */  sltu  $at, $v1, $t3
/* 002CB0 800020B0 0301C023 */  subu  $t8, $t8, $at
/* 002CB4 800020B4 AEA30004 */  sw    $v1, 4($s5)
/* 002CB8 800020B8 3C018006 */  lui   $at, %hi(dword_CODE_bss_8005E4C0) # $at, 0x8006
/* 002CBC 800020BC 006BC823 */  subu  $t9, $v1, $t3
/* 002CC0 800020C0 AC39E4C4 */  sw    $t9, %lo(dword_CODE_bss_8005E4C4)($at)
/* 002CC4 800020C4 AC38E4C0 */  sw    $t8, %lo(dword_CODE_bss_8005E4C0)($at)
/* 002CC8 800020C8 240100F0 */  li    $at, 240
/* 002CCC 800020CC 0221001A */  div   $zero, $s1, $at
/* 002CD0 800020D0 00004010 */  mfhi  $t0
/* 002CD4 800020D4 AFB90044 */  sw    $t9, 0x44($sp)
/* 002CD8 800020D8 AFB80040 */  sw    $t8, 0x40($sp)
/* 002CDC 800020DC AFA20050 */  sw    $v0, 0x50($sp)
/* 002CE0 800020E0 AFA30054 */  sw    $v1, 0x54($sp)
/* 002CE4 800020E4 AFAA0048 */  sw    $t2, 0x48($sp)
/* 002CE8 800020E8 1500001C */  bnez  $t0, .L8000215C
/* 002CEC 800020EC AFAB004C */   sw    $t3, 0x4c($sp)
/* 002CF0 800020F0 8E040000 */  lw    $a0, ($s0)
/* 002CF4 800020F4 8E050004 */  lw    $a1, 4($s0)
/* 002CF8 800020F8 24060000 */  li    $a2, 0
/* 002CFC 800020FC 0C003B2A */  jal   ull_div
/* 002D00 80002100 240700F0 */   li    $a3, 240
/* 002D04 80002104 3C018006 */  lui   $at, %hi(dword_CODE_bss_8005E4CC) # $at, 0x8006
/* 002D08 80002108 AC22E4C8 */  sw    $v0, %lo(dword_CODE_bss_8005E4C8)($at)
/* 002D0C 8000210C AC23E4CC */  sw    $v1, %lo(dword_CODE_bss_8005E4CC)($at)
/* 002D10 80002110 8E990004 */  lw    $t9, 4($s4)
/* 002D14 80002114 8E980000 */  lw    $t8, ($s4)
/* 002D18 80002118 8EAF0004 */  lw    $t7, 4($s5)
/* 002D1C 8000211C 8EAE0000 */  lw    $t6, ($s5)
/* 002D20 80002120 240A0000 */  li    $t2, 0
/* 002D24 80002124 01F9082B */  sltu  $at, $t7, $t9
/* 002D28 80002128 01D84023 */  subu  $t0, $t6, $t8
/* 002D2C 8000212C 01014023 */  subu  $t0, $t0, $at
/* 002D30 80002130 240B0000 */  li    $t3, 0
/* 002D34 80002134 240C0000 */  li    $t4, 0
/* 002D38 80002138 240D0000 */  li    $t5, 0
/* 002D3C 8000213C 01F94823 */  subu  $t1, $t7, $t9
/* 002D40 80002140 AFA90044 */  sw    $t1, 0x44($sp)
/* 002D44 80002144 AE6D0004 */  sw    $t5, 4($s3)
/* 002D48 80002148 AE6C0000 */  sw    $t4, ($s3)
/* 002D4C 8000214C AE0B0004 */  sw    $t3, 4($s0)
/* 002D50 80002150 AFA80040 */  sw    $t0, 0x40($sp)
/* 002D54 80002154 10000011 */  b     .L8000219C
/* 002D58 80002158 AE0A0000 */   sw    $t2, ($s0)
.L8000215C:
/* 002D5C 8000215C 8E0B0004 */  lw    $t3, 4($s0)
/* 002D60 80002160 8FAD0054 */  lw    $t5, 0x54($sp)
/* 002D64 80002164 8E0A0000 */  lw    $t2, ($s0)
/* 002D68 80002168 8FAC0050 */  lw    $t4, 0x50($sp)
/* 002D6C 8000216C 016D7821 */  addu  $t7, $t3, $t5
/* 002D70 80002170 8FB80048 */  lw    $t8, 0x48($sp)
/* 002D74 80002174 8FB9004C */  lw    $t9, 0x4c($sp)
/* 002D78 80002178 01ED082B */  sltu  $at, $t7, $t5
/* 002D7C 8000217C 002A7021 */  addu  $t6, $at, $t2
/* 002D80 80002180 01CC7021 */  addu  $t6, $t6, $t4
/* 002D84 80002184 01D84023 */  subu  $t0, $t6, $t8
/* 002D88 80002188 01F9082B */  sltu  $at, $t7, $t9
/* 002D8C 8000218C 01014023 */  subu  $t0, $t0, $at
/* 002D90 80002190 01F94823 */  subu  $t1, $t7, $t9
/* 002D94 80002194 AE090004 */  sw    $t1, 4($s0)
/* 002D98 80002198 AE080000 */  sw    $t0, ($s0)
.L8000219C:
/* 002D9C 8000219C 8E6A0000 */  lw    $t2, ($s3)
/* 002DA0 800021A0 8FAC0040 */  lw    $t4, 0x40($sp)
/* 002DA4 800021A4 8E6B0004 */  lw    $t3, 4($s3)
/* 002DA8 800021A8 8FAD0044 */  lw    $t5, 0x44($sp)
/* 002DAC 800021AC 018A082B */  sltu  $at, $t4, $t2
/* 002DB0 800021B0 14200008 */  bnez  $at, .L800021D4
/* 002DB4 800021B4 3C048006 */   lui   $a0, %hi(msgQ_Q_8005E718) # $a0, 0x8006
/* 002DB8 800021B8 014C082B */  sltu  $at, $t2, $t4
/* 002DBC 800021BC 14200003 */  bnez  $at, .L800021CC
/* 002DC0 800021C0 016D082B */   sltu  $at, $t3, $t5
/* 002DC4 800021C4 10200003 */  beqz  $at, .L800021D4
/* 002DC8 800021C8 00000000 */   nop   
.L800021CC:
/* 002DCC 800021CC AE6C0000 */  sw    $t4, ($s3)
/* 002DD0 800021D0 AE6D0004 */  sw    $t5, 4($s3)
.L800021D4:
/* 002DD4 800021D4 2484E718 */  addiu $a0, %lo(msgQ_Q_8005E718) # addiu $a0, $a0, -0x18e8
/* 002DD8 800021D8 27A50060 */  addiu $a1, $sp, 0x60
/* 002DDC 800021DC 0C003774 */  jal   osRecvMesg
/* 002DE0 800021E0 03C03025 */   move  $a2, $fp
/* 002DE4 800021E4 0C0008F9 */  jal   audi_length_related
/* 002DE8 800021E8 8FA40060 */   lw    $a0, 0x60($sp)
/* 002DEC 800021EC 10000004 */  b     .L80002200
/* 002DF0 800021F0 00000000 */   nop   
.L800021F4:
/* 002DF4 800021F4 10000002 */  b     .L80002200
/* 002DF8 800021F8 03C09025 */   move  $s2, $fp
/* 002DFC 800021FC 03C09025 */  move  $s2, $fp
.L80002200:
/* 002E00 80002200 5240FF82 */  beql  $s2, $zero, .L8000200C
/* 002E04 80002204 02C02025 */   move  $a0, $s6
/* 002E08 80002208 3C048006 */  lui   $a0, %hi(dword_CODE_bss_8005E750) # $a0, 0x8006
/* 002E0C 8000220C 0C003AB9 */  jal   alClose
/* 002E10 80002210 2484E750 */   addiu $a0, %lo(dword_CODE_bss_8005E750) # addiu $a0, $a0, -0x18b0
/* 002E14 80002214 8FBF003C */  lw    $ra, 0x3c($sp)
/* 002E18 80002218 8FB00018 */  lw    $s0, 0x18($sp)
/* 002E1C 8000221C 8FB1001C */  lw    $s1, 0x1c($sp)
/* 002E20 80002220 8FB20020 */  lw    $s2, 0x20($sp)
/* 002E24 80002224 8FB30024 */  lw    $s3, 0x24($sp)
/* 002E28 80002228 8FB40028 */  lw    $s4, 0x28($sp)
/* 002E2C 8000222C 8FB5002C */  lw    $s5, 0x2c($sp)
/* 002E30 80002230 8FB60030 */  lw    $s6, 0x30($sp)
/* 002E34 80002234 8FB70034 */  lw    $s7, 0x34($sp)
/* 002E38 80002238 8FBE0038 */  lw    $fp, 0x38($sp)
/* 002E3C 8000223C 03E00008 */  jr    $ra
/* 002E40 80002240 27BD0070 */   addiu $sp, $sp, 0x70

process_audio_packet:
/* 002E44 80002244 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 002E48 80002248 AFBF001C */  sw    $ra, 0x1c($sp)
/* 002E4C 8000224C AFB00018 */  sw    $s0, 0x18($sp)
/* 002E50 80002250 00808025 */  move  $s0, $a0
/* 002E54 80002254 0C000984 */  jal   audi_related_4
/* 002E58 80002258 AFA5002C */   sw    $a1, 0x2c($sp)
/* 002E5C 8000225C 0C003A2C */  jal   osVirtualToPhysical
/* 002E60 80002260 8E040000 */   lw    $a0, ($s0)
/* 002E64 80002264 8FA3002C */  lw    $v1, 0x2c($sp)
/* 002E68 80002268 AFA20024 */  sw    $v0, 0x24($sp)
/* 002E6C 8000226C 10600006 */  beqz  $v1, .L80002288
/* 002E70 80002270 00000000 */   nop   
/* 002E74 80002274 84650004 */  lh    $a1, 4($v1)
/* 002E78 80002278 8C640000 */  lw    $a0, ($v1)
/* 002E7C 8000227C 00057080 */  sll   $t6, $a1, 2
/* 002E80 80002280 0C003BC0 */  jal   osAiSetNextBuffer
/* 002E84 80002284 01C02825 */   move  $a1, $t6
.L80002288:
/* 002E88 80002288 0C003BEC */  jal   osAiGetLength
/* 002E8C 8000228C 00000000 */   nop   
/* 002E90 80002290 3C0F8006 */  lui   $t7, %hi(dword_CODE_bss_8005ECC4) # $t7, 0x8006
/* 002E94 80002294 8DEFECC4 */  lw    $t7, %lo(dword_CODE_bss_8005ECC4)($t7)
/* 002E98 80002298 0002C082 */  srl   $t8, $v0, 2
/* 002E9C 8000229C 3C038006 */  lui   $v1, %hi(dword_CODE_bss_8005ECC0) # $v1, 0x8006
/* 002EA0 800022A0 01F8C823 */  subu  $t9, $t7, $t8
/* 002EA4 800022A4 27280035 */  addiu $t0, $t9, 0x35
/* 002EA8 800022A8 3109FFF0 */  andi  $t1, $t0, 0xfff0
/* 002EAC 800022AC A6090004 */  sh    $t1, 4($s0)
/* 002EB0 800022B0 8C63ECC0 */  lw    $v1, %lo(dword_CODE_bss_8005ECC0)($v1)
/* 002EB4 800022B4 86070004 */  lh    $a3, 4($s0)
/* 002EB8 800022B8 3C0C8002 */  lui   $t4, %hi(D_800230FC) # $t4, 0x8002
/* 002EBC 800022BC 00035400 */  sll   $t2, $v1, 0x10
/* 002EC0 800022C0 000A5C03 */  sra   $t3, $t2, 0x10
/* 002EC4 800022C4 00EB082A */  slt   $at, $a3, $t3
/* 002EC8 800022C8 10200003 */  beqz  $at, .L800022D8
/* 002ECC 800022CC 3C048006 */   lui   $a0, 0x8006
/* 002ED0 800022D0 A6030004 */  sh    $v1, 4($s0)
/* 002ED4 800022D4 86070004 */  lh    $a3, 4($s0)
.L800022D8:
/* 002ED8 800022D8 8D8C30FC */  lw    $t4, %lo(D_800230FC)($t4)
/* 002EDC 800022DC 3C058006 */  lui   $a1, %hi(dword_CODE_bss_8005ECCC) # $a1, 0x8006
/* 002EE0 800022E0 24A5ECCC */  addiu $a1, %lo(dword_CODE_bss_8005ECCC) # addiu $a1, $a1, -0x1334
/* 002EE4 800022E4 000C6880 */  sll   $t5, $t4, 2
/* 002EE8 800022E8 008D2021 */  addu  $a0, $a0, $t5
/* 002EEC 800022EC 8C84E518 */  lw    $a0, -0x1ae8($a0)
/* 002EF0 800022F0 0C003C42 */  jal   alAudioFrame
/* 002EF4 800022F4 8FA60024 */   lw    $a2, 0x24($sp)
/* 002EF8 800022F8 3C0E8006 */  lui   $t6, %hi(msgQ_Q_8005E718) # $t6, 0x8006
/* 002EFC 800022FC 24030002 */  li    $v1, 2
/* 002F00 80002300 3C068002 */  lui   $a2, %hi(D_800230FC) # $a2, 0x8002
/* 002F04 80002304 25CEE718 */  addiu $t6, %lo(msgQ_Q_8005E718) # addiu $t6, $t6, -0x18e8
/* 002F08 80002308 24C630FC */  addiu $a2, %lo(D_800230FC) # addiu $a2, $a2, 0x30fc
/* 002F0C 8000230C AE000008 */  sw    $zero, 8($s0)
/* 002F10 80002310 AE0E0058 */  sw    $t6, 0x58($s0)
/* 002F14 80002314 AE10005C */  sw    $s0, 0x5c($s0)
/* 002F18 80002318 AE030010 */  sw    $v1, 0x10($s0)
/* 002F1C 8000231C 8CCF0000 */  lw    $t7, ($a2)
/* 002F20 80002320 3C078006 */  lui   $a3, %hi(dword_CODE_bss_8005E518) # $a3, 0x8006
/* 002F24 80002324 24E7E518 */  addiu $a3, %lo(dword_CODE_bss_8005E518) # addiu $a3, $a3, -0x1ae8
/* 002F28 80002328 000FC080 */  sll   $t8, $t7, 2
/* 002F2C 8000232C 00F8C821 */  addu  $t9, $a3, $t8
/* 002F30 80002330 8F280000 */  lw    $t0, ($t9)
/* 002F34 80002334 3C058002 */  lui   $a1, %hi(rspbootTextStart) # $a1, 0x8002
/* 002F38 80002338 3C188002 */  lui   $t8, %hi(gsp3DTextStart) # $t8, 0x8002
/* 002F3C 8000233C AE080048 */  sw    $t0, 0x48($s0)
/* 002F40 80002340 8CC90000 */  lw    $t1, ($a2)
/* 002F44 80002344 24A50D90 */  addiu $a1, %lo(rspbootTextStart) # addiu $a1, $a1, 0xd90
/* 002F48 80002348 27180E60 */  addiu $t8, %lo(gsp3DTextStart) # addiu $t8, $t8, 0xe60
/* 002F4C 8000234C 00095080 */  sll   $t2, $t1, 2
/* 002F50 80002350 00EA5821 */  addu  $t3, $a3, $t2
/* 002F54 80002354 8D6C0000 */  lw    $t4, ($t3)
/* 002F58 80002358 3C088002 */  lui   $t0, %hi(aspMainTextStart) # $t0, 0x8002
/* 002F5C 8000235C 3C098006 */  lui   $t1, %hi(D_8005D020) # $t1, 0x8006
/* 002F60 80002360 004C6823 */  subu  $t5, $v0, $t4
/* 002F64 80002364 000D70C3 */  sra   $t6, $t5, 3
/* 002F68 80002368 000E78C0 */  sll   $t7, $t6, 3
/* 002F6C 8000236C 0305C823 */  subu  $t9, $t8, $a1
/* 002F70 80002370 25082280 */  addiu $t0, %lo(aspMainTextStart) # addiu $t0, $t0, 0x2280
/* 002F74 80002374 2529D020 */  addiu $t1, %lo(D_8005D020) # addiu $t1, $t1, -0x2fe0
/* 002F78 80002378 240A0800 */  li    $t2, 2048
/* 002F7C 8000237C 3C048006 */  lui   $a0, %hi(D_8005DA40) # $a0, 0x8006
/* 002F80 80002380 AE0F004C */  sw    $t7, 0x4c($s0)
/* 002F84 80002384 AE030018 */  sw    $v1, 0x18($s0)
/* 002F88 80002388 AE050020 */  sw    $a1, 0x20($s0)
/* 002F8C 8000238C AE190024 */  sw    $t9, 0x24($s0)
/* 002F90 80002390 AE00001C */  sw    $zero, 0x1c($s0)
/* 002F94 80002394 AE080028 */  sw    $t0, 0x28($s0)
/* 002F98 80002398 AE090030 */  sw    $t1, 0x30($s0)
/* 002F9C 8000239C AE0A0034 */  sw    $t2, 0x34($s0)
/* 002FA0 800023A0 AE000050 */  sw    $zero, 0x50($s0)
/* 002FA4 800023A4 AE000054 */  sw    $zero, 0x54($s0)
/* 002FA8 800023A8 0C00033E */  jal   osScGetCmdQ
/* 002FAC 800023AC 2484DA40 */   addiu $a0, %lo(D_8005DA40) # addiu $a0, $a0, -0x25c0
/* 002FB0 800023B0 00402025 */  move  $a0, $v0
/* 002FB4 800023B4 26050008 */  addiu $a1, $s0, 8
/* 002FB8 800023B8 0C0037C4 */  jal   osSendMesg
/* 002FBC 800023BC 00003025 */   move  $a2, $zero
/* 002FC0 800023C0 3C038002 */  lui   $v1, %hi(D_800230FC) # $v1, 0x8002
/* 002FC4 800023C4 246330FC */  addiu $v1, %lo(D_800230FC) # addiu $v1, $v1, 0x30fc
/* 002FC8 800023C8 8C6B0000 */  lw    $t3, ($v1)
/* 002FCC 800023CC 8FBF001C */  lw    $ra, 0x1c($sp)
/* 002FD0 800023D0 8FB00018 */  lw    $s0, 0x18($sp)
/* 002FD4 800023D4 396C0001 */  xori  $t4, $t3, 1
/* 002FD8 800023D8 AC6C0000 */  sw    $t4, ($v1)
/* 002FDC 800023DC 03E00008 */  jr    $ra
/* 002FE0 800023E0 27BD0028 */   addiu $sp, $sp, 0x28

audi_length_related:
/* 002FE4 800023E4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 002FE8 800023E8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 002FEC 800023EC 0C003BEC */  jal   osAiGetLength
/* 002FF0 800023F0 AFA40018 */   sw    $a0, 0x18($sp)
/* 002FF4 800023F4 00027083 */  sra   $t6, $v0, 2
/* 002FF8 800023F8 15C00006 */  bnez  $t6, .L80002414
/* 002FFC 800023FC 3C0F8002 */   lui   $t7, %hi(D_800231C8) # $t7, 0x8002
/* 003000 80002400 8DEF31C8 */  lw    $t7, %lo(D_800231C8)($t7)
/* 003004 80002404 3C018002 */  lui   $at, %hi(D_800231C8) # $at, 0x8002
/* 003008 80002408 55E00003 */  bnezl $t7, .L80002418
/* 00300C 8000240C 8FBF0014 */   lw    $ra, 0x14($sp)
/* 003010 80002410 AC2031C8 */  sw    $zero, %lo(D_800231C8)($at)
.L80002414:
/* 003014 80002414 8FBF0014 */  lw    $ra, 0x14($sp)
.L80002418:
/* 003018 80002418 27BD0018 */  addiu $sp, $sp, 0x18
/* 00301C 8000241C 03E00008 */  jr    $ra
/* 003020 80002420 00000000 */   nop   

audi_related_2:
/* 003024 80002424 3C098006 */  lui   $t1, %hi(off_CODE_bss_8005E7B0) # $t1, 0x8006
/* 003028 80002428 2529E7B0 */  addiu $t1, %lo(off_CODE_bss_8005E7B0) # addiu $t1, $t1, -0x1850
/* 00302C 8000242C 8D280004 */  lw    $t0, 4($t1)
/* 003030 80002430 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 003034 80002434 AFB00028 */  sw    $s0, 0x28($sp)
/* 003038 80002438 AFA60058 */  sw    $a2, 0x58($sp)
/* 00303C 8000243C 308A0001 */  andi  $t2, $a0, 1
/* 003040 80002440 AFBF002C */  sw    $ra, 0x2c($sp)
/* 003044 80002444 00803825 */  move  $a3, $a0
/* 003048 80002448 00003025 */  move  $a2, $zero
/* 00304C 8000244C AFAA0048 */  sw    $t2, 0x48($sp)
/* 003050 80002450 11000015 */  beqz  $t0, .L800024A8
/* 003054 80002454 01008025 */   move  $s0, $t0
/* 003058 80002458 8E020008 */  lw    $v0, 8($s0)
.L8000245C:
/* 00305C 8000245C 00E57021 */  addu  $t6, $a3, $a1
/* 003060 80002460 00E2082B */  sltu  $at, $a3, $v0
/* 003064 80002464 14200010 */  bnez  $at, .L800024A8
/* 003068 80002468 24430200 */   addiu $v1, $v0, 0x200
/* 00306C 8000246C 006E082A */  slt   $at, $v1, $t6
/* 003070 80002470 1420000A */  bnez  $at, .L8000249C
/* 003074 80002474 02003025 */   move  $a2, $s0
/* 003078 80002478 8E180010 */  lw    $t8, 0x10($s0)
/* 00307C 8000247C 3C0F8002 */  lui   $t7, %hi(D_800230F4) # $t7, 0x8002
/* 003080 80002480 8DEF30F4 */  lw    $t7, %lo(D_800230F4)($t7)
/* 003084 80002484 0307C821 */  addu  $t9, $t8, $a3
/* 003088 80002488 03222023 */  subu  $a0, $t9, $v0
/* 00308C 8000248C 0C003A2C */  jal   osVirtualToPhysical
/* 003090 80002490 AE0F000C */   sw    $t7, 0xc($s0)
/* 003094 80002494 1000004C */  b     .L800025C8
/* 003098 80002498 8FBF002C */   lw    $ra, 0x2c($sp)
.L8000249C:
/* 00309C 8000249C 8E100000 */  lw    $s0, ($s0)
/* 0030A0 800024A0 5600FFEE */  bnezl $s0, .L8000245C
/* 0030A4 800024A4 8E020008 */   lw    $v0, 8($s0)
.L800024A8:
/* 0030A8 800024A8 8D300008 */  lw    $s0, 8($t1)
/* 0030AC 800024AC 1600000A */  bnez  $s0, .L800024D8
/* 0030B0 800024B0 02002025 */   move  $a0, $s0
/* 0030B4 800024B4 54C00003 */  bnezl $a2, .L800024C4
/* 0030B8 800024B8 8CC40010 */   lw    $a0, 0x10($a2)
/* 0030BC 800024BC 01003025 */  move  $a2, $t0
/* 0030C0 800024C0 8CC40010 */  lw    $a0, 0x10($a2)
.L800024C4:
/* 0030C4 800024C4 0C003A2C */  jal   osVirtualToPhysical
/* 0030C8 800024C8 AFAA0030 */   sw    $t2, 0x30($sp)
/* 0030CC 800024CC 8FAA0030 */  lw    $t2, 0x30($sp)
/* 0030D0 800024D0 1000003C */  b     .L800025C4
/* 0030D4 800024D4 004A1021 */   addu  $v0, $v0, $t2
.L800024D8:
/* 0030D8 800024D8 8E0B0000 */  lw    $t3, ($s0)
/* 0030DC 800024DC AFA70050 */  sw    $a3, 0x50($sp)
/* 0030E0 800024E0 AFA60038 */  sw    $a2, 0x38($sp)
/* 0030E4 800024E4 0C003AA4 */  jal   alUnlink
/* 0030E8 800024E8 AD2B0008 */   sw    $t3, 8($t1)
/* 0030EC 800024EC 8FA60038 */  lw    $a2, 0x38($sp)
/* 0030F0 800024F0 3C098006 */  lui   $t1, %hi(off_CODE_bss_8005E7B0) # $t1, 0x8006
/* 0030F4 800024F4 2529E7B0 */  addiu $t1, %lo(off_CODE_bss_8005E7B0) # addiu $t1, $t1, -0x1850
/* 0030F8 800024F8 10C00007 */  beqz  $a2, .L80002518
/* 0030FC 800024FC 8FA70050 */   lw    $a3, 0x50($sp)
/* 003100 80002500 02002025 */  move  $a0, $s0
/* 003104 80002504 00C02825 */  move  $a1, $a2
/* 003108 80002508 0C003AB0 */  jal   alLink
/* 00310C 8000250C AFA70050 */   sw    $a3, 0x50($sp)
/* 003110 80002510 1000000C */  b     .L80002544
/* 003114 80002514 8FA70050 */   lw    $a3, 0x50($sp)
.L80002518:
/* 003118 80002518 8D280004 */  lw    $t0, 4($t1)
/* 00311C 8000251C 51000007 */  beql  $t0, $zero, .L8000253C
/* 003120 80002520 AD300004 */   sw    $s0, 4($t1)
/* 003124 80002524 AD300004 */  sw    $s0, 4($t1)
/* 003128 80002528 AE080000 */  sw    $t0, ($s0)
/* 00312C 8000252C AE000004 */  sw    $zero, 4($s0)
/* 003130 80002530 10000004 */  b     .L80002544
/* 003134 80002534 AD100004 */   sw    $s0, 4($t0)
/* 003138 80002538 AD300004 */  sw    $s0, 4($t1)
.L8000253C:
/* 00313C 8000253C AE000000 */  sw    $zero, ($s0)
/* 003140 80002540 AE000004 */  sw    $zero, 4($s0)
.L80002544:
/* 003144 80002544 8FAC0048 */  lw    $t4, 0x48($sp)
/* 003148 80002548 3C0D8002 */  lui   $t5, %hi(D_800230F4) # $t5, 0x8002
/* 00314C 8000254C 3C088002 */  lui   $t0, %hi(D_800230F8) # $t0, 0x8002
/* 003150 80002550 00EC3823 */  subu  $a3, $a3, $t4
/* 003154 80002554 AE070008 */  sw    $a3, 8($s0)
/* 003158 80002558 8DAD30F4 */  lw    $t5, %lo(D_800230F4)($t5)
/* 00315C 8000255C 250830F8 */  addiu $t0, %lo(D_800230F8) # addiu $t0, $t0, 0x30f8
/* 003160 80002560 8E030010 */  lw    $v1, 0x10($s0)
/* 003164 80002564 AE0D000C */  sw    $t5, 0xc($s0)
/* 003168 80002568 8D020000 */  lw    $v0, ($t0)
/* 00316C 8000256C 3C0F8006 */  lui   $t7, %hi(dword_CODE_bss_8005ECD0) # $t7, 0x8006
/* 003170 80002570 3C198006 */  lui   $t9, %hi(audDMAMessageQ) # $t9, 0x8006
/* 003174 80002574 00027080 */  sll   $t6, $v0, 2
/* 003178 80002578 01C27023 */  subu  $t6, $t6, $v0
/* 00317C 8000257C 000E70C0 */  sll   $t6, $t6, 3
/* 003180 80002580 2739F2D0 */  addiu $t9, %lo(audDMAMessageQ) # addiu $t9, $t9, -0xd30
/* 003184 80002584 25EFECD0 */  addiu $t7, %lo(dword_CODE_bss_8005ECD0) # addiu $t7, $t7, -0x1330
/* 003188 80002588 24180200 */  li    $t8, 512
/* 00318C 8000258C 244B0001 */  addiu $t3, $v0, 1
/* 003190 80002590 AD0B0000 */  sw    $t3, ($t0)
/* 003194 80002594 AFB80014 */  sw    $t8, 0x14($sp)
/* 003198 80002598 01CF2021 */  addu  $a0, $t6, $t7
/* 00319C 8000259C AFB90018 */  sw    $t9, 0x18($sp)
/* 0031A0 800025A0 24050001 */  li    $a1, 1
/* 0031A4 800025A4 00003025 */  move  $a2, $zero
/* 0031A8 800025A8 AFA3004C */  sw    $v1, 0x4c($sp)
/* 0031AC 800025AC 0C003DA8 */  jal   osPiStartDma
/* 0031B0 800025B0 AFA30010 */   sw    $v1, 0x10($sp)
/* 0031B4 800025B4 0C003A2C */  jal   osVirtualToPhysical
/* 0031B8 800025B8 8FA4004C */   lw    $a0, 0x4c($sp)
/* 0031BC 800025BC 8FAC0048 */  lw    $t4, 0x48($sp)
/* 0031C0 800025C0 004C1021 */  addu  $v0, $v0, $t4
.L800025C4:
/* 0031C4 800025C4 8FBF002C */  lw    $ra, 0x2c($sp)
.L800025C8:
/* 0031C8 800025C8 8FB00028 */  lw    $s0, 0x28($sp)
/* 0031CC 800025CC 27BD0050 */  addiu $sp, $sp, 0x50
/* 0031D0 800025D0 03E00008 */  jr    $ra
/* 0031D4 800025D4 00000000 */   nop   

audi_related_3:
/* 0031D8 800025D8 3C038006 */  lui   $v1, %hi(off_CODE_bss_8005E7B0) # $v1, 0x8006
/* 0031DC 800025DC 2463E7B0 */  addiu $v1, %lo(off_CODE_bss_8005E7B0) # addiu $v1, $v1, -0x1850
/* 0031E0 800025E0 906E0000 */  lbu   $t6, ($v1)
/* 0031E4 800025E4 3C027000 */  lui   $v0, %hi(KSEG_audi_related_2) # $v0, 0x7000
/* 0031E8 800025E8 3C0F8006 */  lui   $t7, %hi(dword_CODE_bss_8005E7C0) # $t7, 0x8006
/* 0031EC 800025EC 15C00006 */  bnez  $t6, .L80002608
/* 0031F0 800025F0 24422424 */   addiu $v0, %lo(KSEG_audi_related_2) # addiu $v0, $v0, 0x2424
/* 0031F4 800025F4 25EFE7C0 */  addiu $t7, %lo(dword_CODE_bss_8005E7C0) # addiu $t7, $t7, -0x1840
/* 0031F8 800025F8 24180001 */  li    $t8, 1
/* 0031FC 800025FC AC600004 */  sw    $zero, 4($v1)
/* 003200 80002600 AC6F0008 */  sw    $t7, 8($v1)
/* 003204 80002604 A0780000 */  sb    $t8, ($v1)
.L80002608:
/* 003208 80002608 03E00008 */  jr    $ra
/* 00320C 8000260C AC830000 */   sw    $v1, ($a0)

audi_related_4:
/* 003210 80002610 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 003214 80002614 AFB40028 */  sw    $s4, 0x28($sp)
/* 003218 80002618 3C148002 */  lui   $s4, %hi(D_800230F8) # $s4, 0x8002
/* 00321C 8000261C 269430F8 */  addiu $s4, %lo(D_800230F8) # addiu $s4, $s4, 0x30f8
/* 003220 80002620 8E8E0000 */  lw    $t6, ($s4)
/* 003224 80002624 AFB00018 */  sw    $s0, 0x18($sp)
/* 003228 80002628 AFBF002C */  sw    $ra, 0x2c($sp)
/* 00322C 8000262C AFB30024 */  sw    $s3, 0x24($sp)
/* 003230 80002630 AFB20020 */  sw    $s2, 0x20($sp)
/* 003234 80002634 AFB1001C */  sw    $s1, 0x1c($sp)
/* 003238 80002638 AFA00040 */  sw    $zero, 0x40($sp)
/* 00323C 8000263C 11C0000D */  beqz  $t6, .L80002674
/* 003240 80002640 00008025 */   move  $s0, $zero
/* 003244 80002644 3C118006 */  lui   $s1, %hi(audDMAMessageQ) # $s1, 0x8006
/* 003248 80002648 2631F2D0 */  addiu $s1, %lo(audDMAMessageQ) # addiu $s1, $s1, -0xd30
/* 00324C 8000264C 27B20040 */  addiu $s2, $sp, 0x40
/* 003250 80002650 02202025 */  move  $a0, $s1
.L80002654:
/* 003254 80002654 02402825 */  move  $a1, $s2
/* 003258 80002658 0C003774 */  jal   osRecvMesg
/* 00325C 8000265C 00003025 */   move  $a2, $zero
/* 003260 80002660 8E8F0000 */  lw    $t7, ($s4)
/* 003264 80002664 26100001 */  addiu $s0, $s0, 1
/* 003268 80002668 020F082B */  sltu  $at, $s0, $t7
/* 00326C 8000266C 5420FFF9 */  bnezl $at, .L80002654
/* 003270 80002670 02202025 */   move  $a0, $s1
.L80002674:
/* 003274 80002674 3C128006 */  lui   $s2, %hi(off_CODE_bss_8005E7B0) # $s2, 0x8006
/* 003278 80002678 2652E7B0 */  addiu $s2, %lo(off_CODE_bss_8005E7B0) # addiu $s2, $s2, -0x1850
/* 00327C 8000267C 8E500004 */  lw    $s0, 4($s2)
/* 003280 80002680 3C138002 */  lui   $s3, %hi(D_800230F4) # $s3, 0x8002
/* 003284 80002684 267330F4 */  addiu $s3, %lo(D_800230F4) # addiu $s3, $s3, 0x30f4
/* 003288 80002688 1200001A */  beqz  $s0, .L800026F4
/* 00328C 8000268C 00000000 */   nop   
.L80002690:
/* 003290 80002690 8E19000C */  lw    $t9, 0xc($s0)
/* 003294 80002694 8E780000 */  lw    $t8, ($s3)
/* 003298 80002698 8E020000 */  lw    $v0, ($s0)
/* 00329C 8000269C 27280001 */  addiu $t0, $t9, 1
/* 0032A0 800026A0 0118082B */  sltu  $at, $t0, $t8
/* 0032A4 800026A4 10200011 */  beqz  $at, .L800026EC
/* 0032A8 800026A8 00408825 */   move  $s1, $v0
/* 0032AC 800026AC 8E490004 */  lw    $t1, 4($s2)
/* 0032B0 800026B0 16090002 */  bne   $s0, $t1, .L800026BC
/* 0032B4 800026B4 00000000 */   nop   
/* 0032B8 800026B8 AE420004 */  sw    $v0, 4($s2)
.L800026BC:
/* 0032BC 800026BC 0C003AA4 */  jal   alUnlink
/* 0032C0 800026C0 02002025 */   move  $a0, $s0
/* 0032C4 800026C4 8E450008 */  lw    $a1, 8($s2)
/* 0032C8 800026C8 50A00006 */  beql  $a1, $zero, .L800026E4
/* 0032CC 800026CC AE500008 */   sw    $s0, 8($s2)
/* 0032D0 800026D0 0C003AB0 */  jal   alLink
/* 0032D4 800026D4 02002025 */   move  $a0, $s0
/* 0032D8 800026D8 10000004 */  b     .L800026EC
/* 0032DC 800026DC 00000000 */   nop   
/* 0032E0 800026E0 AE500008 */  sw    $s0, 8($s2)
.L800026E4:
/* 0032E4 800026E4 AE000000 */  sw    $zero, ($s0)
/* 0032E8 800026E8 AE000004 */  sw    $zero, 4($s0)
.L800026EC:
/* 0032EC 800026EC 1620FFE8 */  bnez  $s1, .L80002690
/* 0032F0 800026F0 02208025 */   move  $s0, $s1
.L800026F4:
/* 0032F4 800026F4 3C138002 */  lui   $s3, %hi(D_800230F4) # $s3, 0x8002
/* 0032F8 800026F8 267330F4 */  addiu $s3, %lo(D_800230F4) # addiu $s3, $s3, 0x30f4
/* 0032FC 800026FC 8E6A0000 */  lw    $t2, ($s3)
/* 003300 80002700 8FBF002C */  lw    $ra, 0x2c($sp)
/* 003304 80002704 AE800000 */  sw    $zero, ($s4)
/* 003308 80002708 254B0001 */  addiu $t3, $t2, 1
/* 00330C 8000270C AE6B0000 */  sw    $t3, ($s3)
/* 003310 80002710 8FB30024 */  lw    $s3, 0x24($sp)
/* 003314 80002714 8FB40028 */  lw    $s4, 0x28($sp)
/* 003318 80002718 8FB00018 */  lw    $s0, 0x18($sp)
/* 00331C 8000271C 8FB1001C */  lw    $s1, 0x1c($sp)
/* 003320 80002720 8FB20020 */  lw    $s2, 0x20($sp)
/* 003324 80002724 03E00008 */  jr    $ra
/* 003328 80002728 27BD0048 */   addiu $sp, $sp, 0x48

/* 00332C 8000272C 00000000 */  nop   

