# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

something_with_joy_c_debug:
/* 00C160 8000B560 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00C164 8000B564 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00C168 8000B568 3C048002 */  lui   $a0, %hi(D_800268C0) # $a0, 0x8002
/* 00C16C 8000B56C 3C058003 */  lui   $a1, %hi(aJoy_c_debug) # $a1, 0x8003
/* 00C170 8000B570 24A59390 */  addiu $a1, %lo(aJoy_c_debug) # addiu $a1, $a1, -0x6c70
/* 00C174 8000B574 0C001398 */  jal   get_ptr_debug_notice_list_entry
/* 00C178 8000B578 248468C0 */   addiu $a0, %lo(D_800268C0) # addiu $a0, $a0, 0x68c0
/* 00C17C 8000B57C 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065370) # $a0, 0x8006
/* 00C180 8000B580 3C058006 */  lui   $a1, %hi(dword_CODE_bss_80065368) # $a1, 0x8006
/* 00C184 8000B584 24A55368 */  addiu $a1, %lo(dword_CODE_bss_80065368) # addiu $a1, $a1, 0x5368
/* 00C188 8000B588 24845370 */  addiu $a0, %lo(dword_CODE_bss_80065370) # addiu $a0, $a0, 0x5370
/* 00C18C 8000B58C 0C0035B4 */  jal   osCreateMesgQueue
/* 00C190 8000B590 24060001 */   li    $a2, 1
/* 00C194 8000B594 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065390) # $a0, 0x8006
/* 00C198 8000B598 3C058006 */  lui   $a1, %hi(dword_CODE_bss_80065388) # $a1, 0x8006
/* 00C19C 8000B59C 24A55388 */  addiu $a1, %lo(dword_CODE_bss_80065388) # addiu $a1, $a1, 0x5388
/* 00C1A0 8000B5A0 24845390 */  addiu $a0, %lo(dword_CODE_bss_80065390) # addiu $a0, $a0, 0x5390
/* 00C1A4 8000B5A4 0C0035B4 */  jal   osCreateMesgQueue
/* 00C1A8 8000B5A8 24060001 */   li    $a2, 1
/* 00C1AC 8000B5AC 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653B0) # $a0, 0x8006
/* 00C1B0 8000B5B0 3C058006 */  lui   $a1, %hi(dword_CODE_bss_800653A8) # $a1, 0x8006
/* 00C1B4 8000B5B4 24A553A8 */  addiu $a1, %lo(dword_CODE_bss_800653A8) # addiu $a1, $a1, 0x53a8
/* 00C1B8 8000B5B8 248453B0 */  addiu $a0, %lo(dword_CODE_bss_800653B0) # addiu $a0, $a0, 0x53b0
/* 00C1BC 8000B5BC 0C0035B4 */  jal   osCreateMesgQueue
/* 00C1C0 8000B5C0 24060001 */   li    $a2, 1
/* 00C1C4 8000B5C4 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653D0) # $a0, 0x8006
/* 00C1C8 8000B5C8 3C058006 */  lui   $a1, %hi(dword_CODE_bss_800653C8) # $a1, 0x8006
/* 00C1CC 8000B5CC 24A553C8 */  addiu $a1, %lo(dword_CODE_bss_800653C8) # addiu $a1, $a1, 0x53c8
/* 00C1D0 8000B5D0 248453D0 */  addiu $a0, %lo(dword_CODE_bss_800653D0) # addiu $a0, $a0, 0x53d0
/* 00C1D4 8000B5D4 0C0035B4 */  jal   osCreateMesgQueue
/* 00C1D8 8000B5D8 24060001 */   li    $a2, 1
/* 00C1DC 8000B5DC 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C1E0 8000B5E0 3C058006 */  lui   $a1, %hi(dword_CODE_bss_80065328) # $a1, 0x8006
/* 00C1E4 8000B5E4 24A55328 */  addiu $a1, %lo(dword_CODE_bss_80065328) # addiu $a1, $a1, 0x5328
/* 00C1E8 8000B5E8 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C1EC 8000B5EC 0C0035B4 */  jal   osCreateMesgQueue
/* 00C1F0 8000B5F0 2406000A */   li    $a2, 10
/* 00C1F4 8000B5F4 3C058006 */  lui   $a1, %hi(interrupt5_thread_list_buf) # $a1, 0x8006
/* 00C1F8 8000B5F8 24A55350 */  addiu $a1, %lo(interrupt5_thread_list_buf) # addiu $a1, $a1, 0x5350
/* 00C1FC 8000B5FC 24040005 */  li    $a0, 5
/* 00C200 8000B600 0C003714 */  jal   osSetEventMesg
/* 00C204 8000B604 00003025 */   move  $a2, $zero
/* 00C208 8000B608 240E0001 */  li    $t6, 1
/* 00C20C 8000B60C 3C018002 */  lui   $at, %hi(D_80026918) # $at, 0x8002
/* 00C210 8000B610 AC2E6918 */  sw    $t6, %lo(D_80026918)($at)
/* 00C214 8000B614 3C018002 */  lui   $at, %hi(disable_all_rumble) # $at, 0x8002
/* 00C218 8000B618 AC206924 */  sw    $zero, %lo(disable_all_rumble)($at)
/* 00C21C 8000B61C 3C0F8006 */  lui   $t7, 0x8006
/* 00C220 8000B620 3C018002 */  lui   $at, %hi(ptr_to_tlb_ramrom_record) # $at, 0x8002
/* 00C224 8000B624 25E24F30 */  addiu $v0, $t7, 0x4f30
/* 00C228 8000B628 3C058006 */  lui   $a1, %hi(dword_CODE_bss_80065328) # $a1, 0x8006
/* 00C22C 8000B62C AC206928 */  sw    $zero, %lo(ptr_to_tlb_ramrom_record)($at)
/* 00C230 8000B630 24A55328 */  addiu $a1, %lo(dword_CODE_bss_80065328) # addiu $a1, $a1, 0x5328
/* 00C234 8000B634 00401825 */  move  $v1, $v0
/* 00C238 8000B638 2404FFFF */  li    $a0, -1
.L8000B63C:
/* 00C23C 8000B63C AC6001E0 */  sw    $zero, 0x1e0($v1)
/* 00C240 8000B640 AC6001E4 */  sw    $zero, 0x1e4($v1)
/* 00C244 8000B644 AC6001E8 */  sw    $zero, 0x1e8($v1)
/* 00C248 8000B648 AC6001EC */  sw    $zero, 0x1ec($v1)
/* 00C24C 8000B64C AC6401F8 */  sw    $a0, 0x1f8($v1)
/* 00C250 8000B650 244201FC */  addiu $v0, $v0, 0x1fc
/* 00C254 8000B654 246301FC */  addiu $v1, $v1, 0x1fc
/* 00C258 8000B658 A040FE1A */  sb    $zero, -0x1e6($v0)
/* 00C25C 8000B65C A040FE19 */  sb    $zero, -0x1e7($v0)
/* 00C260 8000B660 A040FE18 */  sb    $zero, -0x1e8($v0)
/* 00C264 8000B664 A440FE16 */  sh    $zero, -0x1ea($v0)
/* 00C268 8000B668 A040FE14 */  sb    $zero, -0x1ec($v0)
/* 00C26C 8000B66C A040FE13 */  sb    $zero, -0x1ed($v0)
/* 00C270 8000B670 A040FE12 */  sb    $zero, -0x1ee($v0)
/* 00C274 8000B674 A440FE10 */  sh    $zero, -0x1f0($v0)
/* 00C278 8000B678 A040FE0E */  sb    $zero, -0x1f2($v0)
/* 00C27C 8000B67C A040FE0D */  sb    $zero, -0x1f3($v0)
/* 00C280 8000B680 A040FE0C */  sb    $zero, -0x1f4($v0)
/* 00C284 8000B684 A440FE0A */  sh    $zero, -0x1f6($v0)
/* 00C288 8000B688 A440FE04 */  sh    $zero, -0x1fc($v0)
/* 00C28C 8000B68C A040FE06 */  sb    $zero, -0x1fa($v0)
/* 00C290 8000B690 A040FE07 */  sb    $zero, -0x1f9($v0)
/* 00C294 8000B694 1445FFE9 */  bne   $v0, $a1, .L8000B63C
/* 00C298 8000B698 A040FE08 */   sb    $zero, -0x1f8($v0)
/* 00C29C 8000B69C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00C2A0 8000B6A0 27BD0018 */  addiu $sp, $sp, 0x18
/* 00C2A4 8000B6A4 03E00008 */  jr    $ra
/* 00C2A8 8000B6A8 00000000 */   nop   

test_controller_presence:
/* 00C2AC 8000B6AC 3C0E8002 */  lui   $t6, %hi(D_80026918) # $t6, 0x8002
/* 00C2B0 8000B6B0 8DCE6918 */  lw    $t6, %lo(D_80026918)($t6)
/* 00C2B4 8000B6B4 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00C2B8 8000B6B8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00C2BC 8000B6BC 11C00016 */  beqz  $t6, .L8000B718
/* 00C2C0 8000B6C0 3C048006 */   lui   $a0, %hi(dword_CODE_bss_80065370) # $a0, 0x8006
/* 00C2C4 8000B6C4 24845370 */  addiu $a0, %lo(dword_CODE_bss_80065370) # addiu $a0, $a0, 0x5370
/* 00C2C8 8000B6C8 27A5001C */  addiu $a1, $sp, 0x1c
/* 00C2CC 8000B6CC 0C0037C4 */  jal   osSendMesg
/* 00C2D0 8000B6D0 00003025 */   move  $a2, $zero
/* 00C2D4 8000B6D4 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065390) # $a0, 0x8006
/* 00C2D8 8000B6D8 24845390 */  addiu $a0, %lo(dword_CODE_bss_80065390) # addiu $a0, $a0, 0x5390
/* 00C2DC 8000B6DC 27A5001C */  addiu $a1, $sp, 0x1c
/* 00C2E0 8000B6E0 0C003774 */  jal   osRecvMesg
/* 00C2E4 8000B6E4 24060001 */   li    $a2, 1
/* 00C2E8 8000B6E8 0C002E04 */  jal   controller_check_for_rumble_maybe
/* 00C2EC 8000B6EC 00000000 */   nop   
/* 00C2F0 8000B6F0 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653B0) # $a0, 0x8006
/* 00C2F4 8000B6F4 248453B0 */  addiu $a0, %lo(dword_CODE_bss_800653B0) # addiu $a0, $a0, 0x53b0
/* 00C2F8 8000B6F8 27A5001C */  addiu $a1, $sp, 0x1c
/* 00C2FC 8000B6FC 0C0037C4 */  jal   osSendMesg
/* 00C300 8000B700 00003025 */   move  $a2, $zero
/* 00C304 8000B704 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653D0) # $a0, 0x8006
/* 00C308 8000B708 248453D0 */  addiu $a0, %lo(dword_CODE_bss_800653D0) # addiu $a0, $a0, 0x53d0
/* 00C30C 8000B70C 27A5001C */  addiu $a1, $sp, 0x1c
/* 00C310 8000B710 0C003774 */  jal   osRecvMesg
/* 00C314 8000B714 24060001 */   li    $a2, 1
.L8000B718:
/* 00C318 8000B718 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00C31C 8000B71C 27BD0020 */  addiu $sp, $sp, 0x20
/* 00C320 8000B720 03E00008 */  jr    $ra
/* 00C324 8000B724 00000000 */   nop   

osPfsChecker:
/* 00C328 8000B728 AFA40000 */  sw    $a0, ($sp)
/* 00C32C 8000B72C 03E00008 */  jr    $ra
/* 00C330 8000B730 24020003 */   li    $v0, 3

controller_7000B734:
/* 00C334 8000B734 3C0E8002 */  lui   $t6, %hi(controller_1_rumble_inserted) # $t6, 0x8002
/* 00C338 8000B738 25CE68D8 */  addiu $t6, %lo(controller_1_rumble_inserted) # addiu $t6, $t6, 0x68d8
/* 00C33C 8000B73C 00041080 */  sll   $v0, $a0, 2
/* 00C340 8000B740 004E3821 */  addu  $a3, $v0, $t6
/* 00C344 8000B744 8CEF0000 */  lw    $t7, ($a3)
/* 00C348 8000B748 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 00C34C 8000B74C AFBF0014 */  sw    $ra, 0x14($sp)
/* 00C350 8000B750 05E0002B */  bltz  $t7, .L8000B800
/* 00C354 8000B754 00803025 */   move  $a2, $a0
/* 00C358 8000B758 3C188006 */  lui   $t8, %hi(player1_controllerstatus) # $t8, 0x8006
/* 00C35C 8000B75C 271853E8 */  addiu $t8, %lo(player1_controllerstatus) # addiu $t8, $t8, 0x53e8
/* 00C360 8000B760 00581821 */  addu  $v1, $v0, $t8
/* 00C364 8000B764 94790000 */  lhu   $t9, ($v1)
/* 00C368 8000B768 33280004 */  andi  $t0, $t9, 4
/* 00C36C 8000B76C 51000025 */  beql  $t0, $zero, .L8000B804
/* 00C370 8000B770 8FBF0014 */   lw    $ra, 0x14($sp)
/* 00C374 8000B774 90690002 */  lbu   $t1, 2($v1)
/* 00C378 8000B778 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C37C 8000B77C 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C380 8000B780 312A0001 */  andi  $t2, $t1, 1
/* 00C384 8000B784 1140001E */  beqz  $t2, .L8000B800
/* 00C388 8000B788 00065880 */   sll   $t3, $a2, 2
/* 00C38C 8000B78C 01665823 */  subu  $t3, $t3, $a2
/* 00C390 8000B790 000B5880 */  sll   $t3, $t3, 2
/* 00C394 8000B794 01665821 */  addu  $t3, $t3, $a2
/* 00C398 8000B798 3C0C8006 */  lui   $t4, %hi(player1_controller_packet) # $t4, 0x8006
/* 00C39C 8000B79C 258C53F8 */  addiu $t4, %lo(player1_controller_packet) # addiu $t4, $t4, 0x53f8
/* 00C3A0 8000B7A0 000B58C0 */  sll   $t3, $t3, 3
/* 00C3A4 8000B7A4 016C2821 */  addu  $a1, $t3, $t4
/* 00C3A8 8000B7A8 AFA50020 */  sw    $a1, 0x20($sp)
/* 00C3AC 8000B7AC AFA60028 */  sw    $a2, 0x28($sp)
/* 00C3B0 8000B7B0 0C0051D0 */  jal   osPfsInit
/* 00C3B4 8000B7B4 AFA7001C */   sw    $a3, 0x1c($sp)
/* 00C3B8 8000B7B8 2401000A */  li    $at, 10
/* 00C3BC 8000B7BC 8FA50020 */  lw    $a1, 0x20($sp)
/* 00C3C0 8000B7C0 8FA60028 */  lw    $a2, 0x28($sp)
/* 00C3C4 8000B7C4 10410003 */  beq   $v0, $at, .L8000B7D4
/* 00C3C8 8000B7C8 8FA7001C */   lw    $a3, 0x1c($sp)
/* 00C3CC 8000B7CC 2401000B */  li    $at, 11
/* 00C3D0 8000B7D0 1441000B */  bne   $v0, $at, .L8000B800
.L8000B7D4:
/* 00C3D4 8000B7D4 3C048006 */   lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C3D8 8000B7D8 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C3DC 8000B7DC 0C00334E */  jal   controller_7000CD38
/* 00C3E0 8000B7E0 AFA7001C */   sw    $a3, 0x1c($sp)
/* 00C3E4 8000B7E4 14400004 */  bnez  $v0, .L8000B7F8
/* 00C3E8 8000B7E8 8FA7001C */   lw    $a3, 0x1c($sp)
/* 00C3EC 8000B7EC 240D0001 */  li    $t5, 1
/* 00C3F0 8000B7F0 10000003 */  b     .L8000B800
/* 00C3F4 8000B7F4 ACED0000 */   sw    $t5, ($a3)
.L8000B7F8:
/* 00C3F8 8000B7F8 240EFFFF */  li    $t6, -1
/* 00C3FC 8000B7FC ACEE0000 */  sw    $t6, ($a3)
.L8000B800:
/* 00C400 8000B800 8FBF0014 */  lw    $ra, 0x14($sp)
.L8000B804:
/* 00C404 8000B804 27BD0028 */  addiu $sp, $sp, 0x28
/* 00C408 8000B808 03E00008 */  jr    $ra
/* 00C40C 8000B80C 00000000 */   nop   

controller_check_for_rumble_maybe:
/* 00C410 8000B810 3C028002 */  lui   $v0, %hi(D_8002692C) # $v0, 0x8002
/* 00C414 8000B814 2442692C */  addiu $v0, %lo(D_8002692C) # addiu $v0, $v0, 0x692c
/* 00C418 8000B818 8C4E0000 */  lw    $t6, ($v0)
/* 00C41C 8000B81C 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 00C420 8000B820 AFBF001C */  sw    $ra, 0x1c($sp)
/* 00C424 8000B824 11C0000D */  beqz  $t6, .L8000B85C
/* 00C428 8000B828 AFB00018 */   sw    $s0, 0x18($sp)
/* 00C42C 8000B82C 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C430 8000B830 3C058002 */  lui   $a1, %hi(num_controller_plugged_in_flags) # $a1, 0x8002
/* 00C434 8000B834 3C068006 */  lui   $a2, %hi(player1_controllerstatus) # $a2, 0x8006
/* 00C438 8000B838 AC400000 */  sw    $zero, ($v0)
/* 00C43C 8000B83C 24C653E8 */  addiu $a2, %lo(player1_controllerstatus) # addiu $a2, $a2, 0x53e8
/* 00C440 8000B840 24A568D0 */  addiu $a1, %lo(num_controller_plugged_in_flags) # addiu $a1, $a1, 0x68d0
/* 00C444 8000B844 0C005240 */  jal   osContInit
/* 00C448 8000B848 24845350 */   addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C44C 8000B84C 240F0001 */  li    $t7, 1
/* 00C450 8000B850 3C018002 */  lui   $at, %hi(D_8002691C) # $at, 0x8002
/* 00C454 8000B854 10000026 */  b     .L8000B8F0
/* 00C458 8000B858 AC2F691C */   sw    $t7, %lo(D_8002691C)($at)
.L8000B85C:
/* 00C45C 8000B85C 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C460 8000B860 2410000F */  li    $s0, 15
/* 00C464 8000B864 0C005330 */  jal   osContStartQuery
/* 00C468 8000B868 24845350 */   addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C46C 8000B86C 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C470 8000B870 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C474 8000B874 00002825 */  move  $a1, $zero
/* 00C478 8000B878 0C003774 */  jal   osRecvMesg
/* 00C47C 8000B87C 24060001 */   li    $a2, 1
/* 00C480 8000B880 3C048006 */  lui   $a0, %hi(player1_controllerstatus) # $a0, 0x8006
/* 00C484 8000B884 0C005351 */  jal   osContGetQuery
/* 00C488 8000B888 248453E8 */   addiu $a0, %lo(player1_controllerstatus) # addiu $a0, $a0, 0x53e8
/* 00C48C 8000B88C 3C188006 */  lui   $t8, %hi(D_800653EB) # $t8, 0x8006
/* 00C490 8000B890 931853EB */  lbu   $t8, %lo(D_800653EB)($t8)
/* 00C494 8000B894 3C088006 */  lui   $t0, %hi(D_800653EF) # $t0, 0x8006
/* 00C498 8000B898 3C0A8006 */  lui   $t2, %hi(D_800653F3) # $t2, 0x8006
/* 00C49C 8000B89C 33190008 */  andi  $t9, $t8, 8
/* 00C4A0 8000B8A0 13200002 */  beqz  $t9, .L8000B8AC
/* 00C4A4 8000B8A4 3C0C8006 */   lui   $t4, %hi(D_800653F7) # $t4, 0x8006
/* 00C4A8 8000B8A8 2410000E */  li    $s0, 14
.L8000B8AC:
/* 00C4AC 8000B8AC 910853EF */  lbu   $t0, %lo(D_800653EF)($t0)
/* 00C4B0 8000B8B0 3C018002 */  lui   $at, %hi(num_controller_plugged_in_flags) # $at, 0x8002
/* 00C4B4 8000B8B4 31090008 */  andi  $t1, $t0, 8
/* 00C4B8 8000B8B8 11200002 */  beqz  $t1, .L8000B8C4
/* 00C4BC 8000B8BC 00000000 */   nop   
/* 00C4C0 8000B8C0 2610FFFE */  addiu $s0, $s0, -2
.L8000B8C4:
/* 00C4C4 8000B8C4 914A53F3 */  lbu   $t2, %lo(D_800653F3)($t2)
/* 00C4C8 8000B8C8 314B0008 */  andi  $t3, $t2, 8
/* 00C4CC 8000B8CC 11600002 */  beqz  $t3, .L8000B8D8
/* 00C4D0 8000B8D0 00000000 */   nop   
/* 00C4D4 8000B8D4 2610FFFC */  addiu $s0, $s0, -4
.L8000B8D8:
/* 00C4D8 8000B8D8 918C53F7 */  lbu   $t4, %lo(D_800653F7)($t4)
/* 00C4DC 8000B8DC 318D0008 */  andi  $t5, $t4, 8
/* 00C4E0 8000B8E0 11A00002 */  beqz  $t5, .L8000B8EC
/* 00C4E4 8000B8E4 00000000 */   nop   
/* 00C4E8 8000B8E8 2610FFF8 */  addiu $s0, $s0, -8
.L8000B8EC:
/* 00C4EC 8000B8EC A03068D0 */  sb    $s0, %lo(num_controller_plugged_in_flags)($at)
.L8000B8F0:
/* 00C4F0 8000B8F0 00008025 */  move  $s0, $zero
/* 00C4F4 8000B8F4 26100001 */  addiu $s0, $s0, 1
.L8000B8F8:
/* 00C4F8 8000B8F8 00107600 */  sll   $t6, $s0, 0x18
/* 00C4FC 8000B8FC 000E8603 */  sra   $s0, $t6, 0x18
/* 00C500 8000B900 2A010004 */  slti  $at, $s0, 4
/* 00C504 8000B904 5420FFFC */  bnezl $at, .L8000B8F8
/* 00C508 8000B908 26100001 */   addiu $s0, $s0, 1
/* 00C50C 8000B90C 3C078002 */  lui   $a3, %hi(num_controller_plugged_in_flags_0) # $a3, 0x8002
/* 00C510 8000B910 3C068002 */  lui   $a2, %hi(controller_1_rumble_inserted) # $a2, 0x8002
/* 00C514 8000B914 24C668D8 */  addiu $a2, %lo(controller_1_rumble_inserted) # addiu $a2, $a2, 0x68d8
/* 00C518 8000B918 24E768D4 */  addiu $a3, %lo(num_controller_plugged_in_flags_0) # addiu $a3, $a3, 0x68d4
/* 00C51C 8000B91C 00008025 */  move  $s0, $zero
.L8000B920:
/* 00C520 8000B920 3C198002 */  lui   $t9, %hi(num_controller_plugged_in_flags) # $t9, 0x8002
/* 00C524 8000B924 933968D0 */  lbu   $t9, %lo(num_controller_plugged_in_flags)($t9)
/* 00C528 8000B928 24180001 */  li    $t8, 1
/* 00C52C 8000B92C 02182804 */  sllv  $a1, $t8, $s0
/* 00C530 8000B930 03254024 */  and   $t0, $t9, $a1
/* 00C534 8000B934 1100001E */  beqz  $t0, .L8000B9B0
/* 00C538 8000B938 90E30000 */   lbu   $v1, ($a3)
/* 00C53C 8000B93C 3C098006 */  lui   $t1, %hi(player1_controllerstatus) # $t1, 0x8006
/* 00C540 8000B940 252953E8 */  addiu $t1, %lo(player1_controllerstatus) # addiu $t1, $t1, 0x53e8
/* 00C544 8000B944 00102080 */  sll   $a0, $s0, 2
/* 00C548 8000B948 00891021 */  addu  $v0, $a0, $t1
/* 00C54C 8000B94C 944A0000 */  lhu   $t2, ($v0)
/* 00C550 8000B950 314B0003 */  andi  $t3, $t2, 3
/* 00C554 8000B954 51600017 */  beql  $t3, $zero, .L8000B9B4
/* 00C558 8000B958 0065C824 */   and   $t9, $v1, $a1
/* 00C55C 8000B95C 904C0003 */  lbu   $t4, 3($v0)
/* 00C560 8000B960 2C620001 */  sltiu $v0, $v1, 1
/* 00C564 8000B964 00456824 */  and   $t5, $v0, $a1
/* 00C568 8000B968 55800012 */  bnezl $t4, .L8000B9B4
/* 00C56C 8000B96C 0065C824 */   and   $t9, $v1, $a1
/* 00C570 8000B970 15A00003 */  bnez  $t5, .L8000B980
/* 00C574 8000B974 00C47021 */   addu  $t6, $a2, $a0
/* 00C578 8000B978 8DCF0000 */  lw    $t7, ($t6)
/* 00C57C 8000B97C 1DE00009 */  bgtz  $t7, .L8000B9A4
.L8000B980:
/* 00C580 8000B980 02002025 */   move  $a0, $s0
/* 00C584 8000B984 0C002DCD */  jal   controller_7000B734
/* 00C588 8000B988 AFA50024 */   sw    $a1, 0x24($sp)
/* 00C58C 8000B98C 3C078002 */  lui   $a3, %hi(num_controller_plugged_in_flags_0) # $a3, 0x8002
/* 00C590 8000B990 24E768D4 */  addiu $a3, %lo(num_controller_plugged_in_flags_0) # addiu $a3, $a3, 0x68d4
/* 00C594 8000B994 3C068002 */  lui   $a2, %hi(controller_1_rumble_inserted) # $a2, 0x8002
/* 00C598 8000B998 24C668D8 */  addiu $a2, %lo(controller_1_rumble_inserted) # addiu $a2, $a2, 0x68d8
/* 00C59C 8000B99C 90E30000 */  lbu   $v1, ($a3)
/* 00C5A0 8000B9A0 8FA50024 */  lw    $a1, 0x24($sp)
.L8000B9A4:
/* 00C5A4 8000B9A4 0065C025 */  or    $t8, $v1, $a1
/* 00C5A8 8000B9A8 10000008 */  b     .L8000B9CC
/* 00C5AC 8000B9AC A0F80000 */   sb    $t8, ($a3)
.L8000B9B0:
/* 00C5B0 8000B9B0 0065C824 */  and   $t9, $v1, $a1
.L8000B9B4:
/* 00C5B4 8000B9B4 13200005 */  beqz  $t9, .L8000B9CC
/* 00C5B8 8000B9B8 00654026 */   xor   $t0, $v1, $a1
/* 00C5BC 8000B9BC 00104880 */  sll   $t1, $s0, 2
/* 00C5C0 8000B9C0 00C95021 */  addu  $t2, $a2, $t1
/* 00C5C4 8000B9C4 A0E80000 */  sb    $t0, ($a3)
/* 00C5C8 8000B9C8 AD400000 */  sw    $zero, ($t2)
.L8000B9CC:
/* 00C5CC 8000B9CC 26100001 */  addiu $s0, $s0, 1
/* 00C5D0 8000B9D0 00105E00 */  sll   $t3, $s0, 0x18
/* 00C5D4 8000B9D4 000B8603 */  sra   $s0, $t3, 0x18
/* 00C5D8 8000B9D8 2A010004 */  slti  $at, $s0, 4
/* 00C5DC 8000B9DC 1420FFD0 */  bnez  $at, .L8000B920
/* 00C5E0 8000B9E0 00000000 */   nop   
/* 00C5E4 8000B9E4 8FBF001C */  lw    $ra, 0x1c($sp)
/* 00C5E8 8000B9E8 8FB00018 */  lw    $s0, 0x18($sp)
/* 00C5EC 8000B9EC 27BD0038 */  addiu $sp, $sp, 0x38
/* 00C5F0 8000B9F0 03E00008 */  jr    $ra
/* 00C5F4 8000B9F4 00000000 */   nop   

controller_finding_controller_maybe:
/* 00C5F8 8000B9F8 3C0E8002 */  lui   $t6, %hi(ptr_current_point_in_controller_input_index) # $t6, 0x8002
/* 00C5FC 8000B9FC 8DCE68C4 */  lw    $t6, %lo(ptr_current_point_in_controller_input_index)($t6)
/* 00C600 8000BA00 3C028002 */  lui   $v0, 0x8002
/* 00C604 8000BA04 8DC301F8 */  lw    $v1, 0x1f8($t6)
/* 00C608 8000BA08 04600005 */  bltz  $v1, .L8000BA20
/* 00C60C 8000BA0C 00000000 */   nop   
/* 00C610 8000BA10 00031600 */  sll   $v0, $v1, 0x18
/* 00C614 8000BA14 00027E03 */  sra   $t7, $v0, 0x18
/* 00C618 8000BA18 03E00008 */  jr    $ra
/* 00C61C 8000BA1C 01E01025 */   move  $v0, $t7

.L8000BA20:
/* 00C620 8000BA20 904268D0 */  lbu   $v0, 0x68d0($v0)
/* 00C624 8000BA24 30580001 */  andi  $t8, $v0, 1
/* 00C628 8000BA28 17000003 */  bnez  $t8, .L8000BA38
/* 00C62C 8000BA2C 30590002 */   andi  $t9, $v0, 2
/* 00C630 8000BA30 03E00008 */  jr    $ra
/* 00C634 8000BA34 00001025 */   move  $v0, $zero

.L8000BA38:
/* 00C638 8000BA38 17200003 */  bnez  $t9, .L8000BA48
/* 00C63C 8000BA3C 30480004 */   andi  $t0, $v0, 4
/* 00C640 8000BA40 03E00008 */  jr    $ra
/* 00C644 8000BA44 24020001 */   li    $v0, 1

.L8000BA48:
/* 00C648 8000BA48 15000003 */  bnez  $t0, .L8000BA58
/* 00C64C 8000BA4C 30490008 */   andi  $t1, $v0, 8
/* 00C650 8000BA50 03E00008 */  jr    $ra
/* 00C654 8000BA54 24020002 */   li    $v0, 2

.L8000BA58:
/* 00C658 8000BA58 15200003 */  bnez  $t1, .L8000BA68
/* 00C65C 8000BA5C 24020004 */   li    $v0, 4
/* 00C660 8000BA60 03E00008 */  jr    $ra
/* 00C664 8000BA64 24020003 */   li    $v0, 3

.L8000BA68:
/* 00C668 8000BA68 03E00008 */  jr    $ra
/* 00C66C 8000BA6C 00000000 */   nop   

get_num_controllers_plugged_in:
/* 00C670 8000BA70 3C028002 */  lui   $v0, 0x8002
/* 00C674 8000BA74 03E00008 */  jr    $ra
/* 00C678 8000BA78 904268D0 */   lbu   $v0, 0x68d0($v0)

controller_rumble_related:
/* 00C67C 8000BA7C 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 00C680 8000BA80 AFB40028 */  sw    $s4, 0x28($sp)
/* 00C684 8000BA84 AFB1001C */  sw    $s1, 0x1c($sp)
/* 00C688 8000BA88 AFB00018 */  sw    $s0, 0x18($sp)
/* 00C68C 8000BA8C AFB60030 */  sw    $s6, 0x30($sp)
/* 00C690 8000BA90 AFB5002C */  sw    $s5, 0x2c($sp)
/* 00C694 8000BA94 AFB30024 */  sw    $s3, 0x24($sp)
/* 00C698 8000BA98 AFB20020 */  sw    $s2, 0x20($sp)
/* 00C69C 8000BA9C 3C108002 */  lui   $s0, %hi(controller_1_rumble_duration) # $s0, 0x8002
/* 00C6A0 8000BAA0 3C118002 */  lui   $s1, %hi(controller_1_rumble_state) # $s1, 0x8002
/* 00C6A4 8000BAA4 3C148002 */  lui   $s4, %hi(controller_1_rumble_pulse) # $s4, 0x8002
/* 00C6A8 8000BAA8 AFBF0034 */  sw    $ra, 0x34($sp)
/* 00C6AC 8000BAAC 26946908 */  addiu $s4, %lo(controller_1_rumble_pulse) # addiu $s4, $s4, 0x6908
/* 00C6B0 8000BAB0 263168E8 */  addiu $s1, %lo(controller_1_rumble_state) # addiu $s1, $s1, 0x68e8
/* 00C6B4 8000BAB4 261068F8 */  addiu $s0, %lo(controller_1_rumble_duration) # addiu $s0, $s0, 0x68f8
/* 00C6B8 8000BAB8 00009025 */  move  $s2, $zero
/* 00C6BC 8000BABC 00009825 */  move  $s3, $zero
/* 00C6C0 8000BAC0 24150001 */  li    $s5, 1
/* 00C6C4 8000BAC4 24160004 */  li    $s6, 4
.L8000BAC8:
/* 00C6C8 8000BAC8 8E820000 */  lw    $v0, ($s4)
/* 00C6CC 8000BACC 8E2E0000 */  lw    $t6, ($s1)
/* 00C6D0 8000BAD0 00127880 */  sll   $t7, $s2, 2
/* 00C6D4 8000BAD4 01F27823 */  subu  $t7, $t7, $s2
/* 00C6D8 8000BAD8 11C2001A */  beq   $t6, $v0, .L8000BB44
/* 00C6DC 8000BADC 000F7880 */   sll   $t7, $t7, 2
/* 00C6E0 8000BAE0 01F27821 */  addu  $t7, $t7, $s2
/* 00C6E4 8000BAE4 3C188006 */  lui   $t8, %hi(player1_controller_packet) # $t8, 0x8006
/* 00C6E8 8000BAE8 271853F8 */  addiu $t8, %lo(player1_controller_packet) # addiu $t8, $t8, 0x53f8
/* 00C6EC 8000BAEC 000F78C0 */  sll   $t7, $t7, 3
/* 00C6F0 8000BAF0 16A2000B */  bne   $s5, $v0, .L8000BB20
/* 00C6F4 8000BAF4 01F82021 */   addu  $a0, $t7, $t8
/* 00C6F8 8000BAF8 0C0032AB */  jal   controller_7000CAAC
/* 00C6FC 8000BAFC 00000000 */   nop   
/* 00C700 8000BB00 14400003 */  bnez  $v0, .L8000BB10
/* 00C704 8000BB04 3C198002 */   lui   $t9, %hi(controller_1_rumble_inserted) # $t9, 0x8002
/* 00C708 8000BB08 1000000E */  b     .L8000BB44
/* 00C70C 8000BB0C AE350000 */   sw    $s5, ($s1)
.L8000BB10:
/* 00C710 8000BB10 273968D8 */  addiu $t9, %lo(controller_1_rumble_inserted) # addiu $t9, $t9, 0x68d8
/* 00C714 8000BB14 02791021 */  addu  $v0, $s3, $t9
/* 00C718 8000BB18 1000000A */  b     .L8000BB44
/* 00C71C 8000BB1C AC400000 */   sw    $zero, ($v0)
.L8000BB20:
/* 00C720 8000BB20 0C003260 */  jal   send_rumble_off_to_PIF
/* 00C724 8000BB24 00000000 */   nop   
/* 00C728 8000BB28 14400003 */  bnez  $v0, .L8000BB38
/* 00C72C 8000BB2C 3C088002 */   lui   $t0, %hi(controller_1_rumble_inserted) # $t0, 0x8002
/* 00C730 8000BB30 10000004 */  b     .L8000BB44
/* 00C734 8000BB34 AE200000 */   sw    $zero, ($s1)
.L8000BB38:
/* 00C738 8000BB38 250868D8 */  addiu $t0, %lo(controller_1_rumble_inserted) # addiu $t0, $t0, 0x68d8
/* 00C73C 8000BB3C 02681021 */  addu  $v0, $s3, $t0
/* 00C740 8000BB40 AC400000 */  sw    $zero, ($v0)
.L8000BB44:
/* 00C744 8000BB44 8E020000 */  lw    $v0, ($s0)
/* 00C748 8000BB48 26520001 */  addiu $s2, $s2, 1
/* 00C74C 8000BB4C 26730004 */  addiu $s3, $s3, 4
/* 00C750 8000BB50 1C400003 */  bgtz  $v0, .L8000BB60
/* 00C754 8000BB54 26310004 */   addiu $s1, $s1, 4
/* 00C758 8000BB58 10000006 */  b     .L8000BB74
/* 00C75C 8000BB5C AE000000 */   sw    $zero, ($s0)
.L8000BB60:
/* 00C760 8000BB60 2449FFFF */  addiu $t1, $v0, -1
/* 00C764 8000BB64 1D200003 */  bgtz  $t1, .L8000BB74
/* 00C768 8000BB68 AE090000 */   sw    $t1, ($s0)
/* 00C76C 8000BB6C AE000000 */  sw    $zero, ($s0)
/* 00C770 8000BB70 AE800000 */  sw    $zero, ($s4)
.L8000BB74:
/* 00C774 8000BB74 26940004 */  addiu $s4, $s4, 4
/* 00C778 8000BB78 1656FFD3 */  bne   $s2, $s6, .L8000BAC8
/* 00C77C 8000BB7C 26100004 */   addiu $s0, $s0, 4
/* 00C780 8000BB80 8FBF0034 */  lw    $ra, 0x34($sp)
/* 00C784 8000BB84 8FB00018 */  lw    $s0, 0x18($sp)
/* 00C788 8000BB88 8FB1001C */  lw    $s1, 0x1c($sp)
/* 00C78C 8000BB8C 8FB20020 */  lw    $s2, 0x20($sp)
/* 00C790 8000BB90 8FB30024 */  lw    $s3, 0x24($sp)
/* 00C794 8000BB94 8FB40028 */  lw    $s4, 0x28($sp)
/* 00C798 8000BB98 8FB5002C */  lw    $s5, 0x2c($sp)
/* 00C79C 8000BB9C 8FB60030 */  lw    $s6, 0x30($sp)
/* 00C7A0 8000BBA0 03E00008 */  jr    $ra
/* 00C7A4 8000BBA4 27BD0038 */   addiu $sp, $sp, 0x38

set_disable_all_rumble_and_something:
/* 00C7A8 8000BBA8 3C018002 */  lui   $at, %hi(disable_all_rumble) # $at, 0x8002
/* 00C7AC 8000BBAC AC246924 */  sw    $a0, %lo(disable_all_rumble)($at)
/* 00C7B0 8000BBB0 3C018006 */  lui   $at, 0x8006
/* 00C7B4 8000BBB4 03E00008 */  jr    $ra
/* 00C7B8 8000BBB8 AC255324 */   sw    $a1, 0x5324($at)

set_ptr_tlb_ramrom_record:
/* 00C7BC 8000BBBC 3C018002 */  lui   $at, 0x8002
/* 00C7C0 8000BBC0 03E00008 */  jr    $ra
/* 00C7C4 8000BBC4 AC246928 */   sw    $a0, 0x6928($at)

probably_ramrom_related:
/* 00C7C8 8000BBC8 8C8E01E0 */  lw    $t6, 0x1e0($a0)
/* 00C7CC 8000BBCC 8C8F01E8 */  lw    $t7, 0x1e8($a0)
/* 00C7D0 8000BBD0 00001025 */  move  $v0, $zero
/* 00C7D4 8000BBD4 24090014 */  li    $t1, 20
/* 00C7D8 8000BBD8 AC8E01E4 */  sw    $t6, 0x1e4($a0)
/* 00C7DC 8000BBDC AC8F01E0 */  sw    $t7, 0x1e0($a0)
/* 00C7E0 8000BBE0 0002C040 */  sll   $t8, $v0, 1
.L8000BBE4:
/* 00C7E4 8000BBE4 00981821 */  addu  $v1, $a0, $t8
/* 00C7E8 8000BBE8 A46001F0 */  sh    $zero, 0x1f0($v1)
/* 00C7EC 8000BBEC 8C9901E0 */  lw    $t9, 0x1e0($a0)
/* 00C7F0 8000BBF0 8C8501E4 */  lw    $a1, 0x1e4($a0)
/* 00C7F4 8000BBF4 10B9003D */  beq   $a1, $t9, .L8000BCEC
/* 00C7F8 8000BBF8 24AA0001 */   addiu $t2, $a1, 1
/* 00C7FC 8000BBFC 0149001A */  div   $zero, $t2, $t1
/* 00C800 8000BC00 00023880 */  sll   $a3, $v0, 2
/* 00C804 8000BC04 00003010 */  mfhi  $a2
/* 00C808 8000BC08 00E23823 */  subu  $a3, $a3, $v0
/* 00C80C 8000BC0C 00073840 */  sll   $a3, $a3, 1
/* 00C810 8000BC10 15200002 */  bnez  $t1, .L8000BC1C
/* 00C814 8000BC14 00000000 */   nop   
/* 00C818 8000BC18 0007000D */  break 7
.L8000BC1C:
/* 00C81C 8000BC1C 2401FFFF */  li    $at, -1
/* 00C820 8000BC20 15210004 */  bne   $t1, $at, .L8000BC34
/* 00C824 8000BC24 3C018000 */   lui   $at, 0x8000
/* 00C828 8000BC28 15410002 */  bne   $t2, $at, .L8000BC34
/* 00C82C 8000BC2C 00000000 */   nop   
/* 00C830 8000BC30 0006000D */  break 6
.L8000BC34:
/* 00C834 8000BC34 24CE0013 */  addiu $t6, $a2, 0x13
.L8000BC38:
/* 00C838 8000BC38 01C9001A */  div   $zero, $t6, $t1
/* 00C83C 8000BC3C 00007810 */  mfhi  $t7
/* 00C840 8000BC40 000FC080 */  sll   $t8, $t7, 2
/* 00C844 8000BC44 00065880 */  sll   $t3, $a2, 2
/* 00C848 8000BC48 030FC023 */  subu  $t8, $t8, $t7
/* 00C84C 8000BC4C 01665823 */  subu  $t3, $t3, $a2
/* 00C850 8000BC50 0018C0C0 */  sll   $t8, $t8, 3
/* 00C854 8000BC54 000B58C0 */  sll   $t3, $t3, 3
/* 00C858 8000BC58 0098C821 */  addu  $t9, $a0, $t8
/* 00C85C 8000BC5C 008B6021 */  addu  $t4, $a0, $t3
/* 00C860 8000BC60 03275021 */  addu  $t2, $t9, $a3
/* 00C864 8000BC64 95480000 */  lhu   $t0, ($t2)
/* 00C868 8000BC68 01876821 */  addu  $t5, $t4, $a3
/* 00C86C 8000BC6C 95A50000 */  lhu   $a1, ($t5)
/* 00C870 8000BC70 946B01F0 */  lhu   $t3, 0x1f0($v1)
/* 00C874 8000BC74 01006027 */  not   $t4, $t0
/* 00C878 8000BC78 15200002 */  bnez  $t1, .L8000BC84
/* 00C87C 8000BC7C 00000000 */   nop   
/* 00C880 8000BC80 0007000D */  break 7
.L8000BC84:
/* 00C884 8000BC84 2401FFFF */  li    $at, -1
/* 00C888 8000BC88 15210004 */  bne   $t1, $at, .L8000BC9C
/* 00C88C 8000BC8C 3C018000 */   lui   $at, 0x8000
/* 00C890 8000BC90 15C10002 */  bne   $t6, $at, .L8000BC9C
/* 00C894 8000BC94 00000000 */   nop   
/* 00C898 8000BC98 0006000D */  break 6
.L8000BC9C:
/* 00C89C 8000BC9C 00AC6824 */  and   $t5, $a1, $t4
/* 00C8A0 8000BCA0 016D7025 */  or    $t6, $t3, $t5
/* 00C8A4 8000BCA4 A46E01F0 */  sh    $t6, 0x1f0($v1)
/* 00C8A8 8000BCA8 8C8F01E0 */  lw    $t7, 0x1e0($a0)
/* 00C8AC 8000BCAC 24D80001 */  addiu $t8, $a2, 1
/* 00C8B0 8000BCB0 50CF000F */  beql  $a2, $t7, .L8000BCF0
/* 00C8B4 8000BCB4 24420001 */   addiu $v0, $v0, 1
/* 00C8B8 8000BCB8 0309001A */  div   $zero, $t8, $t1
/* 00C8BC 8000BCBC 00003010 */  mfhi  $a2
/* 00C8C0 8000BCC0 15200002 */  bnez  $t1, .L8000BCCC
/* 00C8C4 8000BCC4 00000000 */   nop   
/* 00C8C8 8000BCC8 0007000D */  break 7
.L8000BCCC:
/* 00C8CC 8000BCCC 2401FFFF */  li    $at, -1
/* 00C8D0 8000BCD0 15210004 */  bne   $t1, $at, .L8000BCE4
/* 00C8D4 8000BCD4 3C018000 */   lui   $at, 0x8000
/* 00C8D8 8000BCD8 17010002 */  bne   $t8, $at, .L8000BCE4
/* 00C8DC 8000BCDC 00000000 */   nop   
/* 00C8E0 8000BCE0 0006000D */  break 6
.L8000BCE4:
/* 00C8E4 8000BCE4 1000FFD4 */  b     .L8000BC38
/* 00C8E8 8000BCE8 24CE0013 */   addiu $t6, $a2, 0x13
.L8000BCEC:
/* 00C8EC 8000BCEC 24420001 */  addiu $v0, $v0, 1
.L8000BCF0:
/* 00C8F0 8000BCF0 0002CE00 */  sll   $t9, $v0, 0x18
/* 00C8F4 8000BCF4 00191603 */  sra   $v0, $t9, 0x18
/* 00C8F8 8000BCF8 28410004 */  slti  $at, $v0, 4
/* 00C8FC 8000BCFC 5420FFB9 */  bnezl $at, .L8000BBE4
/* 00C900 8000BD00 0002C040 */   sll   $t8, $v0, 1
/* 00C904 8000BD04 03E00008 */  jr    $ra
/* 00C908 8000BD08 00000000 */   nop   

redirect_to_ramrom_replay_and_record_handlers_if_set:
/* 00C90C 8000BD0C 3C028002 */  lui   $v0, %hi(disable_all_rumble) # $v0, 0x8002
/* 00C910 8000BD10 8C426924 */  lw    $v0, %lo(disable_all_rumble)($v0)
/* 00C914 8000BD14 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00C918 8000BD18 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00C91C 8000BD1C 1040000A */  beqz  $v0, .L8000BD48
/* 00C920 8000BD20 3C048006 */   lui   $a0, %hi(dword_CODE_bss_8006512C) # $a0, 0x8006
/* 00C924 8000BD24 3C058006 */  lui   $a1, %hi(dword_CODE_bss_8006530C) # $a1, 0x8006
/* 00C928 8000BD28 8CA5530C */  lw    $a1, %lo(dword_CODE_bss_8006530C)($a1)
/* 00C92C 8000BD2C 0040F809 */  jalr  $v0
/* 00C930 8000BD30 2484512C */  addiu $a0, %lo(dword_CODE_bss_8006512C) # addiu $a0, $a0, 0x512c
/* 00C934 8000BD34 3C018006 */  lui   $at, %hi(dword_CODE_bss_80065314) # $at, 0x8006
/* 00C938 8000BD38 3C048006 */  lui   $a0, %hi(dword_CODE_bss_8006512C) # $a0, 0x8006
/* 00C93C 8000BD3C AC225314 */  sw    $v0, %lo(dword_CODE_bss_80065314)($at)
/* 00C940 8000BD40 0C002EF2 */  jal   probably_ramrom_related
/* 00C944 8000BD44 2484512C */   addiu $a0, %lo(dword_CODE_bss_8006512C) # addiu $a0, $a0, 0x512c
.L8000BD48:
/* 00C948 8000BD48 3C048006 */  lui   $a0, %hi(controller_input_index) # $a0, 0x8006
/* 00C94C 8000BD4C 0C002EF2 */  jal   probably_ramrom_related
/* 00C950 8000BD50 24844F30 */   addiu $a0, %lo(controller_input_index) # addiu $a0, $a0, 0x4f30
/* 00C954 8000BD54 3C028002 */  lui   $v0, %hi(ptr_to_tlb_ramrom_record) # $v0, 0x8002
/* 00C958 8000BD58 8C426928 */  lw    $v0, %lo(ptr_to_tlb_ramrom_record)($v0)
/* 00C95C 8000BD5C 3C048006 */  lui   $a0, %hi(controller_input_index) # $a0, 0x8006
/* 00C960 8000BD60 24844F30 */  addiu $a0, %lo(controller_input_index) # addiu $a0, $a0, 0x4f30
/* 00C964 8000BD64 50400005 */  beql  $v0, $zero, .L8000BD7C
/* 00C968 8000BD68 8FBF0014 */   lw    $ra, 0x14($sp)
/* 00C96C 8000BD6C 8C8501E4 */  lw    $a1, 0x1e4($a0)
/* 00C970 8000BD70 0040F809 */  jalr  $v0
/* 00C974 8000BD74 8C8601E0 */  lw    $a2, 0x1e0($a0)
/* 00C978 8000BD78 8FBF0014 */  lw    $ra, 0x14($sp)
.L8000BD7C:
/* 00C97C 8000BD7C 27BD0018 */  addiu $sp, $sp, 0x18
/* 00C980 8000BD80 03E00008 */  jr    $ra
/* 00C984 8000BD84 00000000 */   nop   

controller_7000BD88:
/* 00C988 8000BD88 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 00C98C 8000BD8C AFBF0014 */  sw    $ra, 0x14($sp)
/* 00C990 8000BD90 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065370) # $a0, 0x8006
/* 00C994 8000BD94 24845370 */  addiu $a0, %lo(dword_CODE_bss_80065370) # addiu $a0, $a0, 0x5370
/* 00C998 8000BD98 27A5004C */  addiu $a1, $sp, 0x4c
/* 00C99C 8000BD9C 0C003774 */  jal   osRecvMesg
/* 00C9A0 8000BDA0 00003025 */   move  $a2, $zero
/* 00C9A4 8000BDA4 14400015 */  bnez  $v0, .L8000BDFC
/* 00C9A8 8000BDA8 3C0E8002 */   lui   $t6, %hi(D_800268C8) # $t6, 0x8002
/* 00C9AC 8000BDAC 8DCE68C8 */  lw    $t6, %lo(D_800268C8)($t6)
/* 00C9B0 8000BDB0 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00C9B4 8000BDB4 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00C9B8 8000BDB8 11C00005 */  beqz  $t6, .L8000BDD0
/* 00C9BC 8000BDBC 27A5004C */   addiu $a1, $sp, 0x4c
/* 00C9C0 8000BDC0 0C003774 */  jal   osRecvMesg
/* 00C9C4 8000BDC4 24060001 */   li    $a2, 1
/* 00C9C8 8000BDC8 3C018002 */  lui   $at, %hi(D_800268C8) # $at, 0x8002
/* 00C9CC 8000BDCC AC2068C8 */  sw    $zero, %lo(D_800268C8)($at)
.L8000BDD0:
/* 00C9D0 8000BDD0 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065390) # $a0, 0x8006
/* 00C9D4 8000BDD4 24845390 */  addiu $a0, %lo(dword_CODE_bss_80065390) # addiu $a0, $a0, 0x5390
/* 00C9D8 8000BDD8 27A5004C */  addiu $a1, $sp, 0x4c
/* 00C9DC 8000BDDC 0C0037C4 */  jal   osSendMesg
/* 00C9E0 8000BDE0 00003025 */   move  $a2, $zero
/* 00C9E4 8000BDE4 3C038002 */  lui   $v1, %hi(D_800268CC) # $v1, 0x8002
/* 00C9E8 8000BDE8 246368CC */  addiu $v1, %lo(D_800268CC) # addiu $v1, $v1, 0x68cc
/* 00C9EC 8000BDEC 8C6F0000 */  lw    $t7, ($v1)
/* 00C9F0 8000BDF0 25F80001 */  addiu $t8, $t7, 1
/* 00C9F4 8000BDF4 100000B9 */  b     .L8000C0DC
/* 00C9F8 8000BDF8 AC780000 */   sw    $t8, ($v1)
.L8000BDFC:
/* 00C9FC 8000BDFC 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653B0) # $a0, 0x8006
/* 00CA00 8000BE00 248453B0 */  addiu $a0, %lo(dword_CODE_bss_800653B0) # addiu $a0, $a0, 0x53b0
/* 00CA04 8000BE04 27A5004C */  addiu $a1, $sp, 0x4c
/* 00CA08 8000BE08 0C003774 */  jal   osRecvMesg
/* 00CA0C 8000BE0C 00003025 */   move  $a2, $zero
/* 00CA10 8000BE10 14400011 */  bnez  $v0, .L8000BE58
/* 00CA14 8000BE14 3C048006 */   lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00CA18 8000BE18 0C00535C */  jal   osContStartReadData
/* 00CA1C 8000BE1C 24845350 */   addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00CA20 8000BE20 24190001 */  li    $t9, 1
/* 00CA24 8000BE24 3C018002 */  lui   $at, %hi(D_800268C8) # $at, 0x8002
/* 00CA28 8000BE28 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653D0) # $a0, 0x8006
/* 00CA2C 8000BE2C AC3968C8 */  sw    $t9, %lo(D_800268C8)($at)
/* 00CA30 8000BE30 248453D0 */  addiu $a0, %lo(dword_CODE_bss_800653D0) # addiu $a0, $a0, 0x53d0
/* 00CA34 8000BE34 27A5004C */  addiu $a1, $sp, 0x4c
/* 00CA38 8000BE38 0C0037C4 */  jal   osSendMesg
/* 00CA3C 8000BE3C 00003025 */   move  $a2, $zero
/* 00CA40 8000BE40 3C038002 */  lui   $v1, %hi(D_800268CC) # $v1, 0x8002
/* 00CA44 8000BE44 246368CC */  addiu $v1, %lo(D_800268CC) # addiu $v1, $v1, 0x68cc
/* 00CA48 8000BE48 8C6B0000 */  lw    $t3, ($v1)
/* 00CA4C 8000BE4C 256CFFFF */  addiu $t4, $t3, -1
/* 00CA50 8000BE50 100000A2 */  b     .L8000C0DC
/* 00CA54 8000BE54 AC6C0000 */   sw    $t4, ($v1)
.L8000BE58:
/* 00CA58 8000BE58 3C038002 */  lui   $v1, %hi(D_800268CC) # $v1, 0x8002
/* 00CA5C 8000BE5C 246368CC */  addiu $v1, %lo(D_800268CC) # addiu $v1, $v1, 0x68cc
/* 00CA60 8000BE60 8C6D0000 */  lw    $t5, ($v1)
/* 00CA64 8000BE64 3C0E8002 */  lui   $t6, %hi(D_8002691C) # $t6, 0x8002
/* 00CA68 8000BE68 55A0009D */  bnezl $t5, .L8000C0E0
/* 00CA6C 8000BE6C 8FBF0014 */   lw    $ra, 0x14($sp)
/* 00CA70 8000BE70 8DCE691C */  lw    $t6, %lo(D_8002691C)($t6)
/* 00CA74 8000BE74 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00CA78 8000BE78 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00CA7C 8000BE7C 11C00097 */  beqz  $t6, .L8000C0DC
/* 00CA80 8000BE80 27A5004C */   addiu $a1, $sp, 0x4c
/* 00CA84 8000BE84 0C003774 */  jal   osRecvMesg
/* 00CA88 8000BE88 00003025 */   move  $a2, $zero
/* 00CA8C 8000BE8C 14400093 */  bnez  $v0, .L8000C0DC
/* 00CA90 8000BE90 3C058006 */   lui   $a1, %hi(controller_input_index) # $a1, 0x8006
/* 00CA94 8000BE94 3C018002 */  lui   $at, %hi(D_800268C8) # $at, 0x8002
/* 00CA98 8000BE98 24A54F30 */  addiu $a1, %lo(controller_input_index) # addiu $a1, $a1, 0x4f30
/* 00CA9C 8000BE9C AC2068C8 */  sw    $zero, %lo(D_800268C8)($at)
/* 00CAA0 8000BEA0 8CA201E8 */  lw    $v0, 0x1e8($a1)
/* 00CAA4 8000BEA4 24010014 */  li    $at, 20
/* 00CAA8 8000BEA8 8CB801E4 */  lw    $t8, 0x1e4($a1)
/* 00CAAC 8000BEAC 24430001 */  addiu $v1, $v0, 1
/* 00CAB0 8000BEB0 0061001A */  div   $zero, $v1, $at
/* 00CAB4 8000BEB4 00001810 */  mfhi  $v1
/* 00CAB8 8000BEB8 54780003 */  bnel  $v1, $t8, .L8000BEC8
/* 00CABC 8000BEBC 0003C880 */   sll   $t9, $v1, 2
/* 00CAC0 8000BEC0 00401825 */  move  $v1, $v0
/* 00CAC4 8000BEC4 0003C880 */  sll   $t9, $v1, 2
.L8000BEC8:
/* 00CAC8 8000BEC8 0323C823 */  subu  $t9, $t9, $v1
/* 00CACC 8000BECC 0019C8C0 */  sll   $t9, $t9, 3
/* 00CAD0 8000BED0 00B92021 */  addu  $a0, $a1, $t9
/* 00CAD4 8000BED4 0C00538D */  jal   osContGetReadData
/* 00CAD8 8000BED8 AFA30040 */   sw    $v1, 0x40($sp)
/* 00CADC 8000BEDC 8FA20040 */  lw    $v0, 0x40($sp)
/* 00CAE0 8000BEE0 24010014 */  li    $at, 20
/* 00CAE4 8000BEE4 3C048002 */  lui   $a0, %hi(D_80026920) # $a0, 0x8002
/* 00CAE8 8000BEE8 244B0013 */  addiu $t3, $v0, 0x13
/* 00CAEC 8000BEEC 0161001A */  div   $zero, $t3, $at
/* 00CAF0 8000BEF0 24846920 */  addiu $a0, %lo(D_80026920) # addiu $a0, $a0, 0x6920
/* 00CAF4 8000BEF4 8C8D0000 */  lw    $t5, ($a0)
/* 00CAF8 8000BEF8 00006010 */  mfhi  $t4
/* 00CAFC 8000BEFC 24010078 */  li    $at, 120
/* 00CB00 8000BF00 25AE0001 */  addiu $t6, $t5, 1
/* 00CB04 8000BF04 01C1001A */  div   $zero, $t6, $at
/* 00CB08 8000BF08 3C058006 */  lui   $a1, %hi(controller_input_index) # $a1, 0x8006
/* 00CB0C 8000BF0C 24A54F30 */  addiu $a1, %lo(controller_input_index) # addiu $a1, $a1, 0x4f30
/* 00CB10 8000BF10 0000C010 */  mfhi  $t8
/* 00CB14 8000BF14 ACAC01EC */  sw    $t4, 0x1ec($a1)
/* 00CB18 8000BF18 AC8E0000 */  sw    $t6, ($a0)
/* 00CB1C 8000BF1C 17000006 */  bnez  $t8, .L8000BF38
/* 00CB20 8000BF20 ACA201E8 */   sw    $v0, 0x1e8($a1)
/* 00CB24 8000BF24 0C002E04 */  jal   controller_check_for_rumble_maybe
/* 00CB28 8000BF28 00000000 */   nop   
/* 00CB2C 8000BF2C 3C058006 */  lui   $a1, %hi(controller_input_index) # $a1, 0x8006
/* 00CB30 8000BF30 24A54F30 */  addiu $a1, %lo(controller_input_index) # addiu $a1, $a1, 0x4f30
/* 00CB34 8000BF34 8CA201E8 */  lw    $v0, 0x1e8($a1)
.L8000BF38:
/* 00CB38 8000BF38 0002C880 */  sll   $t9, $v0, 2
/* 00CB3C 8000BF3C 0322C823 */  subu  $t9, $t9, $v0
/* 00CB40 8000BF40 0019C8C0 */  sll   $t9, $t9, 3
/* 00CB44 8000BF44 00B93021 */  addu  $a2, $a1, $t9
/* 00CB48 8000BF48 00002025 */  move  $a0, $zero
/* 00CB4C 8000BF4C 24070006 */  li    $a3, 6
.L8000BF50:
/* 00CB50 8000BF50 00870019 */  multu $a0, $a3
/* 00CB54 8000BF54 00001012 */  mflo  $v0
/* 00CB58 8000BF58 00C25821 */  addu  $t3, $a2, $v0
/* 00CB5C 8000BF5C 91630004 */  lbu   $v1, 4($t3)
/* 00CB60 8000BF60 1460000A */  bnez  $v1, .L8000BF8C
/* 00CB64 8000BF64 00000000 */   nop   
/* 00CB68 8000BF68 8CAC01EC */  lw    $t4, 0x1ec($a1)
/* 00CB6C 8000BF6C 000C6880 */  sll   $t5, $t4, 2
/* 00CB70 8000BF70 01AC6823 */  subu  $t5, $t5, $t4
/* 00CB74 8000BF74 000D68C0 */  sll   $t5, $t5, 3
/* 00CB78 8000BF78 00AD7021 */  addu  $t6, $a1, $t5
/* 00CB7C 8000BF7C 01C27821 */  addu  $t7, $t6, $v0
/* 00CB80 8000BF80 91F80004 */  lbu   $t8, 4($t7)
/* 00CB84 8000BF84 1700000C */  bnez  $t8, .L8000BFB8
/* 00CB88 8000BF88 00000000 */   nop   
.L8000BF8C:
/* 00CB8C 8000BF8C 1060000E */  beqz  $v1, .L8000BFC8
/* 00CB90 8000BF90 24840001 */   addiu $a0, $a0, 1
/* 00CB94 8000BF94 8CB901EC */  lw    $t9, 0x1ec($a1)
/* 00CB98 8000BF98 00195880 */  sll   $t3, $t9, 2
/* 00CB9C 8000BF9C 01795823 */  subu  $t3, $t3, $t9
/* 00CBA0 8000BFA0 000B58C0 */  sll   $t3, $t3, 3
/* 00CBA4 8000BFA4 00AB6021 */  addu  $t4, $a1, $t3
/* 00CBA8 8000BFA8 01826821 */  addu  $t5, $t4, $v0
/* 00CBAC 8000BFAC 91AE0004 */  lbu   $t6, 4($t5)
/* 00CBB0 8000BFB0 55C00006 */  bnezl $t6, .L8000BFCC
/* 00CBB4 8000BFB4 00047E00 */   sll   $t7, $a0, 0x18
.L8000BFB8:
/* 00CBB8 8000BFB8 0C002E04 */  jal   controller_check_for_rumble_maybe
/* 00CBBC 8000BFBC 00000000 */   nop   
/* 00CBC0 8000BFC0 10000006 */  b     .L8000BFDC
/* 00CBC4 8000BFC4 00000000 */   nop   
.L8000BFC8:
/* 00CBC8 8000BFC8 00047E00 */  sll   $t7, $a0, 0x18
.L8000BFCC:
/* 00CBCC 8000BFCC 000F2603 */  sra   $a0, $t7, 0x18
/* 00CBD0 8000BFD0 28810004 */  slti  $at, $a0, 4
/* 00CBD4 8000BFD4 1420FFDE */  bnez  $at, .L8000BF50
/* 00CBD8 8000BFD8 00000000 */   nop   
.L8000BFDC:
/* 00CBDC 8000BFDC 0C002E9F */  jal   controller_rumble_related
/* 00CBE0 8000BFE0 00000000 */   nop   
/* 00CBE4 8000BFE4 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00CBE8 8000BFE8 0C00535C */  jal   osContStartReadData
/* 00CBEC 8000BFEC 24845350 */   addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00CBF0 8000BFF0 3C038002 */  lui   $v1, %hi(D_80026970) # $v1, 0x8002
/* 00CBF4 8000BFF4 8C636970 */  lw    $v1, %lo(D_80026970)($v1)
/* 00CBF8 8000BFF8 24190001 */  li    $t9, 1
/* 00CBFC 8000BFFC 3C018002 */  lui   $at, %hi(D_800268C8) # $at, 0x8002
/* 00CC00 8000C000 AC3968C8 */  sw    $t9, %lo(D_800268C8)($at)
/* 00CC04 8000C004 3C018002 */  lui   $at, %hi(D_80026970) # $at, 0x8002
/* 00CC08 8000C008 24630001 */  addiu $v1, $v1, 1
/* 00CC0C 8000C00C AC236970 */  sw    $v1, %lo(D_80026970)($at)
/* 00CC10 8000C010 2861003C */  slti  $at, $v1, 0x3c
/* 00CC14 8000C014 14200031 */  bnez  $at, .L8000C0DC
/* 00CC18 8000C018 3C098002 */   lui   $t1, %hi(pl1_controller_failure_lr) # $t1, 0x8002
/* 00CC1C 8000C01C 3C048002 */  lui   $a0, %hi(pl1_controller_failure_ud) # $a0, 0x8002
/* 00CC20 8000C020 3C058002 */  lui   $a1, %hi(pl1_controller_failure_held) # $a1, 0x8002
/* 00CC24 8000C024 3C038002 */  lui   $v1, %hi(pl1_controller_failure_pressed) # $v1, 0x8002
/* 00CC28 8000C028 3C0A8002 */  lui   $t2, %hi(D_80026970) # $t2, 0x8002
/* 00CC2C 8000C02C 254A6970 */  addiu $t2, %lo(D_80026970) # addiu $t2, $t2, 0x6970
/* 00CC30 8000C030 24636960 */  addiu $v1, %lo(pl1_controller_failure_pressed) # addiu $v1, $v1, 0x6960
/* 00CC34 8000C034 24A56950 */  addiu $a1, %lo(pl1_controller_failure_held) # addiu $a1, $a1, 0x6950
/* 00CC38 8000C038 24846940 */  addiu $a0, %lo(pl1_controller_failure_ud) # addiu $a0, $a0, 0x6940
/* 00CC3C 8000C03C 25296930 */  addiu $t1, %lo(pl1_controller_failure_lr) # addiu $t1, $t1, 0x6930
.L8000C040:
/* 00CC40 8000C040 8D220000 */  lw    $v0, ($t1)
/* 00CC44 8000C044 5440000B */  bnezl $v0, .L8000C074
/* 00CC48 8000C048 AD200000 */   sw    $zero, ($t1)
/* 00CC4C 8000C04C 8C8B0000 */  lw    $t3, ($a0)
/* 00CC50 8000C050 55600008 */  bnezl $t3, .L8000C074
/* 00CC54 8000C054 AD200000 */   sw    $zero, ($t1)
/* 00CC58 8000C058 8CAC0000 */  lw    $t4, ($a1)
/* 00CC5C 8000C05C 55800005 */  bnezl $t4, .L8000C074
/* 00CC60 8000C060 AD200000 */   sw    $zero, ($t1)
/* 00CC64 8000C064 8C6D0000 */  lw    $t5, ($v1)
/* 00CC68 8000C068 51A00006 */  beql  $t5, $zero, .L8000C084
/* 00CC6C 8000C06C 8D220004 */   lw    $v0, 4($t1)
/* 00CC70 8000C070 AD200000 */  sw    $zero, ($t1)
.L8000C074:
/* 00CC74 8000C074 AC800000 */  sw    $zero, ($a0)
/* 00CC78 8000C078 ACA00000 */  sw    $zero, ($a1)
/* 00CC7C 8000C07C AC600000 */  sw    $zero, ($v1)
/* 00CC80 8000C080 8D220004 */  lw    $v0, 4($t1)
.L8000C084:
/* 00CC84 8000C084 5440000B */  bnezl $v0, .L8000C0B4
/* 00CC88 8000C088 AD200004 */   sw    $zero, 4($t1)
/* 00CC8C 8000C08C 8C8E0004 */  lw    $t6, 4($a0)
/* 00CC90 8000C090 55C00008 */  bnezl $t6, .L8000C0B4
/* 00CC94 8000C094 AD200004 */   sw    $zero, 4($t1)
/* 00CC98 8000C098 8CAF0004 */  lw    $t7, 4($a1)
/* 00CC9C 8000C09C 55E00005 */  bnezl $t7, .L8000C0B4
/* 00CCA0 8000C0A0 AD200004 */   sw    $zero, 4($t1)
/* 00CCA4 8000C0A4 8C780004 */  lw    $t8, 4($v1)
/* 00CCA8 8000C0A8 53000006 */  beql  $t8, $zero, .L8000C0C4
/* 00CCAC 8000C0AC 24630008 */   addiu $v1, $v1, 8
/* 00CCB0 8000C0B0 AD200004 */  sw    $zero, 4($t1)
.L8000C0B4:
/* 00CCB4 8000C0B4 AC800004 */  sw    $zero, 4($a0)
/* 00CCB8 8000C0B8 ACA00004 */  sw    $zero, 4($a1)
/* 00CCBC 8000C0BC AC600004 */  sw    $zero, 4($v1)
/* 00CCC0 8000C0C0 24630008 */  addiu $v1, $v1, 8
.L8000C0C4:
/* 00CCC4 8000C0C4 25290008 */  addiu $t1, $t1, 8
/* 00CCC8 8000C0C8 24840008 */  addiu $a0, $a0, 8
/* 00CCCC 8000C0CC 146AFFDC */  bne   $v1, $t2, .L8000C040
/* 00CCD0 8000C0D0 24A50008 */   addiu $a1, $a1, 8
/* 00CCD4 8000C0D4 3C018002 */  lui   $at, %hi(D_80026970) # $at, 0x8002
/* 00CCD8 8000C0D8 AC206970 */  sw    $zero, %lo(D_80026970)($at)
.L8000C0DC:
/* 00CCDC 8000C0DC 8FBF0014 */  lw    $ra, 0x14($sp)
.L8000C0E0:
/* 00CCE0 8000C0E0 27BD0050 */  addiu $sp, $sp, 0x50
/* 00CCE4 8000C0E4 03E00008 */  jr    $ra
/* 00CCE8 8000C0E8 00000000 */   nop   

get_cur_controller_horz_stick_pos:
/* 00CCEC 8000C0EC 3C038002 */  lui   $v1, %hi(ptr_current_point_in_controller_input_index) # $v1, 0x8002
/* 00CCF0 8000C0F0 8C6368C4 */  lw    $v1, %lo(ptr_current_point_in_controller_input_index)($v1)
/* 00CCF4 8000C0F4 AFA40000 */  sw    $a0, ($sp)
/* 00CCF8 8000C0F8 00047600 */  sll   $t6, $a0, 0x18
/* 00CCFC 8000C0FC 8C7801F8 */  lw    $t8, 0x1f8($v1)
/* 00CD00 8000C100 000E7E03 */  sra   $t7, $t6, 0x18
/* 00CD04 8000C104 01E02025 */  move  $a0, $t7
/* 00CD08 8000C108 0701000E */  bgez  $t8, .L8000C144
/* 00CD0C 8000C10C 3C198002 */   lui   $t9, %hi(num_controller_plugged_in_flags) # $t9, 0x8002
/* 00CD10 8000C110 933968D0 */  lbu   $t9, %lo(num_controller_plugged_in_flags)($t9)
/* 00CD14 8000C114 3C0B8002 */  lui   $t3, %hi(pl1_controller_failure_lr) # $t3, 0x8002
/* 00CD18 8000C118 256B6930 */  addiu $t3, %lo(pl1_controller_failure_lr) # addiu $t3, $t3, 0x6930
/* 00CD1C 8000C11C 01F94007 */  srav  $t0, $t9, $t7
/* 00CD20 8000C120 31090001 */  andi  $t1, $t0, 1
/* 00CD24 8000C124 15200007 */  bnez  $t1, .L8000C144
/* 00CD28 8000C128 000F5080 */   sll   $t2, $t7, 2
/* 00CD2C 8000C12C 014B1821 */  addu  $v1, $t2, $t3
/* 00CD30 8000C130 8C6C0000 */  lw    $t4, ($v1)
/* 00CD34 8000C134 00001025 */  move  $v0, $zero
/* 00CD38 8000C138 258D0001 */  addiu $t5, $t4, 1
/* 00CD3C 8000C13C 03E00008 */  jr    $ra
/* 00CD40 8000C140 AC6D0000 */   sw    $t5, ($v1)

.L8000C144:
/* 00CD44 8000C144 8C6E01E0 */  lw    $t6, 0x1e0($v1)
/* 00CD48 8000C148 0004C880 */  sll   $t9, $a0, 2
/* 00CD4C 8000C14C 0324C823 */  subu  $t9, $t9, $a0
/* 00CD50 8000C150 000E7880 */  sll   $t7, $t6, 2
/* 00CD54 8000C154 01EE7823 */  subu  $t7, $t7, $t6
/* 00CD58 8000C158 000F78C0 */  sll   $t7, $t7, 3
/* 00CD5C 8000C15C 006FC021 */  addu  $t8, $v1, $t7
/* 00CD60 8000C160 0019C840 */  sll   $t9, $t9, 1
/* 00CD64 8000C164 03194021 */  addu  $t0, $t8, $t9
/* 00CD68 8000C168 81020002 */  lb    $v0, 2($t0)
/* 00CD6C 8000C16C 03E00008 */  jr    $ra
/* 00CD70 8000C170 00000000 */   nop   

controller_7000C174:
/* 00CD74 8000C174 3C038002 */  lui   $v1, %hi(ptr_current_point_in_controller_input_index) # $v1, 0x8002
/* 00CD78 8000C178 8C6368C4 */  lw    $v1, %lo(ptr_current_point_in_controller_input_index)($v1)
/* 00CD7C 8000C17C AFA40000 */  sw    $a0, ($sp)
/* 00CD80 8000C180 00047600 */  sll   $t6, $a0, 0x18
/* 00CD84 8000C184 8C7801F8 */  lw    $t8, 0x1f8($v1)
/* 00CD88 8000C188 000E7E03 */  sra   $t7, $t6, 0x18
/* 00CD8C 8000C18C 01E02025 */  move  $a0, $t7
/* 00CD90 8000C190 0701000E */  bgez  $t8, .L8000C1CC
/* 00CD94 8000C194 3C198002 */   lui   $t9, %hi(num_controller_plugged_in_flags) # $t9, 0x8002
/* 00CD98 8000C198 933968D0 */  lbu   $t9, %lo(num_controller_plugged_in_flags)($t9)
/* 00CD9C 8000C19C 3C0B8002 */  lui   $t3, %hi(pl1_controller_failure_lr) # $t3, 0x8002
/* 00CDA0 8000C1A0 256B6930 */  addiu $t3, %lo(pl1_controller_failure_lr) # addiu $t3, $t3, 0x6930
/* 00CDA4 8000C1A4 01F94007 */  srav  $t0, $t9, $t7
/* 00CDA8 8000C1A8 31090001 */  andi  $t1, $t0, 1
/* 00CDAC 8000C1AC 15200007 */  bnez  $t1, .L8000C1CC
/* 00CDB0 8000C1B0 000F5080 */   sll   $t2, $t7, 2
/* 00CDB4 8000C1B4 014B1821 */  addu  $v1, $t2, $t3
/* 00CDB8 8000C1B8 8C6C0000 */  lw    $t4, ($v1)
/* 00CDBC 8000C1BC 00001025 */  move  $v0, $zero
/* 00CDC0 8000C1C0 258D0001 */  addiu $t5, $t4, 1
/* 00CDC4 8000C1C4 03E00008 */  jr    $ra
/* 00CDC8 8000C1C8 AC6D0000 */   sw    $t5, ($v1)

.L8000C1CC:
/* 00CDCC 8000C1CC 8C6E01E4 */  lw    $t6, 0x1e4($v1)
/* 00CDD0 8000C1D0 0004C880 */  sll   $t9, $a0, 2
/* 00CDD4 8000C1D4 0324C823 */  subu  $t9, $t9, $a0
/* 00CDD8 8000C1D8 000E7880 */  sll   $t7, $t6, 2
/* 00CDDC 8000C1DC 01EE7823 */  subu  $t7, $t7, $t6
/* 00CDE0 8000C1E0 000F78C0 */  sll   $t7, $t7, 3
/* 00CDE4 8000C1E4 006FC021 */  addu  $t8, $v1, $t7
/* 00CDE8 8000C1E8 0019C840 */  sll   $t9, $t9, 1
/* 00CDEC 8000C1EC 03194021 */  addu  $t0, $t8, $t9
/* 00CDF0 8000C1F0 81020002 */  lb    $v0, 2($t0)
/* 00CDF4 8000C1F4 03E00008 */  jr    $ra
/* 00CDF8 8000C1F8 00000000 */   nop   

get_cur_controller_vert_stick_pos:
/* 00CDFC 8000C1FC 3C038002 */  lui   $v1, %hi(ptr_current_point_in_controller_input_index) # $v1, 0x8002
/* 00CE00 8000C200 8C6368C4 */  lw    $v1, %lo(ptr_current_point_in_controller_input_index)($v1)
/* 00CE04 8000C204 AFA40000 */  sw    $a0, ($sp)
/* 00CE08 8000C208 00047600 */  sll   $t6, $a0, 0x18
/* 00CE0C 8000C20C 8C7801F8 */  lw    $t8, 0x1f8($v1)
/* 00CE10 8000C210 000E7E03 */  sra   $t7, $t6, 0x18
/* 00CE14 8000C214 01E02025 */  move  $a0, $t7
/* 00CE18 8000C218 0701000E */  bgez  $t8, .L8000C254
/* 00CE1C 8000C21C 3C198002 */   lui   $t9, %hi(num_controller_plugged_in_flags) # $t9, 0x8002
/* 00CE20 8000C220 933968D0 */  lbu   $t9, %lo(num_controller_plugged_in_flags)($t9)
/* 00CE24 8000C224 3C0B8002 */  lui   $t3, %hi(pl1_controller_failure_ud) # $t3, 0x8002
/* 00CE28 8000C228 256B6940 */  addiu $t3, %lo(pl1_controller_failure_ud) # addiu $t3, $t3, 0x6940
/* 00CE2C 8000C22C 01F94007 */  srav  $t0, $t9, $t7
/* 00CE30 8000C230 31090001 */  andi  $t1, $t0, 1
/* 00CE34 8000C234 15200007 */  bnez  $t1, .L8000C254
/* 00CE38 8000C238 000F5080 */   sll   $t2, $t7, 2
/* 00CE3C 8000C23C 014B1821 */  addu  $v1, $t2, $t3
/* 00CE40 8000C240 8C6C0000 */  lw    $t4, ($v1)
/* 00CE44 8000C244 00001025 */  move  $v0, $zero
/* 00CE48 8000C248 258D0001 */  addiu $t5, $t4, 1
/* 00CE4C 8000C24C 03E00008 */  jr    $ra
/* 00CE50 8000C250 AC6D0000 */   sw    $t5, ($v1)

.L8000C254:
/* 00CE54 8000C254 8C6E01E0 */  lw    $t6, 0x1e0($v1)
/* 00CE58 8000C258 0004C880 */  sll   $t9, $a0, 2
/* 00CE5C 8000C25C 0324C823 */  subu  $t9, $t9, $a0
/* 00CE60 8000C260 000E7880 */  sll   $t7, $t6, 2
/* 00CE64 8000C264 01EE7823 */  subu  $t7, $t7, $t6
/* 00CE68 8000C268 000F78C0 */  sll   $t7, $t7, 3
/* 00CE6C 8000C26C 006FC021 */  addu  $t8, $v1, $t7
/* 00CE70 8000C270 0019C840 */  sll   $t9, $t9, 1
/* 00CE74 8000C274 03194021 */  addu  $t0, $t8, $t9
/* 00CE78 8000C278 81020003 */  lb    $v0, 3($t0)
/* 00CE7C 8000C27C 03E00008 */  jr    $ra
/* 00CE80 8000C280 00000000 */   nop   

controller_7000C284:
/* 00CE84 8000C284 3C038002 */  lui   $v1, %hi(ptr_current_point_in_controller_input_index) # $v1, 0x8002
/* 00CE88 8000C288 8C6368C4 */  lw    $v1, %lo(ptr_current_point_in_controller_input_index)($v1)
/* 00CE8C 8000C28C AFA40000 */  sw    $a0, ($sp)
/* 00CE90 8000C290 00047600 */  sll   $t6, $a0, 0x18
/* 00CE94 8000C294 8C7801F8 */  lw    $t8, 0x1f8($v1)
/* 00CE98 8000C298 000E7E03 */  sra   $t7, $t6, 0x18
/* 00CE9C 8000C29C 01E02025 */  move  $a0, $t7
/* 00CEA0 8000C2A0 0701000E */  bgez  $t8, .L8000C2DC
/* 00CEA4 8000C2A4 3C198002 */   lui   $t9, %hi(num_controller_plugged_in_flags) # $t9, 0x8002
/* 00CEA8 8000C2A8 933968D0 */  lbu   $t9, %lo(num_controller_plugged_in_flags)($t9)
/* 00CEAC 8000C2AC 3C0B8002 */  lui   $t3, %hi(pl1_controller_failure_ud) # $t3, 0x8002
/* 00CEB0 8000C2B0 256B6940 */  addiu $t3, %lo(pl1_controller_failure_ud) # addiu $t3, $t3, 0x6940
/* 00CEB4 8000C2B4 01F94007 */  srav  $t0, $t9, $t7
/* 00CEB8 8000C2B8 31090001 */  andi  $t1, $t0, 1
/* 00CEBC 8000C2BC 15200007 */  bnez  $t1, .L8000C2DC
/* 00CEC0 8000C2C0 000F5080 */   sll   $t2, $t7, 2
/* 00CEC4 8000C2C4 014B1821 */  addu  $v1, $t2, $t3
/* 00CEC8 8000C2C8 8C6C0000 */  lw    $t4, ($v1)
/* 00CECC 8000C2CC 00001025 */  move  $v0, $zero
/* 00CED0 8000C2D0 258D0001 */  addiu $t5, $t4, 1
/* 00CED4 8000C2D4 03E00008 */  jr    $ra
/* 00CED8 8000C2D8 AC6D0000 */   sw    $t5, ($v1)

.L8000C2DC:
/* 00CEDC 8000C2DC 8C6E01E4 */  lw    $t6, 0x1e4($v1)
/* 00CEE0 8000C2E0 0004C880 */  sll   $t9, $a0, 2
/* 00CEE4 8000C2E4 0324C823 */  subu  $t9, $t9, $a0
/* 00CEE8 8000C2E8 000E7880 */  sll   $t7, $t6, 2
/* 00CEEC 8000C2EC 01EE7823 */  subu  $t7, $t7, $t6
/* 00CEF0 8000C2F0 000F78C0 */  sll   $t7, $t7, 3
/* 00CEF4 8000C2F4 006FC021 */  addu  $t8, $v1, $t7
/* 00CEF8 8000C2F8 0019C840 */  sll   $t9, $t9, 1
/* 00CEFC 8000C2FC 03194021 */  addu  $t0, $t8, $t9
/* 00CF00 8000C300 81020003 */  lb    $v0, 3($t0)
/* 00CF04 8000C304 03E00008 */  jr    $ra
/* 00CF08 8000C308 00000000 */   nop   

get_controller_buttons_held:
/* 00CF0C 8000C30C 3C038002 */  lui   $v1, %hi(ptr_current_point_in_controller_input_index) # $v1, 0x8002
/* 00CF10 8000C310 8C6368C4 */  lw    $v1, %lo(ptr_current_point_in_controller_input_index)($v1)
/* 00CF14 8000C314 AFA40000 */  sw    $a0, ($sp)
/* 00CF18 8000C318 AFA50004 */  sw    $a1, 4($sp)
/* 00CF1C 8000C31C 8C7901F8 */  lw    $t9, 0x1f8($v1)
/* 00CF20 8000C320 00047600 */  sll   $t6, $a0, 0x18
/* 00CF24 8000C324 000E7E03 */  sra   $t7, $t6, 0x18
/* 00CF28 8000C328 30B8FFFF */  andi  $t8, $a1, 0xffff
/* 00CF2C 8000C32C 03002825 */  move  $a1, $t8
/* 00CF30 8000C330 0721000F */  bgez  $t9, .L8000C370
/* 00CF34 8000C334 01E02025 */   move  $a0, $t7
/* 00CF38 8000C338 3C088002 */  lui   $t0, %hi(num_controller_plugged_in_flags) # $t0, 0x8002
/* 00CF3C 8000C33C 910868D0 */  lbu   $t0, %lo(num_controller_plugged_in_flags)($t0)
/* 00CF40 8000C340 3C0C8002 */  lui   $t4, %hi(pl1_controller_failure_held) # $t4, 0x8002
/* 00CF44 8000C344 258C6950 */  addiu $t4, %lo(pl1_controller_failure_held) # addiu $t4, $t4, 0x6950
/* 00CF48 8000C348 01E84807 */  srav  $t1, $t0, $t7
/* 00CF4C 8000C34C 312A0001 */  andi  $t2, $t1, 1
/* 00CF50 8000C350 15400007 */  bnez  $t2, .L8000C370
/* 00CF54 8000C354 000F5880 */   sll   $t3, $t7, 2
/* 00CF58 8000C358 016C1821 */  addu  $v1, $t3, $t4
/* 00CF5C 8000C35C 8C6D0000 */  lw    $t5, ($v1)
/* 00CF60 8000C360 00001025 */  move  $v0, $zero
/* 00CF64 8000C364 25AE0001 */  addiu $t6, $t5, 1
/* 00CF68 8000C368 03E00008 */  jr    $ra
/* 00CF6C 8000C36C AC6E0000 */   sw    $t6, ($v1)

.L8000C370:
/* 00CF70 8000C370 8C6F01E0 */  lw    $t7, 0x1e0($v1)
/* 00CF74 8000C374 00044080 */  sll   $t0, $a0, 2
/* 00CF78 8000C378 01044023 */  subu  $t0, $t0, $a0
/* 00CF7C 8000C37C 000FC080 */  sll   $t8, $t7, 2
/* 00CF80 8000C380 030FC023 */  subu  $t8, $t8, $t7
/* 00CF84 8000C384 0018C0C0 */  sll   $t8, $t8, 3
/* 00CF88 8000C388 0078C821 */  addu  $t9, $v1, $t8
/* 00CF8C 8000C38C 00084040 */  sll   $t0, $t0, 1
/* 00CF90 8000C390 03284821 */  addu  $t1, $t9, $t0
/* 00CF94 8000C394 952A0000 */  lhu   $t2, ($t1)
/* 00CF98 8000C398 01451024 */  and   $v0, $t2, $a1
/* 00CF9C 8000C39C 304BFFFF */  andi  $t3, $v0, 0xffff
/* 00CFA0 8000C3A0 01601025 */  move  $v0, $t3
/* 00CFA4 8000C3A4 03E00008 */  jr    $ra
/* 00CFA8 8000C3A8 00000000 */   nop   

get_controller_buttons_pressed:
/* 00CFAC 8000C3AC 3C038002 */  lui   $v1, %hi(ptr_current_point_in_controller_input_index) # $v1, 0x8002
/* 00CFB0 8000C3B0 8C6368C4 */  lw    $v1, %lo(ptr_current_point_in_controller_input_index)($v1)
/* 00CFB4 8000C3B4 AFA40000 */  sw    $a0, ($sp)
/* 00CFB8 8000C3B8 AFA50004 */  sw    $a1, 4($sp)
/* 00CFBC 8000C3BC 8C7901F8 */  lw    $t9, 0x1f8($v1)
/* 00CFC0 8000C3C0 00047600 */  sll   $t6, $a0, 0x18
/* 00CFC4 8000C3C4 000E7E03 */  sra   $t7, $t6, 0x18
/* 00CFC8 8000C3C8 30B8FFFF */  andi  $t8, $a1, 0xffff
/* 00CFCC 8000C3CC 03002825 */  move  $a1, $t8
/* 00CFD0 8000C3D0 0721000F */  bgez  $t9, .L8000C410
/* 00CFD4 8000C3D4 01E02025 */   move  $a0, $t7
/* 00CFD8 8000C3D8 3C088002 */  lui   $t0, %hi(num_controller_plugged_in_flags) # $t0, 0x8002
/* 00CFDC 8000C3DC 910868D0 */  lbu   $t0, %lo(num_controller_plugged_in_flags)($t0)
/* 00CFE0 8000C3E0 3C0C8002 */  lui   $t4, %hi(pl1_controller_failure_pressed) # $t4, 0x8002
/* 00CFE4 8000C3E4 258C6960 */  addiu $t4, %lo(pl1_controller_failure_pressed) # addiu $t4, $t4, 0x6960
/* 00CFE8 8000C3E8 01E84807 */  srav  $t1, $t0, $t7
/* 00CFEC 8000C3EC 312A0001 */  andi  $t2, $t1, 1
/* 00CFF0 8000C3F0 15400007 */  bnez  $t2, .L8000C410
/* 00CFF4 8000C3F4 000F5880 */   sll   $t3, $t7, 2
/* 00CFF8 8000C3F8 016C1821 */  addu  $v1, $t3, $t4
/* 00CFFC 8000C3FC 8C6D0000 */  lw    $t5, ($v1)
/* 00D000 8000C400 00001025 */  move  $v0, $zero
/* 00D004 8000C404 25AE0001 */  addiu $t6, $t5, 1
/* 00D008 8000C408 03E00008 */  jr    $ra
/* 00D00C 8000C40C AC6E0000 */   sw    $t6, ($v1)

.L8000C410:
/* 00D010 8000C410 00047840 */  sll   $t7, $a0, 1
/* 00D014 8000C414 006FC021 */  addu  $t8, $v1, $t7
/* 00D018 8000C418 971901F0 */  lhu   $t9, 0x1f0($t8)
/* 00D01C 8000C41C 03251024 */  and   $v0, $t9, $a1
/* 00D020 8000C420 3048FFFF */  andi  $t0, $v0, 0xffff
/* 00D024 8000C424 01001025 */  move  $v0, $t0
/* 00D028 8000C428 03E00008 */  jr    $ra
/* 00D02C 8000C42C 00000000 */   nop   

controller_7000C430:
/* 00D030 8000C430 AFA50004 */  sw    $a1, 4($sp)
/* 00D034 8000C434 30A3FFFF */  andi  $v1, $a1, 0xffff
/* 00D038 8000C438 24050011 */  li    $a1, 17
/* 00D03C 8000C43C 2402000F */  li    $v0, 15
.L8000C440:
/* 00D040 8000C440 00437807 */  srav  $t7, $v1, $v0
/* 00D044 8000C444 31F80001 */  andi  $t8, $t7, 1
/* 00D048 8000C448 0018C82A */  slt   $t9, $zero, $t8
/* 00D04C 8000C44C 03250019 */  multu $t9, $a1
/* 00D050 8000C450 2442FFFF */  addiu $v0, $v0, -1
/* 00D054 8000C454 24840001 */  addiu $a0, $a0, 1
/* 00D058 8000C458 00004012 */  mflo  $t0
/* 00D05C 8000C45C 25090020 */  addiu $t1, $t0, 0x20
/* 00D060 8000C460 0441FFF7 */  bgez  $v0, .L8000C440
/* 00D064 8000C464 A089FFFF */   sb    $t1, -1($a0)
/* 00D068 8000C468 03E00008 */  jr    $ra
/* 00D06C 8000C46C 00000000 */   nop   

controller_7000C470:
/* 00D070 8000C470 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D074 8000C474 AFBF001C */  sw    $ra, 0x1c($sp)
/* 00D078 8000C478 AFB00018 */  sw    $s0, 0x18($sp)
/* 00D07C 8000C47C 0C002E7E */  jal   controller_finding_controller_maybe
/* 00D080 8000C480 00008025 */   move  $s0, $zero
/* 00D084 8000C484 58400007 */  blezl $v0, .L8000C4A4
/* 00D088 8000C488 8FBF001C */   lw    $ra, 0x1c($sp)
.L8000C48C:
/* 00D08C 8000C48C 0C002E7E */  jal   controller_finding_controller_maybe
/* 00D090 8000C490 26100001 */   addiu $s0, $s0, 1
/* 00D094 8000C494 0202082A */  slt   $at, $s0, $v0
/* 00D098 8000C498 1420FFFC */  bnez  $at, .L8000C48C
/* 00D09C 8000C49C 00000000 */   nop   
/* 00D0A0 8000C4A0 8FBF001C */  lw    $ra, 0x1c($sp)
.L8000C4A4:
/* 00D0A4 8000C4A4 8FB00018 */  lw    $s0, 0x18($sp)
/* 00D0A8 8000C4A8 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D0AC 8000C4AC 03E00008 */  jr    $ra
/* 00D0B0 8000C4B0 00000000 */   nop   

get_controller_3dstick_L_R:
/* 00D0B4 8000C4B4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00D0B8 8000C4B8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D0BC 8000C4BC AFA40018 */  sw    $a0, 0x18($sp)
/* 00D0C0 8000C4C0 00047600 */  sll   $t6, $a0, 0x18
/* 00D0C4 8000C4C4 000E2603 */  sra   $a0, $t6, 0x18
/* 00D0C8 8000C4C8 AFA5001C */  sw    $a1, 0x1c($sp)
/* 00D0CC 8000C4CC 0C00303B */  jal   get_cur_controller_horz_stick_pos
/* 00D0D0 8000C4D0 AFA60020 */   sw    $a2, 0x20($sp)
/* 00D0D4 8000C4D4 2444003C */  addiu $a0, $v0, 0x3c
/* 00D0D8 8000C4D8 28810079 */  slti  $at, $a0, 0x79
/* 00D0DC 8000C4DC 14200002 */  bnez  $at, .L8000C4E8
/* 00D0E0 8000C4E0 8FA5001C */   lw    $a1, 0x1c($sp)
/* 00D0E4 8000C4E4 24040078 */  li    $a0, 120
.L8000C4E8:
/* 00D0E8 8000C4E8 04810002 */  bgez  $a0, .L8000C4F4
/* 00D0EC 8000C4EC 8FB80020 */   lw    $t8, 0x20($sp)
/* 00D0F0 8000C4F0 00002025 */  move  $a0, $zero
.L8000C4F4:
/* 00D0F4 8000C4F4 0305C823 */  subu  $t9, $t8, $a1
/* 00D0F8 8000C4F8 00990019 */  multu $a0, $t9
/* 00D0FC 8000C4FC 24010078 */  li    $at, 120
/* 00D100 8000C500 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D104 8000C504 27BD0018 */  addiu $sp, $sp, 0x18
/* 00D108 8000C508 00004012 */  mflo  $t0
/* 00D10C 8000C50C 00000000 */  nop   
/* 00D110 8000C510 00000000 */  nop   
/* 00D114 8000C514 0101001A */  div   $zero, $t0, $at
/* 00D118 8000C518 00004812 */  mflo  $t1
/* 00D11C 8000C51C 01251021 */  addu  $v0, $t1, $a1
/* 00D120 8000C520 03E00008 */  jr    $ra
/* 00D124 8000C524 00000000 */   nop   

get_controller_3dstick_U_D:
/* 00D128 8000C528 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00D12C 8000C52C AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D130 8000C530 AFA40018 */  sw    $a0, 0x18($sp)
/* 00D134 8000C534 00047600 */  sll   $t6, $a0, 0x18
/* 00D138 8000C538 000E2603 */  sra   $a0, $t6, 0x18
/* 00D13C 8000C53C AFA5001C */  sw    $a1, 0x1c($sp)
/* 00D140 8000C540 0C00307F */  jal   get_cur_controller_vert_stick_pos
/* 00D144 8000C544 AFA60020 */   sw    $a2, 0x20($sp)
/* 00D148 8000C548 2444003C */  addiu $a0, $v0, 0x3c
/* 00D14C 8000C54C 28810079 */  slti  $at, $a0, 0x79
/* 00D150 8000C550 14200002 */  bnez  $at, .L8000C55C
/* 00D154 8000C554 8FA5001C */   lw    $a1, 0x1c($sp)
/* 00D158 8000C558 24040078 */  li    $a0, 120
.L8000C55C:
/* 00D15C 8000C55C 04810002 */  bgez  $a0, .L8000C568
/* 00D160 8000C560 8FB80020 */   lw    $t8, 0x20($sp)
/* 00D164 8000C564 00002025 */  move  $a0, $zero
.L8000C568:
/* 00D168 8000C568 0305C823 */  subu  $t9, $t8, $a1
/* 00D16C 8000C56C 00990019 */  multu $a0, $t9
/* 00D170 8000C570 24010078 */  li    $at, 120
/* 00D174 8000C574 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D178 8000C578 27BD0018 */  addiu $sp, $sp, 0x18
/* 00D17C 8000C57C 00004012 */  mflo  $t0
/* 00D180 8000C580 00000000 */  nop   
/* 00D184 8000C584 00000000 */  nop   
/* 00D188 8000C588 0101001A */  div   $zero, $t0, $at
/* 00D18C 8000C58C 00004812 */  mflo  $t1
/* 00D190 8000C590 01251021 */  addu  $v0, $t1, $a1
/* 00D194 8000C594 03E00008 */  jr    $ra
/* 00D198 8000C598 00000000 */   nop   

controller_7000C59C:
/* 00D19C 8000C59C 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00D1A0 8000C5A0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D1A4 8000C5A4 AFA40018 */  sw    $a0, 0x18($sp)
/* 00D1A8 8000C5A8 00047600 */  sll   $t6, $a0, 0x18
/* 00D1AC 8000C5AC 000E2603 */  sra   $a0, $t6, 0x18
/* 00D1B0 8000C5B0 AFA5001C */  sw    $a1, 0x1c($sp)
/* 00D1B4 8000C5B4 0C00303B */  jal   get_cur_controller_horz_stick_pos
/* 00D1B8 8000C5B8 AFA60020 */   sw    $a2, 0x20($sp)
/* 00D1BC 8000C5BC 2444003C */  addiu $a0, $v0, 0x3c
/* 00D1C0 8000C5C0 28810079 */  slti  $at, $a0, 0x79
/* 00D1C4 8000C5C4 14200002 */  bnez  $at, .L8000C5D0
/* 00D1C8 8000C5C8 C7A2001C */   lwc1  $f2, 0x1c($sp)
/* 00D1CC 8000C5CC 24040078 */  li    $a0, 120
.L8000C5D0:
/* 00D1D0 8000C5D0 04830003 */  bgezl $a0, .L8000C5E0
/* 00D1D4 8000C5D4 44842000 */   mtc1  $a0, $f4
/* 00D1D8 8000C5D8 00002025 */  move  $a0, $zero
/* 00D1DC 8000C5DC 44842000 */  mtc1  $a0, $f4
.L8000C5E0:
/* 00D1E0 8000C5E0 3C0142F0 */  li    $at, 0x42F00000 # 120.000000
/* 00D1E4 8000C5E4 44814000 */  mtc1  $at, $f8
/* 00D1E8 8000C5E8 468021A0 */  cvt.s.w $f6, $f4
/* 00D1EC 8000C5EC C7B00020 */  lwc1  $f16, 0x20($sp)
/* 00D1F0 8000C5F0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D1F4 8000C5F4 27BD0018 */  addiu $sp, $sp, 0x18
/* 00D1F8 8000C5F8 46028481 */  sub.s $f18, $f16, $f2
/* 00D1FC 8000C5FC 46083283 */  div.s $f10, $f6, $f8
/* 00D200 8000C600 46125102 */  mul.s $f4, $f10, $f18
/* 00D204 8000C604 03E00008 */  jr    $ra
/* 00D208 8000C608 46022000 */   add.s $f0, $f4, $f2

controller_7000C60C:
/* 00D20C 8000C60C 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00D210 8000C610 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D214 8000C614 AFA40018 */  sw    $a0, 0x18($sp)
/* 00D218 8000C618 00047600 */  sll   $t6, $a0, 0x18
/* 00D21C 8000C61C 000E2603 */  sra   $a0, $t6, 0x18
/* 00D220 8000C620 AFA5001C */  sw    $a1, 0x1c($sp)
/* 00D224 8000C624 0C00307F */  jal   get_cur_controller_vert_stick_pos
/* 00D228 8000C628 AFA60020 */   sw    $a2, 0x20($sp)
/* 00D22C 8000C62C 2444003C */  addiu $a0, $v0, 0x3c
/* 00D230 8000C630 28810079 */  slti  $at, $a0, 0x79
/* 00D234 8000C634 14200002 */  bnez  $at, .L8000C640
/* 00D238 8000C638 C7A2001C */   lwc1  $f2, 0x1c($sp)
/* 00D23C 8000C63C 24040078 */  li    $a0, 120
.L8000C640:
/* 00D240 8000C640 04830003 */  bgezl $a0, .L8000C650
/* 00D244 8000C644 44842000 */   mtc1  $a0, $f4
/* 00D248 8000C648 00002025 */  move  $a0, $zero
/* 00D24C 8000C64C 44842000 */  mtc1  $a0, $f4
.L8000C650:
/* 00D250 8000C650 3C0142F0 */  li    $at, 0x42F00000 # 120.000000
/* 00D254 8000C654 44814000 */  mtc1  $at, $f8
/* 00D258 8000C658 468021A0 */  cvt.s.w $f6, $f4
/* 00D25C 8000C65C C7B00020 */  lwc1  $f16, 0x20($sp)
/* 00D260 8000C660 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D264 8000C664 27BD0018 */  addiu $sp, $sp, 0x18
/* 00D268 8000C668 46028481 */  sub.s $f18, $f16, $f2
/* 00D26C 8000C66C 46083283 */  div.s $f10, $f6, $f8
/* 00D270 8000C670 46125102 */  mul.s $f4, $f10, $f18
/* 00D274 8000C674 03E00008 */  jr    $ra
/* 00D278 8000C678 46022000 */   add.s $f0, $f4, $f2

controller_7000C67C:
/* 00D27C 8000C67C 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D280 8000C680 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D284 8000C684 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065370) # $a0, 0x8006
/* 00D288 8000C688 24845370 */  addiu $a0, %lo(dword_CODE_bss_80065370) # addiu $a0, $a0, 0x5370
/* 00D28C 8000C68C 27A5001C */  addiu $a1, $sp, 0x1c
/* 00D290 8000C690 0C0037C4 */  jal   osSendMesg
/* 00D294 8000C694 00003025 */   move  $a2, $zero
/* 00D298 8000C698 3C048006 */  lui   $a0, %hi(dword_CODE_bss_80065390) # $a0, 0x8006
/* 00D29C 8000C69C 24845390 */  addiu $a0, %lo(dword_CODE_bss_80065390) # addiu $a0, $a0, 0x5390
/* 00D2A0 8000C6A0 27A5001C */  addiu $a1, $sp, 0x1c
/* 00D2A4 8000C6A4 0C003774 */  jal   osRecvMesg
/* 00D2A8 8000C6A8 24060001 */   li    $a2, 1
/* 00D2AC 8000C6AC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D2B0 8000C6B0 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D2B4 8000C6B4 03E00008 */  jr    $ra
/* 00D2B8 8000C6B8 00000000 */   nop   

controller_7000C6BC:
/* 00D2BC 8000C6BC 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D2C0 8000C6C0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D2C4 8000C6C4 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653B0) # $a0, 0x8006
/* 00D2C8 8000C6C8 248453B0 */  addiu $a0, %lo(dword_CODE_bss_800653B0) # addiu $a0, $a0, 0x53b0
/* 00D2CC 8000C6CC 27A5001C */  addiu $a1, $sp, 0x1c
/* 00D2D0 8000C6D0 0C0037C4 */  jal   osSendMesg
/* 00D2D4 8000C6D4 00003025 */   move  $a2, $zero
/* 00D2D8 8000C6D8 3C048006 */  lui   $a0, %hi(dword_CODE_bss_800653D0) # $a0, 0x8006
/* 00D2DC 8000C6DC 248453D0 */  addiu $a0, %lo(dword_CODE_bss_800653D0) # addiu $a0, $a0, 0x53d0
/* 00D2E0 8000C6E0 27A5001C */  addiu $a1, $sp, 0x1c
/* 00D2E4 8000C6E4 0C003774 */  jal   osRecvMesg
/* 00D2E8 8000C6E8 24060001 */   li    $a2, 1
/* 00D2EC 8000C6EC 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D2F0 8000C6F0 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D2F4 8000C6F4 03E00008 */  jr    $ra
/* 00D2F8 8000C6F8 00000000 */   nop   

save_7000C6FC:
/* 00D2FC 8000C6FC 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D300 8000C700 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D304 8000C704 0C00319F */  jal   controller_7000C67C
/* 00D308 8000C708 00000000 */   nop   
/* 00D30C 8000C70C 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00D310 8000C710 0C0053F4 */  jal   osEepromProbe
/* 00D314 8000C714 24845350 */   addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00D318 8000C718 0C0031AF */  jal   controller_7000C6BC
/* 00D31C 8000C71C AFA2001C */   sw    $v0, 0x1c($sp)
/* 00D320 8000C720 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D324 8000C724 8FA2001C */  lw    $v0, 0x1c($sp)
/* 00D328 8000C728 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D32C 8000C72C 03E00008 */  jr    $ra
/* 00D330 8000C730 00000000 */   nop   

save_7000C734:
/* 00D334 8000C734 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D338 8000C738 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D33C 8000C73C AFA40020 */  sw    $a0, 0x20($sp)
/* 00D340 8000C740 0C00319F */  jal   controller_7000C67C
/* 00D344 8000C744 AFA50024 */   sw    $a1, 0x24($sp)
/* 00D348 8000C748 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00D34C 8000C74C 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00D350 8000C750 93A50023 */  lbu   $a1, 0x23($sp)
/* 00D354 8000C754 0C005410 */  jal   osEepromRead
/* 00D358 8000C758 8FA60024 */   lw    $a2, 0x24($sp)
/* 00D35C 8000C75C 0C0031AF */  jal   controller_7000C6BC
/* 00D360 8000C760 AFA2001C */   sw    $v0, 0x1c($sp)
/* 00D364 8000C764 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D368 8000C768 8FA2001C */  lw    $v0, 0x1c($sp)
/* 00D36C 8000C76C 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D370 8000C770 03E00008 */  jr    $ra
/* 00D374 8000C774 00000000 */   nop   

save_7000C778:
/* 00D378 8000C778 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D37C 8000C77C AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D380 8000C780 AFA40020 */  sw    $a0, 0x20($sp)
/* 00D384 8000C784 0C00319F */  jal   controller_7000C67C
/* 00D388 8000C788 AFA50024 */   sw    $a1, 0x24($sp)
/* 00D38C 8000C78C 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00D390 8000C790 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00D394 8000C794 93A50023 */  lbu   $a1, 0x23($sp)
/* 00D398 8000C798 0C0054D0 */  jal   osEepromWrite
/* 00D39C 8000C79C 8FA60024 */   lw    $a2, 0x24($sp)
/* 00D3A0 8000C7A0 0C0031AF */  jal   controller_7000C6BC
/* 00D3A4 8000C7A4 AFA2001C */   sw    $v0, 0x1c($sp)
/* 00D3A8 8000C7A8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D3AC 8000C7AC 8FA2001C */  lw    $v0, 0x1c($sp)
/* 00D3B0 8000C7B0 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D3B4 8000C7B4 03E00008 */  jr    $ra
/* 00D3B8 8000C7B8 00000000 */   nop   

save_7000C7BC:
/* 00D3BC 8000C7BC 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D3C0 8000C7C0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D3C4 8000C7C4 AFA40020 */  sw    $a0, 0x20($sp)
/* 00D3C8 8000C7C8 AFA50024 */  sw    $a1, 0x24($sp)
/* 00D3CC 8000C7CC 0C00319F */  jal   controller_7000C67C
/* 00D3D0 8000C7D0 AFA60028 */   sw    $a2, 0x28($sp)
/* 00D3D4 8000C7D4 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00D3D8 8000C7D8 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00D3DC 8000C7DC 93A50023 */  lbu   $a1, 0x23($sp)
/* 00D3E0 8000C7E0 8FA60024 */  lw    $a2, 0x24($sp)
/* 00D3E4 8000C7E4 0C005608 */  jal   osEepromLongRead
/* 00D3E8 8000C7E8 8FA70028 */   lw    $a3, 0x28($sp)
/* 00D3EC 8000C7EC 0C0031AF */  jal   controller_7000C6BC
/* 00D3F0 8000C7F0 AFA2001C */   sw    $v0, 0x1c($sp)
/* 00D3F4 8000C7F4 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D3F8 8000C7F8 8FA2001C */  lw    $v0, 0x1c($sp)
/* 00D3FC 8000C7FC 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D400 8000C800 03E00008 */  jr    $ra
/* 00D404 8000C804 00000000 */   nop   

save_7000C808:
/* 00D408 8000C808 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00D40C 8000C80C AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D410 8000C810 AFA40020 */  sw    $a0, 0x20($sp)
/* 00D414 8000C814 AFA50024 */  sw    $a1, 0x24($sp)
/* 00D418 8000C818 0C00319F */  jal   controller_7000C67C
/* 00D41C 8000C81C AFA60028 */   sw    $a2, 0x28($sp)
/* 00D420 8000C820 3C048006 */  lui   $a0, %hi(interrupt5_thread_list_buf) # $a0, 0x8006
/* 00D424 8000C824 24845350 */  addiu $a0, %lo(interrupt5_thread_list_buf) # addiu $a0, $a0, 0x5350
/* 00D428 8000C828 93A50023 */  lbu   $a1, 0x23($sp)
/* 00D42C 8000C82C 8FA60024 */  lw    $a2, 0x24($sp)
/* 00D430 8000C830 0C005658 */  jal   osEepromLongWrite
/* 00D434 8000C834 8FA70028 */   lw    $a3, 0x28($sp)
/* 00D438 8000C838 0C0031AF */  jal   controller_7000C6BC
/* 00D43C 8000C83C AFA2001C */   sw    $v0, 0x1c($sp)
/* 00D440 8000C840 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D444 8000C844 8FA2001C */  lw    $v0, 0x1c($sp)
/* 00D448 8000C848 27BD0020 */  addiu $sp, $sp, 0x20
/* 00D44C 8000C84C 03E00008 */  jr    $ra
/* 00D450 8000C850 00000000 */   nop   

controller_7000C854:
/* 00D454 8000C854 3C0E8002 */  lui   $t6, %hi(disable_all_rumble) # $t6, 0x8002
/* 00D458 8000C858 8DCE6924 */  lw    $t6, %lo(disable_all_rumble)($t6)
/* 00D45C 8000C85C 44856000 */  mtc1  $a1, $f12
/* 00D460 8000C860 00041880 */  sll   $v1, $a0, 2
/* 00D464 8000C864 15C0001B */  bnez  $t6, .L8000C8D4
/* 00D468 8000C868 3C0F8002 */   lui   $t7, 0x8002
/* 00D46C 8000C86C 01E37821 */  addu  $t7, $t7, $v1
/* 00D470 8000C870 8DEF68D8 */  lw    $t7, 0x68d8($t7)
/* 00D474 8000C874 3C098002 */  lui   $t1, 0x8002
/* 00D478 8000C878 3C014270 */  li    $at, 0x42700000 # 60.000000
/* 00D47C 8000C87C 19E00015 */  blez  $t7, .L8000C8D4
/* 00D480 8000C880 01234821 */   addu  $t1, $t1, $v1
/* 00D484 8000C884 44812000 */  mtc1  $at, $f4
/* 00D488 8000C888 3C188002 */  lui   $t8, %hi(controller_1_rumble_duration) # $t8, 0x8002
/* 00D48C 8000C88C 271868F8 */  addiu $t8, %lo(controller_1_rumble_duration) # addiu $t8, $t8, 0x68f8
/* 00D490 8000C890 46046182 */  mul.s $f6, $f12, $f4
/* 00D494 8000C894 00782021 */  addu  $a0, $v1, $t8
/* 00D498 8000C898 8C880000 */  lw    $t0, ($a0)
/* 00D49C 8000C89C 240A0001 */  li    $t2, 1
/* 00D4A0 8000C8A0 4600320D */  trunc.w.s $f8, $f6
/* 00D4A4 8000C8A4 44024000 */  mfc1  $v0, $f8
/* 00D4A8 8000C8A8 00000000 */  nop   
/* 00D4AC 8000C8AC 0102082A */  slt   $at, $t0, $v0
/* 00D4B0 8000C8B0 10200002 */  beqz  $at, .L8000C8BC
/* 00D4B4 8000C8B4 00000000 */   nop   
/* 00D4B8 8000C8B8 AC820000 */  sw    $v0, ($a0)
.L8000C8BC:
/* 00D4BC 8000C8BC 8D2968E8 */  lw    $t1, 0x68e8($t1)
/* 00D4C0 8000C8C0 3C018002 */  lui   $at, 0x8002
/* 00D4C4 8000C8C4 00230821 */  addu  $at, $at, $v1
/* 00D4C8 8000C8C8 15200002 */  bnez  $t1, .L8000C8D4
/* 00D4CC 8000C8CC 00000000 */   nop   
/* 00D4D0 8000C8D0 AC2A6908 */  sw    $t2, 0x6908($at)
.L8000C8D4:
/* 00D4D4 8000C8D4 03E00008 */  jr    $ra
/* 00D4D8 8000C8D8 00000000 */   nop   

reset_cont_rumble_detect:
/* 00D4DC 8000C8DC 240E0001 */  li    $t6, 1
/* 00D4E0 8000C8E0 3C018002 */  lui   $at, %hi(controller_1_rumble_state) # $at, 0x8002
/* 00D4E4 8000C8E4 AC2E68E8 */  sw    $t6, %lo(controller_1_rumble_state)($at)
/* 00D4E8 8000C8E8 3C018002 */  lui   $at, %hi(controller_1_rumble_pulse) # $at, 0x8002
/* 00D4EC 8000C8EC AC206908 */  sw    $zero, %lo(controller_1_rumble_pulse)($at)
/* 00D4F0 8000C8F0 3C018002 */  lui   $at, %hi(controller_2_rumble_state) # $at, 0x8002
/* 00D4F4 8000C8F4 240F0001 */  li    $t7, 1
/* 00D4F8 8000C8F8 AC2F68EC */  sw    $t7, %lo(controller_2_rumble_state)($at)
/* 00D4FC 8000C8FC 3C018002 */  lui   $at, %hi(controller_2_rumble_pulse) # $at, 0x8002
/* 00D500 8000C900 AC20690C */  sw    $zero, %lo(controller_2_rumble_pulse)($at)
/* 00D504 8000C904 3C018002 */  lui   $at, %hi(controller_3_rumble_state) # $at, 0x8002
/* 00D508 8000C908 24180001 */  li    $t8, 1
/* 00D50C 8000C90C AC3868F0 */  sw    $t8, %lo(controller_3_rumble_state)($at)
/* 00D510 8000C910 3C018002 */  lui   $at, %hi(controller_3_rumble_pulse) # $at, 0x8002
/* 00D514 8000C914 AC206910 */  sw    $zero, %lo(controller_3_rumble_pulse)($at)
/* 00D518 8000C918 3C018002 */  lui   $at, %hi(controller_4_rumble_state) # $at, 0x8002
/* 00D51C 8000C91C 24190001 */  li    $t9, 1
/* 00D520 8000C920 AC3968F4 */  sw    $t9, %lo(controller_4_rumble_state)($at)
/* 00D524 8000C924 3C018002 */  lui   $at, 0x8002
/* 00D528 8000C928 03E00008 */  jr    $ra
/* 00D52C 8000C92C AC206914 */   sw    $zero, 0x6914($at)

controller_7000C930:
/* 00D530 8000C930 000471C0 */  sll   $t6, $a0, 7
/* 00D534 8000C934 01C47023 */  subu  $t6, $t6, $a0
/* 00D538 8000C938 3C0F8006 */  lui   $t7, %hi(controller_input_index) # $t7, 0x8006
/* 00D53C 8000C93C 25EF4F30 */  addiu $t7, %lo(controller_input_index) # addiu $t7, $t7, 0x4f30
/* 00D540 8000C940 000E7080 */  sll   $t6, $t6, 2
/* 00D544 8000C944 01CFC021 */  addu  $t8, $t6, $t7
/* 00D548 8000C948 3C018002 */  lui   $at, 0x8002
/* 00D54C 8000C94C 03E00008 */  jr    $ra
/* 00D550 8000C950 AC3868C4 */   sw    $t8, 0x68c4($at)

controller_7000C954:
/* 00D554 8000C954 3C0E8002 */  lui   $t6, %hi(ptr_current_point_in_controller_input_index) # $t6, 0x8002
/* 00D558 8000C958 8DCE68C4 */  lw    $t6, %lo(ptr_current_point_in_controller_input_index)($t6)
/* 00D55C 8000C95C 3C0F8006 */  lui   $t7, %hi(controller_input_index) # $t7, 0x8006
/* 00D560 8000C960 25EF4F30 */  addiu $t7, %lo(controller_input_index) # addiu $t7, $t7, 0x4f30
/* 00D564 8000C964 240101FC */  li    $at, 508
/* 00D568 8000C968 01CF1023 */  subu  $v0, $t6, $t7
/* 00D56C 8000C96C 0041001A */  div   $zero, $v0, $at
/* 00D570 8000C970 00001012 */  mflo  $v0
/* 00D574 8000C974 03E00008 */  jr    $ra
/* 00D578 8000C978 00000000 */   nop   

/* 00D57C 8000C97C 00000000 */  nop   

