# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel _is_normal_single_precision_float
/* 006160 70005560 E7AC0000 */  swc1  $f12, ($sp)
/* 006164 70005564 8FA40000 */  lw    $a0, ($sp)
/* 006168 70005568 3C01007F */  lui   $at, (0x007FFFFF >> 16) # lui $at, 0x7f
/* 00616C 7000556C 3421FFFF */  ori   $at, (0x007FFFFF & 0xFFFF) # ori $at, $at, 0xffff
/* 006170 70005570 00811024 */  and   $v0, $a0, $at
/* 006174 70005574 2C4E0001 */  sltiu $t6, $v0, 1
/* 006178 70005578 15C00008 */  bnez  $t6, .L7000559C
/* 00617C 7000557C 01C01025 */   move  $v0, $t6
/* 006180 70005580 00041DC2 */  srl   $v1, $a0, 0x17
/* 006184 70005584 306F00FF */  andi  $t7, $v1, 0xff
/* 006188 70005588 000F102B */  sltu  $v0, $zero, $t7
/* 00618C 7000558C 10400003 */  beqz  $v0, .L7000559C
/* 006190 70005590 00000000 */   nop   
/* 006194 70005594 39E200FF */  xori  $v0, $t7, 0xff
/* 006198 70005598 0002102B */  sltu  $v0, $zero, $v0
.L7000559C:
/* 00619C 7000559C 03E00008 */  jr    $ra
/* 0061A0 700055A0 00000000 */   nop   

glabel is_normal_single_precision_float
/* 0061A4 700055A4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0061A8 700055A8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0061AC 700055AC 44856000 */  mtc1  $a1, $f12
/* 0061B0 700055B0 0C001558 */  jal   _is_normal_single_precision_float
/* 0061B4 700055B4 AFA40018 */   sw    $a0, 0x18($sp)
/* 0061B8 700055B8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 0061BC 700055BC 27BD0018 */  addiu $sp, $sp, 0x18
/* 0061C0 700055C0 03E00008 */  jr    $ra
/* 0061C4 700055C4 00000000 */   nop   

glabel set_normality_of_single_precision_floats
/* 0061C8 700055C8 44856000 */  mtc1  $a1, $f12
/* 0061CC 700055CC 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 0061D0 700055D0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 0061D4 700055D4 44056000 */  mfc1  $a1, $f12
/* 0061D8 700055D8 AFA40018 */  sw    $a0, 0x18($sp)
/* 0061DC 700055DC AFA60020 */  sw    $a2, 0x20($sp)
/* 0061E0 700055E0 0C001569 */  jal   is_normal_single_precision_float
/* 0061E4 700055E4 AFA70024 */   sw    $a3, 0x24($sp)
/* 0061E8 700055E8 8FA40018 */  lw    $a0, 0x18($sp)
/* 0061EC 700055EC 8FA50020 */  lw    $a1, 0x20($sp)
/* 0061F0 700055F0 0C001569 */  jal   is_normal_single_precision_float
/* 0061F4 700055F4 24840002 */   addiu $a0, $a0, 2
/* 0061F8 700055F8 8FA40018 */  lw    $a0, 0x18($sp)
/* 0061FC 700055FC 8FA50024 */  lw    $a1, 0x24($sp)
/* 006200 70005600 0C001569 */  jal   is_normal_single_precision_float
/* 006204 70005604 24840004 */   addiu $a0, $a0, 4
/* 006208 70005608 8FA40018 */  lw    $a0, 0x18($sp)
/* 00620C 7000560C 8FA50028 */  lw    $a1, 0x28($sp)
/* 006210 70005610 0C001569 */  jal   is_normal_single_precision_float
/* 006214 70005614 24840006 */   addiu $a0, $a0, 6
/* 006218 70005618 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00621C 7000561C 27BD0018 */  addiu $sp, $sp, 0x18
/* 006220 70005620 03E00008 */  jr    $ra
/* 006224 70005624 00000000 */   nop   

/* 006228 70005628 03E00008 */  jr    $ra
/* 00622C 7000562C 00000000 */   nop   


