# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

send_rumble_off_to_PIF:
/* 00D580 8000C980 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 00D584 8000C984 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D588 8000C988 0C005798 */  jal   __osSiGetAccess
/* 00D58C 8000C98C AFA40050 */   sw    $a0, 0x50($sp)
/* 00D590 8000C990 8FAF0050 */  lw    $t7, 0x50($sp)
/* 00D594 8000C994 240E0003 */  li    $t6, 3
/* 00D598 8000C998 3C018006 */  lui   $at, %hi(__osContLastCmd) # $at, 0x8006
/* 00D59C 8000C99C A02E7CE0 */  sb    $t6, %lo(__osContLastCmd)($at)
/* 00D5A0 8000C9A0 8DF80008 */  lw    $t8, 8($t7)
/* 00D5A4 8000C9A4 3C088006 */  lui   $t0, %hi(rumble_off_player1_packet_buffer) # $t0, 0x8006
/* 00D5A8 8000C9A8 250855A0 */  addiu $t0, %lo(rumble_off_player1_packet_buffer) # addiu $t0, $t0, 0x55a0
/* 00D5AC 8000C9AC 0018C980 */  sll   $t9, $t8, 6
/* 00D5B0 8000C9B0 03282821 */  addu  $a1, $t9, $t0
/* 00D5B4 8000C9B4 0C0057B4 */  jal   __osSiRawStartDma
/* 00D5B8 8000C9B8 24040001 */   li    $a0, 1
/* 00D5BC 8000C9BC 8FA90050 */  lw    $t1, 0x50($sp)
/* 00D5C0 8000C9C0 00002825 */  move  $a1, $zero
/* 00D5C4 8000C9C4 24060001 */  li    $a2, 1
/* 00D5C8 8000C9C8 0C003774 */  jal   osRecvMesg
/* 00D5CC 8000C9CC 8D240004 */   lw    $a0, 4($t1)
/* 00D5D0 8000C9D0 3C058006 */  lui   $a1, %hi(__osPfsPifRam) # $a1, 0x8006
/* 00D5D4 8000C9D4 24A57D70 */  addiu $a1, %lo(__osPfsPifRam) # addiu $a1, $a1, 0x7d70
/* 00D5D8 8000C9D8 0C0057B4 */  jal   __osSiRawStartDma
/* 00D5DC 8000C9DC 00002025 */   move  $a0, $zero
/* 00D5E0 8000C9E0 8FAA0050 */  lw    $t2, 0x50($sp)
/* 00D5E4 8000C9E4 00002825 */  move  $a1, $zero
/* 00D5E8 8000C9E8 24060001 */  li    $a2, 1
/* 00D5EC 8000C9EC 0C003774 */  jal   osRecvMesg
/* 00D5F0 8000C9F0 8D440004 */   lw    $a0, 4($t2)
/* 00D5F4 8000C9F4 8FAB0050 */  lw    $t3, 0x50($sp)
/* 00D5F8 8000C9F8 3C038006 */  lui   $v1, %hi(__osPfsPifRam) # $v1, 0x8006
/* 00D5FC 8000C9FC 24637D70 */  addiu $v1, %lo(__osPfsPifRam) # addiu $v1, $v1, 0x7d70
/* 00D600 8000CA00 8D640008 */  lw    $a0, 8($t3)
/* 00D604 8000CA04 27AC001C */  addiu $t4, $sp, 0x1c
/* 00D608 8000CA08 50800008 */  beql  $a0, $zero, .L8000CA2C
/* 00D60C 8000CA0C 00607825 */   move  $t7, $v1
/* 00D610 8000CA10 18800005 */  blez  $a0, .L8000CA28
/* 00D614 8000CA14 00001025 */   move  $v0, $zero
.L8000CA18:
/* 00D618 8000CA18 24420001 */  addiu $v0, $v0, 1
/* 00D61C 8000CA1C 0044082A */  slt   $at, $v0, $a0
/* 00D620 8000CA20 1420FFFD */  bnez  $at, .L8000CA18
/* 00D624 8000CA24 24630001 */   addiu $v1, $v1, 1
.L8000CA28:
/* 00D628 8000CA28 00607825 */  move  $t7, $v1
.L8000CA2C:
/* 00D62C 8000CA2C 246E0024 */  addiu $t6, $v1, 0x24
.L8000CA30:
/* 00D630 8000CA30 89E10000 */  lwl   $at, ($t7)
/* 00D634 8000CA34 99E10003 */  lwr   $at, 3($t7)
/* 00D638 8000CA38 25EF000C */  addiu $t7, $t7, 0xc
/* 00D63C 8000CA3C 258C000C */  addiu $t4, $t4, 0xc
/* 00D640 8000CA40 AD81FFF4 */  sw    $at, -0xc($t4)
/* 00D644 8000CA44 89E1FFF8 */  lwl   $at, -8($t7)
/* 00D648 8000CA48 99E1FFFB */  lwr   $at, -5($t7)
/* 00D64C 8000CA4C AD81FFF8 */  sw    $at, -8($t4)
/* 00D650 8000CA50 89E1FFFC */  lwl   $at, -4($t7)
/* 00D654 8000CA54 99E1FFFF */  lwr   $at, -1($t7)
/* 00D658 8000CA58 15EEFFF5 */  bne   $t7, $t6, .L8000CA30
/* 00D65C 8000CA5C AD81FFFC */   sw    $at, -4($t4)
/* 00D660 8000CA60 89E10000 */  lwl   $at, ($t7)
/* 00D664 8000CA64 99E10003 */  lwr   $at, 3($t7)
/* 00D668 8000CA68 AD810000 */  sw    $at, ($t4)
/* 00D66C 8000CA6C 93A2001E */  lbu   $v0, 0x1e($sp)
/* 00D670 8000CA70 93A80042 */  lbu   $t0, 0x42($sp)
/* 00D674 8000CA74 305800C0 */  andi  $t8, $v0, 0xc0
/* 00D678 8000CA78 00182103 */  sra   $a0, $t8, 4
/* 00D67C 8000CA7C 14800004 */  bnez  $a0, .L8000CA90
/* 00D680 8000CA80 00000000 */   nop   
/* 00D684 8000CA84 11000002 */  beqz  $t0, .L8000CA90
/* 00D688 8000CA88 00000000 */   nop   
/* 00D68C 8000CA8C 24040004 */  li    $a0, 4
.L8000CA90:
/* 00D690 8000CA90 0C0057A9 */  jal   __osSiRelAccess
/* 00D694 8000CA94 AFA40048 */   sw    $a0, 0x48($sp)
/* 00D698 8000CA98 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D69C 8000CA9C 8FA20048 */  lw    $v0, 0x48($sp)
/* 00D6A0 8000CAA0 27BD0050 */  addiu $sp, $sp, 0x50
/* 00D6A4 8000CAA4 03E00008 */  jr    $ra
/* 00D6A8 8000CAA8 00000000 */   nop   

controller_7000CAAC:
/* 00D6AC 8000CAAC 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 00D6B0 8000CAB0 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00D6B4 8000CAB4 0C005798 */  jal   __osSiGetAccess
/* 00D6B8 8000CAB8 AFA40050 */   sw    $a0, 0x50($sp)
/* 00D6BC 8000CABC 8FAF0050 */  lw    $t7, 0x50($sp)
/* 00D6C0 8000CAC0 240E0003 */  li    $t6, 3
/* 00D6C4 8000CAC4 3C018006 */  lui   $at, %hi(__osContLastCmd) # $at, 0x8006
/* 00D6C8 8000CAC8 A02E7CE0 */  sb    $t6, %lo(__osContLastCmd)($at)
/* 00D6CC 8000CACC 8DF80008 */  lw    $t8, 8($t7)
/* 00D6D0 8000CAD0 3C088006 */  lui   $t0, %hi(rumble_on_player_packet_buffers) # $t0, 0x8006
/* 00D6D4 8000CAD4 250856A0 */  addiu $t0, %lo(rumble_on_player_packet_buffers) # addiu $t0, $t0, 0x56a0
/* 00D6D8 8000CAD8 0018C980 */  sll   $t9, $t8, 6
/* 00D6DC 8000CADC 03282821 */  addu  $a1, $t9, $t0
/* 00D6E0 8000CAE0 0C0057B4 */  jal   __osSiRawStartDma
/* 00D6E4 8000CAE4 24040001 */   li    $a0, 1
/* 00D6E8 8000CAE8 8FA90050 */  lw    $t1, 0x50($sp)
/* 00D6EC 8000CAEC 00002825 */  move  $a1, $zero
/* 00D6F0 8000CAF0 24060001 */  li    $a2, 1
/* 00D6F4 8000CAF4 0C003774 */  jal   osRecvMesg
/* 00D6F8 8000CAF8 8D240004 */   lw    $a0, 4($t1)
/* 00D6FC 8000CAFC 3C058006 */  lui   $a1, %hi(__osPfsPifRam) # $a1, 0x8006
/* 00D700 8000CB00 24A57D70 */  addiu $a1, %lo(__osPfsPifRam) # addiu $a1, $a1, 0x7d70
/* 00D704 8000CB04 0C0057B4 */  jal   __osSiRawStartDma
/* 00D708 8000CB08 00002025 */   move  $a0, $zero
/* 00D70C 8000CB0C 8FAA0050 */  lw    $t2, 0x50($sp)
/* 00D710 8000CB10 00002825 */  move  $a1, $zero
/* 00D714 8000CB14 24060001 */  li    $a2, 1
/* 00D718 8000CB18 0C003774 */  jal   osRecvMesg
/* 00D71C 8000CB1C 8D440004 */   lw    $a0, 4($t2)
/* 00D720 8000CB20 8FAB0050 */  lw    $t3, 0x50($sp)
/* 00D724 8000CB24 3C038006 */  lui   $v1, %hi(__osPfsPifRam) # $v1, 0x8006
/* 00D728 8000CB28 24637D70 */  addiu $v1, %lo(__osPfsPifRam) # addiu $v1, $v1, 0x7d70
/* 00D72C 8000CB2C 8D640008 */  lw    $a0, 8($t3)
/* 00D730 8000CB30 27AC001C */  addiu $t4, $sp, 0x1c
/* 00D734 8000CB34 50800008 */  beql  $a0, $zero, .L8000CB58
/* 00D738 8000CB38 00607825 */   move  $t7, $v1
/* 00D73C 8000CB3C 18800005 */  blez  $a0, .L8000CB54
/* 00D740 8000CB40 00001025 */   move  $v0, $zero
.L8000CB44:
/* 00D744 8000CB44 24420001 */  addiu $v0, $v0, 1
/* 00D748 8000CB48 0044082A */  slt   $at, $v0, $a0
/* 00D74C 8000CB4C 1420FFFD */  bnez  $at, .L8000CB44
/* 00D750 8000CB50 24630001 */   addiu $v1, $v1, 1
.L8000CB54:
/* 00D754 8000CB54 00607825 */  move  $t7, $v1
.L8000CB58:
/* 00D758 8000CB58 246E0024 */  addiu $t6, $v1, 0x24
.L8000CB5C:
/* 00D75C 8000CB5C 89E10000 */  lwl   $at, ($t7)
/* 00D760 8000CB60 99E10003 */  lwr   $at, 3($t7)
/* 00D764 8000CB64 25EF000C */  addiu $t7, $t7, 0xc
/* 00D768 8000CB68 258C000C */  addiu $t4, $t4, 0xc
/* 00D76C 8000CB6C AD81FFF4 */  sw    $at, -0xc($t4)
/* 00D770 8000CB70 89E1FFF8 */  lwl   $at, -8($t7)
/* 00D774 8000CB74 99E1FFFB */  lwr   $at, -5($t7)
/* 00D778 8000CB78 AD81FFF8 */  sw    $at, -8($t4)
/* 00D77C 8000CB7C 89E1FFFC */  lwl   $at, -4($t7)
/* 00D780 8000CB80 99E1FFFF */  lwr   $at, -1($t7)
/* 00D784 8000CB84 15EEFFF5 */  bne   $t7, $t6, .L8000CB5C
/* 00D788 8000CB88 AD81FFFC */   sw    $at, -4($t4)
/* 00D78C 8000CB8C 89E10000 */  lwl   $at, ($t7)
/* 00D790 8000CB90 99E10003 */  lwr   $at, 3($t7)
/* 00D794 8000CB94 AD810000 */  sw    $at, ($t4)
/* 00D798 8000CB98 93A2001E */  lbu   $v0, 0x1e($sp)
/* 00D79C 8000CB9C 93A80042 */  lbu   $t0, 0x42($sp)
/* 00D7A0 8000CBA0 240100EB */  li    $at, 235
/* 00D7A4 8000CBA4 305800C0 */  andi  $t8, $v0, 0xc0
/* 00D7A8 8000CBA8 00182103 */  sra   $a0, $t8, 4
/* 00D7AC 8000CBAC 14800004 */  bnez  $a0, .L8000CBC0
/* 00D7B0 8000CBB0 00000000 */   nop   
/* 00D7B4 8000CBB4 11010002 */  beq   $t0, $at, .L8000CBC0
/* 00D7B8 8000CBB8 00000000 */   nop   
/* 00D7BC 8000CBBC 24040004 */  li    $a0, 4
.L8000CBC0:
/* 00D7C0 8000CBC0 0C0057A9 */  jal   __osSiRelAccess
/* 00D7C4 8000CBC4 AFA40048 */   sw    $a0, 0x48($sp)
/* 00D7C8 8000CBC8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00D7CC 8000CBCC 8FA20048 */  lw    $v0, 0x48($sp)
/* 00D7D0 8000CBD0 27BD0050 */  addiu $sp, $sp, 0x50
/* 00D7D4 8000CBD4 03E00008 */  jr    $ra
/* 00D7D8 8000CBD8 00000000 */   nop   

controller_7000CBDC:
/* 00D7DC 8000CBDC 27BDFFA8 */  addiu $sp, $sp, -0x58
/* 00D7E0 8000CBE0 AFB00018 */  sw    $s0, 0x18($sp)
/* 00D7E4 8000CBE4 00808025 */  move  $s0, $a0
/* 00D7E8 8000CBE8 AFBF001C */  sw    $ra, 0x1c($sp)
/* 00D7EC 8000CBEC AFA5005C */  sw    $a1, 0x5c($sp)
/* 00D7F0 8000CBF0 00E01825 */  move  $v1, $a3
/* 00D7F4 8000CBF4 00004025 */  move  $t0, $zero
/* 00D7F8 8000CBF8 00E01025 */  move  $v0, $a3
.L8000CBFC:
/* 00D7FC 8000CBFC 25080001 */  addiu $t0, $t0, 1
/* 00D800 8000CC00 2901000F */  slti  $at, $t0, 0xf
/* 00D804 8000CC04 24420004 */  addiu $v0, $v0, 4
/* 00D808 8000CC08 1420FFFC */  bnez  $at, .L8000CBFC
/* 00D80C 8000CC0C AC40FFFC */   sw    $zero, -4($v0)
/* 00D810 8000CC10 240E0001 */  li    $t6, 1
/* 00D814 8000CC14 ACEE003C */  sw    $t6, 0x3c($a3)
/* 00D818 8000CC18 240F00FF */  li    $t7, 255
/* 00D81C 8000CC1C 24180023 */  li    $t8, 35
/* 00D820 8000CC20 24190001 */  li    $t9, 1
/* 00D824 8000CC24 24090003 */  li    $t1, 3
/* 00D828 8000CC28 A3AF002C */  sb    $t7, 0x2c($sp)
/* 00D82C 8000CC2C A3B8002D */  sb    $t8, 0x2d($sp)
/* 00D830 8000CC30 A3B9002E */  sb    $t9, 0x2e($sp)
/* 00D834 8000CC34 A3A9002F */  sb    $t1, 0x2f($sp)
/* 00D838 8000CC38 AFA60060 */  sw    $a2, 0x60($sp)
/* 00D83C 8000CC3C AFA30054 */  sw    $v1, 0x54($sp)
/* 00D840 8000CC40 0C0057E0 */  jal   __osContAddressCrc
/* 00D844 8000CC44 97A4005E */   lhu   $a0, 0x5e($sp)
/* 00D848 8000CC48 97AA005E */  lhu   $t2, 0x5e($sp)
/* 00D84C 8000CC4C 240D00FF */  li    $t5, 255
/* 00D850 8000CC50 8FA30054 */  lw    $v1, 0x54($sp)
/* 00D854 8000CC54 000A5940 */  sll   $t3, $t2, 5
/* 00D858 8000CC58 004B6025 */  or    $t4, $v0, $t3
/* 00D85C 8000CC5C A7AC0030 */  sh    $t4, 0x30($sp)
/* 00D860 8000CC60 8FA60060 */  lw    $a2, 0x60($sp)
/* 00D864 8000CC64 A3AD0052 */  sb    $t5, 0x52($sp)
/* 00D868 8000CC68 27A2004C */  addiu $v0, $sp, 0x4c
/* 00D86C 8000CC6C 27A4002C */  addiu $a0, $sp, 0x2c
.L8000CC70:
/* 00D870 8000CC70 90CE0000 */  lbu   $t6, ($a2)
/* 00D874 8000CC74 24840001 */  addiu $a0, $a0, 1
/* 00D878 8000CC78 0082082B */  sltu  $at, $a0, $v0
/* 00D87C 8000CC7C 24C60001 */  addiu $a2, $a2, 1
/* 00D880 8000CC80 1420FFFB */  bnez  $at, .L8000CC70
/* 00D884 8000CC84 A08E0005 */   sb    $t6, 5($a0)
/* 00D888 8000CC88 12000012 */  beqz  $s0, .L8000CCD4
/* 00D88C 8000CC8C 27AF002C */   addiu $t7, $sp, 0x2c
/* 00D890 8000CC90 1A000010 */  blez  $s0, .L8000CCD4
/* 00D894 8000CC94 00004025 */   move  $t0, $zero
/* 00D898 8000CC98 32040003 */  andi  $a0, $s0, 3
/* 00D89C 8000CC9C 10800006 */  beqz  $a0, .L8000CCB8
/* 00D8A0 8000CCA0 00801025 */   move  $v0, $a0
.L8000CCA4:
/* 00D8A4 8000CCA4 25080001 */  addiu $t0, $t0, 1
/* 00D8A8 8000CCA8 A0600000 */  sb    $zero, ($v1)
/* 00D8AC 8000CCAC 1448FFFD */  bne   $v0, $t0, .L8000CCA4
/* 00D8B0 8000CCB0 24630001 */   addiu $v1, $v1, 1
/* 00D8B4 8000CCB4 11100007 */  beq   $t0, $s0, .L8000CCD4
.L8000CCB8:
/* 00D8B8 8000CCB8 25080004 */   addiu $t0, $t0, 4
/* 00D8BC 8000CCBC A0600001 */  sb    $zero, 1($v1)
/* 00D8C0 8000CCC0 A0600002 */  sb    $zero, 2($v1)
/* 00D8C4 8000CCC4 A0600003 */  sb    $zero, 3($v1)
/* 00D8C8 8000CCC8 24630004 */  addiu $v1, $v1, 4
/* 00D8CC 8000CCCC 1510FFFA */  bne   $t0, $s0, .L8000CCB8
/* 00D8D0 8000CCD0 A060FFFC */   sb    $zero, -4($v1)
.L8000CCD4:
/* 00D8D4 8000CCD4 00604825 */  move  $t1, $v1
/* 00D8D8 8000CCD8 25F90024 */  addiu $t9, $t7, 0x24
.L8000CCDC:
/* 00D8DC 8000CCDC 8DE10000 */  lw    $at, ($t7)
/* 00D8E0 8000CCE0 25EF000C */  addiu $t7, $t7, 0xc
/* 00D8E4 8000CCE4 2529000C */  addiu $t1, $t1, 0xc
/* 00D8E8 8000CCE8 A921FFF4 */  swl   $at, -0xc($t1)
/* 00D8EC 8000CCEC B921FFF7 */  swr   $at, -9($t1)
/* 00D8F0 8000CCF0 8DE1FFF8 */  lw    $at, -8($t7)
/* 00D8F4 8000CCF4 A921FFF8 */  swl   $at, -8($t1)
/* 00D8F8 8000CCF8 B921FFFB */  swr   $at, -5($t1)
/* 00D8FC 8000CCFC 8DE1FFFC */  lw    $at, -4($t7)
/* 00D900 8000CD00 A921FFFC */  swl   $at, -4($t1)
/* 00D904 8000CD04 15F9FFF5 */  bne   $t7, $t9, .L8000CCDC
/* 00D908 8000CD08 B921FFFF */   swr   $at, -1($t1)
/* 00D90C 8000CD0C 8DE10000 */  lw    $at, ($t7)
/* 00D910 8000CD10 240A00FE */  li    $t2, 254
/* 00D914 8000CD14 24630028 */  addiu $v1, $v1, 0x28
/* 00D918 8000CD18 A9210000 */  swl   $at, ($t1)
/* 00D91C 8000CD1C B9210003 */  swr   $at, 3($t1)
/* 00D920 8000CD20 A06A0000 */  sb    $t2, ($v1)
/* 00D924 8000CD24 8FBF001C */  lw    $ra, 0x1c($sp)
/* 00D928 8000CD28 8FB00018 */  lw    $s0, 0x18($sp)
/* 00D92C 8000CD2C 27BD0058 */  addiu $sp, $sp, 0x58
/* 00D930 8000CD30 03E00008 */  jr    $ra
/* 00D934 8000CD34 00000000 */   nop   

controller_7000CD38:
/* 00D938 8000CD38 27BDFFA8 */  addiu $sp, $sp, -0x58
/* 00D93C 8000CD3C AFB00020 */  sw    $s0, 0x20($sp)
/* 00D940 8000CD40 AFBF0024 */  sw    $ra, 0x24($sp)
/* 00D944 8000CD44 24070080 */  li    $a3, 128
/* 00D948 8000CD48 00C08025 */  move  $s0, $a2
/* 00D94C 8000CD4C ACA40004 */  sw    $a0, 4($a1)
/* 00D950 8000CD50 ACA60008 */  sw    $a2, 8($a1)
/* 00D954 8000CD54 ACA00000 */  sw    $zero, ($a1)
/* 00D958 8000CD58 A0A70065 */  sb    $a3, 0x65($a1)
/* 00D95C 8000CD5C 27A20030 */  addiu $v0, $sp, 0x30
/* 00D960 8000CD60 27A30050 */  addiu $v1, $sp, 0x50
.L8000CD64:
/* 00D964 8000CD64 24420001 */  addiu $v0, $v0, 1
/* 00D968 8000CD68 0043082B */  sltu  $at, $v0, $v1
/* 00D96C 8000CD6C 1420FFFD */  bnez  $at, .L8000CD64
/* 00D970 8000CD70 A047FFFF */   sb    $a3, -1($v0)
/* 00D974 8000CD74 02002825 */  move  $a1, $s0
/* 00D978 8000CD78 24060400 */  li    $a2, 1024
/* 00D97C 8000CD7C 27A70030 */  addiu $a3, $sp, 0x30
/* 00D980 8000CD80 AFA00010 */  sw    $zero, 0x10($sp)
/* 00D984 8000CD84 0C005840 */  jal   __osContRamWrite
/* 00D988 8000CD88 AFA40058 */   sw    $a0, 0x58($sp)
/* 00D98C 8000CD8C 24010002 */  li    $at, 2
/* 00D990 8000CD90 14410008 */  bne   $v0, $at, .L8000CDB4
/* 00D994 8000CD94 00401825 */   move  $v1, $v0
/* 00D998 8000CD98 8FA40058 */  lw    $a0, 0x58($sp)
/* 00D99C 8000CD9C 02002825 */  move  $a1, $s0
/* 00D9A0 8000CDA0 24060400 */  li    $a2, 1024
/* 00D9A4 8000CDA4 27A70030 */  addiu $a3, $sp, 0x30
/* 00D9A8 8000CDA8 0C005840 */  jal   __osContRamWrite
/* 00D9AC 8000CDAC AFA00010 */   sw    $zero, 0x10($sp)
/* 00D9B0 8000CDB0 00401825 */  move  $v1, $v0
.L8000CDB4:
/* 00D9B4 8000CDB4 10400003 */  beqz  $v0, .L8000CDC4
/* 00D9B8 8000CDB8 8FA40058 */   lw    $a0, 0x58($sp)
/* 00D9BC 8000CDBC 10000033 */  b     .L8000CE8C
/* 00D9C0 8000CDC0 00601025 */   move  $v0, $v1
.L8000CDC4:
/* 00D9C4 8000CDC4 02002825 */  move  $a1, $s0
/* 00D9C8 8000CDC8 24060400 */  li    $a2, 1024
/* 00D9CC 8000CDCC 0C00592C */  jal   __osContRamRead
/* 00D9D0 8000CDD0 27A70030 */   addiu $a3, $sp, 0x30
/* 00D9D4 8000CDD4 10400003 */  beqz  $v0, .L8000CDE4
/* 00D9D8 8000CDD8 93AE004F */   lbu   $t6, 0x4f($sp)
/* 00D9DC 8000CDDC 1000002C */  b     .L8000CE90
/* 00D9E0 8000CDE0 8FBF0024 */   lw    $ra, 0x24($sp)
.L8000CDE4:
/* 00D9E4 8000CDE4 24010080 */  li    $at, 128
/* 00D9E8 8000CDE8 11C10003 */  beq   $t6, $at, .L8000CDF8
/* 00D9EC 8000CDEC 3C048006 */   lui   $a0, %hi(rumble_off_buffer) # $a0, 0x8006
/* 00D9F0 8000CDF0 10000026 */  b     .L8000CE8C
/* 00D9F4 8000CDF4 2402000B */   li    $v0, 11
.L8000CDF8:
/* 00D9F8 8000CDF8 3C038006 */  lui   $v1, %hi(rumble_on_buffer) # $v1, 0x8006
/* 00D9FC 8000CDFC 3C058006 */  lui   $a1, %hi(rumble_off_buffer) # $a1, 0x8006
/* 00DA00 8000CE00 24A557C0 */  addiu $a1, %lo(rumble_off_buffer) # addiu $a1, $a1, 0x57c0
/* 00DA04 8000CE04 246357A0 */  addiu $v1, %lo(rumble_on_buffer) # addiu $v1, $v1, 0x57a0
/* 00DA08 8000CE08 248457C0 */  addiu $a0, %lo(rumble_off_buffer) # addiu $a0, $a0, 0x57c0
/* 00DA0C 8000CE0C 24020001 */  li    $v0, 1
.L8000CE10:
/* 00DA10 8000CE10 24630004 */  addiu $v1, $v1, 4
/* 00DA14 8000CE14 A0820001 */  sb    $v0, 1($a0)
/* 00DA18 8000CE18 A060FFFD */  sb    $zero, -3($v1)
/* 00DA1C 8000CE1C A0820002 */  sb    $v0, 2($a0)
/* 00DA20 8000CE20 A060FFFE */  sb    $zero, -2($v1)
/* 00DA24 8000CE24 A0820003 */  sb    $v0, 3($a0)
/* 00DA28 8000CE28 A060FFFF */  sb    $zero, -1($v1)
/* 00DA2C 8000CE2C 24840004 */  addiu $a0, $a0, 4
/* 00DA30 8000CE30 A082FFFC */  sb    $v0, -4($a0)
/* 00DA34 8000CE34 1465FFF6 */  bne   $v1, $a1, .L8000CE10
/* 00DA38 8000CE38 A060FFFC */   sb    $zero, -4($v1)
/* 00DA3C 8000CE3C 3C0F8006 */  lui   $t7, %hi(rumble_on_player_packet_buffers) # $t7, 0x8006
/* 00DA40 8000CE40 25EF56A0 */  addiu $t7, %lo(rumble_on_player_packet_buffers) # addiu $t7, $t7, 0x56a0
/* 00DA44 8000CE44 3C068006 */  lui   $a2, %hi(rumble_off_buffer) # $a2, 0x8006
/* 00DA48 8000CE48 00101180 */  sll   $v0, $s0, 6
/* 00DA4C 8000CE4C 004F3821 */  addu  $a3, $v0, $t7
/* 00DA50 8000CE50 AFA2002C */  sw    $v0, 0x2c($sp)
/* 00DA54 8000CE54 24C657C0 */  addiu $a2, %lo(rumble_off_buffer) # addiu $a2, $a2, 0x57c0
/* 00DA58 8000CE58 02002025 */  move  $a0, $s0
/* 00DA5C 8000CE5C 0C0032F7 */  jal   controller_7000CBDC
/* 00DA60 8000CE60 24050600 */   li    $a1, 1536
/* 00DA64 8000CE64 8FA2002C */  lw    $v0, 0x2c($sp)
/* 00DA68 8000CE68 3C188006 */  lui   $t8, %hi(rumble_off_player1_packet_buffer) # $t8, 0x8006
/* 00DA6C 8000CE6C 271855A0 */  addiu $t8, %lo(rumble_off_player1_packet_buffer) # addiu $t8, $t8, 0x55a0
/* 00DA70 8000CE70 3C068006 */  lui   $a2, %hi(rumble_on_buffer) # $a2, 0x8006
/* 00DA74 8000CE74 24C657A0 */  addiu $a2, %lo(rumble_on_buffer) # addiu $a2, $a2, 0x57a0
/* 00DA78 8000CE78 02002025 */  move  $a0, $s0
/* 00DA7C 8000CE7C 24050600 */  li    $a1, 1536
/* 00DA80 8000CE80 0C0032F7 */  jal   controller_7000CBDC
/* 00DA84 8000CE84 00583821 */   addu  $a3, $v0, $t8
/* 00DA88 8000CE88 00001025 */  move  $v0, $zero
.L8000CE8C:
/* 00DA8C 8000CE8C 8FBF0024 */  lw    $ra, 0x24($sp)
.L8000CE90:
/* 00DA90 8000CE90 8FB00020 */  lw    $s0, 0x20($sp)
/* 00DA94 8000CE94 27BD0058 */  addiu $sp, $sp, 0x58
/* 00DA98 8000CE98 03E00008 */  jr    $ra
/* 00DA9C 8000CE9C 00000000 */   nop   


