# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

set_stderr_activated:
/* 001570 80000970 3C018002 */  lui   $at, 0x8002
/* 001574 80000974 03E00008 */  jr    $ra
/* 001578 80000978 AC243098 */   sw    $a0, 0x3098($at)

set_stderr_enable:
/* 00157C 8000097C 3C018002 */  lui   $at, 0x8002
/* 001580 80000980 03E00008 */  jr    $ra
/* 001584 80000984 AC243094 */   sw    $a0, 0x3094($at)

set_stderr_permitted:
/* 001588 80000988 3C018002 */  lui   $at, 0x8002
/* 00158C 8000098C 03E00008 */  jr    $ra
/* 001590 80000990 AC24309C */   sw    $a0, 0x309c($at)

set_user_Compare:
/* 001594 80000994 3C018002 */  lui   $at, 0x8002
/* 001598 80000998 03E00008 */  jr    $ra
/* 00159C 8000099C AC2430A0 */   sw    $a0, 0x30a0($at)


