# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

return_TLB_index_for_entry:
/* 0024C0 800018C0 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 0024C4 800018C4 AFB20020 */  sw    $s2, 0x20($sp)
/* 0024C8 800018C8 AFB1001C */  sw    $s1, 0x1c($sp)
/* 0024CC 800018CC AFB00018 */  sw    $s0, 0x18($sp)
/* 0024D0 800018D0 00808825 */  move  $s1, $a0
/* 0024D4 800018D4 AFBF0024 */  sw    $ra, 0x24($sp)
/* 0024D8 800018D8 00008025 */  move  $s0, $zero
/* 0024DC 800018DC 24120020 */  li    $s2, 32
.L800018E0:
/* 0024E0 800018E0 0C003A20 */  jal   __osGetTLBHi
/* 0024E4 800018E4 02002025 */   move  $a0, $s0
/* 0024E8 800018E8 54510004 */  bnel  $v0, $s1, .L800018FC
/* 0024EC 800018EC 26100001 */   addiu $s0, $s0, 1
/* 0024F0 800018F0 10000005 */  b     .L80001908
/* 0024F4 800018F4 02001025 */   move  $v0, $s0
/* 0024F8 800018F8 26100001 */  addiu $s0, $s0, 1
.L800018FC:
/* 0024FC 800018FC 1612FFF8 */  bne   $s0, $s2, .L800018E0
/* 002500 80001900 00000000 */   nop   
/* 002504 80001904 3C028000 */  lui   $v0, 0x8000
.L80001908:
/* 002508 80001908 8FBF0024 */  lw    $ra, 0x24($sp)
/* 00250C 8000190C 8FB00018 */  lw    $s0, 0x18($sp)
/* 002510 80001910 8FB1001C */  lw    $s1, 0x1c($sp)
/* 002514 80001914 8FB20020 */  lw    $s2, 0x20($sp)
/* 002518 80001918 03E00008 */  jr    $ra
/* 00251C 8000191C 27BD0028 */   addiu $sp, $sp, 0x28


