# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

glabel find_remove_TLB_entry
/* 002520 70001920 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 002524 70001924 AFBF0014 */  sw    $ra, 0x14($sp)
/* 002528 70001928 0C000630 */  jal   return_TLB_index_for_entry
/* 00252C 7000192C 00000000 */   nop   
/* 002530 70001930 00027000 */  sll   $t6, $v0, 0
/* 002534 70001934 05C00003 */  bltz  $t6, .L70001944
/* 002538 70001938 00402025 */   move  $a0, $v0
/* 00253C 7000193C 0C0034F4 */  jal   osUnmapTLB
/* 002540 70001940 00000000 */   nop   
.L70001944:
/* 002544 70001944 8FBF0014 */  lw    $ra, 0x14($sp)
/* 002548 70001948 27BD0018 */  addiu $sp, $sp, 0x18
/* 00254C 7000194C 03E00008 */  jr    $ra
/* 002550 70001950 00000000 */   nop   

glabel remove_TLB_entry_from_table
/* 002554 70001954 3C0F8006 */  lui   $t7, %hi(TLB_manager_mapping_table_start) # $t7, 0x8006
/* 002558 70001958 25EFE3F0 */  addiu $t7, %lo(TLB_manager_mapping_table_start) # addiu $t7, $t7, -0x1c10
/* 00255C 7000195C 00047040 */  sll   $t6, $a0, 1
/* 002560 70001960 01CF1821 */  addu  $v1, $t6, $t7
/* 002564 70001964 90780000 */  lbu   $t8, ($v1)
/* 002568 70001968 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00256C 7000196C AFBF0014 */  sw    $ra, 0x14($sp)
/* 002570 70001970 57000016 */  bnezl $t8, .L700019CC
/* 002574 70001974 8FBF0014 */   lw    $ra, 0x14($sp)
/* 002578 70001978 90640001 */  lbu   $a0, 1($v1)
/* 00257C 7000197C 3C017F00 */  lui   $at, 0x7f00
/* 002580 70001980 AFA30018 */  sw    $v1, 0x18($sp)
/* 002584 70001984 0004CB40 */  sll   $t9, $a0, 0xd
/* 002588 70001988 0C000630 */  jal   return_TLB_index_for_entry
/* 00258C 7000198C 03212025 */   or    $a0, $t9, $at
/* 002590 70001990 00024800 */  sll   $t1, $v0, 0
/* 002594 70001994 8FA30018 */  lw    $v1, 0x18($sp)
/* 002598 70001998 05200004 */  bltz  $t1, .L700019AC
/* 00259C 7000199C 00402025 */   move  $a0, $v0
/* 0025A0 700019A0 0C0034F4 */  jal   osUnmapTLB
/* 0025A4 700019A4 AFA30018 */   sw    $v1, 0x18($sp)
/* 0025A8 700019A8 8FA30018 */  lw    $v1, 0x18($sp)
.L700019AC:
/* 0025AC 700019AC 906A0001 */  lbu   $t2, 1($v1)
/* 0025B0 700019B0 3C018006 */  lui   $at, 0x8006
/* 0025B4 700019B4 24020001 */  li    $v0, 1
/* 0025B8 700019B8 000A5900 */  sll   $t3, $t2, 4
/* 0025BC 700019BC 002B0821 */  addu  $at, $at, $t3
/* 0025C0 700019C0 AC22DBF0 */  sw    $v0, -0x2410($at)
/* 0025C4 700019C4 A0620000 */  sb    $v0, ($v1)
/* 0025C8 700019C8 8FBF0014 */  lw    $ra, 0x14($sp)
.L700019CC:
/* 0025CC 700019CC 27BD0020 */  addiu $sp, $sp, 0x20
/* 0025D0 700019D0 03E00008 */  jr    $ra
/* 0025D4 700019D4 00000000 */   nop   

glabel translate_load_rom_from_TLBaddress
/* 0025D8 700019D8 3C028002 */  lui   $v0, %hi(D_800230D0) # $v0, 0x8002
/* 0025DC 700019DC 244230D0 */  addiu $v0, %lo(D_800230D0) # addiu $v0, $v0, 0x30d0
/* 0025E0 700019E0 8C4E0000 */  lw    $t6, ($v0)
/* 0025E4 700019E4 3C017FFF */  lui   $at, (0x7FFFE000 >> 16) # lui $at, 0x7fff
/* 0025E8 700019E8 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 0025EC 700019EC 3421E000 */  ori   $at, (0x7FFFE000 & 0xFFFF) # ori $at, $at, 0xe000
/* 0025F0 700019F0 AFBF001C */  sw    $ra, 0x1c($sp)
/* 0025F4 700019F4 00812024 */  and   $a0, $a0, $at
/* 0025F8 700019F8 25CF0001 */  addiu $t7, $t6, 1
/* 0025FC 700019FC AFB00018 */  sw    $s0, 0x18($sp)
/* 002600 70001A00 AC4F0000 */  sw    $t7, ($v0)
/* 002604 70001A04 0C000648 */  jal   find_remove_TLB_entry
/* 002608 70001A08 AFA40028 */   sw    $a0, 0x28($sp)
/* 00260C 70001A0C 0C0006C4 */  jal   return_tlb_random_value
/* 002610 70001A10 00000000 */   nop   
/* 002614 70001A14 2401005A */  li    $at, 90
/* 002618 70001A18 0041001B */  divu  $zero, $v0, $at
/* 00261C 70001A1C 00002010 */  mfhi  $a0
/* 002620 70001A20 3C038002 */  lui   $v1, %hi(tlb_segment_num) # $v1, 0x8002
/* 002624 70001A24 246330D4 */  addiu $v1, %lo(tlb_segment_num) # addiu $v1, $v1, 0x30d4
/* 002628 70001A28 AC640000 */  sw    $a0, ($v1)
/* 00262C 70001A2C 0C000655 */  jal   remove_TLB_entry_from_table
/* 002630 70001A30 00808025 */   move  $s0, $a0
/* 002634 70001A34 8FA20028 */  lw    $v0, 0x28($sp)
/* 002638 70001A38 3C198006 */  lui   $t9, %hi(ptr_TLBallocatedblock) # $t9, 0x8006
/* 00263C 70001A3C 8F39E4A8 */  lw    $t9, %lo(ptr_TLBallocatedblock)($t9)
/* 002640 70001A40 3C0100FF */  lui   $at, (0x00FFE000 >> 16) # lui $at, 0xff
/* 002644 70001A44 3421E000 */  ori   $at, (0x00FFE000 & 0xFFFF) # ori $at, $at, 0xe000
/* 002648 70001A48 00104340 */  sll   $t0, $s0, 0xd
/* 00264C 70001A4C 3C0A0003 */  lui   $t2, %hi(_rarezipSegmentRomEnd) # $t2, 3
/* 002650 70001A50 00414824 */  and   $t1, $v0, $at
/* 002654 70001A54 254A4B30 */  addiu $t2, %lo(_rarezipSegmentRomEnd) # addiu $t2, $t2, 0x4b30
/* 002658 70001A58 03282021 */  addu  $a0, $t9, $t0
/* 00265C 70001A5C AFA40034 */  sw    $a0, 0x34($sp)
/* 002660 70001A60 012A2821 */  addu  $a1, $t1, $t2
/* 002664 70001A64 01201025 */  move  $v0, $t1
/* 002668 70001A68 AFA90024 */  sw    $t1, 0x24($sp)
/* 00266C 70001A6C 0C001707 */  jal   load_bytes_from_hw_to_rdram
/* 002670 70001A70 24062000 */   li    $a2, 8192
/* 002674 70001A74 3C044000 */  lui   $a0, 0x4000
/* 002678 70001A78 0C0034D4 */  jal   osInvalICache
/* 00267C 70001A7C 3C054000 */   lui   $a1, 0x4000
/* 002680 70001A80 3C048000 */  lui   $a0, 0x8000
/* 002684 70001A84 0C0034D4 */  jal   osInvalICache
/* 002688 70001A88 3C051000 */   lui   $a1, 0x1000
/* 00268C 70001A8C 8FA50024 */  lw    $a1, 0x24($sp)
/* 002690 70001A90 3C0D8006 */  lui   $t5, %hi(TLB_managment_table) # $t5, 0x8006
/* 002694 70001A94 25ADDBF0 */  addiu $t5, %lo(TLB_managment_table) # addiu $t5, $t5, -0x2410
/* 002698 70001A98 00055B42 */  srl   $t3, $a1, 0xd
/* 00269C 70001A9C 000B6100 */  sll   $t4, $t3, 4
/* 0026A0 70001AA0 018D3021 */  addu  $a2, $t4, $t5
/* 0026A4 70001AA4 ACD00004 */  sw    $s0, 4($a2)
/* 0026A8 70001AA8 AFA60020 */  sw    $a2, 0x20($sp)
/* 0026AC 70001AAC AFAB0028 */  sw    $t3, 0x28($sp)
/* 0026B0 70001AB0 0C003A2C */  jal   osVirtualToPhysical
/* 0026B4 70001AB4 8FA40034 */   lw    $a0, 0x34($sp)
/* 0026B8 70001AB8 8FBF001C */  lw    $ra, 0x1c($sp)
/* 0026BC 70001ABC 00027302 */  srl   $t6, $v0, 0xc
/* 0026C0 70001AC0 0010C840 */  sll   $t9, $s0, 1
/* 0026C4 70001AC4 3C088006 */  lui   $t0, %hi(TLB_manager_mapping_table_start) # $t0, 0x8006
/* 0026C8 70001AC8 8FA50028 */  lw    $a1, 0x28($sp)
/* 0026CC 70001ACC 8FA60020 */  lw    $a2, 0x20($sp)
/* 0026D0 70001AD0 000E7980 */  sll   $t7, $t6, 6
/* 0026D4 70001AD4 2508E3F0 */  addiu $t0, %lo(TLB_manager_mapping_table_start) # addiu $t0, $t0, -0x1c10
/* 0026D8 70001AD8 35F8001F */  ori   $t8, $t7, 0x1f
/* 0026DC 70001ADC 03281821 */  addu  $v1, $t9, $t0
/* 0026E0 70001AE0 8FB00018 */  lw    $s0, 0x18($sp)
/* 0026E4 70001AE4 A0600000 */  sb    $zero, ($v1)
/* 0026E8 70001AE8 27BD0050 */  addiu $sp, $sp, 0x50
/* 0026EC 70001AEC A0650001 */  sb    $a1, 1($v1)
/* 0026F0 70001AF0 03E00008 */  jr    $ra
/* 0026F4 70001AF4 ACD80000 */   sw    $t8, ($a2)

glabel return_ptr_TLBmemory
/* 0026F8 70001AF8 3C028006 */  lui   $v0, 0x8006
/* 0026FC 70001AFC 03E00008 */  jr    $ra
/* 002700 70001B00 8C42E4A8 */   lw    $v0, -0x1b58($v0)

/* 002704 70001B04 00000000 */  nop   
/* 002708 70001B08 00000000 */  nop   
/* 00270C 70001B0C 00000000 */  nop   

