# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

find_remove_TLB_entry:
/* 002520 80001920 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 002524 80001924 AFBF0014 */  sw    $ra, 0x14($sp)
/* 002528 80001928 0C000630 */  jal   return_TLB_index_for_entry
/* 00252C 8000192C 00000000 */   nop   
/* 002530 80001930 00027000 */  sll   $t6, $v0, 0
/* 002534 80001934 05C00003 */  bltz  $t6, .L80001944
/* 002538 80001938 00402025 */   move  $a0, $v0
/* 00253C 8000193C 0C0034F4 */  jal   osUnmapTLB
/* 002540 80001940 00000000 */   nop   
.L80001944:
/* 002544 80001944 8FBF0014 */  lw    $ra, 0x14($sp)
/* 002548 80001948 27BD0018 */  addiu $sp, $sp, 0x18
/* 00254C 8000194C 03E00008 */  jr    $ra
/* 002550 80001950 00000000 */   nop   

remove_TLB_entry_from_table:
/* 002554 80001954 3C0F8006 */  lui   $t7, %hi(TLB_manager_mapping_table_start) # $t7, 0x8006
/* 002558 80001958 25EFE3F0 */  addiu $t7, %lo(TLB_manager_mapping_table_start) # addiu $t7, $t7, -0x1c10
/* 00255C 8000195C 00047040 */  sll   $t6, $a0, 1
/* 002560 80001960 01CF1821 */  addu  $v1, $t6, $t7
/* 002564 80001964 90780000 */  lbu   $t8, ($v1)
/* 002568 80001968 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 00256C 8000196C AFBF0014 */  sw    $ra, 0x14($sp)
/* 002570 80001970 57000016 */  bnezl $t8, .L800019CC
/* 002574 80001974 8FBF0014 */   lw    $ra, 0x14($sp)
/* 002578 80001978 90640001 */  lbu   $a0, 1($v1)
/* 00257C 8000197C 3C017F00 */  lui   $at, 0x7f00
/* 002580 80001980 AFA30018 */  sw    $v1, 0x18($sp)
/* 002584 80001984 0004CB40 */  sll   $t9, $a0, 0xd
/* 002588 80001988 0C000630 */  jal   return_TLB_index_for_entry
/* 00258C 8000198C 03212025 */   or    $a0, $t9, $at
/* 002590 80001990 00024800 */  sll   $t1, $v0, 0
/* 002594 80001994 8FA30018 */  lw    $v1, 0x18($sp)
/* 002598 80001998 05200004 */  bltz  $t1, .L800019AC
/* 00259C 8000199C 00402025 */   move  $a0, $v0
/* 0025A0 800019A0 0C0034F4 */  jal   osUnmapTLB
/* 0025A4 800019A4 AFA30018 */   sw    $v1, 0x18($sp)
/* 0025A8 800019A8 8FA30018 */  lw    $v1, 0x18($sp)
.L800019AC:
/* 0025AC 800019AC 906A0001 */  lbu   $t2, 1($v1)
/* 0025B0 800019B0 3C018006 */  lui   $at, 0x8006
/* 0025B4 800019B4 24020001 */  li    $v0, 1
/* 0025B8 800019B8 000A5900 */  sll   $t3, $t2, 4
/* 0025BC 800019BC 002B0821 */  addu  $at, $at, $t3
/* 0025C0 800019C0 AC22DBF0 */  sw    $v0, -0x2410($at)
/* 0025C4 800019C4 A0620000 */  sb    $v0, ($v1)
/* 0025C8 800019C8 8FBF0014 */  lw    $ra, 0x14($sp)
.L800019CC:
/* 0025CC 800019CC 27BD0020 */  addiu $sp, $sp, 0x20
/* 0025D0 800019D0 03E00008 */  jr    $ra
/* 0025D4 800019D4 00000000 */   nop   

translate_load_rom_from_TLBaddress:
/* 0025D8 800019D8 3C028002 */  lui   $v0, %hi(D_800230D0) # $v0, 0x8002
/* 0025DC 800019DC 244230D0 */  addiu $v0, %lo(D_800230D0) # addiu $v0, $v0, 0x30d0
/* 0025E0 800019E0 8C4E0000 */  lw    $t6, ($v0)
/* 0025E4 800019E4 3C017FFF */  lui   $at, (0x7FFFE000 >> 16) # lui $at, 0x7fff
/* 0025E8 800019E8 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 0025EC 800019EC 3421E000 */  ori   $at, (0x7FFFE000 & 0xFFFF) # ori $at, $at, 0xe000
/* 0025F0 800019F0 AFBF001C */  sw    $ra, 0x1c($sp)
/* 0025F4 800019F4 00812024 */  and   $a0, $a0, $at
/* 0025F8 800019F8 25CF0001 */  addiu $t7, $t6, 1
/* 0025FC 800019FC AFB00018 */  sw    $s0, 0x18($sp)
/* 002600 80001A00 AC4F0000 */  sw    $t7, ($v0)
/* 002604 80001A04 0C000648 */  jal   find_remove_TLB_entry
/* 002608 80001A08 AFA40028 */   sw    $a0, 0x28($sp)
/* 00260C 80001A0C 0C0006C4 */  jal   return_tlb_random_value
/* 002610 80001A10 00000000 */   nop   
/* 002614 80001A14 2401005A */  li    $at, 90
/* 002618 80001A18 0041001B */  divu  $zero, $v0, $at
/* 00261C 80001A1C 00002010 */  mfhi  $a0
/* 002620 80001A20 3C038002 */  lui   $v1, %hi(tlb_segment_num) # $v1, 0x8002
/* 002624 80001A24 246330D4 */  addiu $v1, %lo(tlb_segment_num) # addiu $v1, $v1, 0x30d4
/* 002628 80001A28 AC640000 */  sw    $a0, ($v1)
/* 00262C 80001A2C 0C000655 */  jal   remove_TLB_entry_from_table
/* 002630 80001A30 00808025 */   move  $s0, $a0
/* 002634 80001A34 8FA20028 */  lw    $v0, 0x28($sp)
/* 002638 80001A38 3C198006 */  lui   $t9, %hi(ptr_TLBallocatedblock) # $t9, 0x8006
/* 00263C 80001A3C 8F39E4A8 */  lw    $t9, %lo(ptr_TLBallocatedblock)($t9)
/* 002640 80001A40 3C0100FF */  lui   $at, (0x00FFE000 >> 16) # lui $at, 0xff
/* 002644 80001A44 3421E000 */  ori   $at, (0x00FFE000 & 0xFFFF) # ori $at, $at, 0xe000
/* 002648 80001A48 00104340 */  sll   $t0, $s0, 0xd
/* 00264C 80001A4C 3C0A0003 */  lui   $t2, %hi(_rarezipSegmentRomEnd) # $t2, 3
/* 002650 80001A50 00414824 */  and   $t1, $v0, $at
/* 002654 80001A54 254A4B30 */  addiu $t2, %lo(_rarezipSegmentRomEnd) # addiu $t2, $t2, 0x4b30
/* 002658 80001A58 03282021 */  addu  $a0, $t9, $t0
/* 00265C 80001A5C AFA40034 */  sw    $a0, 0x34($sp)
/* 002660 80001A60 012A2821 */  addu  $a1, $t1, $t2
/* 002664 80001A64 01201025 */  move  $v0, $t1
/* 002668 80001A68 AFA90024 */  sw    $t1, 0x24($sp)
/* 00266C 80001A6C 0C001707 */  jal   load_bytes_from_hw_to_rdram
/* 002670 80001A70 24062000 */   li    $a2, 8192
/* 002674 80001A74 3C044000 */  lui   $a0, 0x4000
/* 002678 80001A78 0C0034D4 */  jal   osInvalICache
/* 00267C 80001A7C 3C054000 */   lui   $a1, 0x4000
/* 002680 80001A80 3C048000 */  lui   $a0, 0x8000
/* 002684 80001A84 0C0034D4 */  jal   osInvalICache
/* 002688 80001A88 3C051000 */   lui   $a1, 0x1000
/* 00268C 80001A8C 8FA50024 */  lw    $a1, 0x24($sp)
/* 002690 80001A90 3C0D8006 */  lui   $t5, %hi(TLB_managment_table) # $t5, 0x8006
/* 002694 80001A94 25ADDBF0 */  addiu $t5, %lo(TLB_managment_table) # addiu $t5, $t5, -0x2410
/* 002698 80001A98 00055B42 */  srl   $t3, $a1, 0xd
/* 00269C 80001A9C 000B6100 */  sll   $t4, $t3, 4
/* 0026A0 80001AA0 018D3021 */  addu  $a2, $t4, $t5
/* 0026A4 80001AA4 ACD00004 */  sw    $s0, 4($a2)
/* 0026A8 80001AA8 AFA60020 */  sw    $a2, 0x20($sp)
/* 0026AC 80001AAC AFAB0028 */  sw    $t3, 0x28($sp)
/* 0026B0 80001AB0 0C003A2C */  jal   osVirtualToPhysical
/* 0026B4 80001AB4 8FA40034 */   lw    $a0, 0x34($sp)
/* 0026B8 80001AB8 8FBF001C */  lw    $ra, 0x1c($sp)
/* 0026BC 80001ABC 00027302 */  srl   $t6, $v0, 0xc
/* 0026C0 80001AC0 0010C840 */  sll   $t9, $s0, 1
/* 0026C4 80001AC4 3C088006 */  lui   $t0, %hi(TLB_manager_mapping_table_start) # $t0, 0x8006
/* 0026C8 80001AC8 8FA50028 */  lw    $a1, 0x28($sp)
/* 0026CC 80001ACC 8FA60020 */  lw    $a2, 0x20($sp)
/* 0026D0 80001AD0 000E7980 */  sll   $t7, $t6, 6
/* 0026D4 80001AD4 2508E3F0 */  addiu $t0, %lo(TLB_manager_mapping_table_start) # addiu $t0, $t0, -0x1c10
/* 0026D8 80001AD8 35F8001F */  ori   $t8, $t7, 0x1f
/* 0026DC 80001ADC 03281821 */  addu  $v1, $t9, $t0
/* 0026E0 80001AE0 8FB00018 */  lw    $s0, 0x18($sp)
/* 0026E4 80001AE4 A0600000 */  sb    $zero, ($v1)
/* 0026E8 80001AE8 27BD0050 */  addiu $sp, $sp, 0x50
/* 0026EC 80001AEC A0650001 */  sb    $a1, 1($v1)
/* 0026F0 80001AF0 03E00008 */  jr    $ra
/* 0026F4 80001AF4 ACD80000 */   sw    $t8, ($a2)

return_ptr_TLBmemory:
/* 0026F8 80001AF8 3C028006 */  lui   $v0, 0x8006
/* 0026FC 80001AFC 03E00008 */  jr    $ra
/* 002700 80001B00 8C42E4A8 */   lw    $v0, -0x1b58($v0)

/* 002704 80001B04 00000000 */  nop   
/* 002708 80001B08 00000000 */  nop   
/* 00270C 80001B0C 00000000 */  nop   

