# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

return_tlb_random_value:
/* 002710 80001B10 3C048002 */  lui   $a0, %hi(D_800230E0) # $a0, 0x8002
/* 002714 80001B14 DC8430E0 */  ld    $a0, %lo(D_800230E0)($a0)
/* 002718 80001B18 3C018002 */  lui   $at, %hi(D_800230E0) # $at, 0x8002
/* 00271C 80001B1C 000437FC */  dsll32 $a2, $a0, 0x1f
/* 002720 80001B20 00042FF8 */  dsll  $a1, $a0, 0x1f
/* 002724 80001B24 000637FA */  dsrl  $a2, $a2, 0x1f
/* 002728 80001B28 0005283E */  dsrl32 $a1, $a1, 0
/* 00272C 80001B2C 0004233C */  dsll32 $a0, $a0, 0xc
/* 002730 80001B30 00C53025 */  or    $a2, $a2, $a1
/* 002734 80001B34 0004203E */  dsrl32 $a0, $a0, 0
/* 002738 80001B38 00C43026 */  xor   $a2, $a2, $a0
/* 00273C 80001B3C 0006253A */  dsrl  $a0, $a2, 0x14
/* 002740 80001B40 30840FFF */  andi  $a0, $a0, 0xfff
/* 002744 80001B44 00862026 */  xor   $a0, $a0, $a2
/* 002748 80001B48 0004103C */  dsll32 $v0, $a0, 0
/* 00274C 80001B4C FC2430E0 */  sd    $a0, %lo(D_800230E0)($at)
/* 002750 80001B50 03E00008 */  jr    $ra
/* 002754 80001B54 0002103F */   dsra32 $v0, $v0, 0

/* 002758 80001B58 00000000 */  nop   
/* 00275C 80001B5C 00000000 */  nop   

