# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

set_hardwire_TLB_to_2:
/* 0027B0 80001BB0 24080002 */  li    $t0, 2
/* 0027B4 80001BB4 40883000 */  mtc0  $t0, $6
/* 0027B8 80001BB8 24080000 */  li    $t0, 0
/* 0027BC 80001BBC 40882000 */  mtc0  $t0, $4
/* 0027C0 80001BC0 03E00008 */  jr    $ra
/* 0027C4 80001BC4 00000000 */   nop   

/* 0027C8 80001BC8 00000000 */  nop   
/* 0027CC 80001BCC 00000000 */  nop   

