# Goldeneye 007 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"
.include "globals.inc"

.section .text, "ax"

start_pi_manager:
/* 00B8F0 8000ACF0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00B8F4 8000ACF4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 00B8F8 8000ACF8 3C058006 */  lui   $a1, %hi(dword_CODE_bss_80064ED0) # $a1, 0x8006
/* 00B8FC 8000ACFC 3C068006 */  lui   $a2, %hi(dword_CODE_bss_80064EB0) # $a2, 0x8006
/* 00B900 8000AD00 24C64EB0 */  addiu $a2, %lo(dword_CODE_bss_80064EB0) # addiu $a2, $a2, 0x4eb0
/* 00B904 8000AD04 24A54ED0 */  addiu $a1, %lo(dword_CODE_bss_80064ED0) # addiu $a1, $a1, 0x4ed0
/* 00B908 8000AD08 24040096 */  li    $a0, 150
/* 00B90C 8000AD0C 0C00516C */  jal   osCreatePiManager
/* 00B910 8000AD10 24070008 */   li    $a3, 8
/* 00B914 8000AD14 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00B918 8000AD18 27BD0018 */  addiu $sp, $sp, 0x18
/* 00B91C 8000AD1C 03E00008 */  jr    $ra
/* 00B920 8000AD20 00000000 */   nop   

/* 00B924 8000AD24 00000000 */  nop   
/* 00B928 8000AD28 00000000 */  nop   
/* 00B92C 8000AD2C 00000000 */  nop   
start_nulled_entry:
/* 00B930 8000AD30 03E00008 */  jr    $ra
/* 00B934 8000AD34 00000000 */   nop   

something_with_vi_c_debug:
/* 00B938 8000AD38 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 00B93C 8000AD3C AFBF0014 */  sw    $ra, 0x14($sp)
/* 00B940 8000AD40 3C048002 */  lui   $a0, %hi(D_80024500) # $a0, 0x8002
/* 00B944 8000AD44 3C058003 */  lui   $a1, %hi(aVi_c_debug) # $a1, 0x8003
/* 00B948 8000AD48 24A59200 */  addiu $a1, %lo(aVi_c_debug) # addiu $a1, $a1, -0x6e00
/* 00B94C 8000AD4C 0C001398 */  jal   get_ptr_debug_notice_list_entry
/* 00B950 8000AD50 24844500 */   addiu $a0, %lo(D_80024500) # addiu $a0, $a0, 0x4500
/* 00B954 8000AD54 3C048006 */  lui   $a0, %hi(vi_c_debug_MQ) # $a0, 0x8006
/* 00B958 8000AD58 3C058006 */  lui   $a1, %hi(vi_c_debug_MSG) # $a1, 0x8006
/* 00B95C 8000AD5C 24A54EF0 */  addiu $a1, %lo(vi_c_debug_MSG) # addiu $a1, $a1, 0x4ef0
/* 00B960 8000AD60 24844F10 */  addiu $a0, %lo(vi_c_debug_MQ) # addiu $a0, $a0, 0x4f10
/* 00B964 8000AD64 0C0035B4 */  jal   osCreateMesgQueue
/* 00B968 8000AD68 24060008 */   li    $a2, 8
/* 00B96C 8000AD6C 8FBF0014 */  lw    $ra, 0x14($sp)
/* 00B970 8000AD70 27BD0018 */  addiu $sp, $sp, 0x18
/* 00B974 8000AD74 03E00008 */  jr    $ra
/* 00B978 8000AD78 00000000 */   nop   

/* 00B97C 8000AD7C 00000000 */  nop   

