#ifndef GEDITOR_BGDOCUMENT_H
#define GEDITOR_BGDOCUMENT_H

#include "rotation.h"
#include "scaling.h"
#include <windows.h>

#include "bgload.h"
#include "bgmaterial.h"
#include "bgrender.h"

/* Stable identity used between the editable document and presentation
 * layers. A face remains identifiable even when the viewport sorts its
 * triangles by texture or a room's arrays are later reallocated. */
#define BG_FACE_ID_NONE 0u

typedef enum BgGeometryLayer {
    BG_GEOMETRY_PRIMARY = 0,
    BG_GEOMETRY_SECONDARY = 1
} BgGeometryLayer;

typedef struct BgFaceRef {
    DWORD faceid;
    unsigned short room;
    unsigned char layer;
    unsigned char reserved;
} BgFaceRef;

/* Exact, room-local N64 vertex data. Positions and UVs deliberately remain
 * integral here so opening and inspecting a level can never introduce float
 * round-trip error. */
typedef struct BgDocumentVertex {
    DWORD id;
    unsigned short room;
    short x, y, z;
    unsigned short flag;
    short s, t;
    unsigned char r, g, b, a;
    DWORD usecount;
} BgDocumentVertex;

/* Opaque Fast3D state which preceded a run of triangles in one room layer.
 * Geometry commands are regenerated by the compiler, while these commands
 * preserve the authored combiner, texture, lighting, and render modes. */
typedef struct BgDocumentDrawGroup {
    unsigned char *commands; /* complete eight-byte commands */
    DWORD commandsize;
    DWORD commandcapacity;
} BgDocumentDrawGroup;

typedef struct BgDocumentLayerData {
    BgDocumentDrawGroup *groups;
    DWORD groupcount;
    DWORD groupcapacity;
    BOOL sourcepresent;
} BgDocumentLayerData;

typedef struct BgDocumentFace {
    DWORD id;
    DWORD vertexindices[3];
    DWORD drawgroup;
    unsigned short room;
    unsigned short textureid;
    unsigned char layer;
    unsigned char cullbackfaces;

    /* Complete material state, including texture enable and color combiner,
     * so textured/untextured faces can share an authored draw group. */
    BgMaterial material;
} BgDocumentFace;

typedef struct BgDocumentRoom {
    float origin[3];
    BgDocumentVertex *vertices;
    DWORD vertexcount;
    BgDocumentFace *faces;
    DWORD facecount;
    DWORD facecapacity;
    BgDocumentLayerData layers[2];
} BgDocumentRoom;

typedef struct BgDocument {
    BgDocumentRoom *rooms; /* indexed by authored room number; room 0 unused */
    DWORD roomcount;
    BgPortalFile portals; /* native table order; shared polygons remain distinct entries */
    const char *portalwarning; /* static loader error, or NULL; geometry remains editable */
    DWORD facecount;
    DWORD nextvertexid;
    DWORD nextfaceid;
    float levelscale;
    BOOL dirty;
} BgDocument;

/* Room vertex arrays retain their indices through edits and history. Room 0
 * denotes a rendered corner that is not part of the BG document. */
typedef struct BgDocumentVertexRef {
    DWORD room;
    DWORD index;
} BgDocumentVertexRef;

typedef struct BgDocumentUVEdit {
    BgDocumentVertexRef vertex;
    DWORD vertexid; /* rejects references left over from another document */
    int s, t;       /* signed N64 S/T units (1/32 texel) */
} BgDocumentUVEdit;

/* Validates the complete edit before changing any vertex. Shared source
   vertices are edited once; conflicting duplicate edits are rejected. */
BOOL BgDocumentSetVertexUVs(BgDocument *document, const BgDocumentUVEdit *edits,
                           DWORD count, DWORD *changed, const char **reason);

typedef struct BgDocumentRenderMesh {
    BgVertex *vertices;       /* facecount * 3 world-space vertices */
    unsigned short *tags;     /* one BG_* tag per face */
    BgRenderFlags *renderflags; /* decoded render state and S/T wrapping per face */
    BgFaceRef *facerefs;      /* one stable document identity per face */
    BgDocumentVertexRef *vertexrefs; /* one identity per rendered corner */
    DWORD facecount;
} BgDocumentRenderMesh;

BOOL BgDocumentLoad(const unsigned char *data, DWORD size, float levelscale,
                    BgDocument *out, const char **reasonout);
BOOL BgDocumentClone(const BgDocument *source, BgDocument *out,
                     const char **reasonout);
void BgDocumentFree(BgDocument *document);

/* Add an upright, untextured 1-metre primitive (world units are centimetres).
 * position is the base centre, right the horizontal camera-right direction.
 * A surface drop supplies its room; room=0 chooses the nearest existing room
 * whose native coordinates can hold the primitive. Allocates before mutation.
 * The quad has four shared vertices and two faces. Caller provides out[2]. */
BOOL BgDocumentAddPrimitive(BgDocument *document, BOOL quad, DWORD room,
    const double position[3], const double right[3], BgFaceRef out[2],
    DWORD *countout, const char **reasonout);

/* Room IDs are 1..roomcount and fit the native unsigned-byte fields.
 * Connection edits retain polygon winding, flags, margin and table identity. */
BOOL BgDocumentSetPortalRooms(BgDocument *document, DWORD portal, DWORD room1, DWORD room2,
                              BOOL *changed, const char **reasonout);

BOOL BgDocumentDeleteFaces(BgDocument *document, const BgFaceRef *refs,
                           DWORD refcount, DWORD *deletedout,
                           const char **reasonout);

/* Compare snapshots with identical topology after a vertex-position edit.
 * Finds faces whose area became zero, retaining pre-existing degenerates.
 * Returns an owned reference array (NULL when empty); the caller frees it. */
BOOL BgDocumentFindCollapsedFaces(const BgDocument *before, const BgDocument *after,
                                  BgFaceRef **facesout, DWORD *countout,
                                  const char **reasonout);

/* Replaces the image on each face, preserving UVs and shared vertices.
 * Existing textured faces retain their other material settings; untextured
 * faces receive a standard shaded texture material. BG_TEX_NONE disables
 * texturing and uses vertex RGBA in both cycles. Validates the whole selection
 * before editing; assigning the same image is a no-op. */
BOOL BgDocumentSetFaceTexture(BgDocument *document, const BgFaceRef *refs,
                              DWORD refcount, DWORD textureid,
                              BOOL *changedout, const char **reasonout);

#define BG_FACE_PROPERTY_CULL   1u
#define BG_FACE_PROPERTY_WRAP_U 2u
#define BG_FACE_PROPERTY_WRAP_V 4u
typedef struct BgFacePropertiesEdit {
    unsigned int fields; /* only explicitly changed controls are applied */
    BOOL cullbackfaces;
    BgTextureWrap wrapu, wrapv;
} BgFacePropertiesEdit;

/* Validates all faces before editing. Wrap changes require a texture on every
 * selected face. Materials, shared vertices and unedited axes are preserved. */
BOOL BgDocumentSetFaceProperties(BgDocument *document, const BgFaceRef *refs,
    DWORD count, const BgFacePropertiesEdit *edit, BOOL *changedout,
    const char **reasonout);

/* Paints the existing vertex at one face corner. Every face sharing that
 * vertex sees the edit; coincident vertices with different identities do not.
 * An identical RGBA value succeeds without dirtying the document. */
BOOL BgDocumentPaintVertex(BgDocument *document, const BgFaceRef *ref,
                           unsigned int corner, const unsigned char rgba[4],
                           BOOL *changedout, const char **reasonout);

/* Translates the unique vertices referenced by the selected faces. Shared
 * vertices retain their identity, so adjacent faces using them follow too.
 * World offsets snap to integral room-local coordinates; all references and
 * coordinate limits are checked before anything changes. A zero snapped move
 * succeeds with movedout == 0 and should not create a history entry. */
BOOL BgDocumentTranslateFaces(BgDocument *document, const BgFaceRef *refs,
                              DWORD refcount, const double offset[3],
                              double appliedoffset[3], DWORD *movedout,
                              const char **reasonout);

BOOL BgDocumentTranslateVertices(BgDocument *document,
    const BgDocumentVertexRef *refs, DWORD count, const double offset[3],
    double applied[3], DWORD *movedout, const char **reasonout);

/* Rebuilds every room stream while preserving the source file's header,
 * portals, visibility data, and opaque display-list state. */
BOOL BgDocumentCompile(const BgDocument *document, const BgFile *source,
                       BgFile *out, const char **reasonout);

/* Validate room vertex-cache batches, including the last-load bounds used by
 * player bullet tests. Invalid assets are rejected, never rewritten. */
BOOL BgFileValidateVertexBatches(const BgFile *bg, const char **reasonout);

/* Resolve a painted corner's preview alpha from the same inherited draw
 * state and per-face material as a full rebuild. Raw vertex RGBA stays intact. */
unsigned char BgDocumentPreviewVertexAlpha(const BgDocumentRoom *room,
    const BgDocumentFace *face, unsigned char vertexalpha);

BOOL BgDocumentBuildRenderMesh(const BgDocument *document,
                               BgDocumentRenderMesh *out,
                               const char **reasonout);
void BgDocumentRenderMeshFree(BgDocumentRenderMesh *mesh);

const BgDocumentRoom *BgDocumentGetRoom(const BgDocument *document,
                                        DWORD room);
const BgDocumentFace *BgDocumentFindFace(const BgDocument *document,
                                         const BgFaceRef *ref,
                                         const BgDocumentRoom **roomout);
void BgDocumentGetWorldPosition(const BgDocument *document,
                                const BgDocumentRoom *room,
                                const BgDocumentVertex *vertex,
                                float position[3]);

BOOL BgDocumentRotateVertices(BgDocument *document, const BgDocumentVertexRef *refs,
    DWORD count, const Rotation *rotation, const double pivot[3], DWORD *changed,
    const char **reasonout);

BOOL BgDocumentScaleVertices(BgDocument *document, const BgDocumentVertexRef *refs, DWORD count,
    const Scaling *scale, DWORD *changed, const char **reasonout);

#endif /* GEDITOR_BGDOCUMENT_H */
