#ifndef GEDITOR_BGDOCUMENT_H
#define GEDITOR_BGDOCUMENT_H

#include "rotation.h"
#include "scaling.h"
#include <windows.h>

#include "bgload.h"
#include "bgmaterial.h"
#include "bgrender.h"

/* Stable identity used between the editable document and presentation
 * layers. A face remains identifiable even when the viewport sorts its
 * triangles by texture or a room's arrays are later reallocated. */
#define BG_FACE_ID_NONE 0u

typedef enum BgGeometryLayer {
    BG_GEOMETRY_PRIMARY = 0,
    BG_GEOMETRY_SECONDARY = 1
} BgGeometryLayer;

typedef struct BgFaceRef {
    DWORD faceid;
    unsigned short room;
    unsigned char layer;
    unsigned char seams; /* viewport edge mask; not part of face identity */
} BgFaceRef;

/* Exact, room-local N64 vertex data. Positions and UVs deliberately remain
 * integral here so opening and inspecting a level can never introduce float
 * round-trip error. */
typedef struct BgDocumentVertex {
    DWORD id;
    unsigned short room;
    short x, y, z;
    unsigned short flag;
    short s, t;
    unsigned char r, g, b, a;
    DWORD usecount;
} BgDocumentVertex;

/* Opaque Fast3D state which preceded a run of triangles in one room layer.
 * Geometry commands are regenerated by the compiler, while these commands
 * preserve the authored combiner, texture, lighting, and render modes. */
typedef struct BgDocumentDrawGroup {
    unsigned char *commands; /* complete eight-byte commands */
    DWORD commandsize;
    DWORD commandcapacity;
} BgDocumentDrawGroup;

typedef struct BgDocumentLayerData {
    BgDocumentDrawGroup *groups;
    DWORD groupcount;
    DWORD groupcapacity;
    BOOL sourcepresent;
} BgDocumentLayerData;

typedef struct BgDocumentFace {
    DWORD id;
    DWORD vertexindices[3];
    DWORD drawgroup;
    unsigned short room;
    unsigned short textureid;
    unsigned char layer;
    unsigned char cullbackfaces;
    unsigned char uvseams; /* editor seam guides: bit c joins corner c to c+1 */

    /* Complete material state, including texture enable and color combiner,
     * so textured/untextured faces can share an authored draw group. */
    BgMaterial material;
} BgDocumentFace;

typedef struct BgDocumentRoom {
    float origin[3];
    BgDocumentVertex *vertices;
    DWORD vertexcount;
    BgDocumentFace *faces;
    DWORD facecount;
    DWORD facecapacity;
    BgDocumentLayerData layers[2];
} BgDocumentRoom;

typedef struct BgDocument {
    BgDocumentRoom *rooms; /* indexed by authored room number; room 0 unused */
    DWORD roomcount;
    BgPortalFile portals; /* native table order; shared polygons remain distinct entries */
    const char *portalwarning; /* static loader error, or NULL; geometry remains editable */
    /* Owned native visibility cells, including END. Polygon arguments retain
     * stable geometry identities (including unsaved editor portal identities).
     * Captured even before an edit so Undo remains valid after Save Project. */
    unsigned char *viscommands;
    DWORD viscommandssize;
    BOOL viscommandsloaded; /* FALSE preserves malformed source data verbatim */
    DWORD facecount;
    DWORD nextvertexid;
    DWORD nextfaceid;
    float levelscale;
    BOOL dirty;
} BgDocument;

/* Room vertex arrays retain their indices through edits and history. Room 0
 * denotes a rendered corner that is not part of the BG document. */
typedef struct BgDocumentVertexRef {
    DWORD room;
    DWORD index;
} BgDocumentVertexRef;

/* Directed edge of one source triangle. The face supplies room, layer,
 * winding and complete draw/material state; corner goes to (corner+1)%3. */
typedef struct BgDocumentEdgeRef {
    BgFaceRef face;
    unsigned int corner;
} BgDocumentEdgeRef;

/* Preview writes six world-space corners per edge, in the same order as the
 * committed triangles. Offsets snap to native BG units. A snapped zero is a
 * no-op; parallel/degenerate extrusions and coordinate/UV overflow fail. */
BOOL BgDocumentPreviewEdgeExtrusion(const BgDocument *document,
    const BgDocumentEdgeRef *edges, DWORD count, const double offset[3],
    BgVertex *triangles, double applied[3], const char **reasonout);

/* Append two triangles per edge, retaining the base and selecting the outer
 * edge via out[count]. Shared endpoints stay shared when their UVs agree;
 * UV seams keep separate identities. Validates/allocates before mutation. */
BOOL BgDocumentExtrudeEdges(BgDocument *document, const BgDocumentEdgeRef *edges,
    DWORD count, const double offset[3], BgDocumentEdgeRef *out,
    DWORD *createdout, const char **reasonout);

/* Join two boundary edges in the same room/layer with one triangle when they
 * share a vertex identity, or two triangles when their endpoints are disjoint.
 * Reverse both source edges' winding; inherit the first edge's face material,
 * keeping the endpoints' UV/RGBA. Reject degenerates/twists before editing.
 * CanBridge is read-only; Bridge allocates before mutation and writes out[count]. */
BOOL BgDocumentCanBridgeEdges(const BgDocument *document,
    const BgDocumentEdgeRef edges[2], const char **reasonout);
BOOL BgDocumentBridgeEdges(BgDocument *document, const BgDocumentEdgeRef edges[2],
    BgFaceRef out[2], DWORD *countout, const char **reasonout);

/* Insert a midpoint and split each triangle sharing the selected source edge.
 * Interpolate native XYZ/ST/RGBA; preserve winding/materials and authored seams.
 * Atomic on failure. out[2] selects the two halves of the picked edge. */
BOOL BgDocumentBisectEdge(BgDocument *document, const BgDocumentEdgeRef *edge,
    BgDocumentEdgeRef out[2], const char **reasonout);

/* Replace the shared diagonal of two compatible triangles forming a convex
 * quad. Retain native vertices/UV/RGBA, face IDs, draw state and boundary seams.
 * CanReverse is read-only; Reverse validates before mutation and selects the
 * opposite diagonal via out. Vertex and face counts remain unchanged. */
BOOL BgDocumentCanReverseEdge(const BgDocument *document, const BgDocumentEdgeRef *edge,
    const char **reasonout);
BOOL BgDocumentReverseEdge(BgDocument *document, const BgDocumentEdgeRef *edge,
    BgDocumentEdgeRef *out, const char **reasonout);

/* Mark every geometrically matching edge; UV/color splits remain separate. */
BOOL BgDocumentSetEdgeSeam(BgDocument *document, const BgDocumentEdgeRef *edge,
    BOOL marked, DWORD *changed, const char **reason);

void BgDocumentInheritFaceSeams(const BgDocumentVertex *vertices,
    const BgDocumentFace *source, BgDocumentFace *target);
BOOL BgDocumentSaveSeams(const BgDocument *document, const char *projectdir,
    const char *bgname, const char **reason);
BOOL BgDocumentLoadSeams(BgDocument *document, const char *projectdir,
    const char *bgname, const char **reason);

typedef struct BgDocumentUVEdit {
    BgDocumentVertexRef vertex;
    DWORD vertexid; /* rejects references left over from another document */
    int s, t;       /* signed N64 S/T units (1/32 texel) */
} BgDocumentUVEdit;

/* Validates the complete edit before changing any vertex. Shared source
   vertices are edited once; conflicting duplicate edits are rejected. */
BOOL BgDocumentSetVertexUVs(BgDocument *document, const BgDocumentUVEdit *edits,
                           DWORD count, DWORD *changed, const char **reason);

typedef struct BgDocumentFaceUVEdit {
    BgFaceRef face;
    DWORD vertexids[3];
    int s[3], t[3];
} BgDocumentFaceUVEdit;

/* Per-corner UVs for an unwrap. Split only conflicting UV identities or
 * vertices shared with unselected faces; keep equal-UV corners connected.
 * All geometry/materials and unselected UVs survive. Atomic on failure. */
BOOL BgDocumentSetFaceUVs(BgDocument *document, const BgDocumentFaceUVEdit *edits,
    DWORD count, DWORD *changed, const char **reason);

typedef struct BgDocumentRenderMesh {
    BgVertex *vertices;       /* facecount * 3 world-space vertices */
    unsigned short *tags;     /* one BG_* tag per face */
    BgRenderFlags *renderflags; /* decoded render state and S/T wrapping per face */
    BgFaceRef *facerefs;      /* one stable document identity per face */
    BgDocumentVertexRef *vertexrefs; /* one identity per rendered corner */
    DWORD facecount;
} BgDocumentRenderMesh;

BOOL BgDocumentLoad(const unsigned char *data, DWORD size, float levelscale,
                    BgDocument *out, const char **reasonout);
BOOL BgDocumentClone(const BgDocument *source, BgDocument *out,
                     const char **reasonout);
void BgDocumentFree(BgDocument *document);
/* Compact a newly loaded/staged room, preserving state at every face and at
 * opaque commands. Face/vertex identities are unchanged. On failure discard
 * the staged document. changedout reports redundant native state removed. */
BOOL BgDocumentCompactRoomState(BgDocumentRoom *room, BOOL *changedout,
    const char **reasonout);

/* Add an upright, untextured 1-metre primitive (world units are centimetres).
 * position is the base centre, right the horizontal camera-right direction.
 * A surface drop supplies its room; room=0 chooses the nearest existing room
 * whose native coordinates can hold the primitive. Allocates before mutation.
 * The quad has four shared vertices and two faces. Caller provides out[2]. */
BOOL BgDocumentAddPrimitive(BgDocument *document, BOOL quad, DWORD room,
    const double position[3], const double right[3], BgFaceRef out[2],
    DWORD *countout, const char **reasonout);

#define BG_PRIMITIVE_MAX_SIDES 64
#define BG_PRIMITIVE_MAX_FACES (BG_PRIMITIVE_MAX_SIDES * 2)
/* Horizontal circle or uncapped Y-axis cylinder, with backface culling.
 * position is the circle centre / cylinder base centre; dimensions are in
 * world centimetres. Circle faces point up. Uses the same room/append rules
 * as above, with sides-2 or sides*2 faces and only perimeter vertices. */
BOOL BgDocumentAddRoundPrimitive(BgDocument *document, BOOL cylinder, DWORD room,
    const double position[3], double radius, double height, DWORD sides,
    BgFaceRef out[BG_PRIMITIVE_MAX_FACES], DWORD *countout, const char **reasonout);

/* Room IDs are 1..roomcount and fit the native unsigned-byte fields.
 * Connection edits retain polygon winding, flags, margin and table identity. */
BOOL BgDocumentSetPortalRooms(BgDocument *document, DWORD portal, DWORD room1, DWORD room2,
                              BOOL *changed, const char **reasonout);

/* Margin is in world units, like the viewport; quantized to the native format.
 * Only this connection's margin changes, even when its polygon is shared.
 * Equivalent encodings are a no-op, preserving the original byte. */
BOOL BgDocumentSetPortalMargin(BgDocument *document, DWORD portal, double margin,
                               BOOL *changed, const char **reasonout);

typedef struct BgPortalPointRef { DWORD portal, point; } BgPortalPointRef;
BOOL BgDocumentTranslatePortalPoints(BgDocument *document, const BgPortalPointRef *refs,
    DWORD count, const double offset[3], DWORD *movedout, const char **reasonout);

typedef enum BgPortalPlane { BG_PORTAL_XY, BG_PORTAL_YZ, BG_PORTAL_XZ } BgPortalPlane;
typedef struct BgPortalPlacement {
    DWORD room1, room2;
    double center[3], width, height; /* World units (centimetres). */
    BgPortalPlane plane;
} BgPortalPlacement;
/* Append one rectangular connection. Existing indices and shared polygons
 * remain stable. Validation/allocation failure leaves the document unchanged. */
BOOL BgDocumentAddPortal(BgDocument *document, const BgPortalPlacement *placement,
                         DWORD *indexout, const char **reasonout);
/* Remove selected table entries, retaining other aliases of shared polygons.
 * Reject removal of the last connection named by a visibility script. */
BOOL BgDocumentDeletePortals(BgDocument *document, const BgFile *source,
    const DWORD *indices, DWORD count, const char **reasonout);
/* Level-local snapshots retain connection metadata and internal polygon sharing.
 * Paste appends independent geometry and returns the new table indices. Both
 * operations leave the destination unchanged on validation/allocation failure. */
BOOL BgDocumentCopyPortals(const BgDocument *document, const DWORD *indices,
    DWORD count, BgPortalFile *clipboard, const char **reasonout);
BOOL BgDocumentPastePortals(BgDocument *document, const BgPortalFile *clipboard,
    const double offset[3], DWORD indices[BG_MAX_PORTALS], const char **reasonout);

BOOL BgDocumentDeleteFaces(BgDocument *document, const BgFaceRef *refs,
                           DWORD refcount, DWORD *deletedout,
                           const char **reasonout);

/* Reverse each selected face's winding without changing shared vertex data,
 * materials or culling. Reject missing/duplicate references before any edit. */
BOOL BgDocumentFlipFaces(BgDocument *document, const BgFaceRef *refs,
                         DWORD refcount, const char **reasonout);

/* Separate each face from all others by copying shared source vertices.
 * Split Edge separates only its two endpoints on every incident face; it
 * does not add a midpoint or triangles. Existing positions, UV/RGBA, winding,
 * materials and face IDs remain intact. Already-private vertices are reused.
 * Atomic on failure; duplicatedout=0 is a no-op (including repeated edits). */
BOOL BgDocumentDisconnectFaces(BgDocument *document, const BgFaceRef *refs,
    DWORD count, DWORD *duplicatedout, const char **reasonout);
BOOL BgDocumentSplitEdge(BgDocument *document, const BgDocumentEdgeRef *edge,
    DWORD *duplicatedout, const char **reasonout);

/* Merge two or more distinct vertices within one room. Average XYZ, ST and
 * RGBA (nearest native integer), retain the lowest-index vertex's ID/flag,
 * and compact the removed records. Rewire both layers and delete only newly
 * collapsed triangles; the editor can confirm that count within its transaction.
 * Duplicate refs are counted once. Atomic on failure; out is the survivor. */
BOOL BgDocumentMergeVertices(BgDocument *document, const BgDocumentVertexRef *refs,
    DWORD count, BgDocumentVertexRef *out, DWORD *removedout, DWORD *deletedout,
    const char **reasonout);

/* Compare snapshots with identical topology after a vertex-position edit.
 * Finds faces whose area became zero, retaining pre-existing degenerates.
 * Returns an owned reference array (NULL when empty); the caller frees it. */
BOOL BgDocumentFindCollapsedFaces(const BgDocument *before, const BgDocument *after,
                                  BgFaceRef **facesout, DWORD *countout,
                                  const char **reasonout);

/* Replaces the image on each face, preserving UVs and shared vertices.
 * Existing textured faces retain their other material settings; untextured
 * and shade-only faces receive a standard shaded texture material, retaining
 * any detail tile settings. BG_TEX_NONE disables
 * texturing and uses vertex RGBA in both cycles. Validates the whole selection
 * before editing; assigning the same image is a no-op unless its shade-only
 * combiner still needs to be switched to texture sampling. */
BOOL BgDocumentSetFaceTexture(BgDocument *document, const BgFaceRef *refs,
                              DWORD refcount, DWORD textureid,
                              BOOL *changedout, const char **reasonout);

#define BG_FACE_PROPERTY_CULL   1u
#define BG_FACE_PROPERTY_WRAP_U 2u
#define BG_FACE_PROPERTY_WRAP_V 4u
#define BG_FACE_PROPERTY_TRANSPARENCY 8u
#define BG_FACE_PROPERTY_DETAIL_MODE 16u
#define BG_FACE_PROPERTY_DETAIL_IMAGE 32u
#define BG_FACE_PROPERTY_DETAIL_U 64u
#define BG_FACE_PROPERTY_DETAIL_V 128u
#define BG_FACE_PROPERTY_DETAIL_MINLOD 256u
#define BG_FACE_PROPERTY_DETAIL_OFFSET 512u
#define BG_FACE_PROPERTY_DETAIL_MASK 1008u
#define BG_FACE_PROPERTY_ALPHA_SOURCE 1024u
#define BG_FACE_PROPERTY_DECAL 2048u
#define BG_FACE_PROPERTY_OPACITY 4096u
#define BG_FACE_PROPERTY_FOG 8192u
#define BG_FACE_PROPERTY_ENVIRONMENT 16384u
typedef struct BgFacePropertiesEdit {
    unsigned int fields; /* only explicitly changed controls are applied */
    BOOL cullbackfaces;
    BgTextureWrap wrapu, wrapv;
    BgTransparency transparency;
    BgDetailTexture detail;
    DWORD alphasource;
    BOOL decal;
    DWORD opacity; /* Native environment alpha, 0..255. */
    DWORD environment; /* BG_ENV_* */
    DWORD fog; /* BG_FOG_AUTO/ON/OFF, independent of alpha and transparency. */
} BgFacePropertiesEdit;

/* Resolve partial detail edits without modifying the document. Used for image
 * validation before an edit and by the atomic document operation. */
BOOL BgDocumentDetailMaterial(const BgMaterial *source, const BgFacePropertiesEdit *edit,
    BgMaterial *result, const char **reasonout);

/* Validates all faces before editing. Wrap changes require a texture on every
 * selected face. Transparency changes require a supported explicit pipeline;
 * native state groups are split/restored without changing geometry or layers.
 * Decal changes require depth testing and an ordinary explicit pipeline; they
 * retain transparency and use the native coplanar depth mode without Z writes.
 * Detail switches require supported combiners and explicit texture state;
 * sampling edits retain the existing combiner and change only requested fields.
 * Alpha presets require explicit one/two-cycle state; texture presets also
 * require a base image and explicit LOD/detail settings in two-cycle mode.
 * Presets using vertex alpha disable fog within the compiler's face scope.
 * Auto retains the authored combiner. Opacity edits preserve environment RGB
 * and restore surrounding faces' constants without changing their presets.
 * Fog On promotes standard one-cycle materials at runtime and cannot combine
 * with vertex-alpha presets. Fog Auto restores the authored pipeline exactly.
 * Explicit choices override runtime optimization; Auto restores the native
 * surface saved by the first explicit choice and permits optimization again. */
BOOL BgDocumentSetFaceProperties(BgDocument *document, const BgFaceRef *refs,
    DWORD count, const BgFacePropertiesEdit *edit, BOOL *changedout,
    const char **reasonout);

/* Signed native normal packed in RGB byte order, derived from face winding. */
DWORD BgDocumentEnvironmentNormal(const BgDocumentRoom *room, const BgDocumentFace *face);
/* Self-contained material plus two nine-vertex batches for a Door Shadow. */
BOOL BgCompileDoorShadow(const BgDocumentFace *face, const BgRenderState *state,
    unsigned char **data, DWORD *size, const char **why);

/* Move selected faces to an existing room, retaining world coordinates,
 * UVs, colors, layers, face IDs and shared vertices within the moved set.
 * Source vertices/room slots remain for bounds. Atomic on failure; room refs
 * must be updated by the caller after success. No-op if already in target. */
BOOL BgDocumentMoveFacesToRoom(BgDocument *document, const BgFaceRef *refs,
    DWORD count, DWORD target, BOOL *changedout, const char **reasonout);

/* Retain vertices, materials and authored draw state while changing draw pass.
 * Atomic; the caller updates selection refs to the new layer after success. */
BOOL BgDocumentSetFaceLayer(BgDocument *document, const BgFaceRef *refs,
    DWORD count, BgGeometryLayer layer, BOOL *changedout, const char **reasonout);

/* Level-local, owned face snapshot; initialize clipboard to zero and release
 * with BgDocumentFree. Copy retains selected rooms/layers and native draw state.
 * Failed copies preserve the previous clipboard. Paste gives all copies fresh
 * identities, preserving sharing within the copied set but never with originals.
 * offset is in world units, snapped to the native grid like translation. Paste
 * is atomic and returns owned selection refs; the caller frees *facesout. */
BOOL BgDocumentCopyFaces(const BgDocument *document, const BgFaceRef *refs,
    DWORD count, BgDocument *clipboard, const char **reasonout);
BOOL BgDocumentPasteFaces(BgDocument *document, const BgDocument *clipboard,
    const double offset[3], BgFaceRef **facesout, DWORD *countout, const char **reasonout);

/* Paints the existing vertex at one face corner. Every face sharing that
 * vertex sees the edit; coincident vertices with different identities do not.
 * An identical RGBA value succeeds without dirtying the document. */
BOOL BgDocumentPaintVertex(BgDocument *document, const BgFaceRef *ref,
                           unsigned int corner, const unsigned char rgba[4],
                           BOOL *changedout, const char **reasonout);

/* Translates the unique selected vertices. Shared vertices retain their
 * identity, so adjacent faces using them follow too.
 * World offsets snap to integral room-local coordinates; all references and
 * coordinate limits are checked before anything changes. A zero snapped move
 * succeeds with movedout == 0 and should not create a history entry. */
BOOL BgDocumentTranslateVertices(BgDocument *document,
    const BgDocumentVertexRef *refs, DWORD count, const double offset[3],
    double applied[3], DWORD *movedout, const char **reasonout);

/* Correct UVs after a vertex/edge translation, before changing topology.
 * Unfold each affected triangle around its unchanged edge, and average
 * incident estimates by source area for shared vertices. Existing seams and
 * RGBA remain intact. Whole-face translations retain their original UVs.
 * Degenerate source faces contribute no estimate. UV changes are atomic. */
BOOL BgDocumentCorrectMovedUVs(const BgDocument *before, BgDocument *document,
    const char **reasonout);

/* Rebuilds every room stream while preserving the source file's header,
 * portals, visibility data, and opaque display-list state. */
BOOL BgDocumentCompile(const BgDocument *document, const BgFile *source,
                       BgFile *out, const char **reasonout);

/* Validate room vertex-cache batches, including the last-load bounds used by
 * player bullet tests. Invalid assets are rejected, never rewritten. */
BOOL BgFileValidateVertexBatches(const BgFile *bg, const char **reasonout);

/* Export-time opaque batching for unopened rooms. NULL out->data means no
 * worthwhile change. Keeps original vertex/secondary streams and offsets. */
BOOL BgFileBatchOpaque(const BgFile *source, BgFile *out, const char **reasonout);

/* Save/export optimization for unchanged backgrounds, including both layers.
 * Dense batches and exact vertex reuse are confined to known flat streams.
 * NULL out->data means the original file should be retained. */
BOOL BgFileOptimize(const BgFile *source, BgFile *out, const char **reasonout);

/* Resolve a painted corner's preview alpha from the same inherited draw
 * state and per-face material as a full rebuild. Raw vertex RGBA stays intact. */
unsigned char BgDocumentPreviewVertexAlpha(const BgDocumentRoom *room,
    const BgDocumentFace *face, unsigned char vertexalpha);
/* Read-only inspector data, one state per reference in caller-owned storage.
   Replays prior draw groups just like the viewport; caches the current room
   layer so a multi-face selection does not replay its stream for each face. */
BOOL BgDocumentGetFaceRenderStates(const BgDocument *document, const BgFaceRef *refs,
                                   DWORD count, BgRenderState *out);

BOOL BgDocumentBuildRenderMesh(const BgDocument *document,
                               BgDocumentRenderMesh *out,
                               const char **reasonout);
void BgDocumentRenderMeshFree(BgDocumentRenderMesh *mesh);

const BgDocumentRoom *BgDocumentGetRoom(const BgDocument *document,
                                        DWORD room);
const BgDocumentFace *BgDocumentFindFace(const BgDocument *document,
                                         const BgFaceRef *ref,
                                         const BgDocumentRoom **roomout);
void BgDocumentGetWorldPosition(const BgDocument *document,
                                const BgDocumentRoom *room,
                                const BgDocumentVertex *vertex,
                                float position[3]);

BOOL BgDocumentRotateVertices(BgDocument *document, const BgDocumentVertexRef *refs,
    DWORD count, const Rotation *rotation, const double pivot[3], DWORD *changed,
    const char **reasonout);

BOOL BgDocumentScaleVertices(BgDocument *document, const BgDocumentVertexRef *refs, DWORD count,
    const Scaling *scale, DWORD *changed, const char **reasonout);

#endif /* GEDITOR_BGDOCUMENT_H */
