/* Generated by scripts/generate_character_names.py. */
static const struct { const char *file, *name; } g_CharacterBodyNames[] = {
    {"CcamguardZ", "Jungle Commando"}, /* BODY_Jungle_Commando */
    {"CgreyguardZ", "St. Petersburg Guard"}, /* BODY_St_Petersburg_Guard */
    {"ColiveguardZ", "Russian Soldier"}, /* BODY_Russian_Soldier */
    {"CrusguardZ", "Russian Infantry"}, /* BODY_Russian_Infantry */
    {"CtrevguardZ", "Janus Special Forces"}, /* BODY_Janus_Special_Forces */
    {"CdjbondZ", "Brosnan"}, /* BODY_Brosnan_Tuxedo */
    {"CborisZ", "Boris"}, /* BODY_Boris */
    {"CorumovZ", "Ourumov"}, /* BODY_Ourumov */
    {"CtrevelyanZ", "Trevelyan"}, /* BODY_Trevelyan_Janus */
    {"CboilertrevZ", "Trevelyan 006"}, /* BODY_Trevelyan_006 */
    {"CvalentinZ", "Valentin"}, /* BODY_Valentin_ */
    {"CxeniaZ", "Xenia"}, /* BODY_Xenia */
    {"CbaronsamediZ", "Baron Samedi"}, /* BODY_Baron_Samedi */
    {"CjawsZ", "Jaws"}, /* BODY_Jaws */
    {"CmaydayZ", "Mayday"}, /* BODY_Mayday */
    {"CoddjobZ", "Oddjob"}, /* BODY_Oddjob */
    {"CnatalyaZ", "Natalya"}, /* BODY_Natalya_Skirt */
    {"CarmourguardZ", "Janus Marine"}, /* BODY_Janus_Marine */
    {"CcommguardZ", "Russian Commandant"}, /* BODY_Russian_Commandant */
    {"CgreatguardZ", "Siberian Guard"}, /* BODY_Siberian_Guard_1_Mishkin */
    {"CnavyguardZ", "Naval Officer"}, /* BODY_Naval_Officer */
    {"CsnowguardZ", "Siberian Special Forces"}, /* BODY_Siberian_Special_Forces */
    {"CboilerbondZ", "Special Operations Uniform"}, /* BODY_Special_Operations_Uniform */
    {"CsuitbondZ", "Formal Wear"}, /* BODY_Formal_Wear */
    {"CtimberbondZ", "Jungle Fatigues"}, /* BODY_Jungle_Fatigues */
    {"CsnowbondZ", "Parka"}, /* BODY_Parka */
    {"CbluewomanZ", "Unused Female"}, /* BODY_Unused_Female */
    {"CfattechwomanZ", "Rosika"}, /* BODY_Rosika */
    {"CtechwomanZ", "Scientist"}, /* BODY_Scientist_2_Female */
    {"CjeanwomanZ", "Civilian"}, /* BODY_Civilian_1_Female */
    {"CgreymanZ", "Unused Male 1"}, /* BODY_Unused_Male_1 */
    {"CbluemanZ", "Unused Male 2"}, /* BODY_Unused_Male_2 */
    {"CredmanZ", "Civilian"}, /* BODY_Civilian_4 */
    {"CcardimanZ", "Civilian"}, /* BODY_Civilian_2 */
    {"CcheckmanZ", "Civilian"}, /* BODY_Civilian_3 */
    {"CtechmanZ", "Scientist"}, /* BODY_Scientist_1_Male */
    {"CpilotZ", "Helicopter Pilot"}, /* BODY_Helicopter_Pilot */
    {"Cgreatguard2Z", "Siberian Guard"}, /* BODY_Siberian_Guard_2 */
    {"CbluecamguardZ", "Arctic Commando"}, /* BODY_Arctic_Commando */
    {"CmoonguardZ", "Moonraker Elite"}, /* BODY_Moonraker_Elite_1_Male */
    {"CmoonfemaleZ", "Moonraker Elite"}, /* BODY_Moonraker_Elite_2_Female */
    {"Csuit_lf_handZ", "Left Suit Hand Floating Arm"}, /* BODY_Left_Suit_Hand_Floating_Arm */
    {"CspicebondZ", "Natalya Jungle Fatigues"}, /* BODY_Natalya_Jungle_Fatigues */
};
