/* Every saved ObjectRecord PROPFLAG/PROPFLAG2 from src/propconstants.h,
 * including object-type aliases. Runtime PropRecord flags do not belong here.
 * Values come from the shared enums. tests/object_flags checks coverage.
 * Define OBJECT_FLAG(bank, symbol, label, description) before including. */
OBJECT_FLAG(0, PROPFLAG_ALLOWFALL, "Allow falling", "Allows this object to fall when its support is destroyed or destruction triggers falling. Overridden by No fall.")
OBJECT_FLAG(0, PROPFLAG_ONSIDE, "On side", "ObjectRecord.flags: sideways placement, anchored at the model's Z-min face.")
OBJECT_FLAG(0, PROPFLAG_UPSIDEDOWN, "Upside down", "In-air upside-down placement.")
OBJECT_FLAG(0, PROPFLAG_INAIR, "In air", "")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_PAD_BOUNDS, "Scale to pad bounds", "Scale to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_X_BOUNDS, "Scale to X bounds", "Scale X to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_Y_BOUNDS, "Scale to Y bounds", "Scale Y to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_Z_BOUNDS, "Scale to Z bounds", "Scale Z to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_FORCE_COLLISIONS, "Force collisions", "")
OBJECT_FLAG(0, PROPFLAG_ORTHOGONAL, "Orthogonal", "Use world space model matrices with the combined projection-view matrix. Used for environment mapping.")
OBJECT_FLAG(0, PROPFLAG_ILLUMINATED, "Illuminated", "Ignore stan color")
OBJECT_FLAG(0, PROPFLAG_FREE_STANDING_GLASS, "Free standing glass", "Free Standing Glass")
OBJECT_FLAG(0, PROPFLAG_ABSOLUTEPOSITION, "Absolute position", "Absolute positioning.")
OBJECT_FLAG(0, PROPFLAG_AIUNDROPPABLE, "AI undroppable", "Item Not Droppedz")
OBJECT_FLAG(0, PROPFLAG_ASSIGNEDTOCHR, "Assigned to character", "Assigned to Actor")
OBJECT_FLAG(0, PROPFLAG_INSIDEANOTHEROBJ, "Inside another object", "Embedded Object")
OBJECT_FLAG(0, PROPFLAG_FORCEMORTAL, "Force mortal", "unknown")
OBJECT_FLAG(0, PROPFLAG_INVINCIBLE, "Invincible", "Invincible")
OBJECT_FLAG(0, PROPFLAG_ALLOW_PICKUP, "Allow pickup", "Allow Pickup (chr_type)")
OBJECT_FLAG(0, PROPFLAG_COLLECT_BY_INTERACT, "Collect by interact", "Collect Object by Interaction Button Only")
OBJECT_FLAG(0, PROPFLAG_UNCOLLECTABLE, "Uncollectable", "Item Not Collectable")
OBJECT_FLAG(0, PROPFLAG_BOUND_AND_DESTROY, "Bound and destroy", "Bounce and destroy if Shot")
OBJECT_FLAG(0, PROPFLAG_BOUNCE, "Bounce", "Bounce if shot")
OBJECT_FLAG(0, PROPFLAG_COLLECTABLE_ALLOW_UNARMED_DAMAGE, "Collectable allow unarmed damage", "Allows collectable objects to take damage through the ITEM_UNARMED damage path.")
OBJECT_FLAG(0, PROPFLAG_EMBEDDED, "Embedded", "Embedded Object")
OBJECT_FLAG(0, PROPFLAG_CANNOT_ACTIVATE, "Cannot activate", "Cannot Activate Door/Object")
OBJECT_FLAG(0, PROPFLAG_TRANSPARENT_TO_AI, "Transparent to AI", "AI Sees Through Door/Object")
OBJECT_FLAG(0, PROPFLAG_DOOR_TWOWAY, "Door twoway", "Open Away From Player")
OBJECT_FLAG(0, PROPFLAG_WEAPON_LEFTHANDED, "Weapon left handed", "Left-Handed weapon")
OBJECT_FLAG(0, PROPFLAG_GLASS_HASPORTAL, "Glass has portal", "Glass Has Portal")
OBJECT_FLAG(0, PROPFLAG_CULL_BEHIND_DOOR, "Cull behind door", "Area Behind Door Invisible")
OBJECT_FLAG(0, PROPFLAG_FIXED_MONITOR, "Fixed monitor", "Monitor Fixed")
OBJECT_FLAG(0, PROPFLAG_CCTV_DISABLED, "CCTV disabled", "Disable security camera")
OBJECT_FLAG(0, PROPFLAG_IS_DRONE_GUN, "Is drone gun", "drone gun")
OBJECT_FLAG(0, PROPFLAG_AMMO_DETONATE, "Ammo detonate", "Explosive ammo pickup detonates on its next weapon tick.")
OBJECT_FLAG(0, PROPFLAG_DOOR_OPENTOFRONT, "Door open to front", "Open Backwards")
OBJECT_FLAG(0, PROPFLAG_SPECIAL_FUNC, "Special func", "Special Function")
OBJECT_FLAG(0, PROPFLAG_INMOTION, "In motion", "projectile/prop is in motion")
OBJECT_FLAG(0, PROPFLAG_CONCEAL_GUN, "Conceal gun", "Conceal Weapon")
OBJECT_FLAG(0, PROPFLAG_MONITOR_RENDERPOSTBG, "Monitor render post BG", "")
OBJECT_FLAG(0, PROPFLAG_NO_PORTAL_CLOSE, "No portal close", "Area Behind Door Visible")
OBJECT_FLAG(0, PROPFLAG_NO_AMMO, "No ammo", "No Ammo on pickup")
OBJECT_FLAG(0, PROPFLAG_STARTOPEN, "Start open", "Door open By Default")
OBJECT_FLAG(0, PROPFLAG_IS_DOUBLE, "Is double", "Weapon paired for player")
OBJECT_FLAG(1, PROPFLAG2_DRONEGUN, "Drone gun", "Activate Drone Gun")
OBJECT_FLAG(1, PROPFLAG2_LIGHTWEIGHT, "Lightweight", "lightweight (move when shot)")
OBJECT_FLAG(1, PROPFLAG2_DOOR_HIDE_LOCKED_MSG, "Door hide locked msg", "Locked door message not shown, used by Dam's double gates.")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_MP, "No load mp", "Don't Load in Multiplayer")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_A, "No load a", "Don't Load on Agent Mode")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_SA, "No load sa", "Don't Load on Secret Agent Mode")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_00A, "No load 00a", "Don't Load on 00 Agent Mode")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_007, "No load 007", "Don't Load on 007 Mode")
OBJECT_FLAG(1, PROPFLAG2_NOFALL, "No fall", "Immobile")
OBJECT_FLAG(1, PROPFLAG2_FALLWITHOUTROTATION, "Fall without rotation", "Used with mines")
OBJECT_FLAG(1, PROPFLAG2_LINKEDTOSAFE, "Linked to safe", "Inside a safe")
OBJECT_FLAG(1, PROPFLAG2_INTERACTCHECKLOS, "Interact check LOS", "Don't activate if stan gap Bond/Object")
OBJECT_FLAG(1, PROPFLAG2_PICKUP_THROUGH_WALLS, "Pickup through walls", "Watch Magnet Attract through walls/objects.")
OBJECT_FLAG(1, PROPFLAG2_REMOVE_WHEN_DESTROYED, "Remove when destroyed", "Remove When Destroyed")
OBJECT_FLAG(1, PROPFLAG2_GUNFIRE_IMMUNE, "Gunfire immune", "Immune to Gunfire")
OBJECT_FLAG(1, PROPFLAG2_SHOOTTHROUGH, "Shoot through", "Can Shoot Through Object")
OBJECT_FLAG(1, PROPFLAG2_DISABLE_ZBUFFER, "Disable Z-buffer", "Always Visible (in front)")
OBJECT_FLAG(1, PROPFLAG2_USESTANROOM, "Use stan room", "Register only in the prop's stan room. Skip bounding box room detection. Used for Streets building models.")
OBJECT_FLAG(1, PROPFLAG2_HIDE_FROM_INVENTORY, "Hide from inventory", "Hide inventory item (for tagged armor/ammo/magazine)")
OBJECT_FLAG(1, PROPFLAG2_ONLYEXPLOSIONDAMAGE, "Only explosion damage", "Invincible Except to Explosions")
OBJECT_FLAG(1, PROPFLAG2_BULLETPROOFGLASS, "Bulletproof glass", "Bulletproof Glass")
OBJECT_FLAG(1, PROPFLAG2_EXPLOSION_IMMUNE, "Explosion immune", "Immune to Explosions")
OBJECT_FLAG(1, PROPFLAG2_NOLOAD2P, "No load 2P", "Don't load on 2P")
OBJECT_FLAG(1, PROPFLAG2_NOLOAD3P, "No load 3P", "Don't load on 3P")
OBJECT_FLAG(1, PROPFLAG2_NOLOAD4P, "No load 4P", "Don't load on 4P")
OBJECT_FLAG(1, PROPFLAG2_THROWTHROUGH, "Throw through", "Rockets/Mines/Grenades Pass Through")
OBJECT_FLAG(1, PROPFLAG2_FORCEONSCREEN, "Force on screen", "Bypass the room-based scissor rectangle.")
OBJECT_FLAG(1, PROPFLAG2_LOCKEDFRONT, "Locked front", "One-Way Lock (Front)")
OBJECT_FLAG(1, PROPFLAG2_LOCKEDBACK, "Locked back", "One-Way Lock (Back)")
OBJECT_FLAG(1, PROPFLAG2_LOCKEDTOAI, "Locked to AI", "Character AI Cannot Operate")
OBJECT_FLAG(1, PROPFLAG2_AUTOGUN_STOP_SCAN, "Autogun stop scan", "Hold the current yaw and pitch during random scanning.")
OBJECT_FLAG(1, PROPFLAG2_DOOR_INTERLOCK, "Door interlock", "Close linked doors before opening this door.")
OBJECT_FLAG(1, PROPFLAG2_DOOR_ALTCOORDSYSTEM, "Door altcoordsystem", "Massive Explosion (08 Type)/Rotating Disabled Drone Gun (0D Type)")
OBJECT_FLAG(1, PROPFLAG2_RANDOM_SCAN, "Random scan", "Turn towards a random yaw and pitch, used by the Surface communications dish.")
