/* Every saved ObjectRecord PROPFLAG/PROPFLAG2 from src/propconstants.h,
 * including object-type aliases. Runtime PropRecord flags do not belong here.
 * Values come from the shared enums. tests/object_flags checks coverage.
 * Define OBJECT_FLAG(bank, symbol, label, description) before including. */
OBJECT_FLAG(0, PROPFLAG_ALLOWFALL, "Allow falling", "Allows this object to fall when its support is destroyed or destruction triggers falling. Overridden by No fall.")
OBJECT_FLAG(0, PROPFLAG_ONSIDE, "On side", "Sideways placement, anchored at the model's Z-min face.")
OBJECT_FLAG(0, PROPFLAG_UPSIDEDOWN, "Upside down", "In-air upside-down placement")
OBJECT_FLAG(0, PROPFLAG_INAIR, "In air", "")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_PAD_BOUNDS, "Scale to pad bounds", "Scale to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_X_BOUNDS, "Scale to X bounds", "Scale X to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_Y_BOUNDS, "Scale to Y bounds", "Scale Y to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_SCALE_TO_Z_BOUNDS, "Scale to Z bounds", "Scale Z to Pad Bounds")
OBJECT_FLAG(0, PROPFLAG_FORCE_COLLISIONS, "Solid collision", "Blocks player and character movement.")
OBJECT_FLAG(0, PROPFLAG_ORTHOGONAL, "Orthogonal", "Use world space model matrices with the combined projection-view matrix. Used for environment mapping.")
OBJECT_FLAG(0, PROPFLAG_ILLUMINATED, "Illuminated", "Ignore stan color")
OBJECT_FLAG(0, PROPFLAG_FREE_STANDING_GLASS, "Free standing glass", "Glass not embedded in another object.")
OBJECT_FLAG(0, PROPFLAG_ABSOLUTEPOSITION, "Absolute position", "Preserve the object's position when not on a stan tile instead of snapping to its pad.")
OBJECT_FLAG(0, PROPFLAG_AIUNDROPPABLE, "Prevent automatic item drops.", "Prevents automatic dropping when the carrying character dies or drops concealed items. Scripts can still explicitly transfer or drop the item.")
OBJECT_FLAG(0, PROPFLAG_ASSIGNEDTOCHR, "Assigned to character", "Gives this object to a character when the level loads. The Pad field specifies the character ID instead of a placement pad.")
OBJECT_FLAG(0, PROPFLAG_INSIDEANOTHEROBJ, "Inside another object", "Embedded object e.g. the weapons and ammo that pop out of destroyed crates.")
OBJECT_FLAG(0, PROPFLAG_FORCEMORTAL, "Force mortal", "Allows normally protected collectibles, such as keys, hats, and ammo crates, to take damage and be destroyed.")
OBJECT_FLAG(0, PROPFLAG_INVINCIBLE, "Invincible", "Self-explanatory")
OBJECT_FLAG(0, PROPFLAG_ALLOW_PICKUP, "Allow pickup", "Allows players to collect this normally noncollectible object by approaching it. Standard weapons, ammo, keys, and armor do not require this flag.")
OBJECT_FLAG(0, PROPFLAG_COLLECT_BY_INTERACT, "Collect by interact", "Collect object by interaction button only.")
OBJECT_FLAG(0, PROPFLAG_UNCOLLECTABLE, "Uncollectable", "Item not collectable")
OBJECT_FLAG(0, PROPFLAG_BOUND_AND_DESTROY, "Bound and destroy", "Bounce and destroy if shot.")
OBJECT_FLAG(0, PROPFLAG_BOUNCE, "Bounce", "Bounce if shot.")
OBJECT_FLAG(0, PROPFLAG_COLLECTABLE_ALLOW_UNARMED_DAMAGE, "Collectable allow unarmed damage", "Allows collectable objects to take damage through the ITEM_UNARMED damage path.")
OBJECT_FLAG(0, PROPFLAG_EMBEDDED, "Prevent landing damage", "Prevents noncollectible objects from taking damage when they land or bounce. Does not place the object inside another object.")
OBJECT_FLAG(0, PROPFLAG_CANNOT_ACTIVATE, "Cannot activate", "Cannot Activate door/object")
OBJECT_FLAG(0, PROPFLAG_TRANSPARENT_TO_AI, "Transparent to AI", "AI Sees through door/object")
OBJECT_FLAG(0, PROPFLAG_DOOR_TWOWAY, "Door two-way", "Open away from player")
OBJECT_FLAG(0, PROPFLAG_WEAPON_LEFTHANDED, "Weapon left handed", "Equips this weapon in the character’s left hand instead of the right. Also identifies the left-hand weapon in a linked pair.")
OBJECT_FLAG(0, PROPFLAG_GLASS_HASPORTAL, "Glass has portal", "Glass is connected to a portal.")
OBJECT_FLAG(0, PROPFLAG_CULL_BEHIND_DOOR, "Cull behind door", "Area behind door is not rendered.")
OBJECT_FLAG(0, PROPFLAG_FIXED_MONITOR, "Render screen as decal", "Renders the monitor image as an overlay on its supporting surface to prevent z-fighting.")
OBJECT_FLAG(0, PROPFLAG_CCTV_DISABLED, "Disable CCTV camera", "Stops camera scanning and player detection. The camera remains visible and cannot trigger the alarm.")
OBJECT_FLAG(0, PROPFLAG_AUTOGUN_DISABLED, "Disable drone gun", "Disables turret aiming and firing. The turret remains visible. Also set automatically when destroyed.")
OBJECT_FLAG(0, PROPFLAG_AMMO_DETONATE, "Ammo detonate", "Explosive ammo pickup detonates on its next weapon tick.")
OBJECT_FLAG(0, PROPFLAG_DOOR_REVERSE_SWING, "Reverse door swing", "Reverses the opening rotation and switches the hinge side for swinging doors. Two-way doors choose this setting automatically when opened.")
OBJECT_FLAG(0, PROPFLAG_MONITOR_SECONDARY_SCREENS_DECAL, "Render screens 2–4 as decals.", "Uses decal rendering for screens 2–4 to prevent depth flickering. Leaves screen 1’s rendering mode unchanged.")
OBJECT_FLAG(0, PROPFLAG_INMOTION, "In motion", "projectile/prop is in motion")
OBJECT_FLAG(0, PROPFLAG_CONCEAL_GUN, "Conceal gun", "Conceal Weapon")
OBJECT_FLAG(0, PROPFLAG_MONITOR_RENDERPOSTBG, "Monitor render post BG", "")
OBJECT_FLAG(0, PROPFLAG_NO_PORTAL_CLOSE, "No portal close", "Area Behind Door Visible")
OBJECT_FLAG(0, PROPFLAG_NO_AMMO, "No ammo", "No Ammo on pickup")
OBJECT_FLAG(0, PROPFLAG_STARTOPEN, "Start open", "Door open By Default")
OBJECT_FLAG(0, PROPFLAG_IS_DOUBLE, "Is double", "Weapon paired for player")
OBJECT_FLAG(1, PROPFLAG2_DRONEGUN, "Drone gun", "Activate Drone Gun")
OBJECT_FLAG(1, PROPFLAG2_LIGHTWEIGHT, "Lightweight", "lightweight (move when shot)")
OBJECT_FLAG(1, PROPFLAG2_DOOR_HIDE_LOCKED_MSG, "Door hide locked msg", "Locked door message not shown, used by Dam's double gates.")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_MP, "No load mp", "Don't Load in Multiplayer")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_A, "No load a", "Don't Load on Agent Mode")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_SA, "No load sa", "Don't Load on Secret Agent Mode")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_00A, "No load 00a", "Don't Load on 00 Agent Mode")
OBJECT_FLAG(1, PROPFLAG2_NO_LOAD_007, "No load 007", "Don't Load on 007 Mode")
OBJECT_FLAG(1, PROPFLAG2_NOFALL, "No fall", "Immobile")
OBJECT_FLAG(1, PROPFLAG2_FALLWITHOUTROTATION, "Fall without rotation", "Used with mines")
OBJECT_FLAG(1, PROPFLAG2_LINKEDTOSAFE, "Linked to safe", "Inside a safe")
OBJECT_FLAG(1, PROPFLAG2_INTERACTCHECKLOS, "Interact check LOS", "Don't activate if stan gap Bond/Object")
OBJECT_FLAG(1, PROPFLAG2_PICKUP_THROUGH_WALLS, "Pickup through walls", "Watch Magnet Attract through walls/objects.")
OBJECT_FLAG(1, PROPFLAG2_REMOVE_WHEN_DESTROYED, "Remove when destroyed", "Remove When Destroyed")
OBJECT_FLAG(1, PROPFLAG2_GUNFIRE_IMMUNE, "Gunfire immune", "Immune to Gunfire")
OBJECT_FLAG(1, PROPFLAG2_SHOOTTHROUGH, "Shoot through", "Can Shoot Through Object")
OBJECT_FLAG(1, PROPFLAG2_DISABLE_ZBUFFER, "Disable Z-buffer", "Always Visible (in front)")
OBJECT_FLAG(1, PROPFLAG2_USESTANROOM, "Use stan room", "Register only in the prop's stan room. Skip bounding box room detection. Used for Streets building models.")
OBJECT_FLAG(1, PROPFLAG2_HIDE_FROM_INVENTORY, "Hide from inventory", "Hide inventory item (for tagged armor/ammo/magazine)")
OBJECT_FLAG(1, PROPFLAG2_ONLYEXPLOSIONDAMAGE, "Only explosion damage", "Invincible Except to Explosions")
OBJECT_FLAG(1, PROPFLAG2_BULLETPROOFGLASS, "Bulletproof glass", "Bulletproof Glass")
OBJECT_FLAG(1, PROPFLAG2_EXPLOSION_IMMUNE, "Explosion immune", "Immune to Explosions")
OBJECT_FLAG(1, PROPFLAG2_NOLOAD2P, "No load 2P", "Don't load on 2P")
OBJECT_FLAG(1, PROPFLAG2_NOLOAD3P, "No load 3P", "Don't load on 3P")
OBJECT_FLAG(1, PROPFLAG2_NOLOAD4P, "No load 4P", "Don't load on 4P")
OBJECT_FLAG(1, PROPFLAG2_THROWTHROUGH, "Throw through", "Rockets/Mines/Grenades Pass Through")
OBJECT_FLAG(1, PROPFLAG2_FORCEONSCREEN, "Force on screen", "Bypass the room-based scissor rectangle.")
OBJECT_FLAG(1, PROPFLAG2_LOCKEDFRONT, "Locked front", "One-Way Lock (Front)")
OBJECT_FLAG(1, PROPFLAG2_LOCKEDBACK, "Locked back", "One-Way Lock (Back)")
OBJECT_FLAG(1, PROPFLAG2_LOCKEDTOAI, "Locked to AI", "Character AI Cannot Operate")
OBJECT_FLAG(1, PROPFLAG2_AUTOGUN_STOP_SCAN, "Autogun stop scan", "Hold the current yaw and pitch during random scanning.")
OBJECT_FLAG(1, PROPFLAG2_DOOR_INTERLOCK, "Door interlock", "Close linked doors before opening this door.")
OBJECT_FLAG(1, PROPFLAG2_DOOR_ALTCOORDSYSTEM, "Door altcoordsystem", "Massive Explosion (08 Type)/Rotating Disabled Drone Gun (0D Type)")
OBJECT_FLAG(1, PROPFLAG2_RANDOM_SCAN, "Random scan", "Turn towards a random yaw and pitch, used by the Surface communications dish.")
