/* Generated by scripts/generate_weapon_choices.py; do not edit IDs. */
static const SetupWeaponChoice g_SetupWeaponChoices[] = {
    {-1, -1, "None"},
    {4, 191, "PP7 Special Issue"}, /* ITEM_WPPK, PROP_CHRWPPK */
    {5, 204, "PP7 (Silenced)"}, /* ITEM_WPPKSIL, PROP_CHRWPPKSIL */
    {6, 205, "DD44 Dostovei"}, /* ITEM_TT33, PROP_CHRTT33 */
    {7, 193, "Klobb"}, /* ITEM_SKORPION, PROP_CHRSKORPION */
    {8, 184, "KF7 Soviet"}, /* ITEM_AK47, PROP_CHRKALASH */
    {9, 195, "ZMG (9mm)"}, /* ITEM_UZI, PROP_CHRUZI */
    {10, 189, "D5K Deutsche"}, /* ITEM_MP5K, PROP_CHRMP5K */
    {11, 206, "D5K (Silenced)"}, /* ITEM_MP5KSIL, PROP_CHRMP5KSIL */
    {12, 194, "Phantom"}, /* ITEM_SPECTRE, PROP_CHRSPECTRE */
    {13, 188, "AR33 Assault Rifle"}, /* ITEM_M16, PROP_CHRM16 */
    {14, 197, "RC-P90"}, /* ITEM_FNP90, PROP_CHRFNP90 */
    {15, 192, "Shotgun"}, /* ITEM_SHOTGUN, PROP_CHRSHOTGUN */
    {16, 207, "Automatic Shotgun"}, /* ITEM_AUTOSHOT, PROP_CHRAUTOSHOT */
    {17, 210, "Sniper Rifle"}, /* ITEM_SNIPERRIFLE, PROP_CHRSNIPERRIFLE */
    {18, 190, "Cougar Magnum"}, /* ITEM_RUGER, PROP_CHRRUGER */
    {19, 208, "Golden Gun"}, /* ITEM_GOLDENGUN, PROP_CHRGOLDEN */
    {20, 230, "Silver PP7"}, /* ITEM_SILVERWPPK, PROP_CHRSILVERWPPK */
    {21, 231, "Gold PP7"}, /* ITEM_GOLDWPPK, PROP_CHRGOLDWPPK */
    {22, 187, "Moonraker Laser"}, /* ITEM_LASER, PROP_CHRLASER */
    {24, 185, "Grenade Launcher"}, /* ITEM_GRENADELAUNCH, PROP_CHRGRENADELAUNCH */
    {25, 211, "Rocket Launcher"}, /* ITEM_ROCKETLAUNCH, PROP_CHRROCKETLAUNCH */
    {26, 196, "Grenade"}, /* ITEM_GRENADE, PROP_CHRGRENADE */
    {27, 201, "Timed Mine"}, /* ITEM_TIMEDMINE, PROP_CHRTIMEDMINE */
    {28, 200, "Proximity Mine"}, /* ITEM_PROXIMITYMINE, PROP_CHRPROXIMITYMINE */
    {29, 199, "Remote Mine"}, /* ITEM_REMOTEMINE, PROP_CHRREMOTEMINE */
    {2, 186, "Hunting Knife"}, /* ITEM_KNIFE, PROP_CHRKNIFE */
    {3, 209, "Throwing Knife"}, /* ITEM_THROWKNIFE, PROP_CHRTHROWKNIFE */
};
