#!/bin/bash
rm -rf asm/
mkdir asm asm/code asm/game asm/rarezip asm/libultra
yamlfile=../notes/ge007.u.yaml
assemblyfile=../notes/ge007_u.s
#process yaml to useable list
grep -A1 '^   # file .*\.s$' ../notes/ge007.u.yaml | grep -v "^--" > filelist.txt
#read filelist to process assembly
LINECOUNTERLIST=1
while IFS= read -r listlinetext; do
    #search for object
    if [[ "$listlinetext" == "   # file "* ]]; then
        printf '%s ' "$LINECOUNTERLIST"
        #printf '%s\n' "$listlinetext"
        #get address and first function name
        NEXTLISTLINETEXT=$(head -n $(expr $LINECOUNTERLIST + 1) filelist.txt | tail -1)
        FILENAME=$(printf '%s' "$listlinetext" | cut -f6 -d ' ')
        printf '%s\n' "$FILENAME"
        FIRSTFUNCTIONNAME=$(printf '%s' "$NEXTLISTLINETEXT" | cut -f2 -d '"')
        FIRSTFUNCTIONLINE=$(grep -n ${FIRSTFUNCTIONNAME}: ../notes/ge007_u.s | cut -f1 -d ':')
        printf ' %s %s - ' "$FIRSTFUNCTIONLINE" "$FIRSTFUNCTIONNAME"

        #get name of next function
        ENDFUNCTIONLINETEXT=$(head -n $(expr $LINECOUNTERLIST + 3) filelist.txt | tail -1)
        ENDFUNCTIONNAME=$(printf '%s' "$ENDFUNCTIONLINETEXT" | cut -f2 -d '"')
        ENDFUNCTIONLINE=$(grep -n ${ENDFUNCTIONNAME}: ../notes/ge007_u.s | cut -f1 -d ':')
        ENDFUNCTIONLINE=$(expr $ENDFUNCTIONLINE - 1)
        printf '%s %s\n\n' "$ENDFUNCTIONLINE" "$ENDFUNCTIONNAME"

        printf '%s\n' "# Goldeneye 007 (U) disassembly and split file" > ${FILENAME}
        printf '%s\n\n' "# generated by n64split v0.4a - N64 ROM splitter" >> ${FILENAME}

        printf '%s\n' "# assembler directives" >> ${FILENAME}
        printf '%s\n' ".set noat      # allow manual use of \$at" >> ${FILENAME}
        printf '%s\n' ".set noreorder # don't insert nops after branches" >> ${FILENAME}
        printf '%s\n\n' ".set gp=64" >> ${FILENAME}

        printf '%s\n' ".include \"macros.inc\"" >> ${FILENAME}
        printf '%s\n\n' ".include \"globals.inc\"" >> ${FILENAME}

        printf '%s\n\n' ".section .text, \"ax\"" >> ${FILENAME}
        sed -n "${FIRSTFUNCTIONLINE},${ENDFUNCTIONLINE}p" ${assemblyfile} >> ${FILENAME}
        printf '\n' >> ${FILENAME}

    fi
    LINECOUNTERLIST=$(expr $LINECOUNTERLIST + 1)
    


    
done < filelist.txt
rm asm/end.s
cp -R ./asm/. ../asm/
rm -rf asm/