base origin()
text_rom_start:

//vaddr is unknown
//base $vaddr
//text_vaddr:



include "text/LameE.rz.asm"
insert LameJ, "text/LameJ"
include "text/LarchE.rz.asm"
insert LarchJ, "text/LarchJ"
include "text/LarecE.rz.asm"
insert LarecJ, "text/LarecJ"
include "text/LarkE.rz.asm"
insert LarkJ, "text/LarkJ"
include "text/LashE.rz.asm"
insert LashJ, "text/LashJ"
include "text/LaztE.rz.asm"
insert LaztJ, "text/LaztJ"
include "text/LcatE.rz.asm"
insert LcatJ, "text/LcatJ"
include "text/LcaveE.rz.asm"
insert LcaveJ, "text/LcaveJ"
include "text/LcradE.rz.asm"
insert LcradJ, "text/LcradJ"
include "text/LcrypE.rz.asm"
insert LcrypJ, "text/LcrypJ"
include "text/LdamE.rz.asm"
insert LdamJ, "text/LdamJ"
include "text/LdepoE.rz.asm"
insert LdepoJ, "text/LdepoJ"
include "text/LdestE.rz.asm"
insert LdestJ, "text/LdestJ"
include "text/LdishE.rz.asm"
insert LdishJ, "text/LdishJ"
include "text/LearE.rz.asm"
insert LearJ, "text/LearJ"
include "text/LeldE.rz.asm"
insert LeldJ, "text/LeldJ"
include "text/LgunE.rz.asm"
insert LgunJ, "text/LgunJ"
include "text/LimpE.rz.asm"
insert LimpJ, "text/LimpJ"
include "text/LjunE.rz.asm"
insert LjunJ, "text/LjunJ"
include "text/LleeE.rz.asm"
seg_LleeJ_rom_start:;insert LleeJ, "text/LleeJ";seg_LleeJ_rom_end:
include "text/LlenE.rz.asm"
insert LlenJ, "text/LlenJ"
include "text/LlipE.rz.asm"
insert LlipJ, "text/LlipJ"
include "text/LlueE.rz.asm"
insert LlueJ, "text/LlueJ"
include "text/LmiscE.rz.asm"
insert LmiscJ, "text/LmiscJ"
include "text/LmpmenuE.rz.asm"
insert LmpmenuJ, "text/LmpmenuJ"
include "text/LmpweaponsE.rz.asm"
insert LmpweaponsJ, "text/LmpweaponsJ"
include "text/LoatE.rz.asm"
insert LoatJ, "text/LoatJ"
include "text/LoptionsE.rz.asm"
insert LoptionsJ, "text/LoptionsJ"
include "text/LpamE.rz.asm"
insert LpamJ, "text/LpamJ"
include "text/LpeteE.rz.asm"
insert LpeteJ, "text/LpeteJ"
include "text/LpropobjE.rz.asm"
insert LpropobjJ, "text/LpropobjJ"
include "text/LrefE.rz.asm"
insert LrefJ, "text/LrefJ"
include "text/LritE.rz.asm"
insert LritJ, "text/LritJ"
include "text/LrunE.rz.asm"
insert LrunJ, "text/LrunJ"
include "text/LsevE.rz.asm"
insert LsevJ, "text/LsevJ"
include "text/LsevbE.rz.asm"
insert LsevbJ, "text/LsevbJ"
include "text/LsevxE.rz.asm"
insert LsevxJ, "text/LsevxJ"
include "text/LsevxbE.rz.asm"
insert LsevxbJ, "text/LsevxbJ"
include "text/LshoE.rz.asm"
insert LshoJ, "text/LshoJ"
include "text/LsiloE.rz.asm"
insert LsiloJ, "text/LsiloJ"
include "text/LstatE.rz.asm"
insert LstatJ, "text/LstatJ"
include "text/LtitleE.rz.asm"
insert LtitleJ, "text/LtitleJ"
include "text/LtraE.rz.asm"
insert LtraJ, "text/LtraJ"
include "text/LwaxE.rz.asm"
insert LwaxJ, "text/LwaxJ"

text_rom_end:
