name: JAP-Status

on:
  push:
    branches: master
    paths-ignore:
    - 'tools/**'
  pull_request:
    branches: master
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildjp:
    
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Depedencies
        run: |
          sudo apt update
          sudo apt install binutils-mips-linux-gnu make
      
      - name: Get US File
        env:
          FILE_US: ${{ secrets.SECRET_FILE_US  }}
        run: wget -O baserom.u.z64 $FILE_US
      
      - name: Get JP File
        env:
          FILE_JP: ${{ secrets.SECRET_FILE_JP  }}
        run: wget -O baserom.j.z64 $FILE_JP

      - name: Extract US Assets
        run: ./extract_baserom.u.sh

      - name: Extract JP Assets
        run: ./extract_diff.j.sh

      - name: Make JP 
        run: make -j VERSION=JP

      - name: Stats
        run: python3 tools/ge-stats.py --version jp
      
#need way of telling report that JAP passed/failed
